### ISSUE TITLE
Major Frame Rate Drops When Feeding One Way with NDI

### ISSUE THREAD

**Issue by PXAbstraction** [Palakis/obs-ndi#100]
I hope this is the right place to post this as I can't find another where I might find assistance. I'm pulling my hair out with this. I built a new dedicated streaming PC over Christmas to use with this plug-in. Here are my two PCs:

Gaming PC: 6700K (overclocked), 16GB RAM, GTX1080
Streaming PC: Ryzen 1600 (stock clock), 8GB RAM, HD7870
Both run Windows 10 Pro x64 with latest updates and both were recently reloaded from scratch.
Everything is connected via gigabit with my router, PassMark benches Ethernet performance at 850MBit/sec.
My gaming PC's monitor runs at 144Hz and my aim is to stream at 1080p60 to Mixer FTL. I'm using 7500Kbps bitrate and I've tried fast and medium encoding presets (neither overloads the Ryzen.)
I manage all my scenes on my main PC, all the streaming box does is take NDI, encode it and pump it out to Mixer.

Here's the problem: When I feed video from my main gaming PC to the streaming machine, everything's a stuttery mess. The frame rate is all over the place. OBS says it's 60 on both ends and even Mixer's player says it's 60 but the visuals absolutely are not. Even if I don't stream to Mixer and just do a local recording from the stream machine, the results are exactly the same. To give an example, [here is an MP4 I recorded of a 60fps game played directly on the streaming machine](https://mega.nz/#!ZpEw1Y7A!k4u9Cg0XpPiUxjOHeQ4Uo1TaXiiC_MhC38nitGsXyn8) and [here is the same section played on my gaming PC, sent to the server with NDI](https://mega.nz/#!hkM3VDgL!wZF1BxziykOiBsl9642QLPE5FH6f8Xa6lFWX4ww3BPM). This is with Dead Cells but the same thing happens in any other 60fps title, whether low-fi indie graphics like that or AAA titles like PUBG, Siege and Battlefield 1. All of these games can easily hold over 100fps on my gaming PC. If you go to [my Mixer channel](https://mixer.com/PXAbstraction) and scroll down, any of my recent VoDs will showcase this. [Compare this to another member of my stream team who also uses NDI](https://mixer.com/BizzoMephisto?vod=16705675) and the difference is night and day. I also have a friend who is a new streamer and is using a similar setup with no issues. His gaming PC specs are almost identical to mine as well.

I have tried the following things in no particular order:

-Completely nuked and reconfigured OBS from scratch on both ends. Also tried a fresh OBS install on my gaming PC with nothing but a Game Capture source.
-Using Display Capture instead of Game Capture.
-Updated all drivers on both systems (including my gaming PC's Killer NIC drivers, which are known to be problematic.)
-Disabled G-Sync on my monitor.
-Dropped my refresh rate to 60Hz.
-Using V-Sync both on and off.
-Using both Internal and Network modes on NDI. Also tried hardware acceleration on and off.
-New network cables.
-Forcing gigabit, full duplex on both NICs (this was already set by auto negotiation.)
-Using multiple Mixer ingest servers (though as I said, this happens on local recordings too.)

The problem seems very clearly to be not in OBS properly sending the video data to Mixer but in my gaming PC sending the video data to the streaming box. However, I am completely out of ideas as to what it could be. Nothing is being overtaxed and nothing is an obvious bottleneck. Nonetheless, I dropped a grand on a new streaming server and right now, my streams are worse quality than when I was doing everything off a single PC. I badly don't want to go to a capture card solution and I'm sure there's a way to deal with this but I can't see it.

I'm hoping Palakis or someone else has seen this and can give me some kind of advice because I'm desperate to solve this. NDI is the whole reason I built this streaming box and I can't let that be a waste. I haven't tried XSplit NDI yet either but aside from the fact that I really don't like XSplit in general, their NDI implementation also has a major audio sync bug at the moment and basically isn't usable anyway. I don't know if this project is taking financial donations or not but I'm willing to put money where my mouth is if it means getting the help needed to solve this properly. It's worth it for me.

I'm incredibly frustrated at the moment because I know there's a solution, I just can't see it. If anyone can help, I'd be super grateful. Thank you.

**Comment by matiaspl** [comment]
Try Newtek's NDI Scan Converter from the free NDI Tools (
https://www.newtek.com/ndi/tools/) instead of OBS on the gaming PC, see if
it changes anything.

2018-01-24 5:18 GMT+01:00 PXAbstraction <notifications@github.com>:

**Comment by PXAbstraction** [comment]
That's a great suggestion, thank you! I will try this tonight and report the results.

**Comment by PXAbstraction** [comment]
So, I can now confirm the problem is with OBS in some respect. I ended up installing XSplit on my server and using is as the NDI receiver, while still using OBS on my gaming PC with all my normal scenes in place. It worked substantially better than OBS on both ends ([see this test VoD](https://mixer.com/PXAbstraction?vod=17414434)). I haven't tried transmitting from XSplit as well but I'm curious of the result there.

So, this is obviously something with OBS on my server causing it. That's a big step in the right direction. While I do have an XSplit license that's valid until 2019, this is obviously still not an ideal solution and I'd like to use OBS on both sides if possible. Does anyone have any ideas? Thanks!

**Comment by PXAbstraction** [comment]
[I did a longer stream tonight where I was using XSplit on my encoding machine while still using OBS on my gaming machine](https://mixer.com/PXAbstraction?vod=17518609). An improvement to be sure but for a lot of the stream, it still wasn't running at proper 60.

Here's where things get really weird though. So on matiaspl's advice, I downloaded NewTek Scan Converter and tried that. If I'm exclusively using that on my gaming PC and sending it's feed to OBS or XSplit on my streaming PC, everything is rock solid. Any game, 60fps. As soon as I run OBS on the gaming PC, the performance tanks again. Even if I still have Scan Converter running, it's performance will also tank as long as OBS is running at all on my gaming PC. This is progress in the sense that it's confirming OBS is the problem but not progress in the sense that using Scan Converter isn't a solution as it removed the ability for me to control any scenes.

Does anyone else have any insights? I'm demoralised and desperate to fix this but I have hit a wall. Thanks.

**Comment by PXAbstraction** [comment]
So, since I never got an official response, I kept at it. I'm happy to say this particular issue (though not another one related to audio sync that's for another thread) seems to be largely resolved. I did a complete nuke from orbit of the NVIDIA drivers on my gaming system using Display Driver Uninstaller. After a reinstall of those, things seem to have improved a lot. They're not perfect but most of the remaining stutters are down to OBS Game Capture and not NDI. They are far less frequent though and my viewers have noticed a clear improvement. Hopefully this can help someone else.

**Comment by Palakis** [comment]
@PXAbstraction apologies for the delay. I'm glad to hear you managed to fix your issue. Do you think it could have something to do with GeForce Experience?

**Comment by PXAbstraction** [comment]
No problem, I know you're busy and I can't complain too much about a free product. :)

That's a good question about ShadowPlay. I do have it disabled now because I no longer use it but after doing the full driver reinstall, it was still enabled for a bit without issue if I recall. I'll try to give it a test soon and I'll advise of the results.

**Comment by ChanceOW** [comment]
Seem late to the problem here but have you considered it maybe a flooding issue of your router? if you are using your router as a switch between the two computers and then also streaming on it, it could be causing dropped frames and a host of other problems. I'm only saying this as its seemed to be the solution for me. I couldn't connect the idea of dropped frames when it was working fine without streaming, it didn't seem logical at first. Curious if everything is still working fine for you abstract

**Comment by Maelas84** [comment]
@PXAbstraction Any chance of you moving your scenes to the streaming PC? As far controlling your scenes, thats an idea you could try?

**Comment by CrustyDollar** [comment]
From what I understand, this sounds like a CPU issue. I had the same kind of issue. so I went to my gaming PC->task manager->OBS->details->priority->real time. Did this for all OBS programs(they said something like OBS browser) and it cleaned up instantly.
