### ISSUE TITLE
OBS Linux Problems

### ISSUE THREAD

**Issue by barankx** [Palakis/obs-ndi#103]
I got obs everything was working fine after, I downloaded 'obs-ndi_4.2-1_amd64.deb' and 'libndi3_3.0.1-1_amd64.3.deb'. I then opened the terminal and typed:
'sudo dpkg -i libndi3_3.0.1-1_amd64.3.deb'
'sudo dpkg -i obs-ndi_4.2-1_amd64.deb'

And the obs-ndi.so installed on usr/lib/obs-plugin/ and obs did not show ndi 

when i move obs-ndi.so to usr/lib/x86_64-linux-gnu/obs-plugins , obs doesn’t run any fix for this?

**Comment by mrmakeit** [comment]
Try version 4.4 as there appeared to be a bug in 4.2 that prevented it from running (#93)

**Comment by Palakis** [comment]
@barankx Will be fixed in 4.6.1 (coming in a few hours)
