### ISSUE TITLE
Source with ndi filter

### ISSUE THREAD

**Issue by gamespeaker** [Palakis/obs-ndi#105]
Trying to add a NDI source from another source located in another scene show blank.

Example:
Scene 1 has my webcam with ndi filter
Now I go to build scene 2 and try to add the existing NDI source from scene 1, the source is blank.

Windows 10 version 1703 os build 15063.850, 
07:33:19.050: OBS 21.0.1 (64bit, windows)
OBS NDI Plugin 4.2.2

**Comment by gamespeaker** [comment]
Windows 10 latest obs and ndi

**Comment by Palakis** [comment]
@gamespeaker Wait, why are you doing this? Why not just add the webcam as a source in scene 2 without having to use NDI at all?

**Comment by gamespeaker** [comment]
It’s remote ndi webcam source.
