### ISSUE TITLE
Better support for crossover cable connections between PC's + weird quality issue.

### ISSUE THREAD

**Issue by sorenhoyer** [Palakis/obs-ndi#107]
Hi

First of all, when it works, this ndi plugin is amazing.

I have a problem though.

Since my router is only allowing 100Mbit connections, I've invested in a couple of [gigabit ethernet adapters](http://www.dlink.com/uk/en/products/dub-1312-usb-3-gigabit-ethernet-adapter). 

Even when specifically chosing the network connection under advanced settings, it's like ndi is ignoring it, and usually tries to send data through the router connection instead of the direct crossover connection. The weird thing is that this happens randomly, when I enable and disable ndi a couple of times.

Also sometimes when I do get the connection to run over the crossover connection, the recorded video seems laggy, even though neither streaming or gaming pc is anywhere near its maximum. The quality also seems lower than it should be. With the exact same setup, I find it working in 1 out of 8 times or so, and in that case I do see smooth 720p 60fps 8K bitrate video.

Unfortunately I haven't been able to pinpoint this any further, but it sure would be sweet if ndi would respect the chosen connection from obs advanced settings.

About the reduced quality and laggy playback that happens sometimes, I have no clue what would cause this. The bandwidth transferred seems to be the same, so it must be on the receiving end something's wrong.

**Comment by Helgaiden** [comment]
An easier solution for you would be to buy a 4-port unmanaged gigabit ethernet switch, plug both PCs to that switch, then run an ethernet cable from the router to the gigabit switch for internet. The two computers will (should) communicate with EACHOTHER at gigabit speed, both should have internet, and the streaming PC will only use a fraction of the available network bandwidth only sending up 4-5mbps worth of upload (the encoded stream) to the internet.

**Comment by sorenhoyer** [comment]
Thanks a gigabit switch definitely is the way to go. Closing this.
