### ISSUE TITLE
Installed OBS-NDI + Redist. Error says I haven't installed NDI-Redist

### ISSUE THREAD

**Issue by Kiwi-1995** [Palakis/obs-ndi#110]
![5f5c4c91-4560-4fb2-a721-b3d9e3b05afd](https://user-images.githubusercontent.com/4647694/35775551-72430c9c-09ef-11e8-82e5-55f52ac5d0f6.png)
![image](https://user-images.githubusercontent.com/4647694/35775553-83aabb4c-09ef-11e8-9c4c-6246f840004e.png)
[2018-02-04 21-08-28.txtasdfghjkl.txt](https://github.com/Palakis/obs-ndi/files/1692585/2018-02-04.21-08-28.txtasdfghjkl.txt)

Have tried:
Re-install of NDI + Redist
Re-install of OBS.

**Comment by Helgaiden** [comment]
And it still says that after installing the redist then rebooting?

**Comment by Palakis** [comment]
@Kiwi-1995 Did you reboot your computer?

**Comment by Kiwi-1995** [comment]
I love it when github doesn’t give me notifications. Yeah reboot didn’t fix it. Had to uninstall, reboot, install, reboot several times before it worked.
