### ISSUE TITLE
Ndi wont show up under tools on my gaming pc

### ISSUE THREAD

**Issue by ZachBrez** [Palakis/obs-ndi#112]
I got it to work easily on my laptop however on my gaming pc it wont show up even after uninstalling and reinstalling obs and the pluggins

My log file

-----------------------------------------------------------------------------------------------------------------

https://gist.github.com/anonymous/419a12e472e17bd8486aa38ff3974cea

**Comment by Helgaiden** [comment]
I dont see any mention of NDI in your log. Did you make sure to reboot it after installing the NDI redist that OBS asks for?

**Comment by Palakis** [comment]
@ZachBrez The installer didn't find your OBS Studio installation folder. Try installing it manually from the Zip archive.
