### ISSUE TITLE
Lag on preview

### ISSUE THREAD

**Issue by joxgarcia1997** [Palakis/obs-ndi#118]
Lastly I tried to make a stream with the plugin, and previously I worked perfectly, but when I updated the plugin and obs to its latest version, its present lag in the preview and likewise in the stream. 

this occurs when I put a game, example CS: GO, in full screen, but if I change the program to windows mode, it does not present lag, this did not happen previously

**Comment by Palakis** [comment]
@joxgarcia1997 
> its present lag in the preview

Which preview? In OBS on the gaming computer or streaming computer?

**Comment by joxgarcia1997** [comment]
i tried the problem on both computers, and its appears on both of them.

**Comment by Palakis** [comment]
@joxgarcia1997 This is kinda normal behavior on Windows and has nothing to do with NDI. Try running CS:GO in Bordeless Windowed (fake fullscreen to facilitate alt-tab).
