### ISSUE TITLE
Preview on the streaming PC stuttering.

### ISSUE THREAD

**Issue by veimiK** [Palakis/obs-ndi#119]
Oh noes, it's this problem again. JUST FIX YOUR GODDAMN CONNECTION BRUH
I wish, but not this time. 
I've recently got NDI because I've got a pretty strong laptop, so I wanted to use it as a streaming PC. The problem is, the preview in OBS on streaming PC (laptop) is laggy - about 15 fps constant. Now, the things I've tried:
- using the netsh int tcp reset command in cmd (didn't help)
- checking if everything everywhere is 1gbit. My router can handle 10/100/1000, my Z97-Pro has a gigabit LAN port and I use an official ASUS (since the laptop's made by ASUS) USB to ethernet thingy and I do have gigabit connection between my laptop and PC - check here: https://imgur.com/RaLY5W7
- switching to WiFi - now, this was a surprise. It actually works just fine on WiFi (about 50 fps, uses about 130 Mb/s) but it sometimes drops to 80Mb/s (and stutters at that time), so I'm worried it might not be stable enough. 
- using different ports in my router
- switching from capture game to capture display
- resetting both laptop and PC
- running 32bit and 64bit OBS versions

Gaming PC: 
4770k @ stock
GTX 1070
8GB 1600MHz DDR3 RAM
Both Windows and OBS are on an SSD

Laptop:
i5-7300HQ
8GB 2400MHz DDR4 RAM
GTX 1050
Both Windows and OBS are on an M.2 SSD

I'm stuck and out of ideas. I'm ready to provide all the information you need. 

EDIT:
I forgot to mention one thing.
When I'm on Ethernet connection (both laptop and PC plugged into router) this is what my task manager shows when using NDI:
Gaming PC - https://imgur.com/pkfcG4Z
Laptop - https://imgur.com/7zvwqKo

**Comment by violentbunny** [comment]
I used the NDI Tools-(Video monitoring to be exact) and received the video feed from the gaming pc and captured that windows on obs in streaming. My video feed in input ndi in obs was stuttery but video feed in the video monitoring software was smooth and never dipped a frame so this option ws much better for me.

**Comment by Helgaiden** [comment]
@Maelas84 Yeah

**Comment by WreckedMech** [comment]
So I made a bit of a discovery regarding those lost frames.

In a two system setup I was getting major frame drops on the incoming NDI connection. The OBS monitor on the giving side appeared smooth, but the receiving OBS was far from it. The odd solution was to Minimize a browser window i had set to monitor my Twitch broadcast. Not Close, just Minimize, sometimes even tab away from a video playing window. Although i bet closing works too. 

My advice if your having the OBS-NDI frame loss issue is to go through your windows and minimize them until you locate the one causing the stutter by being active.
