### ISSUE TITLE
Compatible w/OBS 21 on Mac?

### ISSUE THREAD

**Issue by IceMan391** [Palakis/obs-ndi#120]
The installer is no longer working for me with OBS 21.02.  Plugin isn't getting installed. Do we need to wait for a new version?

**Comment by iBobik** [comment]
Me too. But it was solved immediately when I installed NewTek's tools for Mac: http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/NewTekNDIToolsForMacOS.dmg

**Comment by IceMan391** [comment]
Cool! Yes that did work...but in case anyone else is here struggling w/the same thing... One must install the NewTek tools and then run the obs-ndi-4.2.2.pkg after doing that.

**Comment by iBobik** [comment]
For me it worked opposite - first install obs-ndi and then newtek tools.

Jan Pobořil
https://honza.poboril.cz/

22. 2. 2018 v 19:52, IceMan391 <notifications@github.com>:

**Comment by lunchisara** [comment]
> Cool! Yes that did work...but in case anyone else is here struggling w/the same thing... One must install the NewTek tools and then run the obs-ndi-4.2.2.pkg after doing that.

I am struggling very much to get NDI plug-in to show up on mac. I have installed obs 23.10  and ndi 4.6.0  . I also tried to download the NDI SDK from newtek as well as the link above. can anyone help?

**Comment by xman51** [comment]
I am having the exact same issue as lunchisara. Can someone assist me? NDI source not appearing in my OBS after installing v4.6.0 on a mac Mojave v10.14.6 and OBS v23.2.1.
