### ISSUE TITLE
obs-ndi 4.2+ unable to reliably source video into OBS

### ISSUE THREAD

**Issue by dx9s** [Palakis/obs-ndi#123]
obs-ndi 4.2.2 + obs-studio 21.0.1 partially stopped working.

Previous was able to output NDI and OBS input source NDI -- but I wasn't not paying attention to if it stopped working after which update. I know that multiple network cards can be an issue, so made sure only one IP (not including loop back) is present and that hasn't seemed to fix it either.

I've removed the software, cleared out ~/.config/obs-studio and so forth then reinstalled

obs-studio 21.0.1 (from  PPA)

obs-ndi_4.2.2-1_amd64.deb and libndi3_3.0.1-1_amd64.deb (from github)

Tested with ndi-monitor and ndi-generator [ http://www.sienna-tv.com/ndi/ ] so I know I can output NDI from the canvas .. but cannot bring in the test generated signal.

Believe putting this here is first best place.

I can run and dump logs but just need instructions on what best works for folks here.

**Comment by dx9s** [comment]
Sometimes it will open and bring in OBS sources, but it is weird and requires a voodoo dance and careful/quick timing: (output from log when it worked ... sort of / preview in the:

03:08:12 PM.195: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
03:08:20 PM.582: [obs-ndi] starting main NDI output with name 'OBS1'
03:08:20 PM.602: [obs-ndi] asynchronous video sending disabled
03:08:24 PM.956: [obs-ndi] can't create a receiver for NDI source ''
03:08:24 PM.959: User added source 'NDI™ Source' (ndi_source) to scene 'SOURCES-THINGS'
03:08:28 PM.069: [obs-ndi] video thread for 'NDI™ Source' started
03:08:28 PM.069: [obs-ndi] video thread for 'NDI™ Source' started
03:08:28 PM.069: [obs-ndi] started A/V threads for source 'HPPD (OBS1)'
03:08:28 PM.069: [obs-ndi] audio thread for 'NDI™ Source' started


Note, process was loading OBS, enabling NDI output, adding a source and quickly closing the Properties [with preview that never shows up]), and it works..


Open a session that has pre-defined NDI Source:

03:11:40 PM.921: [obs-ndi] started A/V threads for source 'HPPD (OBS1)'
03:11:40 PM.921: [obs-ndi] video thread for 'NDI™ Source' started
03:11:40 PM.921: [obs-ndi] audio thread for 'NDI™ Source' started

and nothing works/shows up.. have to remove Source and disable NDI output and then restart OBS and try again.

(This is purely testing on one machine "looping" back a test stream, not a typical case, but DID work in previous versions of obs-studio+obs-ndi)

BUT when it doesn't work:

**Comment by dx9s** [comment]
obs ndi isn't stable on Linux or Windows .. using 3rd party NDI monitor and signal generator on Mac to test.

**Comment by dx9s** [comment]
I've hunted down part of a problem (which could be related), in the log/console output this occurs:
**error: [obs-ndi] can't create a receiver for NDI source ''**

which is create inside obs-ndi-source.cpp:
```
void ndi_source_update(void* data, obs_data_t* settings) {
[...]
    s->ndi_receiver = ndiLib->NDIlib_recv_create_v2(&recv_desc);
    if (s->ndi_receiver) {
[...]
    } else {
        blog(LOG_ERROR,
            "can't create a receiver for NDI source '%s'",
            recv_desc.source_to_connect_to.p_ndi_name);
    }
```

and I suspect there might be a stuck thread from the 'source create preview' process that is messing up the NDI library side of things. Putting blog entries into each thread (inside the running while loop, which a large counter so it outputs a "I'm alive" every so many seconds) to see them actually running.

Just a thought. will investigate places to put more debugging logic into the code.

--Doug (dx9s)

**Comment by dx9s** [comment]
Started a fork.. Made these changes (minimal): https://github.com/Palakis/obs-ndi/compare/master...dx9s:master 

Trying to track down and make repeatable failures or successes and why/where!

I've had OBS core dump when closing the NDI output dialog (for example), and it is rare, but it has happened twice now and can't reliably cause that to happen.

Trying to determine all the moving pieces involved -- this is a bit of a headache to scope out.

**Comment by dx9s** [comment]
example of a core dump: (note with as well obs-websocket from 7fdace9b79759ef9d558b5d6f00b1677f2338612):
```
[...]
info: All scene data cleared
info: ------------------------------------------------
info: Freeing OBS context data
info: [obs-websocket] goodbye!
info: [obs-ndi] goodbye !
Segmentation fault (core dumped)
```

**Comment by dx9s** [comment]
I see v2 and v3 references (assuming v3 has v2 compatible calls)?! : 
```
dx@x99:~/git/obs-ndi/src$ grep ndiLib *
grep: forms: Is a directory
obs-ndi.cpp:const NDIlib_v3* ndiLib = nullptr;
obs-ndi.cpp:    ndiLib = load_ndilib();
obs-ndi.cpp:    if (!ndiLib) {
obs-ndi.cpp:    if (!ndiLib->NDIlib_initialize()) {
obs-ndi.cpp:    ndi_finder = ndiLib->NDIlib_find_create_v2(&find_desc);
obs-ndi.cpp:    if (ndiLib) {
obs-ndi.cpp:        ndiLib->NDIlib_find_destroy(ndi_finder);
obs-ndi.cpp:        ndiLib->NDIlib_destroy();
obs-ndi-filter.cpp:    ndiLib->NDIlib_send_send_video_v2(s->ndi_sender, &video_frame);
obs-ndi-filter.cpp:    ndiLib->NDIlib_send_destroy(s->ndi_sender);
obs-ndi-filter.cpp:    s->ndi_sender = ndiLib->NDIlib_send_create(&send_desc);
obs-ndi-filter.cpp:    ndiLib->NDIlib_send_destroy(s->ndi_sender);
obs-ndi-filter.cpp:    ndiLib->NDIlib_send_destroy(s->ndi_sender);
obs-ndi-filter.cpp:    ndiLib->NDIlib_send_send_audio_v2(s->ndi_sender, &audio_frame);
obs-ndi.h:extern const NDIlib_v3* ndiLib;
obs-ndi-output.cpp:    ndiLib->NDIlib_send_destroy(o->ndi_sender);
obs-ndi-output.cpp:    o->ndi_sender = ndiLib->NDIlib_send_create(&send_desc);
obs-ndi-output.cpp:    ndiLib->NDIlib_send_destroy(o->ndi_sender);
obs-ndi-output.cpp:        ndiLib->NDIlib_send_send_video_async_v2(o->ndi_sender, &video_frame);
obs-ndi-output.cpp:        ndiLib->NDIlib_send_send_video_v2(o->ndi_sender, &video_frame);
obs-ndi-output.cpp:    ndiLib->NDIlib_send_send_audio_v2(o->ndi_sender, &audio_frame);
obs-ndi-source.cpp:    const NDIlib_source_t* sources = ndiLib->NDIlib_find_get_current_sources(ndi_finder,
obs-ndi-source.cpp:        frame_received = ndiLib->NDIlib_recv_capture_v2(
obs-ndi-source.cpp:            ndiLib->NDIlib_recv_free_audio_v2(s->ndi_receiver, &audio_frame);
obs-ndi-source.cpp:        frame_received = ndiLib->NDIlib_recv_capture_v2(s->ndi_receiver,
obs-ndi-source.cpp:            ndiLib->NDIlib_recv_free_video_v2(s->ndi_receiver, &video_frame);
obs-ndi-source.cpp:    ndiLib->NDIlib_recv_destroy(s->ndi_receiver);
obs-ndi-source.cpp:      s->ndi_receiver = ndiLib->NDIlib_recv_create_v2(&recv_desc);
obs-ndi-source.cpp:              ndiLib->NDIlib_recv_send_metadata(
obs-ndi-source.cpp:          ndiLib->NDIlib_recv_set_tally(s->ndi_receiver, &s->tally);
obs-ndi-source.cpp:        ndiLib->NDIlib_recv_set_tally(s->ndi_receiver, &s->tally);
obs-ndi-source.cpp:        ndiLib->NDIlib_recv_set_tally(s->ndi_receiver, &s->tally);
obs-ndi-source.cpp:        ndiLib->NDIlib_recv_set_tally(s->ndi_receiver, &s->tally);
obs-ndi-source.cpp:        ndiLib->NDIlib_recv_set_tally(s->ndi_receiver, &s->tally);
obs-ndi-source.cpp:    ndiLib->NDIlib_recv_destroy(s->ndi_receiver);
```

**Comment by dx9s** [comment]
Not sure if this is related but is at least another problem: https://stackoverflow.com/questions/20051224/qt-socket-notifiers-cannot-be-enabled-from-another-thread

**Comment by dx9s** [comment]
## Bumped everything up:
* OBS 21.1.0 (Linux) from PPA, or later (from source)
* OBS-NDI 4.2.3 (release) or later (from source)
* forked code, submitted cosmetic pull request https://github.com/Palakis/obs-ndi/pull/135
* added additional debugging in my testing branch: https://github.com/dx9s/obs-ndi/commit/d524cec8e9e036a3e1c122ccb186ec824c1427a5 based on upstream @Palakis upstream master (newer than 4.2.3)
* tested libndi.so.3.0.1 and libndi.so.3.0.9

## Findings:
* not extensively tested, but had a segfault which GDB pointed to libavahi-common.so.3 (network discovery related -- part of libndi). So far only documented this with libndi.so.3.0.1 but still could be issue under 3.0.9
* 3.0.9 **seems** to more reliable (but still not consistent) at starting up an NDI source, but this needs more testing!
* the create source "Properties for '%s'" which is dynamically created on the OBS side tries to create a source for nothing ( _error: [obs-ndi] can't create a receiver for NDI source ''_ ) even before the dialog is closed. Think this might be related to a non-existent (not required) ``struct obs_source_info.get_defaults`` callback -- will tinker with this eventually
* Re-openning the "Properties for '%s'" on existing NDI Source (a working one) will show the preview at that point, but closing it might cause the source to stop.
* The create NDI Source UI is missing preview on Linux and Windows it appears, so not platform specific.

Will continue to see what repeatable difference there is between 3.0.1 and 3.0.9 from Newtek's binary only library but think that 3.0.9 might be an improvement (but have not repeatability confirmed this).

--Doug (dx9s)

**Comment by dx9s** [comment]
## UPDATE:
Was able to get crash with libndi.so.3.0.9 where gdb determines it has something to do between libndi.so.3.0.9 (as-well-as 3.0.1) and libavahi-common.so.3. I did research based on hunch, perhaps libavahi-common.so.3 isn't entirely thread safe and came across this:

https://github.com/benoitc/dnssd_erlang/issues/5

Since we don't have access to the source for libndi.so.3.0.x, we might need to contact Newtek about this!

Also there remains the possibility that changing the listening loop (receiving frames from NDI side) to a single thread -- that THAT will fix/workaround the issue. All the sample code from NDI's SDK shows it that way so I assume they only developed reference code for testing purposes that way.

I will re-introduce parts of my previous test code that deals with single threading that part (see https://github.com/dx9s/obs-ndi/blob/3beaf73b48b4517fcfa1addc6fe6f2248bf58f97/src/obs-ndi-source.cpp ) and test to see if I can get libndi.so.3.0.(9|1) to segfault against libavahi .

--Doug (dx9s)

**Comment by dx9s** [comment]
reporting back... I haven't done extensive testing.. Only narrowed it down to something between libavahi and libndi .. HOWEVER This came up in change logs for libavahi:

http://changelogs.ubuntu.com/changelogs/binary/liba/libavahi-common3/0.6.32~rc+dfsg-1ubuntu2.2/changelog

And it is worth updating to latest library and testing (been busy) -- preparing for trip to LFNW.

**Comment by Gibbz** [comment]
im having a similar issue with obs-ndi on linux.
I can see the stream listed in obs, but no audio or video comes through. I have not been able to get any combination working!

**Comment by kevingarman** [comment]
I concur with @narcogen with same versions on Linux and Mac...haven't used it on Windows.

**Comment by Gibbz** [comment]
Ive had a play with disabling ipv6 which was recommended else where. But no luck.
Still can only see the NDI source name, but its always just blank.

Has anyone made any progress on this one?

**Comment by Gibbz** [comment]
I finally got my hands on a windows machine for more testing...

I can confirm the problem is with the linux obs not displaying (or intialising?) the stream. 

I can stream from linux to windows via ndi without issue.
I can stream from windows to windows.

I can not stream from window to linux via ndi.
I can not stream from linux to linux.

**Comment by kenna-bmcdevitt** [comment]
I have a similar setup. doing a dual pc streaming system. gaming rig is windows 10, streaming rig is archlinux. i have to re-add ndi source multiple times on streaming system and sometimes have to reboot in order for the initialization of the ndi source. otherwise, just a black screen in obs.

**Comment by noydarly** [comment]
Still I'm having the same issue, any progress on this?

**Comment by padcom** [comment]
The issue still persists a year later. Tried it with the HX iPhone app and I am getting just a blank screen from that source.

However on the upside streaming from one linux machine to another works without issues
