### ISSUE TITLE
Alpha layer?

### ISSUE THREAD

**Issue by lud4l** [Palakis/obs-ndi#124]
Hi everyone,

This plugin works like a charm, but when i'm using a browser source or something with an alpha layer, the NDI send it as a black background.

Can you try to make this plugin able to send alpha layer in NDI? By this way i'll b able to integrate some transparent content into my tricaster, using OBS for browsersource  (tricaster isn't able to do a browersource).

**Comment by Palakis** [comment]
The main OBS output uses NV12, not RGBA, and it's a justifiable limitation of OBS because it's not possible to stream alpha.
I suggest you to try hooking a Dedicated NDI filter to your browser source, or even to the whole scene, as the Dedicated NDI output filter supports RGBA natively and doesn't depend on the pixel format of the main output

**Comment by lud4l** [comment]
Into the advanced menu of OBS, i can chose the format between NV12, I420, I444 or RGB. Does RGB support Alpha maybe?
In Browser source, i'v no problem to get the alpha layer into the CSS of my browser source.
As I need OBS as a NDI source, I can't apply a NDI filter because NDI filter apply only on NDI source into OBS as a source, not the destination.
In my setup, OBS is just a source to get my browser source, something that tricaster can't do.

**Comment by btorellALTA** [comment]
Right click on your browser source and go to Filters. Then add an NDI output filter. That will make the browser source appear as an NDI source for your Tricaster, and it will include alpha transparency.

**Comment by lud4l** [comment]
I don't have a tricaster right here but i'm gonna try iot asap. Thanks a lot for this precious information!!

**Comment by Palakis** [comment]
@lud4l 
> Do I have to activate the NDI output then or not?

Nope!

**Comment by lud4l** [comment]
So easy... I should have know it! Thanks a lot guys and keep doing this excellent work.
