### ISSUE TITLE
NDI-HX

### ISSUE THREAD

**Issue by sellbud** [Palakis/obs-ndi#129]
Have been using OBS and NDI separately for a while now, but just started experimenting with the plugin since I found out about it last week and I love it. I am an AV systems designer and installer and this will solve a lot of problems for me. I ran some tests this week with the new Panasonic PTZ cameras that send a new flavor of NDI called NDI-HX. I have found that the HX driver installation deletes NDI from the Source list in OBS. Sienna has now included HX support in all of their products. I was wondering if there are plans to include HX support in this plug-in.

**Comment by dx9s** [comment]
I think that the v3 of the NDI libraries support HX:

Page 16 from SDK documentation "NDI SDk Docunmentation.pdf":
```
NDI-HX is supported by NDI applications starting at SDK v2.1 on Windows and SDK v3.0 on Mac and
Linux. A separate NDI-HX driver for the hardware device that is being used must be downloaded (your
device documentation will provide you with the link). All HX devices support device recording and web
control, with PTZ cameras supporting all PTZ support. NDI-HX supports hardware assisted compression
on many platforms. Drivers are provided on Mac and Windows, if you require support of NDI-HX on
Linux within your application please email ndi@newtek.com .
```

However I think it requires use of the newer _v3 interface. OBS-NDI still uses NDIlib_recv_create_v2 / NDIlib_recv_capture_v2 -- as the driver is intended to be cross platform (no fork in code so a "windows only" version is maintained separately), it will require contacting newtek.com on what is required for Linux.

I'm not the developer, so I might have some information wrong and I can't speak to timeline.

I myself am hammering out threading issues that is causing instability (crashes, memory leaks, and no NDI video source -- on Linux).

--Doug (dx9s)

**Comment by sellbud** [comment]
Thank you. I am not a programmer so I only understood some of your reply, but I can see that compatibility will progress as the libraries are updated.

**Comment by Palakis** [comment]
@dx9s there is no such thing as `*_v3` interfaces/functions. It's already the most recent API version.

**Comment by dx9s** [comment]
My mistake! I thought I saw some. Perhaps for something else (not receiver then).

**Comment by Palakis** [comment]
@sellbud What platform are you on?

**Comment by svisintin** [comment]
Dear all,
I would like to install/use obs on Linux with video flow from NDI-HX. I've prepared a machine with Ubuntu 18.04. I've installed obs-ndi 4.4 and the latest version of OBS (21.1.1-84-g051c58ee (linux) ).
Unfortunately I cannot see the NDI-HX flows. Someone can help?
Thanks a lot!

**Comment by sellbud** [comment]
I am on both Mac and PC depending on various factors, but generally I use a Mac for streaming with OBS. Sometimes I test using a PC so I don't have to haul around both laptops. Thank you for the title change. My bad.

**Comment by Palakis** [comment]
Gonna close this, as I can't do much with NDI|HX from the SDK itself.
