### ISSUE TITLE
Stuck installing

### ISSUE THREAD

**Issue by DNVIC** [Palakis/obs-ndi#132]
The installer just stops installing completely on one of my computers at the last millisecond. This doesn't happen on my other computer which installed it correctly. Even when I restart, it doesn't show up in OBS, and I don't even get an error message. I've tried installing manually, too, with no avail. (using the zip file)

Specs:
Streaming PC: 
16 GB DDR3 RAM
CPU: AMD A8-3860 APU 2.90 GHz
Graphics Card: NVIDIA GeForce GTX 650
Operating System: Windows 7 Service Pack 1
Recording PC (the one that installed correctly):
8 GB DDR3 RAM
CPU: Intel i7 4700-MQ 2.40 GHz
Graphics Card: Intel HD Graphics 4600
Operating System: Windows 10

OBS LOG (Streaming PC)
https://gist.github.com/de764146adf07bfdd689c93871f89ebe
OBS LOG (Recording PC) (Laptop)
https://gist.github.com/a3ddea1f30a2813998d8953a708db0d3

**Comment by Palakis** [comment]
@DNVIC Try installing the plugin manually from the zip archive, and don't forget to install the NDI runtime as well.
