### ISSUE TITLE
Great video quality but low FPS

### ISSUE THREAD

**Issue by Noctim** [Palakis/obs-ndi#133]
Hello there. I just tried streaming via 2nd PC and with NDI and OBS it worked quite well. Putting the encoding on a 2nd machine really helped increasing the image quality of my stream, but I still have Problems with my framerate. The games run fluidly, but more with 30/40 than 60 fps.

Im sending the signal from PC1 to PC2 with a 1GBit LAN Connection, but on OBS on PC2 the framerate seems to be locked around 30-40 fps.

Every channel (CPU, GPU, Networkspeed etc.)
on both PCs seems to be underloaded, so I cannot really identify my Mini-bottleneck.

And Ideals?

**Comment by Noctim** [comment]
Thanks to my iphone for bad autocomplete 😂

**Comment by Naruske** [comment]
Do you think this is related to issue #94?

This video seems to show off the issue I and many others are having. https://www.youtube.com/watch?v=liU7GzNqWEs

**Comment by Helgaiden** [comment]
What are your settings under "video" for both PCs?

**Comment by Noctim** [comment]
@Naruske I think it differs from this issue, because I don't have any kind of "heavy load", although the symptons are comparable. The stream doesn't even stutter, it just runs with low FPS.

But wait, it's not completely true: I think it's interesting to note, that the framerate seems to vary from time to time. Sometimes it really goes up to what I would call 60fps, but most of the time it stays around 30/40.

I've already taken a look on my GPU workload, because I thought that my PC1 has problems delivering a constant framerate to PC2, but the GPU never really peaks and stays around 60-90%. I also minimized Details in Overwatch (example) and fixed my gaming framerate from 144 to 90. But in Games like PUBG, which is not as configurable, I have the same problems.

Here is a test video with Overwatch and PUBG:

https://www.twitch.tv/videos/240563737

Please note, the overall quality is GREAT. I just want to really push the possibilities here. And that's the only concern I have is the framerate :)

Regarding video settings: I will post them later when I'm home.

**Comment by Naruske** [comment]
I don't think it necessarily means that your streaming pc is not able to keep up. It justs needs a little more work done when a lot of complex scenes start to render. Check with ndi studio monitor if the framerate is better. Because like I and many others the framerate is just lacking in OBS but not there.

**Comment by Noctim** [comment]
Here are two demo videos. I'm currently unable to get a higher FPS for Twitch. NDI Studio Monitor is a little bit better, but trying to capture the screen here leads me to the same result in OBS.

https://www.twitch.tv/videos/241273332
https://www.twitch.tv/videos/241277755

OBS-Videosettings PC1:

Base Resolution: 2560x1440
Output Resolution: 1280x720
Downscale: Lanczos
FPS: 60

OBS-Videosettings PC2:
Base Res: 1280x720
Output Res: 1280x720
Downscale: Lanczos
FPS: 60
