### ISSUE TITLE
Unable to receive NDI feed from NDI filter applied to indivudla source in OBs

### ISSUE THREAD

**Issue by TheMuso** [Palakis/obs-ndi#134]
As per the title, I am unable to receive an NDI feed from the NDI filter, specifically the “Dedicated NDI Output” that can be applied in the effect filters section of the filters dialog. I am however able to receive the feed from the master NDI output when enabled under the tools menu.

I have tried the following send and receive combinations, and all show the same behaviour.

Senders:
* OBS studio 21.1.0 on Linux Fedora 27, built from source using the source RPM found in the free repository at http://www.rpmfusion.org, and the latest release of OBS NDI plugin built against that version of OBS, using the libndi source rpm found in the Negativo17 multimedia repository, https://negativo17.org/multimedia/
* OBS 21.0.3 for Mac OS using the latest Mac binary release of OB NDI, on Mac OS Sierra 10.12.6.

Receivers:
* OBS studio 21.1.0 on Linux Fedora 27, built from source using the source RPM found in the free repository at http://www.rpmfusion.org, and the latest release of OBS NDI plugin built against that version of OBS, using the libndi source rpm found in the Negativo17 multimedia repository, https://negativo17.org/multimedia/
* OBS 21.0.3 for Mac OS using the latest Mac binary release of OB NDI, on Mac OS Sierra 10.12.6.
* Newtek Studio Monitor for Mac, on Mac OS Sierra 10.12.6.
* Wirecast 8.3 for Mac running in demo mode, on Mac OS Sierra 10.12.6.
* FFMPEG 3.4, as found in the Negativo17 multimedia repository for Fedora 27, https://negativo17.org/multimedia/, built against libndi found in the same repository.

* The Mac OBS sender was running on a 2013 Mac Pro, 6-core Xeon E5, 3.5GHz base clock.
* The Linux OBS sender was running on a Core i7 4930K system, 3.4GHz base clock.
* The FFMPEG receiver was running on a 2011 Mac mini Server, Fedora 27, Core i7 Quad 2.0GHz base clock, command-line instructed fm-eg to encode using libx264, ultrafast preset, CRF of 18, copy the audio, all into an MKV container.
* The 4930K system above was also used as an OBS and FFMPEG receiver, FFMPEG command-line the same as for the Mac mini.
* The Newtek Studio Monitor and Wirecast receivers were running on a 2011 MacBook Pro, Core i7 2.3GHz base clock.

* All testing was done between 2 machines, I did not test with a sender and receiver on the same machine.
* All computers were connected using a gigabit network, no router in the traffic path, only unmanaged network switches.
* File transfer speeds between all machines achieve well over 10MB/Sec, close to full gigabit speeds, i.e 112MB/Sec given fast enough storage.
* When attempting to receive with NewTek Studio Monitor, OBS, and Wirecast, I get a black image canvas/no video.
* When attempting to receive using FFMPEG, no file was created and the encoding process did not start. FFMPEG would start, it would print its various library versions, and then the process would appear to hang, although Control + C did kill it and return to the command prompt. FFMPEG did not print any errors or concerning/unusual error messages. I did not test audio, as I figured when I first saw this behaviour that video would be enough to determine whether a feed was being received.
* No testing was done using Windows, as I currently do not have a Windows install to hand right now.
* Source content was a game console captured via HDMI using a Magewell USB 3 capture device.
* When sending and receiving the main NDI output from OBS, i.e activated from the tools menu, I saw no stuttering, unless I was using FFMPEG configured to encode with a codec or compression settings that were too much for the system’s CPU to handle.

**Comment by TheMuso** [comment]
Log from the Mac OB sender:

16:01:17.363: CPU Name: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
16:01:17.363: CPU Speed: 3500MHz
16:01:17.363: Physical Cores: 6, Logical Cores: 12
16:01:17.363: Physical Memory: 16384MB Total
16:01:17.363: OS Name: Mac OS X (NSMACHOperatingSystem)
16:01:17.363: OS Version: Version 10.12.6 (Build 16G1212)
16:01:17.363: Kernel Version: 16.7.0
16:01:17.365: hotkeys-cocoa: Using layout 'com.apple.keylayout.Australian'
16:01:17.365: Portable mode: false
16:01:17.509: OBS 21.0.3 (mac)
16:01:17.509: ---------------------------------
16:01:17.510: ---------------------------------
16:01:17.510: audio settings reset:
16:01:17.510: 	samples per sec: 48000
16:01:17.510: 	speakers:        2
16:01:17.511: ---------------------------------
16:01:17.511: Initializing OpenGL...
16:01:17.523: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon HD - FirePro D300 OpenGL Engine
16:01:17.523: OpenGL loaded successfully, version 4.1 ATI-1.51.8, shading language 4.10
16:01:17.581: ---------------------------------
16:01:17.581: video settings reset:
16:01:17.581: 	base resolution:   1920x1080
16:01:17.581: 	output resolution: 1920x1080
16:01:17.581: 	downscale filter:  Bicubic
16:01:17.581: 	fps:               60/1
16:01:17.581: 	format:            I444
16:01:17.581: 	YUV mode:          709/Full
16:01:17.581: Audio monitoring device:
16:01:17.581: 	name: Default
16:01:17.581: 	id: default
16:01:17.581: ---------------------------------
16:01:17.634: No blackmagic support
16:01:17.661: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
16:01:17.678: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib, 1): Library not loaded: @rpath/libvlccore.dylib
16:01:17.678:   Referenced from: /Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib
16:01:17.678:   Reason: image not found
16:01:17.678: 
16:01:17.678: Couldn't find VLC installation, VLC video source disabled
16:01:17.680: Failed to load 'en-US' text for module: 'obs-browser.so'
16:01:17.680: [browser_source: 'Version: 1.30.1']
16:01:17.681: [obs-ndi] hello ! (version 4.2.3)
16:01:17.681: [obs-ndi] Trying ''
16:01:17.681: [obs-ndi] Trying '/usr/lib'
16:01:17.681: [obs-ndi] Trying '/usr/local/lib'
16:01:17.681: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.3.dylib'
16:01:17.682: [obs-ndi] NDI runtime loaded successfully
16:01:17.682: [obs-ndi] NDI library initialized successfully
16:01:17.684: ---------------------------------
16:01:17.684:   Loaded Modules:
16:01:17.684:     obs-ndi.so
16:01:17.684:     obs-browser.so
16:01:17.684:     vlc-video.so
16:01:17.684:     text-freetype2.so
16:01:17.684:     rtmp-services.so
16:01:17.684:     obs-x264.so
16:01:17.684:     obs-vst.so
16:01:17.684:     obs-transitions.so
16:01:17.684:     obs-outputs.so
16:01:17.684:     obs-filters.so
16:01:17.684:     obs-ffmpeg.so
16:01:17.684:     mac-vth264.so
16:01:17.684:     mac-syphon.so
16:01:17.684:     mac-decklink.so
16:01:17.684:     mac-capture.so
16:01:17.684:     mac-avcapture.so
16:01:17.684:     linux-jack.so
16:01:17.684:     image-source.so
16:01:17.684:     frontend-tools.so
16:01:17.684:     coreaudio-encoder.so
16:01:17.684: ---------------------------------
16:01:17.684: ==== Startup complete ===============================================
16:01:17.702: Service '' not found
16:01:17.703: All scene data cleared
16:01:17.703: ------------------------------------------------
16:01:17.755: Magewell: Selected device 'XI100DUSB-HDMI'
16:01:17.755: Magewell: Capturing 'XI100DUSB-HDMI' (0x210000029350001):
16:01:17.755: 	Resolution: 1920x1080
16:01:17.755: 	FPS: 59.9999 (59999880/1000000)
16:01:17.755: 	Frame interval: 0.0166667 s
16:01:17.755: 	Input format: Auto (actual: YUY2 - 422YpCbCr8_yuvs (yuvs))
16:01:17.755: 	Requested color space: Auto (-1)
16:01:17.755: 	Requested video range: Full (2)
16:01:17.755: 	Using format: <AVCaptureDeviceFormat: 0x7fca3b75cd90> 'vide'/'yuvs' enc dims = 1920x1080, pres dims = 1920x1080 { 60.00 59.94 50.00 30.00 29.97 25.00 15.00 fps }
16:01:17.800: Switched to scene 'Scene'
16:01:17.800: ------------------------------------------------
16:01:17.800: Loaded scenes:
16:01:17.800: - scene 'Scene':
16:01:17.800:     - source: 'Magewell' (av_capture_input)
16:01:17.800: ------------------------------------------------
16:01:51.895: device_swapchain_create (GL) failed
16:01:51.895: obs_display_init: Failed to create swap chain
16:01:51.895: User added filter 'Magewell_NDI' (ndi_filter) to source 'Magewell'
16:01:58.589: device_swapchain_create (GL) failed
16:01:58.590: obs_display_init: Failed to create swap chain
16:21:58.761: [obs-ndi] starting main NDI output with name 'OBS'
16:21:58.767: [obs-ndi] asynchronous video sending disabled
16:28:50.587: [obs-ndi] stopping main NDI output
16:28:50.587: Output 'main_ndi_output': stopping
16:28:50.587: Output 'main_ndi_output': Total frames output: 24710
16:28:50.587: Output 'main_ndi_output': Total drawn frames: 24710

**Comment by TheMuso** [comment]
Log from Linux sender:

16:30:18.890: CPU Name: Intel(R) Core(TM) i7-4930K CPU @ 3.40GHz
16:30:18.890: CPU Speed: 2794.424MHz
16:30:18.891: Physical Cores: 6, Logical Cores: 12
16:30:18.891: Physical Memory: 32171MB Total, 30561MB Free
16:30:18.891: Kernel Version: Linux 4.15.10-300.fc27.x86_64
16:30:18.891: Distribution: Fedora 27
16:30:18.891: Portable mode: false
16:30:18.921: OBS 21.1.0 (linux)
16:30:18.921: ---------------------------------
16:30:18.921: ---------------------------------
16:30:18.921: audio settings reset:
16:30:18.921: 	samples per sec: 48000
16:30:18.921: 	speakers:        2
16:30:18.931: ---------------------------------
16:30:18.931: Initializing OpenGL...
16:30:18.984: Loading up OpenGL on adapter X.Org AMD Radeon (TM) RX 480 Graphics (POLARIS10 / DRM 3.23.0 / 4.15.10-300.fc27.x86_64, LLVM 5.0.1)
16:30:18.984: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 17.3.6, shading language 4.50
16:30:19.010: ---------------------------------
16:30:19.010: video settings reset:
16:30:19.010: 	base resolution:   1920x1080
16:30:19.010: 	output resolution: 1280x720
16:30:19.010: 	downscale filter:  Bicubic
16:30:19.010: 	fps:               60/1
16:30:19.010: 	format:            I444
16:30:19.010: 	YUV mode:          601/Partial
16:30:19.011: Audio monitoring device:
16:30:19.011: 	name: Default
16:30:19.011: 	id: default
16:30:19.011: ---------------------------------
16:30:19.025: No blackmagic support
16:30:19.073: NVENC supported
16:30:19.075: [obs-ndi] hello ! (version 4.2.3)
16:30:19.075: [obs-ndi] Trying ''
16:30:19.076: [obs-ndi] Trying '/usr/lib64'
16:30:19.076: [obs-ndi] Found NDI library at '/usr/lib64/libndi.so.3'
16:30:19.076: [obs-ndi] NDI runtime loaded successfully
16:30:19.076: [obs-ndi] NDI library initialized successfully
16:30:19.099: VLC found, VLC video source enabled
16:30:19.099: ---------------------------------
16:30:19.099:   Loaded Modules:
16:30:19.099:     vlc-video.so
16:30:19.099:     text-freetype2.so
16:30:19.099:     rtmp-services.so
16:30:19.099:     obs-x264.so
16:30:19.099:     obs-transitions.so
16:30:19.099:     obs-outputs.so
16:30:19.099:     obs-ndi.so
16:30:19.099:     obs-filters.so
16:30:19.099:     obs-ffmpeg.so
16:30:19.099:     linux-v4l2.so
16:30:19.099:     linux-pulseaudio.so
16:30:19.099:     linux-jack.so
16:30:19.099:     linux-decklink.so
16:30:19.099:     linux-capture.so
16:30:19.099:     linux-alsa.so
16:30:19.099:     image-source.so
16:30:19.099:     frontend-tools.so
16:30:19.099: ---------------------------------
16:30:19.099: ==== Startup complete ===============================================
16:30:19.099: Service '' not found
16:30:19.100: All scene data cleared
16:30:19.100: ------------------------------------------------
16:30:20.102: [obs-ndi] started A/V threads for source 'HOLMS.YELAVICH.HOME (Magewell_NDI)'
16:30:20.102: [obs-ndi] video thread for 'Magewell_In' started
16:30:20.102: [obs-ndi] audio thread for 'Magewell_In' started
16:30:20.105: Switched to scene 'Scene'
16:30:20.105: ------------------------------------------------
16:30:20.105: Loaded scenes:
16:30:20.105: - scene 'Scene':
16:30:20.105:     - source: 'Magewell_In' (ndi_source)
16:30:20.105: ------------------------------------------------
16:30:27.999: User Removed source 'Magewell_In' (ndi_source) from scene 'Scene'
16:30:28.012: [obs-ndi] video thread for 'Magewell_In' completed
16:30:28.012: [obs-ndi] audio thread for 'Magewell_In' completed
16:30:35.212: v4l2-input: Start capture from 
16:30:35.212: v4l2-input: Unable to open device
16:30:35.212: v4l2-input: Initialization failed
16:30:35.220: User added source 'Maewell' (v4l2_input) to scene 'Scene'
16:30:35.310: v4l2-input: Found device 'XI100DUSB-HDMI: XI100DUSB-HDMI ' at /dev/video0
16:30:35.312: v4l2-input: Found input 'Camera 1' (Index 0)
16:30:35.313: v4l2-input: Pixelformat: YUYV 4:2:2 (available)
16:30:35.313: v4l2-input: Pixelformat: 24-bit BGR 8-8-8 (unavailable)
16:30:35.313: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)
16:30:35.313: v4l2-input: Pixelformat: YU12 (Emulated) (available)
16:30:35.313: v4l2-input: Pixelformat: YV12 (Emulated) (available)
16:30:35.314: v4l2-input: Stepwise and Continuous framesizes are currently hardcoded
16:30:35.315: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
16:30:35.318: v4l2-input: Pixelformat: YUYV 4:2:2 (available)
16:30:35.318: v4l2-input: Pixelformat: 24-bit BGR 8-8-8 (unavailable)
16:30:35.318: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)
16:30:35.318: v4l2-input: Pixelformat: YU12 (Emulated) (available)
16:30:35.318: v4l2-input: Pixelformat: YV12 (Emulated) (available)
16:30:35.319: v4l2-input: Stepwise and Continuous framesizes are currently hardcoded
16:30:35.320: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
16:30:35.324: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
16:30:35.328: v4l2-input: Start capture from /dev/video0
16:30:35.328: v4l2-input: Input: 0
16:30:35.332: v4l2-input: Resolution: 720x576
16:30:35.332: v4l2-input: Pixelformat: VYUY
16:30:35.332: v4l2-input: Linesize: 1440 Bytes
16:30:35.332: v4l2-input: Framerate: 60.00 fps
16:30:43.478: v4l2-input: Stopped capture after 488 frames
16:30:43.486: v4l2-input: Start capture from /dev/video0
16:30:43.487: v4l2-input: Input: 0
16:30:43.491: v4l2-input: Resolution: 1920x1080
16:30:43.491: v4l2-input: Pixelformat: VYUY
16:30:43.491: v4l2-input: Linesize: 3840 Bytes
16:30:43.491: v4l2-input: Framerate: 60.00 fps
16:30:46.701: v4l2-input: Stopped capture after 195 frames
16:30:46.719: v4l2-input: Start capture from /dev/video0
16:30:46.720: v4l2-input: Input: 0
16:30:46.724: v4l2-input: Resolution: 1920x1080
16:30:46.724: v4l2-input: Pixelformat: VYUY
16:30:46.724: v4l2-input: Linesize: 3840 Bytes
16:30:46.726: v4l2-input: Framerate: 60.00 fps
16:30:49.181: v4l2-input: Stopped capture after 151 frames
16:30:49.199: v4l2-input: Start capture from /dev/video0
16:30:49.199: v4l2-input: Input: 0
16:30:49.203: v4l2-input: Resolution: 1920x1080
16:30:49.203: v4l2-input: Pixelformat: VYUY
16:30:49.203: v4l2-input: Linesize: 3840 Bytes
16:30:49.205: v4l2-input: Framerate: 60.00 fps
16:31:20.627: Failed to fetch parent window geometry!
16:31:20.627: gl_platform_init_swapchain  failed
16:31:20.627: obs_display_init: Failed to create swap chain
16:31:20.627: User added filter 'Magewell_NDI' (ndi_filter) to source 'Maewell'
16:31:27.784: Failed to fetch parent window geometry!
16:31:27.784: gl_platform_init_swapchain  failed
16:31:27.784: obs_display_init: Failed to create swap chain
16:33:03.451: [obs-ndi] starting main NDI output with name 'Master'
16:33:03.458: [obs-ndi] asynchronous video sending disabled
16:39:00.615: ==== Shutting down ==================================================
16:39:00.615: [obs-ndi] stopping main NDI output
16:39:00.615: Output 'main_ndi_output': stopping
16:39:00.615: Output 'main_ndi_output': Total frames output: 21429
16:39:00.615: Output 'main_ndi_output': Total drawn frames: 21060 (21430 attempted)
16:39:00.615: Output 'main_ndi_output': Number of lagged frames due to rendering lag/stalls: 370 (1.7%)
16:39:00.617: Switched to scene '(null)'
16:39:00.628: v4l2-input: Stopped capture after 29489 frames
16:39:00.711: All scene data cleared
16:39:00.711: ------------------------------------------------
16:39:00.734: Freeing OBS context data
16:39:00.737: [obs-ndi] goodbye !
16:39:00.746: == Profiler Results =============================
16:39:00.746: run_program_init: 1348.97 ms
16:39:00.746:  ┣OBSApp::AppInit: 0.808 ms
16:39:00.746:  ┃ ┗OBSApp::InitLocale: 0.686 ms
16:39:00.746:  ┗OBSApp::OBSInit: 1287.62 ms
16:39:00.746:    ┣obs_startup: 12.955 ms
16:39:00.746:    ┗OBSBasic::OBSInit: 1227.34 ms
16:39:00.746:      ┣OBSBasic::InitBasicConfig: 0.069 ms
16:39:00.746:      ┣OBSBasic::ResetAudio: 0.134 ms
16:39:00.746:      ┣OBSBasic::ResetVideo: 90.078 ms
16:39:00.746:      ┣OBSBasic::InitOBSCallbacks: 0.003 ms
16:39:00.746:      ┣OBSBasic::InitHotkeys: 0.051 ms
16:39:00.746:      ┣obs_load_all_modules: 87.366 ms
16:39:00.746:      ┃ ┣obs_init_module(frontend-tools.so): 3.041 ms
16:39:00.746:      ┃ ┣obs_init_module(image-source.so): 0.002 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-alsa.so): 0.001 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-capture.so): 0.373 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-decklink.so): 0.119 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-jack.so): 0.001 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.007 ms
16:39:00.746:      ┃ ┣obs_init_module(linux-v4l2.so): 0.001 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.478 ms
16:39:00.746:      ┃ ┃ ┗nvenc_check: 0.434 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-filters.so): 0.008 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-ndi.so): 11.671 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-outputs.so): 0.002 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-transitions.so): 0.006 ms
16:39:00.746:      ┃ ┣obs_init_module(obs-x264.so): 0.001 ms
16:39:00.746:      ┃ ┣obs_init_module(rtmp-services.so): 0.154 ms
16:39:00.746:      ┃ ┣obs_init_module(text-freetype2.so): 0.005 ms
16:39:00.746:      ┃ ┗obs_init_module(vlc-video.so): 3.786 ms
16:39:00.746:      ┣OBSBasic::ResetOutputs: 0.093 ms
16:39:00.746:      ┣OBSBasic::CreateHotkeys: 0.021 ms
16:39:00.746:      ┣OBSBasic::InitService: 0.831 ms
16:39:00.746:      ┣OBSBasic::InitPrimitives: 0.073 ms
16:39:00.746:      ┗OBSBasic::Load: 1005.58 ms
16:39:00.746: obs_hotkey_thread(25 ms): min=0.058 ms, median=0.169 ms, max=58.247 ms, 99th percentile=0.772 ms, 99.4326% below 25 ms
16:39:00.746: audio_thread(Audio): min=0 ms, median=0.056 ms, max=2.44 ms, 99th percentile=1.925 ms
16:39:00.746: obs_graphics_thread(16.6667 ms): min=0.469 ms, median=7.542 ms, max=997.212 ms, 99th percentile=10.372 ms, 99.3619% below 16.667 ms
16:39:00.746:  ┣tick_sources: min=0 ms, median=0.011 ms, max=990.999 ms, 99th percentile=0.025 ms
16:39:00.746:  ┣output_frame: min=0.461 ms, median=6.812 ms, max=8.791 ms, 99th percentile=7.648 ms
16:39:00.746:  ┃ ┣gs_context(video->graphics): min=0.461 ms, median=6.154 ms, max=8.209 ms, 99th percentile=6.885 ms
16:39:00.746:  ┃ ┃ ┣render_video: min=0.027 ms, median=6.088 ms, max=8.082 ms, 99th percentile=6.802 ms
16:39:00.746:  ┃ ┃ ┃ ┣render_main_texture: min=0.012 ms, median=1.891 ms, max=3.759 ms, 99th percentile=2.314 ms
16:39:00.746:  ┃ ┃ ┃ ┣render_output_texture: min=0.001 ms, median=0.044 ms, max=0.473 ms, 99th percentile=0.104 ms
16:39:00.746:  ┃ ┃ ┃ ┣render_convert_texture: min=0.001 ms, median=0.046 ms, max=0.351 ms, 99th percentile=0.08 ms
16:39:00.746:  ┃ ┃ ┃ ┗stage_output_texture: min=0 ms, median=4.077 ms, max=4.944 ms, 99th percentile=4.619 ms
16:39:00.746:  ┃ ┃ ┣download_frame: min=0 ms, median=0.009 ms, max=0.194 ms, 99th percentile=0.103 ms
16:39:00.746:  ┃ ┃ ┗gs_flush: min=0.001 ms, median=0.003 ms, max=3.957 ms, 99th percentile=0.004 ms
16:39:00.746:  ┃ ┗output_video_data: min=0.37 ms, median=0.663 ms, max=2.386 ms, 99th percentile=0.879 ms
16:39:00.746:  ┗render_displays: min=0.006 ms, median=0.69 ms, max=60.598 ms, 99th percentile=3.265 ms
16:39:00.746: video_thread(video): min=0 ms, median=5.891 ms, max=18.108 ms, 99th percentile=8.45 ms
16:39:00.746: =================================================
16:39:00.746: == Profiler Time Between Calls ==================
16:39:00.746: obs_hotkey_thread(25 ms): min=25.081 ms, median=25.243 ms, max=83.316 ms, 97.3489% within ±2% of 25 ms (0% lower, 2.65114% higher)
16:39:00.746: obs_graphics_thread(16.6667 ms): min=4.956 ms, median=16.667 ms, max=997.222 ms, 99.336% within ±2% of 16.667 ms (0.0291526% lower, 0.63488% higher)
16:39:00.746: =================================================
16:39:00.790: Number of memory leaks: 0

**Comment by lincolnstake** [comment]
In case it helps you, I had to tick the "async" checkbox in the NDI output dialog to get things going for the receiving PCs (was using Windows). Once they got the feed, I could uncheck the box.

**Comment by Palakis** [comment]
@TheMuso the latest releases fix a lot of issues with OpenGL rendering in the filter, which is used on Linux and macOS. Try the latest release and come back here if you run into any issue.
