### ISSUE TITLE
Not seeing NDI HX source, can see other NDI sources.

### ISSUE THREAD

**Issue by DaFiddlette** [Palakis/obs-ndi#136]
OBS 21.0.3

For some reason, I cannot see the PTZ Optics camera (NDI HX) as a source. I can see it in the NDI monitor but not in OBS. I can see two Connect Sparks and the NDI Scan Converter just fine.  My other computer,(Macbook Pro) with the same OS and OBS version can see the PTZOptics camera just fine. 

Thoughts?

High Sierra 10.13.3 
Model Name:	iMac
  Model Identifier:	iMac17,1
  Processor Name:	Intel Core i7
  Processor Speed:	4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Memory:	16 GB

**Comment by et84121** [comment]
I guess the reason is that NDI HX use H.264 as its codec. Not same as NDI use TICO codec.

**Comment by Palakis** [comment]
@et84121 NDI uses SpeedHQ, not TICO

**Comment by Palakis** [comment]
@DaFiddlette Is the application firewall enabled in Security & Privacy settings?

**Comment by DaFiddlette** [comment]
@Palakis , Yes. Even when the firewall is off, same result.  I now know however that this is a known issue and NewTek is working on it. Only one program/window can capture the PTZOptics camera at a time. You cannot have two instances of the cam up simultaneously. So for example, Ill either see it in OBS or in NDI Monitor but not in both and vice versa. This is a problem as I was hoping to control PTZ with the NDI Mon while streaming w/ OBS. The work around is to have control the cam w the second/back up computer and just send the OBS NDI Output to it from the first computer.

**Comment by Helgaiden** [comment]
You can also just use OBS to capture the NDI Monitor window

**Comment by DaFiddlette** [comment]
@Helgaiden, yes, that works but there seems to be some dropped frames doing it that way. Also, if I try and do that on the back up machine, (MacBooPpro, i5, 2.3GHz) I have complete signal degradation.  See attached..  The top two inputs are connect sparks, the bottom is the scan converter. They are not in sync either. It works fine on the main machine though.(MBP /i7 2.8GHz) I do have a GB Switch. 

<img width="1257" alt="screen shot 2018-04-20 at 10 51 20 am" src="https://user-images.githubusercontent.com/37718732/39061308-808c833a-4489-11e8-9dd4-fd5a0df1735d.png">

**Comment by et84121** [comment]
@Palakis I apologize for my ignorance

**Comment by DaFiddlette** [comment]
@ForrestScott, If you close NDI Monitor and then relaunch OBS, do you see the PTZCam then?

**Comment by ForrestScott** [comment]
No.  Let me clarify.  The cameras aren't even listed as a source when trying to choose an NDI source.  I can see and capture the NDI output from our Propresenter running on another Mac so I know that NDI is working.

**Comment by ForrestScott** [comment]
I understand but that is not my issue.  Even when OBS is started first, the cameras are not available to be chosen as a source.

**Comment by DaFiddlette** [comment]
Ah ok, the only other issue I had when trying to see my PTZOptics cam was
the firewall. First, under the Security/Privacy General tab, be sure the
app is allowed.  I  then added the rule to allow camera under the firewall
rules.  It was still somehow blocked. I just turned off the firewall and it
showed up. Thats the only other advice I can think of right now...

**Comment by ForrestScott** [comment]
Thanks, I'll check that out and report back.

**Comment by ForrestScott** [comment]
My firewall is turned off so that's not the issue.

**Comment by ForrestScott** [comment]
I found a solution to my problem. I had to install the New Tec NDI-HX driver. Once I did that I wad able to see the PTZOptics cameras in the source list.
