### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by Kazenin** [Palakis/obs-ndi#137]
Is possible to create this package?

**Comment by Gnuk** [comment]
I'm also looking for this package on fedora for example

**Comment by Redundanz** [comment]
Same here, can't use .deb package to install on Fedora.
Are there any workarounds / instructions for installing libndi/obs-ndi on Fedora/CentOS ?

**Comment by gbraad** [comment]
This has to be based of the package at RPMFusion. Any help I could provide?

**Comment by deepu105** [comment]
The instructions in https://github.com/Palakis/obs-ndi/issues/311 works
