### ISSUE TITLE
OBS seg fault when starting with empty source name

### ISSUE THREAD

**Issue by pschichtel** [Palakis/obs-ndi#143]
This happened the first time to me when facing #104, but even with working service discovery it is still possible to accidentally create a source without a name, when you NDI device is not on yet or not in the network yet.

The stacktrace is the same one as here: https://github.com/Palakis/obs-ndi/issues/104#issuecomment-361100205

OBS typically crashes shortly after I close the source dialog without selecting a source. Which is impossible to prevent if there are no source available. Only workarounds are to remove the source entry manually from the scene json before startup or to temporarly uninstall the plugin.

**Comment by Palakis** [comment]
@pschichtel Is it on Linux?

**Comment by pschichtel** [comment]
@Palakis yep. The setup is the same as in #104, forgot to mention that.
