### ISSUE TITLE
False Detection in newest release?

### ISSUE THREAD

**Issue by FitzKred** [Palakis/obs-ndi#146]
When you are about to install the latest version of NDI, you are prompt with Malwarebytes screaming at you there's a Adware Generic Table. Upon using Virus Total ( provided below ), there's 2 detections.

https://www.virustotal.com/#/file/7e4c844e879c416d035f9435743cc64a835bac46260c58e7e78293cc909dcd7a/detection

**Comment by ElectronicWar** [comment]
For only two reports it's very likely a false-positive.
