### ISSUE TITLE
NDI Runtime Not Found

### ISSUE THREAD

**Issue by FrosTValor** [Palakis/obs-ndi#148]
So i have been trying to get my new streaming pc to run ndi for about 4 days now and i cannont figure out how to fix the runtime not found issue. I have tried every possible thing and still nothing. Here is the log from when i get the error. 
[2018-04-09 05-10-29.txt](https://github.com/Palakis/obs-ndi/files/1889804/2018-04-09.05-10-29.txt)

**Comment by Helgaiden** [comment]
According to your log, your CPU is an Athlon 64. AMDs before the bulldozer FX series did not support Supplemental SSE3 aka SSSE3, and NDI needs this to work. No SSSE3, no NDI.

**Comment by FrosTValor** [comment]
@Helgaiden So is there anything i can do to use my second pc as a straming pc now?

**Comment by Helgaiden** [comment]
Check your motherboard's support page, look for the newest BIOS revision. Look to see if they add AM2+ (or better yet) AM3 or AM3+ CPU support. Look to see if any Bulldozer FX CPUs are supported, like the FX-4100 or FX-6100. If a newer BIOS allows support for these FX CPUs, then you can buy an FX CPU and upgrade to it and then you'll be able to use that PC for streaming. If you cant do that, then you're out of luck entirely.
