### ISSUE TITLE
NDI Source Freezes in Streamlabs OBS - Using NDI Scan Converter. 

### ISSUE THREAD

**Issue by Henry1k** [Palakis/obs-ndi#152]
Hi, 

Just purchased a streaming PC with a huge CPU. 
I now convert my game and system audio using NDI Scan Converter. 

LOOKS GREAT, SOUNDS GREAT. 

My only issue is say in a 5 hour stream my NDI Source will freeze atleast 3 times. 
I have to remove the source and reattach it, this solves the issue temporarily (until the next time) 

Any suggestions will be greatly appreciated as I do not want to stop using NDI but this is making things difficult. 

Thanks in advance!! 

Henry1k

**Comment by Palakis** [comment]
@Henry1k This is an issue with Streamlabs' fork of obs-ndi. Please report this on their bugtracker.
