### ISSUE TITLE
Cannot find NDI enabled Camera in sources. 

### ISSUE THREAD

**Issue by LukasW1337** [Palakis/obs-ndi#155]
Hi! 

I bought the app ["NDICam"](http://www.sienna-tv.com/ndi/ndicam.html), and tried to get it as an source in OBS. Didnt show up at all. Tried in vMix and it appears just fine. Is there a reason for this? Would it be able to be fixed?

**Comment by Palakis** [comment]
@LukasW1337 In your firewall settings (I presume you're running Windows), allow OBS to access Private and Public networks, and add a firewall exception for the program.

NDI relies on mDNS / Bonjour network discovery and network profiles on Windows can conflict with this.
