### ISSUE TITLE
NDI Not found runtime

### ISSUE THREAD

**Issue by vKhaloode** [Palakis/obs-ndi#160]
NDI Not Work and No Runtime found

**Comment by vKhaloode** [comment]
Help me guys to fix this problem i've been searching in youtube and it doesn't works can you guys help
i actually when i install it i restart my computer but when i finish to restart it i just open obs and it said no ndi runtime found can you guys please tell me to fix this problem :(

**Comment by vKhaloode** [comment]
it actually works in my streaming pc but gaming pc no but i don't what is problem for this i just reboot or restart my computer and nothing happend what a bad lucky

**Comment by Helgaiden** [comment]
You're missing some of information in your request. Post an OBS log of when the issue happens. What CPU are you using in that machine? You may have to manually put the NDI runtime in the folder. On the plugin download page: https://github.com/Palakis/obs-ndi/releases/tag/4.3.0

you would download the zip file, obs-ndi-4.3.0-Windows.zip, then copy the contents of the archive to the root of your OBS Studio installation folder. That could help.
