### ISSUE TITLE
Windowed capture working, Fullscreen locked up

### ISSUE THREAD

**Issue by ERDKayy** [Palakis/obs-ndi#162]
# Specs:
**Gaming PC**
- i7 7700k
- rx 480
- 16gb ram
- Dual monitors

**Streaming PC**

- ryzen 5 1600
- 16gb ram
- gtx 1060

# **Issue:**

Using NDI Scan converter to send Game capture to OBS.
Attempting to send Specific game capture (in this case Fortnite) over NDI to OBS studio running ndi 4.4.0.
If I send game capture when fortnite is in windowed or Fullscreen-windowed mode I get signal and works as intended. However when I capture fortnite in full screen It shows a single frame locked up, I can see the mouse pointer moving on screen and getting sound feedback. No game capture whatsoever.

Same issue persists with other fullscreen applications.

**Comment by spencerhon** [comment]
I have the same issue. Can some one help?

**Comment by Palakis** [comment]
@ERDKayy What are you Game Capture settings? Selecting "Capture any fullscreen app" might help.

**Comment by Palakis** [comment]
Oh wait, you're using NDI Scan Converter. Try using vMix Desktop Capture, or even OBS on the gaming pc to capture Fornite and send it over NDI.

**Comment by droopified** [comment]
same issue. notice with my game (PUBG) more lag while in window mode as of this post. lag free in full screen but then i cant use NDI.
