### ISSUE TITLE
More settings for stream quality

### ISSUE THREAD

**Issue by iBobik** [Palakis/obs-ndi#164]
Currently there are only two presets for quality. Is it possible to separate options for bitrate and fps?

My use case: I want to stream PC desktop and needs to have it in highest possible image quality. But it shows only slides without animations, so FPS could be 1 without problem. I can save network for cameras and have nice picture from desktop.

**Comment by Palakis** [comment]
@iBobik The NDI plugin internally uses the NDI SDK provided by NewTek. It is not possible currently to have more than the available quality settings. Rest assured that if NewTek adds more quality settings, these will be implemented in the source and output settings.
