### ISSUE TITLE
CPU usage doubling

### ISSUE THREAD

**Issue by ForrestScott** [Palakis/obs-ndi#165]
Ok, I have a weird one.  When I first start an NDI source, OBS reports my CPU usage is around 14%.  At some point, my CPU usage will double to aprox 30%.  If I pull up the NDI source properties and then press OK, my CPU usage drops back down to 14% for some time until the cycle repeats itself.

When I look at the logs, I see that OBS restarts the threads when I do this:

18:59:54.492: [obs-ndi] video thread for 'PTZ Camera 1 (Center)' completed
18:59:54.492: [obs-ndi] audio thread for 'PTZ Camera 1 (Center)' completed
18:59:55.561: [obs-ndi] started A/V threads for source 'PTZOptics_Camera_1 (Channel 1)'
18:59:55.561: [obs-ndi] audio thread for 'PTZ Camera 1 (Center)' started
18:59:55.561: [obs-ndi] video thread for 'PTZ Camera 1 (Center)' started

Running:
OBS 21.1.1
NDI 4.4.0
Max OS X 10.10.5
iMac 2.7Ghz I5
8 GB ram

**Comment by ForrestScott** [comment]
I have duplicated the problem on a Windows PC running OBS 21.1.2.  After some time, the CPU load will double.  Pulling up the NDI source for the PTZ camera will restart the thread and the CPU load goes back to normal for a period of time.

**Comment by ForrestScott** [comment]
Has no one else seen this issue?

**Comment by TekSoup** [comment]
if your running win 10, turn off the xbox dvr capture. it is in the settings for games. no background capture.  i saw same issue in another forum, so try that
________________________________

**Comment by ForrestScott** [comment]
Thanks for the reply but I am running OBS on a Mac.  I found the cause over on a VMix forum.  The culprit is the NewTek NDI HX driver needed for the PTZ Optics NDI cameras.  A newer version of the driver fixes the CPU load doubling.
