### ISSUE TITLE
Multicast (Real Broadcast)

### ISSUE THREAD

**Issue by reustaquiojr** [Palakis/obs-ndi#169]
> MULTICAST OR UNICAST Flag? Multicast can seem like a bandwidth-saving miracle. Unlike NDI’s default mode (unicast), multicast does not require a unique stream from the source to each receiver. When using unicast, each connection to the sender reduces the bandwidth available by a similar amount.

According Newtek forum ! 

Could we see theese capabilities in future ?

**Comment by Palakis** [comment]
@reustaquiojr you can enable Multicast NDI in the NDI Access Manager app.

**Comment by reustaquiojr** [comment]
Sorry.. but Is there an Access Manager for Linux ? I`m using OBS 21.1 on Ubuntu host !
