### ISSUE TITLE
Can not receive signal from multiple networks

### ISSUE THREAD

**Issue by iBobik** [Palakis/obs-ndi#170]
This setup works:
- Mac running OBS and receiving over NDI:
- iPhone connected by USB (tethering) with app JustWiFiCam
- Sienna Scan converter on the same Mac

But when I create wifi network on the mac and connect there iPad (with JustWiFiCam) then OBS can not receive it's signal (I can see iPad in sources list, but no image is loaded). Sienna NDI Monitor can receive signal for iPhone, Scan converter and iPad correctly.

**Comment by narcogen** [comment]
Out of curiosity, try turning the low bandwidth option ON, and then if image appears, turn it off. This seems to work many times (not all times) for me when I have problems getting an NDI source to appear under MacOS.

**Comment by Palakis** [comment]
Should be better since NDI 3.5. Closing.
