### ISSUE TITLE
Game (not stream!) stuttering when using NDI plugin

### ISSUE THREAD

**Issue by Cerunya** [Palakis/obs-ndi#172]
Hiya everyone, 

so I am having the strangest issue. I am using the plugin to stream to from OBS on my gaming machine to OBS on my streaming machine (1st: ryzen 2700, second: ryzen 1700, so both are pretty good, I generally do not need to use NDI I just wanted to play with it to test it out). Anyway. The stream and everything goes perfectly well. No issues whatsoever. 

BUT: No matters what game I play, I am getting microstutters in game. Not the stream. The game. It just hangs for a second or so. They are only there when I use OBS with with NDI-plugin runing. If I game normally or stream without the plugin just from my gaming machine everything is fine. 

Any ideas as to why this would happen? Thanks in advance!

**Comment by Palakis** [comment]
@Cerunya NDI can be CPU-intensive sometimes. Try with different in-game performance settings and see if it fixes the microstutters.
