### ISSUE TITLE
NDI - Gaming PC showing nothing when sourcing to streaming PC

### ISSUE THREAD

**Issue by SwerL1** [Palakis/obs-ndi#173]
I can source my streaming pc to my gaming and see its desktop, but when I try to send my gaming pc screen to my streaming one nothing comes up.

Any help?

**Comment by SwerL1** [comment]
Nevermind, I got it to work!

**Comment by Banbeucmas** [comment]
No the problem doesn’t end there
Same as #167
The problem is it will work and it won’t depends on your luck, this is the same problem I am encountering.
It might always work for some people, it might not for some.
