### ISSUE TITLE
Performance Issues with multiple NDI Sources (Video / Audio)

### ISSUE THREAD

**Issue by Morodar** [Palakis/obs-ndi#174]
## Summary

I'm currently trying to find the **best settings** and **applications** to be able to **stream multiple** (at least 6) **gaming PC's** (+Local Webcams, +multiple IP-Wecams, +multiple Microphones / Audio Sources, + Capture Cards) - all at **1080p@60FPS**, **recording and streaming**.

So far I'm making good progress, however, after reading many forums and issues, I still could not **fix stutters from some sources** (some work like a charm).

## Example

A **YouTube-Video** of the **stuttering** can be found [here](https://www.youtube.com/watch?v=N0vq8Ooupf0).

### Information to Example

- I've recorded a Video where all PC's can be seen at once. 
- CPU / Memory / Network / GPU workload of the Streaming PC can be seen in the middle of the screen
  - **CPU** ~70% (**OBS** ~45%)
  - **RAM** ~ 18%  (3 GB /16 GB)
  - **Network** ~52%, (Gbit)
  - **GPU** ~18%
- **Audio** of one PC is enabled, the others are **disabled** (**stutter** a lot).  
- **Preview stutters** just like the Video
- **Encoder**: NVENC ( on Gaming & Streaming PCs)
- Games run between **1000 FPS** and **2000 FPS**
  - Game is called [osu!](https://osu.ppy.sh/home) which is not GPU heavy
- The **video** of the **Webcams** are **always smooth**
- I've tried **all three Sync Modes** (Internal, Network, Source Timing)

## Logs

The Log of the Streaming/Recording PC can be found [here](https://gist.github.com/Morodar/f9cf66b74b72f73cde638a5cc6bbf82a)

## Setup

I don't know if it matters, but the **monitors run @144Hz**

### Software

- **OBS Studio:** 21.1.2
- **NewTek NDI:** 3.5
- **obs-ndi:** 4.4.0
- **GEFORCE Driver**: 398.11 (06/05/2018)
### Streaming PC

- Intel Core i5-6600K 3.50 GHz running @ 4.2GHz
- 16 GB DDR4 RAM @ 2133 MHz
- Nvidia GTX 1080 ( 8GB RAM)

### Gaming PC

- AMD 8 Cores (16 Threads) @ 3.2 GHz, 8 GB DDR4, Nvidia GTX 1060
- OBS + NDI-OBS Plugin used as output

### Switch

It's a 24-Port Gbit-Switch:  
[HP ProCurve Switch 1800-24g j9028b](https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-c01955915#N10013)
Maybe the switch is too old?

## Note
The Stutter also occurs when I do not have a 6-PC-All-in-One-Scene.  
If I have 6 separate Scenes each receiving 1 PC, the preview still lags :| .  
Receiving 3 Sources (instead of 6) works like a charm. 

I appreciate any suggestions!  

STUDY HARD, PLAY HARDER! 😄

**Comment by Helgaiden** [comment]
That's a ton of traffic for a switch to handle, even though all ports would be gigabit the processor and RAM within the switch itself (and possible configuration) can all have an impact in how well all the data goes through it. I've done something similar to you with anywhere from 4-6 PCs and webcams and had similar issues. I hated that I had to do this, but enabling the low quality setting on each laggy NDI source cured the issue, leading me to think it was the power of the switch itself as the bottleneck and also probably the CPU in the streaming rig receiving all these inputs. At some point I plan to try to a 8 or 10 core cpu in my stream rig and see how that goes (I think an e5-2680v2 is only like $240 on eBay), as well as trying a custom configured Enterprise grade switch (a good friend is a network manager and can probably figure it out).

**Comment by ThePooN** [comment]
Going off-topic, but I imagine you're setting this up to stream an osu! tournament. In that case, using the osu!tourney client is way more recommended: https://osu.ppy.sh/help/wiki/osu!tourney

This is used by tournament organizers to stream multiplayer lobbies. It spectates every players at once and synchronize them.  
osu!'s network implementation isn't real-time, so if you're simply capturing every PC's display, it won't be synchronized. This is what the osu!tourney client is for.

**Comment by Morodar** [comment]
@ThePooN 
Thanks for the suggestion, apparently that's not the case. ^~^  
I've used **osu!** because I can let it play long beatmaps and use auto-pilot.  
It's much easier to setup than 6 League of Legends / CS:Go / any other game.  

## Panned Games for tournaments
We plan to play and stream on:

- League of Legends
- Overwatch
- Counter Strike: GO
- Rocket League
- Hearth Stone
- ... ?

**Comment by Morodar** [comment]
## Still Testing different Settings

@Helgaiden

> Im leaning towards your streaming PC CPU having a weak CPU for encoding that many input sources first imo. I asked my friend about your switch and he says that should be good enough, but your i5 as an encoding CPU might be letting you down. You said you have NVENC configured, but thats for streaming out to the internet not taking the inputs in. That still uses CPU......well unless you maybe check the "hardware acceleration" box for every NDI source. Hmmmm

### CPU
Fair point with the **weaker CPU** I use **as encoder**.  
I **turned hardware acceleration on** because of the huge workload.  

I still believe that the CPU should able to handle the workload since the **CPU** has a **stable 70% usage**.  
I've also tested one gaming machine as Encoder (which has more cores/threads) but everything still shuttered (in this case all scenes shuttered, while the "weaker" one outputs three scenes quite good as seen in the [video](https://www.youtube.com/watch?v=N0vq8Ooupf0))


### Even more Testing
I'm still testing every **reasonable combination** of **settings** to archive a good result.  
When I set the **bandwidth** to **lowest**, everything works just fine. (but the Quality is too bad)  

### Bandwidth Options?
Is it possible to **limit** the **NDI Output bandwith**?
I would like to **limit** the Output bandwidth to e.g. **50 Mbit/s** instead of **100 Mbit/s**.

**Comment by Helgaiden** [comment]
The only way to lower bandwidth usage as far as im aware is to configure the video settings on each PC to a lower resolution at 30fps. 720p30 i believe uses around 100 Mbps, so you'd have to try going lower than that to see if the result i bandwidth usage scales further down. As far your CPU workload staying around 70%, well my stream PC i've done this similar setup on would also only get up to around 60%ish, and thats when things start getting wonky. If OBS is using 70%, then realistic CPU load is pretty close to maxed out i think especially if that rig has other windows open, browser tabs, music playing, chat programs running, etc since the OS and misc programs are adding extra load that isn't reflected in OBS's stats. Im not sure how well the hardware acceleration works with NDI so i cant really speak to that. The low bandwidth mode on the sources causing them to run well only points to two things to me...
-Network performance
-Weak CPU still. And i say this about the CPU since low bandwidth mode = less data to process

Maybe @Palakis can chime in at some point

**Comment by Morodar** [comment]
@Helgaiden 
Whoops, I meant that the whole System takes 70%.

If you look at the [video](https://www.youtube.com/watch?v=N0vq8Ooupf0), you can see that **OBS takes about 45%** - the **System has a CPU usage of ~70%**.

**Comment by girald0** [comment]
Try using the new version of NDI Tools' Scan Converter to send the content via NDI , works way better than before.

**Comment by Morodar** [comment]
@girald0 

Thanks for the tip, I've tried Scan Converter, apparently the problem stays.
[Wikipedia: NDI](https://en.wikipedia.org/wiki/Network_Device_Interface): tells something about **NDI HX** which only requires 8-20 Mbit/s. I could not figure out how to set NDI Scan COnverter to use it (?)

---

## Problem solved!

The switch caused the problem.  
I plugged all the Gaming PCs and the Streaming PC into this switch: 
[D-Link DGS-108](https://eu.dlink.com/de/de/products/dgs-108-8-port-gigabit-ethernet-switch)

Depending on the game, six 1080p@60FPS causes up to 800 MBit/s traffic (depending on game).

My "Streaming PC" does not have enough CPU power.  
So I still have lags but I know that it depends on my machine (CPU).

I've tried one Gaming PC (which also lagged with the old switch) with 5 Inputs and it finally works pretty good!

---

When I came up with a final solution I'll make another Video and post it here.

**Comment by Helgaiden** [comment]
Good to know that CPU power of the streaming PC really does play a factor as much as i thought it would, will help me with my eventual config.
