### ISSUE TITLE
NDI Plugin using more network than it should.

### ISSUE THREAD

**Issue by ijsPod** [Palakis/obs-ndi#180]
So I've looked around and everyone's solution seems to be 
"open a command prompt, run this command, reboot.
netsh int tcp reset"
However this does not work for me at all. I've ran the command prompt as and admin and it says its successful then I reboot my PC and I still am using 99% of my network with this plugin.
I've ran this on both PCs as well and nothing has changed.
Thanks in advanced for any tips!
Edit: It is now up to 93mbps when the original issue was only 18-20

**Comment by TweakGames** [comment]
If you are using 99% of your network doing 93 mbps, get a gigabit nic.  A 10/100 network isn't recommended for this at all.  Mine at 1080p, only send 20 mbps, when it's a completely black screen, sending nothing. Over 150 mbps when something is actually happening.

**Comment by ijsPod** [comment]
I've been using this for a month and a half prior to this happening, with no issues same hardware. It randomly started happening a day before I posted here.

**Comment by ForrestScott** [comment]
Did you update your NDI driver?

**Comment by ijsPod** [comment]
No, unless it has auto updates. I've also uninstalled and reinstalled on both PCs in the process of trying to fix it.
