### ISSUE TITLE
Feature Request - CPU/GPU SElection

### ISSUE THREAD

**Issue by dvaguirre** [Palakis/obs-ndi#183]
NDI is used in OBS as capture card alternative, games like PUBG need insane GPU.
We need the option to choose between CPU or GPU.

**Comment by Helgaiden** [comment]
PUBG is actually also very sensitive to CPU so it isn't just "crazy GPU intensive." That aside, "use hardware acceleration" is already an available option for NDI sources. While/after adding an NDI source, the properties of that source has the check box you're looking for.

But as it stands, it already uses very little CPU so if you're having an issue with resource use of NDI, you might want to double check the rest of your system too.

**Comment by Palakis** [comment]
NDI uses the CPU for encoding and decoding. You can also optionally enable GPU hardware acceleration for decoding in the NDI source settings.
