### ISSUE TITLE
Feature Request - NIC/TCP IP Address selection

### ISSUE THREAD

**Issue by dvaguirre** [Palakis/obs-ndi#184]
I can block exe or NDI traffic for some network on windows firewall (not the best option).
We need the option to choose NIC and/or TCPI IP Address for NDI.

**Comment by Helgaiden** [comment]
Pretty sure the NIC NDI uses thru OBS is the NIC you can specify for OBS to use in the regular OBS settings.

**Comment by Palakis** [comment]
@dvaguirre Right now there's no such setting in the NDI SDK itself.

**Comment by Palakis** [comment]
@Helgaiden 
> Pretty sure the NIC NDI uses thru OBS is the NIC you can specify for OBS to use in the regular OBS settings.

Nope, unfortunately... :/

**Comment by dvaguirre** [comment]
And about choose CPU/GPU or GPU1/GPU2, any chance @Palakis?

@Helgaiden if I choose one NIC on OBS I cant for exemple, provide NDI to another PC and stream to another provider from that one (w/o a gateway in that NDI network). 

*** OBS as NDI Source uses more CPU/GPU that Scan Converter. Streaming 90 or 120FPS is the only reason to use OBS as source, that Scan Converter cant do.

https://www.twitch.tv/videos/280461568

**Comment by Palakis** [comment]
> And about choose CPU/GPU or GPU1/GPU2, any chance @Palakis?

Nope, unfortunately.
