### ISSUE TITLE
Audio choppy / distorted while streaming and recording - OBS Studio with NDI Plugin

### ISSUE THREAD

**Issue by Abaddonix** [Palakis/obs-ndi#185]
Hey @Palakis I have searched all over google, forums, reddit, and here to find a solution. I was streaming about a month ago using NDI plugin for OBS Studio, everything worked great! Audio quality was great, and so was video. I took a month break and came back last night to stream and for some reason my audio is incredibly choppy / distorted.

I've tried all sorts of fixes, I've installed the latest versions of NDI plugin, as well as OBS to no avail. The audio monitoring sounds perfect on the stream PC (destination PC), I have the highest bandwidth setup on this as well. Nothing has changed on my setup since I last streamed, just can't seem to figure out what the deal is.

Both PCs are connected via 1gb ethernet, the quality of audio is terrible for both recording and streaming.

Thanks in advance for any help you could provide, and thanks so much for creating this plugin! It's seriously been amazing using it up until this point.

**Comment by Palakis** [comment]
@Abaddonix samples & logs, please
