### ISSUE TITLE
Not getting 60fps and micro stuttering

### ISSUE THREAD

**Issue by Maelas84** [Palakis/obs-ndi#189]
Hello All,
The issue I have may be related to the below issues:

https://github.com/Palakis/obs-ndi/issues/43
https://github.com/Palakis/obs-ndi/issues/100
https://github.com/Palakis/obs-ndi/issues/59

My systems:
GamePC - 4770k and GTX 970 and 32GB RAM
StreamPC - 2 X5650 and GTX 770 and 24GB RAM

I use OBS + NDI for streaming and I/my viewers have noticed though the stream says its 60fps, it definitely does not look like it and my stream has lot of micro stuttering going on. Right now the main issue I want to tackle is the stuttering.

I have removed and reinstalled Nvidia drivers
I have made sure both computers have a 1Gps connection.
I have updated NDI to 4.5.0 on both computers
Game mode is disabled on both devices.
I have downloaded and used  NewTek Studio monitor on my streamPC and had OBS use window capture to capture the monitor window and did not notice any change. 
Here is an example of that https://www.twitch.tv/videos/283882753

Log from streampc = https://hastebin.com/redeqipiqe
Log from gamepc = https://hastebin.com/ozowedeziz

An example of the issue using obs NDI is here: https://www.twitch.tv/videos/283846084

Im kinda out of things to try and am considering just going to a capture card method. Is there anything at all I can try to help figure this out?

**Comment by Maelas84** [comment]
Here is an example of me using NDI Scan Converter instead of OBS on the gamePC - https://www.twitch.tv/videos/283920562

**Comment by Maelas84** [comment]
I will attempt to remove OBS from gamingPC and remove NDI tools from StreamPC. I am going to attempt to use the NDI scan converter on gamepc and only OBS NDI on streampc to see if this helps.

**Comment by Maelas84** [comment]
So i have been doing much testing and I do in fact see no problems when i use NDI Scan Converter alone on the gamePC. As long as OBS is not used, I have no issues. Unfortunately I couldnt for the life of me figure out how to work the audio over to the streamPC so I went with a capture card. BUT as long as OBS is not in use on GamePC, all is well. Very odd though

**Comment by zovk** [comment]
i cant installing scan converter hes stop on the instalation screen and now i wait 15 minits O o
