### ISSUE TITLE
32bit deb build

### ISSUE THREAD

**Issue by JonnyTech** [Palakis/obs-ndi#190]
There are only 64 bit deb builds in the releases section, any possibility of supplying 32 bit deb packages too?

**Comment by Palakis** [comment]
@JonnyTech I have no plans to provide 32-bit binaries on ubuntu, as the NDI runtime is optimized for 64-bit processors and 90% of users run NDI on 64-bit systems.

**Comment by Palakis** [comment]
However, if you're interested in contributing this, i'd be happy to review your pull request!
