### ISSUE TITLE
GPU usage 100% when not using hardware acc/nvenc

### ISSUE THREAD

**Issue by wazerstar** [Palakis/obs-ndi#193]
So since my 1070 gpu is getting replaced im using a backup 520gt card from nvidia and using my cpu to encode with.

I did a test stream here, as you can see the video "encoding" is flawless and the fps shows 60fps output but the inside the ndi pluging/obs it shows 20-45 fps jumping around.
https://www.twitch.tv/videos/287042546##

Began hunting down issues and immediately i saw the gpu usage on the 520gt gpu was 100% usage, why, i'm not even using the gpu at all?
https://image.prntscr.com/image/IiXxr4H-RXSRprLeDX84bg.png

Video preview is disable and hardware acceleration is un-ticked in ndi source.
https://image.prntscr.com/image/JsK33T0QQH6xOaVpK-hTDA.png

Here's a log from obs just opening obs and the gpu usage is 100% disabling ndi it goes down to 0% again

[2018-07-20 19-30-22.txt](https://github.com/Palakis/obs-ndi/files/2214889/2018-07-20.19-30-22.txt)

**Comment by TekSoup** [comment]
that card does not have nvenc im pretty shure.

**Comment by wazerstar** [comment]
@TekSoup I was not using nvenc, think you did not read :)

**Comment by CoDEmanX** [comment]
I ran into an issue recently, where GPU load was also on 100% all the time, but not using NDI or anything. This happened after updating the Nvidia graphics driver. After a reboot it went back to normal, with maybe 10% load.

Another thing you might try is a different color range and space. I saw YUV full 709 causing massive CPU load once when I changed these settings in OBS. Again, this was not related to this plugin in any way, but maybe something you can test.

**Comment by Palakis** [comment]
@wazerstar did one of the NDI sources in OBS had hardware accel enabled?
