### ISSUE TITLE
OBS NDI and the "Video Delay" (Async) filter

### ISSUE THREAD

**Issue by cazrep** [Palakis/obs-ndi#194]
I help run a competitive Rainbow Six Siege stream and I wanted to use NDI as apart of my dual PC stream setup. The NDI plugin is fantastic and I didn't run into any issues until I started using the "Video Delay" function to delay the feed.

To give a little insight on my setup I need to delay the game feed on my streaming PC because I stream my game feed from my Gaming PC to a RTMP server so my casters can see the feed before the stream and properly sync the casting with whats happening in game for the viewers. So I have tried using the "Video Delay" filter in OBS to accomplish this.

The first time running this setup I start experiencing terrible audio delay issues and it was affecting the viewership pretty greatly. I have conducted multiple paths of troubleshooting that still haven't pointed out anything that is specifically causing the audio to derail from the video. I chased down every post on the OBS NDI plugins page and OBS forums for audio delay issues when using NDI. 

A brief rundown of some of the configurations I tested to try and solve my problem include changing the timings (source, network internal), including a separate audio only source and changing the timings there as well, reinstalling drivers, reinstalling audio devices, re-configuring OBS and all devices included.  

With no success I re-watched some of my streams and noticed the VIDEO was speeding up and slowing down randomly or during rapid camera switches (basically slo-mo moments and super sonic fast moments were happening)

After I noticed this I tested it and streamed it so I can verify it. The clip below shows that fast moving and camera switches (or switching to "drones" as you see in the video) causes the VIDEO to really screw itself up.

The clip provided has a 4000ms "Video Delay (Async)" filter applied to the NDI source. Without the filter the video and audio stay perfectly synced but heres an example of the filter causing the audio and video to desync. I also applied the same amount of AUDIO delay in the "Advanced Audio Properties" to properly sync video and Audio

https://www.twitch.tv/videos/287128780

Gaming PC:
Intel i7 4790k
16 GB DDR3 Ram
GTX 1080

Streaming PC
FX 6300 (Which i specifically chased down for the SSSE3 support)
8 GB RAM
GTX 660

TL:DR
I believe the OBS filter "Video Delay (Async)" is not functioning properly with the NDI source for OBS, or vice versa. I don't personally have enough experience other than my troubleshooting efforts to point to which specifically is causing the problems but this is what I found and I'm hoping to bring it to someones attention. So couple questions I have are:

Is this an issue with a feature in OBS or is it NDI? 

Is it a fault of my own using this filter? Are there alternatives I should be using to accomplish this?

Has anyone else noticed this happening when they use the filter?

Thank you for taking some time into reading into my issue. The plugin works great for when I play around with it I just haven't been able to put it to good use and I really want to. I've resorted to using the "Record to URL" feature so I can use VLC to delay the video feed and thats been working great but NDI is much more straightforward and flexible and would like to take advantage of it. 

If there is any missing information I will update the post.

**Comment by kstebbs** [comment]
I am having this issue as well, though not with NDI source. It is happening with any video source (most notably Video Input Capture). The footage occasionally speeds up or slows down, and it's totally random. I feel that the plugin might not be properly optimized, as my machine is quite powerful and brand new.
