### ISSUE TITLE
NDI won't show drop down sources on stream PC when NDI Output is set on game PC

### ISSUE THREAD

**Issue by smashlolcs** [Palakis/obs-ndi#195]
I see a whole lot of problems with this program but I couldn't find a solution to mine. I think it might have to due with some porting, I'm not too technical in that area.

But today I purchased a Linksys gigabyte ethernet usb3 adapter to connect my main PC to my stream pc.

Couple troubleshoots here and there, finally got a working connection between two PCs, WHOO!

Spent the half day doing that, now I've spent the other half trying to figure out why it just doesn't work on my stream PC. 

Everyone seems to have a red dot or black screen, but I didn't even get passed that part. I simply cannot select the outputs on my stream PC, there is nothing in source name. It's almost as if my stream PC is on it's own network or something... BUT NDI output on my stream PC will show up on my gaming PC however.

Can anybody help? I think my i5 2400 should be compatible. I am using a bridged connection on my main PC to share the internet with my stream PC.

**Comment by smashlolcs** [comment]
Solved. Don't use usb dongle.

**Comment by wazerstar** [comment]
@smashlolcs what adapter for others to come, and did you ever try maybe a intel usb dongle if it exist.
