### ISSUE TITLE
Feature request, broadcast active window on main rig

### ISSUE THREAD

**Issue by wazerstar** [Palakis/obs-ndi#197]
r1ch has already created this, I have not tested this, but I guess it works as described, would be really cool to get implemented to your ndi plugin @Palakis 

https://r1ch.net/blog/findwindowlan

**Comment by Palakis** [comment]
@wazerstar can you describe more precisely what you're looking for, please?

**Comment by wazerstar** [comment]
@Palakis what r1ch tool does just by sending it via ndi with your tool instead of another application

FindWindowLAN

I made a small utility for two PC stream setups called FindWindowLAN. When run in "Send" mode, it will broadcast the foreground window title to a PC on the same network that's in "Receive" mode. This lets applications like OBS Studio's automatic scene switcher function on your encoding PC, as it thinks the application is open locally. The name comes from the Windows API call "FindWindow", which many applications use to find an active window.
