### ISSUE TITLE
Lag And Framedrops in Preview and stream

### ISSUE THREAD

**Issue by AkmanTV** [Palakis/obs-ndi#199]
Hello guys, I'm trying to stream with using obs ndi, but i got huge lag and fps drops in preview.

My lan speed is 120 mbps per second
Gaming Rig : 
Ryzen 1800X
Gtx1060
16 GB RAM
Streaming Pc : 
I7-2630QM
4 Gb ram

Seems like i couldn't handle the setup process, game lags so much. 

Can anyone help ? 
https://www.twitch.tv/videos/293046274 Cpu prest fast 
https://www.twitch.tv/videos/293057758 : Cpu preset ultra fast

**Comment by danielpetre** [comment]
If you're not on a gigabit you should be. If you are on a gigabit switch and you are still having problems maybe you can set up a dedicated gigabit link between the two computers.
