### ISSUE TITLE
obs-ndi on MacOSX - problem with loading obs-ndi.so due to  QtWidgets version mismatch

### ISSUE THREAD

**Issue by warrior1724** [Palakis/obs-ndi#20]
Hi 
thank you for your great job !
but  I have got error. 

error: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1): Library not loaded: @rpath/QtWidgets

  Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
  Reason: Incompatible library version: obs-ndi.so requires version 5.9.0 or later, but QtWidgets provides version 5.8.0

warning: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not found

environment:
MacOSX 10.11.6
OBS-Studio - 19.0.2

Update: 
OBS 19.0.2 for Mac OSX is build/using Qt 5.8.0 version.

**Comment by Palakis** [comment]
Hmm, seems like Homebrew already has the latest Qt version. Gonna fix this and issue a hotfix release.

**Comment by Palakis** [comment]
@warrior1724 Does this error happens with the release build of obs-ndi 4.0, or did you build it yourself?

**Comment by warrior1724** [comment]
It happens with obs-ndi 4.0. 

otool -L obs-ndi.so |grep Qt
	@rpath/QtWidgets (compatibility version 5.9.0, current version 5.9.0)
	@rpath/QtGui (compatibility version 5.9.0, current version 5.9.0)
	@rpath/QtCore (compatibility version 5.9.0, current version 5.9.0)

Official OBS 19.0.2 is build with 5.8.0 Qt

otool -L obs |grep Qt
	@rpath/QtWidgets (compatibility version 5.8.0, current version 5.8.0)
	@rpath/QtGui (compatibility version 5.8.0, current version 5.8.0)
	@rpath/QtCore (compatibility version 5.8.0, current version 5.8.0)

I think you are building OBS and obs-ndi from source and both are using Qt 5.9.0 but most users are simply download OBS and obs-ndi in binary form.

**Comment by Palakis** [comment]
The OS X version of obs-ndi is built on Travis. The build script installs Qt using Homebrew, and apparently Homebrew switched from Qt 5.8 to Qt 5.9, and removed 5.8 from their formulas.

**Comment by Palakis** [comment]
Seems fixed, a build is in progress on Travis.

**Comment by Palakis** [comment]
Here's the latest build, with Qt dependencies supposedly fixed: http://obs-ndi-osx-builds.s3-eu-central-1.amazonaws.com/obs-ndi-c3dfc02-master.pkg
@warrior1724 Can you please test it and tell me if it works on your system?

**Comment by warrior1724** [comment]
Unfortunelty no :(

two problems
1
error: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1): Library not loaded: /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
  Reason: image not found

warning: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not found

2.  when I copied Qt* from OBS to /usr/local/opt/qt5/lib/* (just for test)

objc[48678]: Class RunLoopModeTracker is implemented in both /Applications/OBS.app/Contents/Resources/bin//QtCore and /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore. One of the two will be used. Which one is undefined.
objc[48678]: Class NotificationReceiver is implemented in both /Applications/OBS.app/Contents/Resources/bin//QtWidgets and /usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets. One of the two will be used. Which one is undefined.

info: [obs-ndi] hello ! (version 4.0.1)
info: [obs-ndi] Found NDI library at /Library/Application Support/obs-studio/plugins/obs-ndi/bin/libndi.dylib
QWidget: Cannot create a QWidget without QApplication

and OBS crashed.

**Comment by Palakis** [comment]
@warrior1724 I forgot to update the scripts responsible for library link fixing... Fixed in the latest commit, build in progress.

**Comment by Palakis** [comment]
@warrior1724 Latest build: http://obs-ndi-osx-builds.s3-eu-central-1.amazonaws.com/obs-ndi-7756703-master.pkg

**Comment by warrior1724** [comment]
@Palakis Yes I confirm it just work :) Thank you.
