### ISSUE TITLE
CPU unsupported by NDI library. Module won't load.

### ISSUE THREAD

**Issue by Xro9Z** [Palakis/obs-ndi#202]
My 32-bit streaming PC doesn't work with OBS-NDI, my 64-bit gaming PC works but my AMD 32-bit streaming PC doesn't, it also says "Failed to intialize module "obs-ndi.dll"

EDIT 1: I have seen "issue 33" but nothing there worked.

**Comment by narcogen** [comment]
Nothing there was supposed to work-- the dev closed that issue as the problem is with NewTek's NDI software and not the OBS plugin. Unless your 32 bit AMD CPU is somehow different from those listed there?

**Comment by Xro9Z** [comment]
What can i do then? My gaming PC can't handle recording at all and i also need my Streaming PC in order for my microphone to work since the microphone port is broken on my gaming PC.

**Comment by narcogen** [comment]
Not sure, but that discussion is probably better had either in the OBS support forum or on reddit rather than here, because I don't think this is actually a bug in the OBS NDI plugin.

**Comment by Helgaiden** [comment]
NDI requires that the CPU have support for SSSE3. Double check that. That is likely the reason it isn't working. 

Use SL-OBS to stream if youe NDI streming rig won't work as a result of the above information. You can change your encoder in the settings of SL-OBS to use NVENC (if you have Nvidia GPU 600 series or better) or Radeon encoder if you have an HD7xxx series card or better. GPU based encoding for streaming will minimally impact your FPS in gaming. It might not look the greatest at lower bitrate, but it'll get the job done if you only have one system. 

As far as your microhphone port issue goes, get a cheap USB mic/headset or a cheap USB sound card. They are all over Amazon and eBay.

**Comment by narcogen** [comment]
OBS can also use NVENC. Don't see how SL-OBS is different in this case, could you elaborate?

**Comment by Helgaiden** [comment]
SL-OBS is pretty much all in one solution. Use OBS with nvenc, it doesn't really matter. Was just a suggestion. Bebo is also another one that is all-on-one streaming solution that is supposed to be lightweight.
