### ISSUE TITLE
NDI Plugin not working

### ISSUE THREAD

**Issue by abi2016** [Palakis/obs-ndi#206]
Hello

I have a PC and a laptop. 

**Gaming PC Specs:**
CPU: Intel Corei5 4690K
GPU: Geforce 960GTX 2Gb
RAM: 16GB Corsiar

**Stream Laptop Specs:**
CPU: Intel Corei7 4510U
GPU: AMD Radeon R5 M255
RAM: 8Gb

I want play game and stream, but i don't have Capture card. i install **ndi plugin** but not working.

Can i use this plugin (ndi plugin) or can not ? 

Can I stream with these computers ?

**Comment by AGoldenVoice** [comment]
Hey Abi I had to reinstall my OBS and Plugins last night and was having issues as well. I discovered the solution was locating where the folders "data" and "locales" were being installed (which for some reason was not in the proper location in OBS files) and dragging them there. Sorry I cannot provide any screen shots but let me know if you need clarification. :) 

In the past it went to the proper file location, but with the most updated OBS (which you need to install btw) it was not installing in the proper spot.

**Comment by Helgaiden** [comment]
Check your OBS logs on both computers for any clues as well. Both of those computers should work fine for NDI. Also make sure you have OBS allowed through the windows firewall on both computers and dont forget to reboot each PC after installing the NDI runtime.

**Comment by abi2016** [comment]
my laptop stream find gamer pc but not showing anythings.

**Comment by AGoldenVoice** [comment]
Abi did you make sure to create a scene on the game pc's OBS (such as game capture)? The stream PC will show up black if the game pc's obs does not direct a focus for the NDI.
