### ISSUE TITLE
Broken on MacOS 10.13.6 with update to 22.0.2

### ISSUE THREAD

**Issue by trixiefine** [Palakis/obs-ndi#208]
NDI option no longer available as source + in menu from tools.

**Comment by narcogen** [comment]
OBS NDI 4.5.2 seems to depend on a different version of QT Widgets than OBS 22.0.2.

13:03:28.565:   Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0

**Comment by SObS** [comment]
4.5.1 works...

**Comment by narcogen** [comment]
Confirmed. 22.0.1 and OBS-NDI 4.5.1 work for me on Sierra.

**Comment by AlBaum** [comment]
Thanks SObS, 4.5.1 works  on OBS 22.0.2. Confirmed

**Comment by rgbjoy** [comment]
Now working on OBS 22.0.3

**Comment by SouthChurch** [comment]
@rgbjoy Are you saying 4.5.1 works with 22.0.3?

**Comment by narcogen** [comment]
It does.

**Comment by rgbjoy** [comment]
NDI 4.5.2 with OBS 22.0.3 does NOT work. Getting black screen.

**Comment by BatteryAcid** [comment]
Downgrading to the [obs-ndi 4.5.1 (macOS hotfix release)](https://github.com/Palakis/obs-ndi/releases/tag/4.5.1) worked for me.  4.5.2 Did not work.  
OBS 22.0.3

**Comment by Palakis** [comment]
Fixed in the latest release. Closing.
