### ISSUE TITLE
obs-ndi on MacOSX - crash on remove NDI Source 

### ISSUE THREAD

**Issue by warrior1724** [Palakis/obs-ndi#21]
When I try to remove NDI Source from Scene - OBS is crashing 

info: User Removed source 'NDI™ Source' (ndi_source) from scene 'Scena'
Assertion failed: (ec == 0), function unlock, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx/libcxx-120.1/src/mutex.cpp, line 45.
Assertion failed: (ec == 0), function unlock, file /BuildRoot/Library/Caches/com.apple.xbs/Sources/libcxx/libcxx-120.1/src/mutex.cpp, line 45.
2017-06-07 10:30:53.753 CEF[61060:4426504] Parent process died, exiting isolated CEF process.

2017-06-07 10:30:54.319 CEF[61060:4426504] *** -[NSConditionLock dealloc]: lock (<NSConditionLock: 0x7f8b41e2de90> '(null)') deallocated while still in use
2017-06-07 10:30:54.319 CEF[61060:4426504] *** Break on _NSLockError() to debug.

**Comment by Palakis** [comment]
@warrior1724 I tried something to fix this. Please test this: http://obs-ndi-osx-builds.s3-eu-central-1.amazonaws.com/obs-ndi-6000324-master.pkg

**Comment by warrior1724** [comment]
@Palakis it looks better - no crash. 
But when I remove NDI Source, OBS is freezing with Rainbow Spinning Wheel of Death - not good. 
I will try to restart system and will try to run OBS with obs_ndi on another MacOSX system.

**Comment by warrior1724** [comment]
@Palakis After restart - OBS can't start. 
- I have moved obs-ndi plugin directory out of plugins and OBS started. 
- I have removed all scenes and started from clean OBS. 
- added one NDI Source with NDI Signal generator
- removed NDI Source 
- OBS freezes with Rainbow wheel

**Comment by warrior1724** [comment]
@Palakis I have catch OBS process sampling from activity monitor when it is freezing - https://pastebin.com/ftQc6vxn. Maybe it helps a little to find bug

**Comment by 1kfilms** [comment]
Hi, 
I got it to work without crashing sometimes, but now it killed my "Advanced scene switcher".  Any possible solutions?

**Comment by 1kfilms** [comment]
No worries I found a solution.  I updated the plugin

**Comment by Palakis** [comment]
@warrior1724 any update on this? have you tried with the latest release?

**Comment by Palakis** [comment]
Latest development build: http://obs-ndi-osx-builds.s3-eu-central-1.amazonaws.com/obs-ndi-b364a3a-master.pkg

**Comment by warrior1724** [comment]
I have updated OBS to and installed Latest development build but OBS is freezing when I remove NDI Source. 
Another issue - when i close OBS with NDI Source and NDI Output it is freezing
info: ==== Shutting down ==================================================
info: [obs-ndi] stopping main NDI output
info: Output 'main_ndi_output': stopping
info: Output 'main_ndi_output': Total encoded frames: 344
info: Output 'main_ndi_output': Total drawn frames: 349
info: Output 'main_ndi_output': Number of lagged frames due to rendering lag/stalls: 172 (49,3%)
info: Switched to scene '(null)'

**Comment by Palakis** [comment]
This happens on Linux too, and I managed to fix it. Maybe this fix applies to OS X too.

**Comment by Palakis** [comment]
Just tested this on OS X. Fixed!
