### ISSUE TITLE
Hi, Im a noob, completely a Noob, I cant build Obs-Ndi

### ISSUE THREAD

**Issue by NoriegaMxl** [Palakis/obs-ndi#210]
I have no idea what tha means, I see a folder on home/obs-ndi/build whwere I guessing the build goes, I ve installed OBS, OBS Studio, Lib ndi, libndi3, Ive followed palakis instructutions downloaded the Obs Source code en modified like this:
---------------------------------------------------------------
git clone https://github.com/Palakis/obs-ndi.git
cd obs-ndi
mkdir build && cd build
cmake -DLIBOBS_INCLUDE_DIR=/home/obs-studio/libobs
DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo make install
---------------------------------------------------------------------------------
My problem begins at DCMAKE_INSTALL_PREFIX=/usr .. what do I have to do there?... Also J4 not found

Im using Ubuntu 18.04.1LTS...

Also I am planning to migrate to ARCH... just because...

**Comment by DryReef** [comment]
Watch eposvox on YouTube with this,  it helped me
