### ISSUE TITLE
OBS NDI Source not showing the gaming pc. i have installed both obs ndi plugin the ndi runtime then restarted both the pc. I also tried reinstalling multiple times but no solution was found

### ISSUE THREAD

**Issue by bodhisatta19** [Palakis/obs-ndi#213]

**Comment by bodhisatta19** [comment]
![capture](https://user-images.githubusercontent.com/43184051/45380595-b2d03b80-b620-11e8-8552-c2ccd2060d85.JPG)
![41642392_2376661185707797_4240005312477659136_n](https://user-images.githubusercontent.com/43184051/45380902-7c46f080-b621-11e8-9f85-9df0fd03fb01.png)


here are the two snaps first from streaming pc 2nd from gaming pc

**Comment by Claustrophobiac** [comment]
Do your pcs see each other on the network? Can you transfer files from pc 1 to 2 and vice versa ? If not probably the problem is there.
