### ISSUE TITLE
Major Bitrate Drops When using Ndi Above 100 Mbps switch In OBS

### ISSUE THREAD

**Issue by serdarakmanss** [Palakis/obs-ndi#214]
Gaming Pc 
Intel i5-8600K 
GTX 1060
16 GB Ram
Asus Tuf x470 Motherboard

Streaming PC
Ryzen 1800x
Gtx 1060 
16 Gb Ram
B350 Asus Prime plus

When using ndi, my lan speed between 2 pc is like 100 Mbps in idle and my bitrate is normal. But when i stream game or watch a video from youtube my bitrate getting unstable like so much. Normally i use 3k bitrate for my streams with 5 mbps upload speed but now i can't even stream with dual pc.

So if i turn back to 100 mbps switch everything is getting normal but i want to stream with 720 60 fps so i need more then 100 mbps.

My Lan Cables are Cat 6 and Cat 7, So should i make them both cat 7 or it not related ? 

https://prnt.sc/ku4yv6 As you can see upload is going crazy when i use ndi. Even my streaming pc has cat 7. 

I need help...

**Comment by danielpetre** [comment]
So you get unstable connection over a gigabit switch..? Well, i got a/v desync while sending 1440p a/v stream over a linksys wrt1900acv2 and seeing it was around 200 Mbit/s.. i set up a direct cable between my two computers (secondary gigabit on the mb and a usb3 gigabit dongle) and everything solved. 
Seems like the main gigabit router cannot handle too well a 200 Mbit/s stream..
