### ISSUE TITLE
Choppy and low framerate on streaming pc

### ISSUE THREAD

**Issue by Daxtarious** [Palakis/obs-ndi#216]
Hey there,
I am having some problems setting up my stream with NDI. Getting the stream to appear on my streaming notebook works fine, but it sadly is pretty choppy on there. I tried using the NDI studio monitor tool, which does not give a much better result. I'm running both my gaming pc aswell as my streaming notebook off of a gigabit network switch with nothing else plugged into it.

If you need any additional informations just let me know, then I'll provide them asap.

[2018-09-16 15-41-31 Gaming.txt](https://github.com/Palakis/obs-ndi/files/2386623/2018-09-16.15-41-31.Gaming.txt)
[2018-09-16 15-41-42 Streaming.txt](https://github.com/Palakis/obs-ndi/files/2386624/2018-09-16.15-41-42.Streaming.txt)

https://www.youtube.com/watch?v=-P8QEgZH3S8

**Comment by Daxtarious** [comment]
Just tried connecting my streaming notebook directly to the gaming pc via CAT 5e cable, same result, very choppy framerate, static image when there is little movement on the gaming pc itself.

**Comment by Helgaiden** [comment]
Why do you have an NDI source on your gaming PC? Your gaming PC shouldn't be bringing IN any sources, it should only be sending them out via the NDI Main Output for best performance. The only thing that should be taking in sources in the Streaming PC.

**Comment by Daxtarious** [comment]
Thanks for the answer. 
There was indeed a NDI source on my gaming pc, I didn't mean to do that, but as it had no active source, it wasn't doing anything. After removal of the NDI source from my main pc the performance was unchanged. I triple checked every bit of my network that I use for my setup, everything should be gigabit. 10/100/1000 router + switch, CAT 5e cables, modern network adapters on both pc's (no killer networking) capable of 1gbps. 
I disabled everything that wasn't being used in OBS as you suggested without any luck, the low framerate still persists.

**Comment by TekSoup** [comment]
I noticed that the latest version of OBS and ndi did not like working together when the beta came out a month or more ago. Try downloading the Free Trial Version of Vmix and see if that works, it does for me. Just run Scan Converter on your gaming rig and Vmix on capture computer. Yeh Vmix is $60 but it just works.

**Comment by DryReef** [comment]
the same has been happening to me for the past 2 days and i know for a fact it isnt my internet speed or bandwidth! nothing changed aside from a obs and windows update! i made sure my internet speed was the same and that the firewalls were turned off

**Comment by DryReef** [comment]
I raised my cpu preset from very slow to medium and it works now.. not as good looking but finally able to stream again

**Comment by Palakis** [comment]
> fuck OBS NDI.

You won't be getting help with that kind of manners. Closing and locking this thread.
