### ISSUE TITLE
OBS NDI Installer not working for 64-bit installs

### ISSUE THREAD

**Issue by DannySupernova** [Palakis/obs-ndi#217]
Windows 10
OBS 64 bit
Install Location: D:\Programs\obs-studio
CPU: Ryzen 7 1700

The OBS NDI installer correctly discovers the install location, but for some reason the NDI runtime is not detected. I have tried manually installing the NDI via the link included in the error message. That still does not work.

But if I launch OBS 32 bit then the plugin works. So it seems like the issue is only with 64 bit.

```
20:10:52.291: [obs-ndi] hello ! (version 4.5.2)
20:10:52.291: [obs-ndi] Trying ''
20:10:52.291: [obs-ndi] Can't find the NDI library
20:10:53.664: Failed to initialize module 'obs-ndi.dll'
```

**Comment by DryReef** [comment]
it's not working for me either and its irritating me.  You find a solution yet?

**Comment by DannySupernova** [comment]
Actually, yes, or at least maybe. I reinstalled the NDI v3 runtime on my D drive, then I rebooted the computer. That seemed to fix it. I'm not sure if the issue now is that the plugin couldn't find the runtime library on my C drive, or if it was just not installing properly to start with. I had tried rebooting after install before to no avail.

So I guess you can try manually installing the NDI v3 runtime manually, then reboot.

**Comment by Palakis** [comment]
@DannySupernova I think it's related to the fact that the latest releases of OBS Studio have separate 32 and 64-bit installers with different install paths. The obs-ndi installer still uses the old path system. This is actually an issue to fix.

**Comment by Alexufo** [comment]
the same. On 32 bit all ok but then I launch 64bit "ndi runtime not found"

**Comment by MrAlexEsisteGia** [comment]
after trying everything, i missed the button "open" and i clicked "open as admin"           
and ndi started working :D

sooo just run as admin
