### ISSUE TITLE
MAC's OBS studio can't show up NDI tools

### ISSUE THREAD

**Issue by alanwake83** [Palakis/obs-ndi#218]
Hello guys, I have been trying this issues for hours, I do wish somebody can help me out :)

I have no issues with my gaming desktop which can work NDI tool properly.

But I can't let my streaming laptop show the NDI tool, 
no matter how I reinstall it or restart my MacBook Pro....

I am using MacBook Pro with OBS Studio 22.0.3....
I've tried 21.1 version on OBS Studio and several versions in NDI.. no luck

Does anyone knows why :(?

Thanks

**Comment by gferguson1815** [comment]
I am having exactly the same issue.

On the MacBook Pro running High Sierra 10.13.6 I have downloaded OBS22.0.3 and the NDI plugin and also downloaded the runtime library but it is not visible on the mac but no issues installing on a Windows PC

**Comment by BillKills974** [comment]
There is a QtWidgets library version mismatch (again) on OBS NDP plugin 4.5.2. 
Workaround: downgrade to 4.5.1 and it will work

**Comment by PMcGoldrick** [comment]
This appears to be resolved in 4.5.3 as of 2 days previous to my comment.

**Comment by daveatbigplay** [comment]
Hi guys- I’m trying to get NDI to show up as a source in OBS on a MacBook Pro, yet after downloading 4.5.3 package, I still cannot get it to show up on OBS as a source option. Any ideas?

**Comment by allenwixted** [comment]
Still doesnt work for me. Fresh installs of both

**Comment by alankent** [comment]
I am getting all NDI streams on Mac not working. The mDNS entry seems incorrect. It does not have the hostname and port number, unlike my windows desktop entries which do work. Did you get it solved? Could it be the same problem?

![image](https://user-images.githubusercontent.com/5702163/78416879-4ee5dd00-75e1-11ea-9aee-59a49de2646e.png)

**Comment by vschoener** [comment]
> I am getting all NDI streams on Mac not working. The mDNS entry seems incorrect. It does not have the hostname and port number, unlike my windows desktop entries which do work. Did you get it solved? Could it be the same problem?
> 
> ![image](https://user-images.githubusercontent.com/5702163/78416879-4ee5dd00-75e1-11ea-9aee-59a49de2646e.png)

Same for me with last OBS version and NDI plugin.
The mac seems not sending anything over the network, my windows(stream machine) can't resolve the mac. (It works with my iPhone for example).

**Comment by alankent** [comment]
Yes, I solved my case. It turned out the output from my "hostname" command could not be resolved to an IP address. Once I set hostname by hand to something sensible and added it to /etc/hosts by hand it worked.

**Comment by vschoener** [comment]
> Yes, I solved my case. It turned out the output from my "hostname" command could not be resolved to an IP address. Once I set hostname by hand to something sensible and added it to /etc/hosts by hand it worked.

Indeed, it's the same for me, thanks for the tip. I'll put an ip then. :) I created a ticket about it, hope it could have a fix ;)

**Comment by vschoener** [comment]
> Yes, I solved my case. It turned out the output from my "hostname" command could not be resolved to an IP address. Once I set hostname by hand to something sensible and added it to /etc/hosts by hand it worked.

I just tried this but still doesn't work for me and my hostname resolves to my local address ip. So sad :(
