### ISSUE TITLE
NDI is destroying my internet speed? 

### ISSUE THREAD

**Issue by Henry1k** [Palakis/obs-ndi#219]
Good Evening, 

I would like to start by saying I have used NDI for the past year and it has worked perfectly! 

Recently NDI has become a nightmare! When the NDI is connected between two PCs which both have a direct link to my router, the internet speed on my receiving pc (streaming PC) goes from 200mbps to 2mbps. As you can imagine the ndi then lags to the point it I can not stream with it. 

Any reason why this may be happening? 

I have fully updated the version of newtek. Any way I try do do this the same thing happens, using OBS or Streamlabs obs.

**Comment by Henry1k** [comment]
I would like to add as soon as I turn the NDI off, the network goes back to full speed! 

Your help is greatly appreciated, thanks in advance!!

**Comment by Henry1k** [comment]
Can I also add the internet is only down to 2mbps on my streaming pc, the gaming pc has 200mbps solid at all times.

**Comment by Helgaiden** [comment]
open a command prompt and try these two commands then reboot

netsh int ip reset
netsh winsock reset

**Comment by DryReef** [comment]
my streams were buffering very badly the past 2 days too and now ndi wont even install onto either of my pc's!
