### ISSUE TITLE
NDI Runtime download not running

### ISSUE THREAD

**Issue by Athenaxfox** [Palakis/obs-ndi#220]
I'm not entirely sure what happened in the last 24 hours but the installer and link from the install instructions is downloading the NDI 3.5 runtime. It installed perfectly fine on my gaming pc, but it refuses to download on my stream pc. I think it's an issue with the Newtek website, but I just wanted to know if that's an issue that anyone else is running into.

**Comment by DryReef** [comment]
man i'm having this issue too and its irritating me! I cant stream with my 2 computers!

**Comment by DryReef** [comment]
I tried restarting my computers, restarting my router/modem and nothing.  before this happened to me today the streams were buffering very badly the past 2 days before and nothing changed! My internet and hardware are easily able to handle streaming

**Comment by JuanTafur123** [comment]
Yes, i can't download obs-ndi 4.5.2 and 3.5+ runtimem, idk what i should go to start to downloading, it's just getme in a blank page.

**Comment by DryReef** [comment]
the ndi tools download page wont even load!!

**Comment by DryReef** [comment]
agghhh hope itll be back up soon!!
