### ISSUE TITLE
NDI Installer won't download file

### ISSUE THREAD

**Issue by EpicLPer** [Palakis/obs-ndi#222]
The URL the installer is trying to access does not exist anymore. "http://64-150-181-205.dedicated.codero.net/" is what it's trying to access yet it doesn't seem to exist anymore. 2 days ago it still worked.

**Comment by DryReef** [comment]
has this happened in the past?

**Comment by EpicLPer** [comment]
Only just now, tried updating the NDI plugin on my Main PC after installing it on my server 2 days ago. On my server it still worked, tho on my Main PC today it didn't anymore. I've updated the plugin via the ZIP now.

Tho curious, why are you downloading the file from an external source instead of just uploading and grabbing it from Github?

**Comment by DryReef** [comment]
it wont download and install from github for me and i tried doing it on the newtek website also and that didnt work either...

**Comment by scallister** [comment]
I'm having the same problem. Tried from two computers and also tried downloading directly from the NDI site and that fails too.

**Comment by scallister** [comment]
Spoke with NDI customer support. They're aware and trying to fix it. They're trying to find an alternate install that still has the NDI 3.5+ runtime that we might be able to use in the meantime.

**Comment by TekSoup** [comment]
i just email a person i have talked with before at newtek, maybe fix soon

**Comment by DryReef** [comment]
Thank goodness

**Comment by Rdorifd** [comment]
same issue today cant download

**Comment by impoze** [comment]
has a new download link been released for runtime 3.5+?

having the same issue trying to install the plugin
