### ISSUE TITLE
Unable to install NDI

### ISSUE THREAD

**Issue by 7bytes** [Palakis/obs-ndi#223]
Whenever I try to install NDI 4.5.2 i get an error during installation, "Download failed: operation timed out" due to this, i've been unable to install the plugin. I've also tried to install it manually however, when i try to do that, the website for the runtime never loads. I also can't post a log, because there aren't any. Thanks!

**Comment by scallister** [comment]
@7bytes this is a duplicate issue, other issue is over at:
https://github.com/Palakis/obs-ndi/issues/222

Lets consolidate over there. I can't mark this as a duplicate myself.

**Comment by TekSoup** [comment]
i just email a person i have talked with before at newtek, maybe fix soon

**Comment by EpicLPer** [comment]
> @7bytes it's not just you, I think the NDI site is broken possibly? I tried using the installer on two different computers, same issue. I also tried using the manual link for downloading the NDI runtime and that times out as well. I also tried downloading the SDK from their site (I was hoping that was the right thing). That download fails even using NDI's link.
> 
> Really unfortunate, I was hoping to use this for a stream today :(.

I was able to install the Redist even while the stuff is offline, need the installer?

**Comment by Frey622** [comment]
> 
> 
> > @EpicLPer that would be wonderful actually. Mind sending it my way? steven.callister is my gmail address, ty.
> 
> Sent :)

Hey ,could you please send it to me as well?
My gmail is johntheripper0123 :)
