### ISSUE TITLE
OBS 22.0.3 Loading NDI on MacOS fails - QtWidgets version mismatch?

### ISSUE THREAD

**Issue by plocher** [Palakis/obs-ndi#224]
OBS 22.0.3 (Mac)
OS Version: Version 10.13.6 (Build 17G65)

error:
os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): 
dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1):
 Library not loaded: @rpath/QtWidgets

  Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so

  **Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0**

**Comment by Jurik81** [comment]
Same here:

```
19:03:02.956: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1): Library not loaded: @rpath/QtWidgets
19:03:02.956:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
19:03:02.956:   Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0
19:03:02.956: 
19:03:02.956: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded
```

**Comment by zachflauaus** [comment]
Same thing here as well, macOS Mojave 10.14.

**Comment by gianniskarmas** [comment]
+1

**Comment by fredemmott** [comment]
Yeah, this is because obs-ndi is built against the version of qt5 available in homebrew - currently 5.11.2 - but OBS itself is built against an older version. I tried using `install_name_tool` to point OBS at the newer version, but Qt checks for that and stops you :'(

To fix, you need to build both yourself, using homebrew for the dependencies. You can basically follow https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos, though you will need to add `-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.11.2/lib/cmake` to the cmake commands, then following the instructions on https://github.com/Palakis/obs-ndi#os-x

**Comment by zachflauaus** [comment]
That cmake command to the obs-studio build is what I was missing. Got it running with that solution now. :D

**Comment by PatTheMav** [comment]
Tried compiling everything myself (I need the CPU usage fix from #229) but gave up when I couldn't compile the suggested CEF version for the browser source plugin as my Xcode was "too recent" for this particular CEF version to work. It's a mess. 

If anybody has builds of a recent OBS+Browser Source plugin, OBS-NDI with #229 implemented and OBS-Websocket I'd be one happy streamer..

**Comment by Palakis** [comment]
Rolled back the macOS CI script to have it build against Qt 5.10.0, although the CI jobs may fail because some URLs the Homebrew formula for 5.10.0 need updates.

**Comment by PatTheMav** [comment]
@Palakis Much appreciated!

**Comment by PatTheMav** [comment]
@Palakis OBS and the NDI plugin work out of the box, CPU usage went from 200% to 43-50%. Minimising the OBS main window or disabling preview doesn't seem to have any noticeable impact on CPU usage as well.

OBS itself meanwhile only reports 11% CPU usage without encoding - I don't know where that discrepancy between OBS and Activity Monitor comes from, but usage is down across the board.

**Comment by plocher** [comment]
Bingo - works as expected - Thanks!

I've got a convention in 3 weeks - this just gave me my "Plan A" back!

**Comment by PatTheMav** [comment]
I still get weird freezes on macOS though - the launch animation freezes when OBS is launched from Launchpad, but also when browsing for media sources or just changing something in OBS freezes the whole system for a few seconds.

Does anyone else have these issues as well? Could be Mojave and OBS itself, but I haven't ruled out the non-working obs-websocket plugin (same QT5 library issue yet).

**Comment by plocher** [comment]
I saw this in an earlier version - it seemed to hang enumerating the NDI
streams or in instantiating them.  For me, it was 30 seconds to several
minutes.  I reinstalled the NDI drivers and rebooted, and have not seen the
problem since.

  -John

**Comment by PatTheMav** [comment]
@plocher Thanks - the restart did indeed fix the freeze upon launching OBS, but within OBS I still get small freezes all over the place.

If I don't do anything, it encodes and streams flawlessly though. One more reason I'm looking forward to the obs-websockets update..

**Comment by zachflauaus** [comment]
@Palakis Late commenting on this but that package fixed the issue. 👍

**Comment by Palakis** [comment]
Should be fixed on the latest release. Closing.
