### ISSUE TITLE
Audio Delay

### ISSUE THREAD

**Issue by TweakGames** [Palakis/obs-ndi#23]
There appears to be a 1 second audio delay when using NDI on my OBS 2 PC setup.   Video has no delay, but audio does.

**Comment by Palakis** [comment]
This is likely an issue with OBS' audio subsystem which adds buffering under some conditions. Can you post a log **when this happens** using OBS' log upload tool (Help > Log files > Upload current log file), please?

**Comment by Palakis** [comment]
@TweakGames Any update on this?

**Comment by trbomode** [comment]
I to am having this issue. I'm available to help test but do you want log file from both PCs or just the PC streaming to twitch.

**Comment by trbomode** [comment]
Just did some more testing, fresh started stream and the audio is synced but an hour later I've got audio sync issues. I do have OBS audio filters being applied to my MIC only, I don't know if that matters or not. Matching HZ and Audio Bitrate on both PCs.

**Comment by Palakis** [comment]
@trbomode Log please. Thus I can see which OBS source might be causing this.

**Comment by Pimpmuckl** [comment]
@Palakis Noticed the same issue today.

https://gist.github.com/anonymous/30669b1ef6593e8bf2ee8a17dc525744 is the log, OBS adds audio buffer seemingly out of the blue.

`20:02:41.068: adding 92 milliseconds of audio buffering, total audio buffering is now 116 milliseconds
20:02:41.811: adding 905 milliseconds of audio buffering, total audio buffering is now 1021 milliseconds`

**Comment by Palakis** [comment]
Seems like it's linked to #24. Sources sending wrong timestamps to OBS' audio engine can cause additional audio buffering (`adding X milliseconds of audio buffering` messages).

**Comment by Palakis** [comment]
#24 has been fixed. Can someone please test the development builds providere there and confirm if this is fixed or not?

**Comment by kevmuller** [comment]
im having the same issue, it only happened once when streaming pubg,

**Comment by Palakis** [comment]
@kevmuller This is a known issue. See #80
