### ISSUE TITLE
stuck at 30fps

### ISSUE THREAD

**Issue by justiszafi** [Palakis/obs-ndi#232]
Before i open ndi source, obs was running perfectly good, 60fps. It only drops down to 30fps after i clicked ndi source under "Sources" in obs. What can i do to fix this? 

*this happens on my streaming pc which is running on i7 8570h

**Comment by justiszafi** [comment]
I have seen others saying that you need a gigabit cable. I'll try to test and see if it works but do i need to buy 2 gigabit cables both for gaming and streaming pc or just for streaming pc?

**Comment by Helgaiden** [comment]
Why are you enabling the NDI output on the streaming PC?
