### ISSUE TITLE
Micro stuttering with 4.5.2 - possible fix?

### ISSUE THREAD

**Issue by loopy750** [Palakis/obs-ndi#234]
I've created a fork that appears to eliminate the "choppy" streaming some people are experiencing. Seeing Palakis active again, maybe this could be looked at and possibly even a setting implemented that allows varying latency settings ie "Normal", "Lower", so people can find their best latency setting that doesn't cause duplicate frames?

**Comment by MattGerard** [comment]
Would like to test this out, I'm getting a micro stutter every few seconds on the stream pc, everything else checks out, seems like it may just be this last release?

**Comment by Ghostaunt** [comment]
This needs to be added/accepted

**Comment by Palakis** [comment]
@loopy750 Apologies for closing this, I may have screwed up when triaging.

**Comment by Palakis** [comment]
@loopy750 As commented in another thread, it'd be nice if you could make a pull request with your fix (just don't use master). Otherwise I can fix it right away if you really don't mind.

**Comment by Palakis** [comment]
@loopy750 Gonna open that PR myself but with you as co-author. Again, thanks for discovering this fix.

**Comment by loopy750** [comment]
Hi mate, no problem, I don't mind if you fix it right away, that'll be fine - it's more or less just changing **obs_source_set_async_unbuffered(s->source, true);** to false. I'm not sure if you would want to enable that to be toggled or if having it set to true will be bad in all cases, but with my own personal experience it was definitely stuttering often with it set to true.

**Comment by Viskositaet** [comment]
Hello guys,hope somebody can help me?
where can i find this "obs_source_set_async_unbuffered(s->source, true);" in whihc direction is it or better how to change it?

best regards
