### ISSUE TITLE
NDI Download issue

### ISSUE THREAD

**Issue by MagicMaxMan007** [Palakis/obs-ndi#237]
Do you have any other downloadlinks for the runtime, because the download servers are down. 

The installer dont working any more, same on this: [new.tk/NDIRedistV3](url)

Thanks!

**Comment by Rdorifd** [comment]
same for me i cant download anything, i installed the dll manually but without the runtime were fucked

**Comment by PatTheMav** [comment]
Might have been a temporary issue - download works fine for me.
