### ISSUE TITLE
Problem with latency even when using wired connection

### ISSUE THREAD

**Issue by Quassin** [Palakis/obs-ndi#239]
Hi

Recently i set up obs-ndi on my 2 PC's (one is a "gaming" laptop) and found that it works great but i get a 1-2s of latency so i tried connecting my main pc to my 2nd pc and got the same latency so, I checked on YT and in most cases people didn't have that much latency. Connecting computers directly didn't help. So my question is: do i have a problem with connection between my computers or this amount of latency is normal?

My main gaming rig:
Ryzen 7 2700x
Radeon RX 580
ASRock X470 master SLI

My laptop (Acer Nitro 5):
Ryzen 5 2500U
Radeon RX 560x

My 2nd gaming rig
i5-6600
GeForce GTX 960
MSI Z170i Gaming AC

Thanks for any help!

**Comment by Palakis** [comment]
@Quassin You probably have a media source or a capture device that is causing increased audio latency, and the output tries to keep video synced to audio.
