### ISSUE TITLE
Choppy audio from NDI Source

### ISSUE THREAD

**Issue by burritodreamer** [Palakis/obs-ndi#24]
I'm experiencing choppy audio when using an NDI source in OBS. I have both copies of OBS set to 48khz. I have also tried setting them both to 44.1khz with the same results.

Monitoring the NDI source's audio in realtime is fine, but the output to the file is choppy.

**Comment by Lange** [comment]
I'm having a similar issue, but maybe not quite identical. In my case, I hear some occasional crackling when monitoring the audio. This is also present in the recording.

**Comment by shadikka** [comment]
I can also attest to this. The monitor output of audio is fine, but the recording is wonky. I also have some recordings of it for reference purposes, if necessary.

Our setup included two NDI sources, and the issue was especially present when switching between them, but happened all the time. Changing audio bitrates etc. did not help, and CPU usage never peaked to worrisome levels. The video seems to be fine as well.

**Comment by chazragg** [comment]
i am currently experiencing this issue at work. i have found that using NDI video monitor and recording that from OBS works but the video quality drops a bit. would love to hear some feedback on the issue.

**Comment by Helgaiden** [comment]
Having this issue as well. Made a reddit thread about NDI for OBS and it appears im not the only one. This was also brought up on a youtube video i made about this. Seems like its an issue, any ideas on how to remedy this? 

https://www.reddit.com/r/Twitch/comments/6kbz3k/streaming_with_separate_pc_via_obs_with_new_ndi/

https://www.youtube.com/watch?v=AH_ECDLkKEA

**Comment by Palakis** [comment]
Thanks a lot with your feedbacks, everyone. I don't have much time available these days but I'll manage to dedicate some time to this since this is quite important. Btw, thanks for the video @Helgaiden!

**Comment by Palakis** [comment]
Speaking of videos, I'd appreciate if people encountering this issue can send me sample recordings of the problem happening. You can upload them somewhere (unlisted YT video, transfer.sh, WeTransfer link, ...) and put a link in the comments here.

**Comment by Palakis** [comment]
And btw, please tell what kind of software or hardware you use as an NDI source (e.g : a Tricaster, VLC, etc) when this happens

**Comment by Lange** [comment]
I am using CasparCG as the NDI source. The issue happens even if Caspar is
running on localhost.

**Comment by Helgaiden** [comment]
No problem, Palakis. I'll try to get a sample later today.

**Comment by Helgaiden** [comment]
No problem, Palakis! Thanks for all you do.

Here is a sample a user on reddit sent me for you. OBS log link is in description

https://www.youtube.com/watch?v=d2QwO-qhhRI&feature=youtu.be

There was a workaround posted and here is a sample with the workaround implemented:
https://www.youtube.com/watch?v=znCloXguJZM
From the user:  that "quick fix" works just fine, when you change the NDI audio source to monitor only, and just leave the desktop audio as the only audio device and use that as your primary audio source, the choppiness is completely gone. 

the "quick fix" in question:
" "Setting the receiving OBS NDI Source to monitor only, mute output - set the monitoring device in advanced to something that does not cause echo for you and adding THAT as "desktop audio device" in obs will workaround the audio stuttering for now. For some reason it is only the encoded output that suffers from the stutter and ONLY if recorded directly from the ndi source, so routing it through some other device first fixes the stutter.""

**Comment by Helgaiden** [comment]
quick update: a user on reddit sent me a tutorial video to post on the workaround that'll work for now in a pinch

https://www.youtube.com/watch?v=PfCz_j3RD9I&feature=youtu.be

**Comment by Aketzu** [comment]
Here is one test file directly from OBS: http://aketzu.net/~akolehma/desu/2017-06-17%2013-55-03.flv
There are two NDI sources (computer and camera). Both go with HDMI to BMD Intensity cards on one PC and there Caspar does NDI sending.
OBS is running on another laptop and has two NDI sources. In the video I click them disabled/enabled. That seems to generate lots of these audio issues.

**Comment by Palakis** [comment]
@Aketzu That's an interesting sample. Messed up audio from the BMD input when an NDI source is active reveal that the problem seems to be caused by NDI frame timestamping within OBS. Put another way: frames sent to OBS from an NDI source might not have a correct timestamp.

**Comment by Palakis** [comment]
Just fixed this in https://github.com/Palakis/obs-ndi/commit/44194f4c1ab7ecdb9ee97986253a0f0268138f3a. Automated builds are in progress, will provide links to binaries once it's done.

**Comment by Palakis** [comment]
So this issue all comes down to audio frame timestamping. Timestamps provided by the NDI library seem to cause choppy audio in OBS' outputs (except monitoring). Manually crafting timestamps based on current system time solves this.

**Comment by Palakis** [comment]
Here are the binary builds:
* Windows: https://ci.appveyor.com/api/buildjobs/b0nd7u2myt94lg7r/artifacts/obs-ndi-44194f4.zip
* Linux: http://obs-ndi-linux-builds.s3-eu-central-1.amazonaws.com/obs-ndi_1-44194f4-master-git-1_amd64.deb
* OS X/macOS: http://obs-ndi-osx-builds.s3-eu-central-1.amazonaws.com/obs-ndi-44194f4-master.pkg

**Comment by KlasiK116** [comment]
I think its just me, but is anyone else still having the audio issue after the fix? Maybe I do not have my setup configured properly but I am still having the audio issues after copying the changes to OBS.

**Comment by Palakis** [comment]
To whoever interested: [obs-ndi 4.0.1 has been released](https://github.com/Palakis/obs-ndi/releases/tag/4.0.1) and contains the fix for this issue.

**Comment by mangosango** [comment]
Woo! Thank you for fixing this

**Comment by Helgaiden** [comment]
Thank you, Palakis. I will have to update and try this out soon!

**Comment by shadikka** [comment]
Thank you, the fix seems to work perfectly. :)

**Comment by narcogen** [comment]
Version 4.1.3 on MacOS still seems to have this exact problem. The workaround described above-- setting the audio on the NDI source to monitor, but not output, and then setting the monitoring device as a separate audio track, works fine.

**Comment by w3djyt** [comment]
Just adding that I've just setup NDI between OBS on gaming PC and OBS on streaming PC and can confirm I still needed to do the monitor/mute of NDI to Default Audio work around on the streaming PC in order to eliminate the audio stutter. 

Thanks for all your hard work!

**Comment by sijaffer** [comment]
Hi, 

I have OBS 25.0.8 (64bit), installed obs-ndi 4.9.0 and obs-ndi runtime 4.5.1 and still experiance the choppy audio when recording. I have tried the Monitor Only (mute output) option but dont see Device Audio. when I add Audio Input Capture it also bleeds the mic audio. not sure what I am doing wrong. I have tried the NDI Native Virtual input and that works fine, but the Mac I can only add one NDI device. Your help is greatly appreciated. I have added the screen shot of my setup. 

![Screen Shot 2020-08-20 at 12 24 41 AM](https://user-images.githubusercontent.com/5897456/90720131-99f44a00-e27b-11ea-9c0b-d60c8d60e25e.png)

**Comment by jus1029** [comment]
Not sure if this is a similar problem with this thread, but it's choppy. Sound kicks in for a millisecond and disappears for three seconds: https://streamable.com/kxlrlg

On one instance, audio recording worked perfectly: https://streamable.com/xwi2pi
Only when I disabled and re-enabled the main output did the problem return.

**Comment by HiImEli** [comment]
> I've had the same issue using Birddog cloud (WebRTC) as an NDI source. The issue seems to be resolved when I set the NDI input in OBS on Sync: Network.

Hey man, thanks this seemed to work for me. Appreciate it.

**Comment by comemyfanatics** [comment]
> Speaking of videos, I'd appreciate if people encountering this issue can send me sample recordings of the problem happening. You can upload them somewhere (unlisted YT video, transfer.sh, WeTransfer link, ...) and put a link in the comments here.
I have sample video that I can send to you if you can advise how to contact you. I filmed multiple cameras using ndi-obs and experienced popping on a consistent basis.

The audio direct from the cameras is distorted so I routed the NDI Studio audio into OBS. This is using Birddog Flex 4K In devices.
