### ISSUE TITLE
No NDI source available on macOS 10.14

### ISSUE THREAD

**Issue by zerodistraction** [Palakis/obs-ndi#246]
I'm running the latest OBS 22.03 on macOS 10.14. I've installed the latest NDI 4.5.2 update, but when I try to add an NDI source to a scene, there's no option for that.

In the logs, it's complaining about the version and says NDI 5.10 is required

"Reason: Incompatible library version: obs-ndi.so requires version 5.11.0 or later, but QtWidgets provides version 5.10.0"

Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded

System specs: 2012 Mac Pro, 2.4Ghz 12-core.

**Comment by Palakis** [comment]
@zerodistraction Update to obs-ndi 4.5.3, which fixes macOS issues.
