### ISSUE TITLE
OBS not finding source

### ISSUE THREAD

**Issue by kastlerok** [Palakis/obs-ndi#249]
OBS 22.0.2
Installed OBS-NDI 4.5.3 with windows installer.
Installed NDI 3.5+ Runtime w/ reboot

OBS NDI Output settings available under OBS Tools menu

Adding NDI Source is avail but when selected it does not find a "source name" 

Skype is running on OBS machine and running a skype conversation with my cellphone on separate skype account to test.

Skype for creators installed and NDI enabled. Skype screen on OBS machine showed RED dot and stop NDI option so NDI is enabled on skype.

I've watched every video on the internet but cannot find a solution.

Downloaded NewTek Tools. Video Monitor is able to find SKYPE NDI. 
Checked firewall and everything appears to be allowed.

Any ideas what I have missed and why OBS cannot find the NDI Source name?

![obs ndi source](https://user-images.githubusercontent.com/44988487/48385295-220eee00-e6ab-11e8-97c3-c92721ebc60c.png)

**Comment by Palakis** [comment]
@kastlerok Add OBS as a firewall exception and add it to both Public and Private network profiles.
