### ISSUE TITLE
OBS-NDI Debian Install Directory

### ISSUE THREAD

**Issue by nu11reason** [Palakis/obs-ndi#25]
I noticed when installing the .deb packages for OBS-NDI on Debian specifically, instead of adding to the already existing "obs-studio" directory the package would create a new directory titled "obs". Once I merged the files into the "obs-studio" directory the plugin picks up perfectly. 

This is not a huge concern, but others may assume that the package just doesn't work correctly.

**Comment by Palakis** [comment]
How did you installed OBS Studio? Debian repositories, OBS PPA or source build?

**Comment by nu11reason** [comment]
I tried it both ways through the Debian Repo and then source build. The .deb files will create a separate "OBS" folder instead of just adding th plugin to the "OBS-Studio" folder.
