### ISSUE TITLE
Not working with OBS.

### ISSUE THREAD

**Issue by Waldoctg** [Palakis/obs-ndi#251]
It's posted here: https://support.loola.tv/using-additional-streaming-softwares/can-i-use-obs-with-loola that I can use this with OBS. Do I have to have the NDI hardware?

**Comment by Helgaiden** [comment]
To make OBS NDI work, you just need the latest OBS Studio and the NDI plugin installed

**Comment by Waldoctg** [comment]
So I don't need the NDI plugin?

**Comment by Helgaiden** [comment]
Why are you confused?

**Comment by Waldoctg** [comment]
I mistyped. I don't need the NDI hardware*?

**Comment by Helgaiden** [comment]
OBS with NDI doesn't need any specific hardware.

**Comment by Waldoctg** [comment]
Understood. Thanks.

**Comment by Waldoctg** [comment]
Can you send instructions on how to connect OBS with the NDI plugin?
Sincerely,
Connor W.

-- 
Connor Waldo
waldoctg@gmail.com

**Comment by Helgaiden** [comment]
@Waldoctg https://youtu.be/AH_ECDLkKEA

**Comment by Helgaiden** [comment]
Nope

**Comment by Waldoctg** [comment]
Ok. But it is possible? Thanks for being so responsive.

**Comment by Helgaiden** [comment]
The website says it is, so it should be. The links on support page you linked are pretty informative. it does looks a little complicated though. If you needed to stream out to multiple services, i'd use Restream.io instead of that as Restream is just a stream key you put in OBS, then use OBS for everything. Loola wants you to use a virtual camera plugin thats video only and use another software for a virtual audio cable that re-routes the audio back in so that  the virtual camera can have video + audio...it sounds complicated for you from what i can tell so far. I cant advise any further on loola usage.

**Comment by Waldoctg** [comment]
All I really want is to just be able to simply stream to instagram from my
computer easily. I have another method of doing it, but it's sort of
finicky and complicated.

Restream.io doesn't allow for streaming to instagram, correct? That's what
I remember at least....

Sincerely,
Connor W.

-- 
Connor Waldo
waldoctg@gmail.com

**Comment by Palakis** [comment]
@Waldoctg 
> All I really want is to just be able to simply stream to instagram from my
computer easily.

You don't need the NDI plugin then. Install OBS Studio, add your sources (webcam, etc), configure your stream settings and off you go.

But at this time, Instagram doesn't support streaming from third-party programs over RTMP. That's another issue and is neither in the scope of this plugin nor of this issue board.

**Comment by Palakis** [comment]
> But at this time, Instagram doesn't support streaming from third-party programs over RTMP. That's another issue and is neither in the scope of this plugin nor of this issue board.

Sorry, my mistake here. You use Loola for this if I understand correctly, so it's possible. But you still don't need the NDI plugin.

**Comment by Waldoctg** [comment]
Do you have instructions for Loola? I tried it, but it wasn't working with
your plugin. Their website says it'll work with your plugin.

**Comment by Waldoctg** [comment]
So do you?

**Comment by Palakis** [comment]
@Waldoctg NDI has nothing to do with Loola, and the way NDI is mentioned in their setup guide has nothing to do with connecting OBS to their platform.

**Comment by dodgepong** [comment]
This entire conversation is really better to be had with Loola support, not here. It's not Palakis's responsibility to get OBS working with Loola, it's Loola's responsibility to get it working with OBS.

**Comment by Waldoctg** [comment]
I agree. They don't have a support channel though...figured I'd ask Ndi.

**Comment by Helgaiden** [comment]
You aren't "asking NDI" here. This is a third party plugin that utilizes NDI developed by a guy on his free time. If you want to "ask NDI" then go over to the Newtek NDI support forums (no I don't have a link) and ask the actual creators of the NDI tech there. 
Maybe Loola has a discord server you can join for help with OBS.
