### ISSUE TITLE
NDI Settings on GAMING PC

### ISSUE THREAD

**Issue by k4iLeb** [Palakis/obs-ndi#252]
Hello Palakis,
I'm experimenting with all kinds of settings in OBS NDI and i was wondering if apart from VIDEO tab on the GAMING PC, is output tab playing any important role on the quality of the footage that is being transmitted to the STREAMING PC.

like, do the changes i apply on the GAMING's PC OBS on the Streaming and Recording tab affect anything ?

Can't figure out after many tests and also haven't seen a question like that while googling for  it.

**Comment by Helgaiden** [comment]
Video tab only. Output tab does nothing for NDI.

**Comment by Empathetic** [comment]
Does anyone know what the difference between the 3 sync modes is and which one is the best? I have spent hours trying to look it up online and can't seem to find any info.

**Comment by Palakis** [comment]
@Empathetic Try with "Source Timing", otherwise "Internal"
