### ISSUE TITLE
NDI high usage CPU

### ISSUE THREAD

**Issue by Sanswed** [Palakis/obs-ndi#254]
When NDI not working - http://prntscr.com/lk4k7q - http://prntscr.com/lk4lar
when NDI working - http://prntscr.com/lk4kx5 - http://prntscr.com/lk4lhx

This is on my gaming pc and I only use game capture, display capture.
my gaming pc - -I5 6600k 3.5GHz
-GTX 1060 6G
-16 GB RAM

my obs settings -  http://prntscr.com/lk4mzo - http://prntscr.com/lk4n2n - http://prntscr.com/lk4n6r
 

Here's my OBS log -- https://obsproject.com/logs/aVH2o_2WR06xCgjD

**Comment by guitaristtom** [comment]
NDI still uses some of your CPU, it's still encoding the video. It's just a lot less than using RTMP (default streaming protocol in OBS) to stream to Twitch, Facebook, etc.
