### ISSUE TITLE
artifacts with PTZoptics camera

### ISSUE THREAD

**Issue by mjehnichen** [Palakis/obs-ndi#256]
first: thank you very much for your plug-in!!
i am experiencing artifacts when the camera ist tilting or panning. This only happens with NDI-Source Plugin in to OBS 22.03 (Mac). Whereas the same stream shown in the Newtek NDI-Video Monitor is just fine. Any Idea?
I upgrade to the new plugin version 4.5.3 but i am not sure if OBS is using the new one. How can i remove the old plug-in and then install the newest one?
s. video: https://bildwolke.de/index.php/s/bsx4b5cX8gwsnKr
thank you for answering

martin

**Comment by Palakis** [comment]
@mjehnichen Hi, this is out of the scope of this plugin, as the video quality with NDI|HX uses H.264 and depends on the settings provided (or not) to you through the Web GUI of the device.

The user manual of the PT12X-NDI mentions a "Video" settings page in the Web GUI. On this page, you have access to H.264 encoding settings (level, bitrate, bitrate mode, ...)
