### ISSUE TITLE
Gaming PC has NDI discovery issues

### ISSUE THREAD

**Issue by CheenoA** [Palakis/obs-ndi#257]
I've been searching for a solution for this for a week now to no avail.

First off, specs:

**Gaming PC (GPC):**
CPU: i7 8700k
GPU: Asus 1080ti
Windows 10 Home 1803 (build 17134.407)

**Streaming PC (SPC):**
CPU: i7 4700MQ
GPU: GeForce GT 755M
Windows 8.1 ver 6.3 (build 9600)

Both have been on the same router/switch
Firewalls for both are set to allow all.
Both have the same versions of OBS and NDI.

**What's happening (PROBLEMS):**
SPC can see its own NDI source.
GPC can see and show SPC NDI source.
GPC can't see it's own NDI source.

**What has been done:**
Firewall configured to allow
Both are on the same home network.
GPC sees SPC source but not vice versa.
![image](https://user-images.githubusercontent.com/45553165/49358943-74be5180-f70f-11e8-9af1-5efac2a16b95.png)

**Comment by TekSoup** [comment]
turn OFF Firewall on both computers and see if that works?

**Comment by CheenoA** [comment]
> 
> 
> turn OFF Firewall on both computers and see if that works?

Will check, but I doubt that it will resurface because my gaming PC can't detect the NDI source either way.

**Comment by CheenoA** [comment]
@TekSoup No dice. Turning off the firewalls for both did not resolve anything. :(

**Comment by TekSoup** [comment]
maybe a router setting? can you access your computers both ways over the network? this video will help also, i had a similar problem. https://www.youtube.com/watch?v=K4e0ULIlWOM

**Comment by TekSoup** [comment]
PTZoptics has a NDI video on youtube, im in a hurry, i cant look for it right now, but it helps also.

**Comment by CheenoA** [comment]
@TekSoup Super appreciate the help. I'm checking the videos out. I'll let you know how it turns out.

**Comment by CheenoA** [comment]
@TekSoup My computers can talk to each other just fine. I'm starting to think it's really a program issue now, rather than a network issue.

**Comment by Helgaiden** [comment]
@CheenoA if you think thats the case, i'd try removing everything NDI related...maybe even nuking it with revo uninstaller, then running ccleaner for apps AND registry, then rebooting and reinstalling what you need to try again.

**Comment by CheenoA** [comment]
@Helgaiden Media Streaming has been enabled on both prior to posting this issue. :(

I'll try removing everything NDI-related and reinstalling. I'll get back to you on the outcome.

**Comment by CheenoA** [comment]
@Helgaiden The same problem persists. :(

**Comment by CheenoA** [comment]
Now I'm thinking fixing the IP works, but I'm not sure on how that works.

**Comment by CheenoA** [comment]
Bumping.

**Comment by CheenoA** [comment]
Fixed it! Used OBS 32-bit.
