### ISSUE TITLE
All settings appear to be sufficient for live streaming quality video, but the quality is poor

### ISSUE THREAD

**Issue by chrono18** [Palakis/obs-ndi#259]
Hello, I am having problems with the OBS NDI plugin. When transferring the content from my gaming PC to streaming PC, the quality is great. When I expand the NDI source on my streaming PC it looks great (I think that this implies that there is no problem with the connection between my two PCs?)
The problem is that when I start streaming the quality is much lower than it should be. Below I have included my settings:
STREAMING PC OBS SETTINGS (Ryzen 7 2700X + GTX560 + 16GB DDR4 RAM @2666)
![image](https://user-images.githubusercontent.com/45730074/49695503-4ef2db80-fb59-11e8-9ac5-2a82c1f3bae2.png)
![image 1](https://user-images.githubusercontent.com/45730074/49695504-50240880-fb59-11e8-84fd-bfc1f7ca0aaa.png)
![image 2](https://user-images.githubusercontent.com/45730074/49695505-51edcc00-fb59-11e8-88f4-8196423dc48a.png)

GAMING PC Settings (I7-6700k + GTX970 + 16GB RAM)
![image](https://user-images.githubusercontent.com/45730074/49695528-c6286f80-fb59-11e8-851d-01e71c281adb.png)
![image](https://user-images.githubusercontent.com/45730074/49695531-d4768b80-fb59-11e8-8fbf-f252d138745c.png)

Any idea what the issues might be?

**Comment by Ghostaunt** [comment]
Same issue here

**Comment by Palakis** [comment]
@chrono18 @Ghostaunt If the video quality in fine in the main program view but not on the stream output, this is an issue with your H.264 stream settings on the streaming PC, not an NDI issue.

**Comment by Ghostaunt** [comment]
I have a Ryzen 7 1700. I tried every settings for x264. CPU pressets , Fast, very fast , extrafast etc... Nothing seems to be good for an hight quality.
