### ISSUE TITLE
Dedicated NDI™ Output filter not available in Mac OS

### ISSUE THREAD

**Issue by glatorg** [Palakis/obs-ndi#261]
iMac Sierra 10.12.6
OBS 22.0.3
obs-ndi 4.5.3

I can see in Tools > NDI™ Output settings
but I can't see "Dedicated NDI™ Output " in filter list

What I am missing?

**Comment by Palakis** [comment]
@glatorg Does it appear if you update obs-ndi to 4.6.0 ?
