### ISSUE TITLE
60fps stutter

### ISSUE THREAD

**Issue by darthclide** [Palakis/obs-ndi#265]
This issue has been brought up since 2017, and I was hoping that with this post, it will encourage someone to take a crack at solving it.

I simply need to send my OBS scene, to another computer, with as close to lossless quality as possible (such as setting the bitrate to 500mbps on my 1 Gigabit cable), with 0 stutter.

Any help would be appreciated.

**Comment by Helgaiden** [comment]
You cant manually set the bitrate the that NDI works in OBS.

**Comment by Palakis** [comment]
@darthclide 
> This issue has been brought up since 2017

Which issue? "60fps stutter" or the ability to control NDI bandwidth?

**Comment by Palakis** [comment]
As @Helgaiden said, it's not possible to control NDI bandwidth/bitrate atm. It's a limitation of the NDI SDK.
The closest thing to this is the "Bandwidth mode" input setting, with allows you to chose between highest quality, low bandwidth or audio-only modes when receiving NDI.

**Comment by darthclide** [comment]
> @darthclide
> 
> > This issue has been brought up since 2017
> 
> Which issue? "60fps stutter" or the ability to control NDI bandwidth?

The 60fps stutter is the problem. The second paragraph is only there to say exactly what I am looking for, in the hopes that maybe NDI can offer this solution one day.

Any suggestions as to why after 10 minutes it turns into a stutter-fest? (I have tried all timings before you ask).

**Comment by Helgaiden** [comment]
I've been doing 60fps with NDI since palakis originally released it. Doesn't seem to be an issue for me. If all configuration is good and all on your end, I'd guess it's something to do with router/switch/networking settings of some sort.

**Comment by loopy750** [comment]
If you're on Windows can you try my fork and see if anything changes? Older versions <4.1.3 were ok, so I changed something, and then used QCTools to check recordings for stutters, or "duplicate frames."

**Comment by darthclide** [comment]
> I've been doing 60fps with NDI since palakis originally released it. Doesn't seem to be an issue for me. If all configuration is good and all on your end, I'd guess it's something to do with router/switch/networking settings of some sort.

I am connected directly between 2 network cards. There is no router involved. This is the best possible method for NDI as there is no device the cable must pass through (the cable is 10 feet long).

On both computers I use the stock motherboard ethernet for my internet connection. Maybe NDI is randomly sending packets over the router instead of through my network cards?

**Comment by darthclide** [comment]
> If you're on Windows can you try my fork and see if anything changes? Older versions <4.1.3 were ok, so I changed something, and then used QCTools to check recordings for stutters, or "duplicate frames."

I have tried NDI ever 4-6 months since 2017, and this issue persists. Things are 60fps smooth at first, but then after 10 minutes it gets super stuttery.

**Comment by Helgaiden** [comment]
NDI automatically will use any and all available network connections, so there is a chance you might be running into an issue where it tries to go through your router instead of the direct connection between the computers. Try both on the same switch, and if thats no possible, then buy a standalone gigabit switch and plug both computers into that, and instead of running your ethernet cable for internet access to the one PC, plug it into the switch instead to give both PCs internet access.

**Comment by Helgaiden** [comment]
You can't specifically configure NDI to use a specific interface.

**Comment by darthclide** [comment]
> You can't specifically configure NDI to use a specific interface.

I know. But wouldn't it be better to have this ability anyway?

**Comment by Palakis** [comment]
@darthclide I'd be nice to have that feature I agree. But the thing is... NewTek's SDK doesn't any option to allow such a thing. Otherwise rest assured that option would already be in the plugin if such a thing were possible.

**Comment by Palakis** [comment]
@darthclide
> And if NDI was dumb enough to go over more hops than my network cards, then how can we be sure this switch will help? What if it tries going past the switch, to the router, and then back again?

Doesn't make much sense I'm afraid. The router is not involved at all unless your computer needs to reach another subnet (it's that way for everything, not just NDI).

If your both of your computers are on the same subnet and the same switch, traffic between them two will stay on the switch and won't make any hop through the router.

**Comment by darthclide** [comment]
> @darthclide
> 
> > And if NDI was dumb enough to go over more hops than my network cards, then how can we be sure this switch will help? What if it tries going past the switch, to the router, and then back again?
> 
> Doesn't make much sense I'm afraid. The router is not involved at all unless your computer needs to reach another subnet (it's that way for everything, not just NDI).
> 
> If your both of your computers are on the same subnet and the same switch, traffic between them two will stay on the switch and won't make any hop through the router.

So let's go back to the original problem. If my data is being routed correctly between my 2 computers, then why is there stutter? What other reason could there be?

**Comment by Helgaiden** [comment]
Sooooooooo have you tried both PCs to a switch or have you always tried then directly connected to eachother? Because you ignored my suggestion, or rather you treated it as pointless and instead wished for a feature we can't have, then...well your posts are clear and don't need to be repeated.

Try my previous suggestion. Scroll up if you need to read it again.

**Comment by darthclide** [comment]
> Sooooooooo have you tried both PCs to a switch or have you always tried then directly connected to eachother? Because you ignored my suggestion, or rather you treated it as pointless and instead wished for a feature we can't have, then...well your posts are clear and don't need to be repeated.
> 
> Try my previous suggestion. Scroll up if you need to read it again.

Because I shouldn't have to go out and buy a switch if that isn't the problem. I said it already: I have confirmed that NDI uses the correct line but this stutter persists. So unless NDI is randomly sending a few packets the wrong way, this is not the problem. I will listen to suggestions that aren't already proven "pointless" as you say.

**Comment by darthclide** [comment]
Extra info: The stutter is showing in the preview before I even start recording/streaming

**Comment by MrFloooo** [comment]
I use NDI as well. The preview in obs on my Streaming PC is lagging, if i play with 100+ fps on my Gaming PC. My GPU is by 99%.  If i cap my Games @60fps my GPU is by 60-70% & the preview on my Streaming PC is smoother! Not perfect, but better.

**Comment by darthclide** [comment]
> I use NDI as well. The preview in obs on my Streaming PC is lagging, if i play with 100+ fps on my Gaming PC. My GPU is by 99%. If i cap my Games at 60fps my GPU is by 60-70% & the preview on my Streaming PC is smoother! Not perfect, but better.

Ahhhh, so even if you are encoding with the cpu your gpu can sometimes be taxed too much. I just tested, and can confirm I get far less stutter with my preview disabled. It seems the UHD 630 is not powerful enough to simply process the incoming NDI stream. (Even though the 8700k is actually encoding the stream)

**Comment by MrFloooo** [comment]
[My Setup](https://obsproject.com/forum/threads/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.69240/page-12) (First Post) is strong enough. I hope anyone find a Solution or i have to buy an external Capture Device. Many People have this Problem.

**Comment by darthclide** [comment]
> Ah okay, so you haven't and won't try a solution proposed to you in a place where you asked for help. Classy. As if a little 4 port gigabit switch will make you go broke, cool dude.
> 
> So about what @MrFloooo was saying. @darthclide this might help you as well (since thats what you're here for). You don't need to cap your games at 60fps if you don't want to. OBS sometimes freaks out when games are too high FPS and issues like you're describing arise. Go to your game capture source, whatever it might be, go into its properties and look for the toggle "limit capture FPS." See if that helps.

Nice job assuming I have a spare 20$ laying around...
Also, let's go through this logically
1. I state I have 60fps stutter
2. You suggest that a switch will help if NDI is not sending it over the direct connection
3. I tell you that this is not the problem, but even if it were, I ask how a switch can help
4. You say get a switch
5. I again tell you that the data is being sent over the direct connection
6. You tell me that I am ignoring your proposed solution and act smug.

You do realize how dumb you look right now correct?

But in any case, I have confirmed that lack of a dedicated gpu is the problem. After multiple tests, the stutter is much less with preview disabled. And it matches up with task manager going from 85% gpu usage, to 62% when I disable the preview. But as I have no money to spare for a gpu, I will just have to suffer with rtmp's gradual audio desync over time.

**Comment by darthclide** [comment]
> It really shows how shortsighted you are thinking I'm the one looking dumb right now. Good job on that.
> 
> But in any case,
> @Palakis it looks like it's time to close this issue and get rid of this disrespectful scrub.
> 
> Clide, it brings me joy you struggled with this for so long. Thank you for this entertaining exchange.

calls customer "disrespectful scrub" hmmmm. Not sure if this is a good idea? In any case, you can lock the thread. I have determined what is wrong via a fellow customer. Thank you @MrFloooo

**Comment by Helgaiden** [comment]
You are not my customer. I am neither associated with Newtek nor this plugin, nor OBS, not GitHub in any official capacity. What I am able to say is... whatever I want. Bye bye, broke ass.

**Comment by Gedablo** [comment]
I did some research on this stuttering thing. Well i was using obs ndi and having same issues on streaming pc. It actually doesn't matter if i use scan converter or obs on gaming pc the stutter persists. Ive tried playing with effects and noticed after i apply deinterlacer x2 on the streaming pc source the preview and stream became so much more smooth, so that would mean its a lack of buffering that causes the stutter since deinterlacer 2x is naturally a buffered thing. Ive checked the plugins code and bingo, found commit that disables buffering for the source for "less latency between machines" ive removed the code corresponding to it and recompiled plugin, ill try streaming today, to see if stuttering sittuation improves.

**Comment by loopy750** [comment]
> 
> 
> I did some research on this stuttering thing. Well i was using obs ndi and having same issues on streaming pc. It actually doesn't matter if i use scan converter or obs on gaming pc the stutter persists. Ive tried playing with effects and noticed after i apply deinterlacer x2 on the streaming pc source the preview and stream became so much more smooth, so that would mean its a lack of buffering that causes the stutter since deinterlacer 2x is naturally a buffered thing. Ive checked the plugins code and bingo, found commit that disables buffering for the source for "less latency between machines" ive removed the code corresponding to it and recompiled plugin, ill try streaming today, to see if stuttering sittuation improves.

If you're referring to the commit "source: buffering disabled. results in lower latency", I've already mentioned that in this thread, and made a fork specifically for that issue. Also I raised the issue about it some time ago but it was closed.

**Comment by Gedablo** [comment]
Why was it closed, it didnt help?

**Comment by loopy750** [comment]
No idea. It was marked as a "duplicate" issue, even though I don't think it was something anyone else had looked into.

**Comment by loopy750** [comment]
Good to hear mate. I knew that the problem all these months (or one of them anyway), but sometimes all you can do is make people aware of it, you can't force them to do anything more.

**Comment by Gephos** [comment]
loopy750 has some releases with changes forked at his repository, i think he addressed those issues. you should check that out

**Comment by egoorbb** [comment]
Is it necessary to have a switch?

**Comment by LadyViktoria** [comment]
hi maybe this sheet helps a bit. [https://forums.newtek.com/attachment.php?attachmentid=141848&d=1527267510](url)
apart from that if you install the ndi tools you will have a tool calles access manager where you can route a ndi stream to a ip address.
you can also setup a firewall rule to block traffic on port 5353/UDP on the nic you don't want ndi to use.

**Comment by Ghostaunt** [comment]
> > I did some research on this stuttering thing. Well i was using obs ndi and having same issues on streaming pc. It actually doesn't matter if i use scan converter or obs on gaming pc the stutter persists. Ive tried playing with effects and noticed after i apply deinterlacer x2 on the streaming pc source the preview and stream became so much more smooth, so that would mean its a lack of buffering that causes the stutter since deinterlacer 2x is naturally a buffered thing. Ive checked the plugins code and bingo, found commit that disables buffering for the source for "less latency between machines" ive removed the code corresponding to it and recompiled plugin, ill try streaming today, to see if stuttering sittuation improves.
> 
> If you're referring to the commit "source: buffering disabled. results in lower latency", I've already mentioned that in this thread, and made a fork specifically for that issue. Also I raised the issue about it some time ago but it was closed.

I'll try your fork. How this doesn't be added in official package ?

**Comment by Palakis** [comment]
@loopy750 Could you please make a pull request with your fix? I could fix it in a whim but I'd rather let you get proper credit for your discovery.

Also, i'm trying to keep the issue board tidy whenever i can, but you can still comment on closed issues. Don't hesitate to push for an issue to be reopened (with proper argumenting of course).
