### ISSUE TITLE
Choppy External Audio

### ISSUE THREAD

**Issue by bpstream** [Palakis/obs-ndi#268]
Hi, I'm having an interesting issue.

I've looked around and the issues that people tend to have with audio is based on audio from the ndi source being choppy.

My issue is with unrelated audio. I have a behringer mixer that brings in audio for commentary and game sound. The audio of the ndi source is muted.

The ndi source is actually from the camera of a phone, using the wifi (not ideal). It's just a rough setup that we're testing out to see if a similar setup would be viable.

Any scene in OBS without the ndi source has perfectly good audio. However, when swapping to a scene with the ndi source, the audio becomes choppy. The video itself is perfectly fine.

Any help would be appreciated.

**Comment by paulpv** [comment]
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.
