### ISSUE TITLE
obs-ndi plugin doesn't connect to and display NDI source

### ISSUE THREAD

**Issue by Warp999** [Palakis/obs-ndi#27]
**Prerequisites:**

- Two PCs
- Newtek NDI tools (downloadable here: [https://www.newtek.com/ndi/tools/](https://www.newtek.com/ndi/tools/))
- OBS Studio with obs-ndi plugin

**Repro Steps:**

1. Run NDI Test Pattern Generator on a PC-1
2. Run OBS Studio with the obs-ndi plugin on PC-2
3. In OBS Studio, set up a scene that includes an NDI source. Configure the source to use the NDI Test Pattern from PC-1.

**Expected Results:**

The obs-ndi plugin should recognize the test pattern generated from PC-1, and should display video/audio from the test pattern.

**Actual Results:**

The obs-ndi plugin recognizes that PC-1 is an NDI source, but no video/audio is present. Only a blank (black) screen is seen. NOTE: The repro on this sometimes requires closing and reopening OBS Studio.

**Workaround:**

I've discovered a workaround that seems to work 100% of the time. On PC-2 (running OBS Studio), if I run the NDI Video Monitor tool, the obs-ndi plugin will also display video. Once video is present in obs-ndi, I can close the Video Monitor tool, and obs-ndi will continue to display video. It seems Video Monitor is doing something to initialize the video/audio stream that obs-ndi doesn't currently (or doesn't always) do.

**Comment by Palakis** [comment]
How many network interfaces do you see in Windows Network Settings ?

**Comment by Warp999** [comment]
One wifi adapter. But there are also a couple of Bluetooth devices showing up under network adapters (see attached screen clip).
![networkadapters](https://user-images.githubusercontent.com/16965538/27981891-23fc0598-635a-11e7-8804-ef75b173aba8.png)

**Comment by Palakis** [comment]
Try these things:
- Download and install NewTek's NDI Tools and open the Video Monitor to see if the issue happens in this app too (this would mean a broader network issue or NDI library issue)
- Disconnect from the any AP or disable the wifi adapter and try to look for NDI sources again

**Comment by Palakis** [comment]
@Warp999 Please see #31.
