### ISSUE TITLE
obs-ndi lag in OBS but not XSplit?

### ISSUE THREAD

**Issue by cole2kb** [Palakis/obs-ndi#271]
Hiya! Having a bit of an odd issue. OBS running on gaming PC, sending NDI output to streaming PC. On the streaming PC, the video is fairly choppy, but if I receive the same output on the same PC in XSplit, it's smooth as butter. Any thoughts on how I can track down the issue?

I'd prefer to use OBS simply because XSplit does not allow me to set a render delay for the NDI source, which means I have audio sync issues that I simply can not solve.

**Comment by Palakis** [comment]
@cole2kb Please update to obs-ndi 4.6. It has a fix for stuttering issues.
