### ISSUE TITLE
Obs 23.0.0-rc1 support?

### ISSUE THREAD

**Issue by kerinzeebart** [Palakis/obs-ndi#272]
Hey,
I tried to get NDI working on Obs 23 and install goes fine but NDI does not shop up on menu. Any suggestions?

**Comment by Helgaiden** [comment]
The websocket plugin is reportedly broken as well with the new OBS update. @Palakis

**Comment by dodgepong** [comment]
The issue there is that the RC accidentally shipped with Qt5Network.dll. That file just needs to be deleted from the `bin/64bit` inside the OBS folder.

**Comment by kerinzeebart** [comment]
> The issue there is that the RC accidentally shipped with Qt5Network.dll. That file just needs to be deleted from the `bin/64bit` inside the OBS folder.

Tried to delete it but still didn't help NDI not showing up in menus.

**Comment by dodgepong** [comment]
Sorry, that was in response to @Helgaiden's comment about the websocket plugin.

**Comment by Helgaiden** [comment]
@dodgepong oh great, ill let the Touch Portal guys know about it. Thanks.

**Comment by kerinzeebart** [comment]
Update Got it to work! had to manually copy the files from .zip Autoinstaller failed.

**Comment by Helgaiden** [comment]
Cool hopefully @Palakis can update the installer when its needed then :D
