### ISSUE TITLE
obs-4.5.3 compilation fails with CMake Error at external/FindLibObs.cmake:98 (include)

### ISSUE THREAD

**Issue by martinkg** [Palakis/obs-ndi#275]
Hi,
I'am trying to compile obs-ndi for fedora, but this fails with the following error message:

 + /usr/bin/cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DLIBOBS_INCLUDE_DIR=/usr/include/obs .
-- The C compiler identification is GNU 8.2.1
-- The CXX compiler identification is GNU 8.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- works -- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++
-- works -- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Libobs: /usr/bin/../lib64/libobs.so CMake Error at external/FindLibObs.cmake:98 (include): include could not find load file: /usr/include/obs/../cmake/external/ObsPluginHelpers.cmake Call Stack (most recent call first): CMakeLists.txt:9 (include)
-- Configuring incomplete, errors occurred! See also "/home/martin/rpmbuild/BUILD/obs-ndi-4.5.3/CMakeFiles/CMakeOutput.log".

The error happens with obs-studio-22.0.2 and obs-studio-23.0rc1
Regards Martin

**Comment by mphartzheim** [comment]
Same issue occurs for me using Solus 4.0 with obs-studio-23.0.2 and obs-studio-devel-23.0.2.

**Comment by martinkg** [comment]
On Fedora 30, I was able to compile obs-ndi, but only with a quick and dirty workaround.
For this I first had to copy the files obs-frontend-api.h and ObsPluginHelpers.cmake to certain directories.

```
# cp /home/martin/rpmbuild/BUILD/obs-studio-23.0.2/UI/obs-frontend-api/obs-frontend-api.h / usr / include / obs
# cp /home/martin/rpmbuild/BUILD/obs-ndi-4.6.0/external/ObsPluginHelpers.cmake / usr / lib64 / cmake / LibObs
```
In the appendix I added the rpm spec file, in which are still further distri specific attitudes, which I use by sed command.
[obs-ndi.spec.txt](https://github.com/Palakis/obs-ndi/files/3042762/obs-ndi.spec.txt)

**Comment by mphartzheim** [comment]
Thanks. That resolved it for me.
