### ISSUE TITLE
OBS streaming pc obs disconnects / lag after

### ISSUE THREAD

**Issue by arthurkowinski** [Palakis/obs-ndi#278]
Hello, 

My obs works fine at the begining (10 mins) then my obs disconnects. It takes a bit of time to reconnect but once it reconnected my NDI source is lagging (audio and video). It can not be the connection. I have 400 mbits download and 20 mbits upload.

Streaming pc spec :

AMD Ryzen 5 1600 Six-Core 3.20 ghz
16 ram 
1050 ti 3 gbit

I don't know why I have this with that PC. Is my processor too weak for 6000 bitrate stream with 720p 60 fps quality?

Thx in advance

**Comment by Palakis** [comment]
@arthurkowinski 
>  It can not be the connection. I have 400 mbits download and 20 mbits upload.

NDI is a LAN technology. Even if you have 1Gig Fiber Internet, if your computer has shitty 100mbps NICs you won't go very far with NDI.

What is your NDI source?
