### ISSUE TITLE
i cant install the mac pluggin

### ISSUE THREAD

**Issue by zacksito** [Palakis/obs-ndi#279]
i try to instal the pluggin in my mac, the instalation works well but when i open the obs the ndi options doesnt apear, help pls!

**Comment by Palakis** [comment]
@zacksito I'll need you to provide an OBS log file (see under Help > Logs) and try to update to obs-ndi 4.6.

**Comment by Camichan** [comment]
Me too. I tried to install the plugin on Mac and the instalation said OK, but then I can't see the ndi sourcer to add. I looked for among archives in OBS plugins data folder and obs-ndi-plugin archives weren't there. Then, I watched the Logs and only could see modules loaded but obs-ndi-plugin module wasn't there too.

OBS log file:

23:41:50.983: Initializing OpenGL...
23:41:51.007: Loading up OpenGL on adapter Intel Inc. Intel Iris OpenGL Engine
23:41:51.007: OpenGL loaded successfully, version 4.1 INTEL-10.36.23, shading language 4.10
23:41:51.084: ---------------------------------
23:41:51.084: video settings reset:
23:41:51.084: 	base resolution:   1280x800
23:41:51.084: 	output resolution: 1024x640
23:41:51.084: 	downscale filter:  Bicubic
23:41:51.084: 	fps:               30/1
23:41:51.084: 	format:            NV12
23:41:51.084: 	YUV mode:          601/Partial
23:41:51.084: NV12 texture support not available
23:41:51.084: Audio monitoring device:
23:41:51.084: 	name: Por defecto
23:41:51.084: 	id: default
23:41:51.084: ---------------------------------
23:41:51.089: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
23:41:51.097: os_dlopen(libpython3.6m.dylib->libpython3.6m.dylib): dlopen(libpython3.6m.dylib, 1): image not found
23:41:51.097: 
23:41:51.097: [Python] Could not load library: libpython3.6m.dylib
23:41:51.154: No blackmagic support
23:41:51.223: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
23:41:51.252: [obs-browser]: Version 2.3.0
23:41:51.274: VLC found, VLC video source enabled
23:41:51.275: Ignoring old obs-browser.so version
23:41:51.279: Failed to load 'es-ES' text for module: 'obs-ios-camera-source.so'
23:41:51.279: Loading iOS Camera Plugin (version 2.5.0)
23:41:51.279: ---------------------------------
23:41:51.279:   Loaded Modules:
23:41:51.279:     obs-ios-camera-source.so
23:41:51.279:     vlc-video.so
23:41:51.279:     text-freetype2.so
23:41:51.279:     rtmp-services.so
23:41:51.279:     obs-x264.so
23:41:51.279:     obs-vst.so
23:41:51.279:     obs-transitions.so
23:41:51.279:     obs-outputs.so
23:41:51.279:     obs-filters.so
23:41:51.279:     obs-ffmpeg.so
23:41:51.279:     obs-browser.so
23:41:51.279:     mac-vth264.so
23:41:51.279:     mac-syphon.so
23:41:51.279:     mac-decklink.so
23:41:51.279:     mac-capture.so
23:41:51.279:     mac-avcapture.so
23:41:51.279:     linux-jack.so
23:41:51.279:     image-source.so
23:41:51.279:     frontend-tools.so
23:41:51.279:     decklink-ouput-ui.so
23:41:51.279:     coreaudio-encoder.so
23:41:51.279: ---------------------------------
23:41:51.279: ==== Startup complete ===============================================
23:41:51.298: Service '' not found
23:41:51.512: All scene data cleared

**Comment by Palakis** [comment]
@Camichan @zacksito In the NDI installer, which install drive did you select?

**Comment by Camichan** [comment]
@Palakis In my case, Macintosh HD. The installer doesn't let me select any folder, only that drive.

**Comment by anophelles** [comment]
I have the same issue. Has anyone found a solution?

**Comment by anophelles** [comment]
Hi Guys, I found this version of plugin and works for me.:
obs-ndi-655a7a3-master
I hope it works for you too...
