### ISSUE TITLE
Performance issue on the output/encode module

### ISSUE THREAD

**Issue by Pimpmuckl** [Palakis/obs-ndi#28]
Been testing the last few hours with the updated plugin from #24 and noticed the output module having some performance issues.

Following setup:
PC1 has one scene with a 1440p game capture on a 1440p 60fps canvas, sends to PC2 via the NDI Output which has one scene with the respective NDI Input and then encodes everything to twitch.

OBS/OBS: PC1 OBS preview is smooth, PC2 OBS preview (and resulting stream) is not smooth (feels like ~45fps)
OBS/Xsplit: PC1 OBS preview is smooth, PC2 Xsplit preview (and resulting stream) is not smooth (similar to above)
Xsplit/OBS: PC1 Xsplit preview is smooth, PC2 OBS preview is also smooth, stream feels very smooth.

Both PCs are quite beefy (5820k, GTX 1080 in PC1, Ryzen 1700 in PC2). Same happens with a full 1080p pipeline.

Exactly nothing in the log, I suspect that the frame pacing might be the culprit here, but can't verify.

**Comment by Palakis** [comment]
Thanks for the report, @Pimpmuckl. I'll have a look at this. Can try previewing the NDI output with NewTek's Video Monitor (part of NewTek's NDI Tools)?

**Comment by Palakis** [comment]
Also, what do OBS' stats window (Show menu > Stats) says? Is it reporting dropped frames? Frame jumps? Is the mean frame render time is low enough (less than 16ms for 60fps)?

**Comment by Palakis** [comment]
Make sure that you're running at least Gigabit Ethernet (not wifi or 100Mbit/s Ethernet) between the two computers. But I guess that if Xsplit's output works properly then your network setup seems fine.

**Comment by Palakis** [comment]
You say you noticed this issue with the latest development builds, but does the same happens with the official 4.0 release of obs-ndi as well?

**Comment by Palakis** [comment]
I changed the timestamp source of the NDI Output to make it use OBS' engine timestamp. Please try build here: https://ci.appveyor.com/api/buildjobs/2xo4smcwjsj8k8yg/artifacts/obs-ndi-d8d3952.zip

**Comment by Pimpmuckl** [comment]
Thanks, will test that tomorrow and report back, thank you for taking the time to swap the timestamps back.

To clarify, I used your updated build from [here](https://github.com/Palakis/obs-ndi/issues/24#issuecomment-318367317) to fix a/v desync issues, if you simply "reverted" the changes, I'll definitely see if it's smooth, but it will a/v drift after a few hours again.

**Comment by Pimpmuckl** [comment]
Alright tested now: With OBS generated timestamps the A/V desync occurs again after a few hours.

**Comment by Palakis** [comment]
Thanks for your feedback. At least the framerate issue is fixed.
The desync issue will need deeper investigation.
