### ISSUE TITLE
Is it possible to stream over WAN?

### ISSUE THREAD

**Issue by Jonatino** [Palakis/obs-ndi#280]
I'd like to send my NDI stream from my gaming PC to my AWS vm over WAN. 

Is this possible?

**Comment by stickus** [comment]
You could probably do this over VPN to your AWS instance. You'd need an awful big upload speed to be able to handle it though.

**Comment by Jonatino** [comment]
@stickus I'll try that. Right now I got 1500 download 940 upload at home so I think I have the bandwidth available. Thanks.
