### ISSUE TITLE
NDI not showing on OBS 23.0.1 (Ubuntu)

### ISSUE THREAD

**Issue by johnweland** [Palakis/obs-ndi#282]
As the title says the NDI plugin is not showing up in OBS 23.0.1.  I have install libndi3_3.5.1-1_amd64.deb I installed obs-ndi_4.5.3-1_amd64.deb it of course installed to /usr/lib/obs-plugins and I moved it to /usr/lib/x86_64-linux-gnu/obs-plugins as mentioned in issue #81 

the plugin does for with OBS 23.0.1 on Windows as  I tried this earlier, I was hoping to move my encoding rig to Linux for less overhead.
Log file
[2019-03-04 20-20-37.txt](https://github.com/Palakis/obs-ndi/files/2929008/2019-03-04.20-20-37.txt)

**Comment by Palakis** [comment]
@johnweland I don't see `obs-ndi.so` in the loaded plugins list. Try running: `sudo cp /usr/lib/obs-plugins/obs-ndi.so /usr/lib/x86_64-linux-gnu/obs-plugins/`.

**Comment by johnweland** [comment]
That did not work however this seems to be related to the OBS installed form the software manager in Ubuntu. If you install from the OBS website this works fine.
