### ISSUE TITLE
Hidden Audio source in other scene continue to be sent

### ISSUE THREAD

**Issue by Ghostaunt** [Palakis/obs-ndi#285]
In my main scene, I have an audio output for my microphone. For this source I have added a NDI filter to get audio on my Streaming computer. 
But If i change scene, without this audio source, audio keep to be sent on my streaming computer, So I can mute it as I want.

I think this is an issue of this plugin

Thanks for help

**Comment by theodonal** [comment]
I Have just come across something similar, however i believe it is a wider bug than audio just being sent even after switching scene. Using the latest release build (4.6.0) when I mute an dedicated audio source on the NDI host the audio is still routed to the NDI receiver. This means i am unable to mute and any audio sources from the host side. I need to access my streaming pc to mute the source there.

**Comment by unknowndomain** [comment]
I also have this issue, the audio from any given scene only plays out if the scene is active in program output, where as with a USB interface the audio device is 'omni-present' so to speak.

**Comment by Palakis** [comment]
Duplicate of #138
