### ISSUE TITLE
Jerky video on the streaming computer

### ISSUE THREAD

**Issue by EvergreenGOD** [Palakis/obs-ndi#29]
Hi all,
I followed this tuto to install the NDI input/output from there https://youtu.be/AH_ECDLkKEA?list=WL

Everything works but my NDI output on my "streaming computer" is f**king jerky and I really don't know how to fix that.. 'cause of this bug, it's jerky on my stream too.. 

Does someone know this problem and how to fix it?

Regards﻿

**Comment by Palakis** [comment]
This has already been reported here: #28
