### ISSUE TITLE
Unable to compile for windows, help from someone who can build 4.6.0

### ISSUE THREAD

**Issue by cfreeman29** [Palakis/obs-ndi#290]
I am unable to compile 4.6.0 the current version. It comes with a very important stutter fix that I need to use. If anyone is able to compile that and send it to me that would be awesome.

**Comment by Palakis** [comment]
@cfreeman29 4.6 is coming out this week, but in the meantime you can use one of the automated builds: https://ci.appveyor.com/project/Palakis/obs-ndi/builds/22994688/artifacts
