### ISSUE TITLE
NDi plugin doesn't appear on OBS tools

### ISSUE THREAD

**Issue by FernandoNeo** [Palakis/obs-ndi#291]
I've downloaded OBS 23.0.2   + NDI 3.8+ Runtime  +  obs-ndi-4.6.0-Windows-Installer.exe, and ok it worked in my Intel core i5.  But the same three didn't worked in my AMD Phenon II.  When I open tools window on my Intel NDI Output settings appears. But in my AMD don't. I've tried everyting, include copy all folder instalation from my Intel and past in my AMD and nothing =/. What can I do?

**Comment by dodgepong** [comment]
The Phenom II doesn't support Supplemental SSE3, and thus does not support NDI.
