### ISSUE TITLE
building libndi3_3.8.0-1_amd64.deb 

### ISSUE THREAD

**Issue by LPhil** [Palakis/obs-ndi#292]
There is debian package, named libndi3_3.8.0-1_amd64.deb. How is this package build?
I have to build up this part with all dependencies as source binary package for the ARM platform.
Thx a lot

**Comment by Palakis** [comment]
@LPhil It's built with checkinstall in `CI/package-xenial.sh`: https://github.com/Palakis/obs-ndi/blob/master/CI/package-xenial.sh#L37-L43
