### ISSUE TITLE
No NDI connection between Gaming PC and Stream PC

### ISSUE THREAD

**Issue by Meggsey** [Palakis/obs-ndi#293]
Been streaming for a month straight and all of a sudden the NDI connection does not seem to work. 

Specifically, when I select an NDI Output Source, there is no 'Source Name' to select from the dropdown list. 

Spent hours on this issue so looking for any advice that can help on this. I have disabled firewalls on both devices.

Logs:

Game PC: https://obsproject.com/logs/pgnVkl8RHuMt-c4g
Stream PC: https://obsproject.com/logs/16J7SyOqtef9zJYB

**Comment by paulpv** [comment]
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.
