### ISSUE TITLE
First PC Freezes indefinitely 

### ISSUE THREAD

**Issue by taariqamozilla** [Palakis/obs-ndi#294]
Whenever my second pc receives any video signal from the first, before it displays on the second, the first pc freezes indefinitely. I have a video of the issue: https://drive.google.com/file/d/1NDrBeVcIWvQmDK2JbV07ItfEkPRyjyJL/view?usp=drivesdk

**Comment by taariqamozilla** [comment]
bump?

**Comment by paulpv** [comment]
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.
