### ISSUE TITLE
NDI library/runtime found but not loaded gentoo linux

### ISSUE THREAD

**Issue by oyviaase** [Palakis/obs-ndi#297]
Starting obs-ndi with libndi manually installed to /usr/local/lib gives the error "NDI Runtime not found", and the following relevant log from the verbose option

``
info: [obs-ndi] hello ! (version 4.6.0)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.so.3'
error: [obs-ndi] Can't find the NDI library
``

This error might be related to https://github.com/Palakis/obs-ndi/issues/276

**Comment by Palakis** [comment]
@oyviaase You probably need to run `ldconfig` again after copying libndi.
