### ISSUE TITLE
Premultiplied alpha?

### ISSUE THREAD

**Issue by ToxMox** [Palakis/obs-ndi#30]
This is on Windows 10 x64.  I am using Magic Music Visuals which has Spout output support. I am using Spout to NDI to send via NDI to the plugin as a source in OBS. All alpha effects have a darkening effect instead of looking normal. From what I understand this is probably due to the plugin using premultiplied alpha? If this is the case can we get a fix for this please? I could be wrong and maybe Spout to NDI is the culprit. PS this plugin is amazing!

**Comment by Palakis** [comment]
Hi @ToxMox, can you provide a video sample of the issue happening?
I don't explicitely enforce premultiplied alpha in the code, and I don't quite see how the mask resulting from premultiplied alpha could cause this, but I'll have a look. Thanks for your report!

**Comment by ToxMox** [comment]
Hi @Palakis 
Here is a screenshot.  http://i.imgur.com/zLYA2p5.png

The top one is the NDI input. You can see the glow effect is all dark and shadowy looking. The bottom one is a PNG I exported from the software and put in as an image source in OBS. You can see the nice colorful glow effect and what it's supposed to look like.

**Comment by Palakis** [comment]
Hmm, strange. Thanks for this!

**Comment by Palakis** [comment]
Btw this actually looks like a premultiplied alpha issue.

**Comment by ToxMox** [comment]
@Palakis gotcha. Like I mentioned before I can't rule out that the issue isn't caused by the Spout to NDI app I'm using to convert from Spout to NDI. I actually hope it is something simple in the NDI OBS plugin because I'm not sure I would be able to get the Spout to NDI app fixed :)

I don't know if this helps but the CEF browser had this problem at one point and it was supposedly an easy fix:
https://obsproject.com/forum/threads/browser-plugin.20212/page-17
(last four posts on page 17)

Thanks again for looking into this!

**Comment by Palakis** [comment]
I checked the documentation of the NDI library and the alpha pixels are provided not premultiplied to obs-ndi, so something must happen inside OBS' engine.
By looking around I found this might actually be an issue within OBS' engine itself, that has been fixed by this commit: https://github.com/jp9000/obs-studio/commit/f8b14bdb462bfa56dfc129908f48df4c2e4ec297
It will be available in OBS 20.0.0, along with many new exciting features.

**Comment by ToxMox** [comment]
@Palakis yeah I saw that too but my only concern is that I don't meet any of those criteria. Not scaling. Not using it as a scene, and not cropping it.
BTW I found the commit on the browser source plugin that fixed the same issue there. Maybe this will help?:
https://github.com/kc5nra/obs-browser/commit/8a58665a6d70e6114ffb65929429fa234aff2d0e

**Comment by Palakis** [comment]
> my only concern is that I don't meet any of those criteria. Not scaling. Not using it as a scene, and not cropping it.

You don't need to. It's general to every source.

> BTW I found the commit on the browser source plugin that fixed the same issue there. Maybe this will help?

I found that commit too, but due to how obs-ndi pushes frames to OBS, it can't be done in a finger snap. Implementing this fix would mean reimplementing in obs-ndi the rendering code already used in OBS' engine,
I suggest that we wait for OBS 20.0.0 to come out. Then, we'll see if this fixes this issue, else I'll have to reinvent the wheel in obs-ndi.

**Comment by ToxMox** [comment]
> You don't need to. It's general to every source.

Oh. I read it as the issue only happened in those scenarios based on that commit description. 

> I suggest that we wait for OBS 20.0.0 to come out. Then, we'll see if this fixes this issue

Ok sounds like a plan. Thanks again for checking into this :)

**Comment by Palakis** [comment]
@ToxMox OBS 20.0.1 has been released. Can you test this again, please?

**Comment by Palakis** [comment]
Meh, still no luck... Tried with OBS 20.0.1 and MMV's RadialWave sample.
![Uploading obs64_2017-08-12_12-20-16.png…]()

**Comment by Palakis** [comment]
Hmm, still no luck. Tried with OBS 20.0.1 and MMV's RadialWave sample and still the same issue.
I wrote a simple filter to fix this, gonna include it in obs-ndi soon.

**Comment by ToxMox** [comment]
@Palakis yup just tested too. No luck. Also tested direct to NDI using Adobe Character Animator just to rule our the Spout to NDI converter and having the same issue.

**Comment by Palakis** [comment]
I fixed this in the latest commits. I added an optional "Fix alpha blending" setting to NDI sources. Enabling it will automatically add a premultiplied alpha filter to the source, listed as a normal filter under the source's filters.

**Comment by Palakis** [comment]
It will be available in 4.0.1, which will be available soon.

**Comment by ToxMox** [comment]
Fantastic! Looking forward to trying it :) 👍

**Comment by ToxMox** [comment]
@Palakis ok so I installed the latest NDI runtime and the new plugin. Rebooted. There is no alpha at all for me now. The background is just black for the ndi source with or without the new filter.

**Comment by Palakis** [comment]
There's a filter to add through the source properties ("Fix alpha blending" option) or you can add the filter manually in the source's filters window.

**Comment by ToxMox** [comment]
@Palakis as I mentioned. With or without the filter there simply is no alpha at all. The entire source background is black.

**Comment by Palakis** [comment]
Ah, sorry. Tired answer.

**Comment by ToxMox** [comment]
@Palakis sorry I didn't mean to come off as an ass. That's why I edited that part out but not in time I guess lol :) I appreciate everything you do!

**Comment by Palakis** [comment]
Turns out the "fastest" color format receiver mode discards alpha completely... Reverted this. There are enough issues fixed to make a hotfix soon.

**Comment by ToxMox** [comment]
Bless you! I just downloaded the latest release. It works and it's glorious! Congrats on being the first NDI implementation that works properly with alpha in a broadcasting app. ie Vmix, Xsplit, and Wirecast all do the premultiplied thing and OBS is the only one that works right :) 👍

**Comment by Lange** [comment]
@ToxMox For what it's worth, you can get alpha from NDI out of vMix if you set vMix to use ARGB32 colors. I wrote up a guide on doing this for TriCaster integration with a client about a year back: https://docs.google.com/document/d/13AECtpglESoj6sihirEgiIU68vjFHFiefC_7pyvOUHA/edit

**Comment by ToxMox** [comment]
@Lange I meant for using NDI as a source in vMix.
