### ISSUE TITLE
Blank window in windows10

### ISSUE THREAD

**Issue by uestcpollen** [Palakis/obs-ndi#300]
Thank you very much for your plugin！I have tested it and it works perfectly while we use office 2016 on windows7. At the same time, while we use office 2019 on windows10, it also displays a blank window. Could you give us any suggestions? We are looking forward to hear good news from you! Thank you very much!

**Comment by Palakis** [comment]
@uestcpollen I don't understand your question. This likely seems to be an issue with Scan Converter or vMix Desktop Capture, and not the plugin itself.

**Comment by Palakis** [comment]
@uestcpollen Could you elaborate please? Gonna close this in the meantime
