### ISSUE TITLE
German translation file de-DE.ini

### ISSUE THREAD

**Issue by martinkg** [Palakis/obs-ndi#301]
attached is the german translation file de-DE.ini
[de-DE.ini.txt](https://github.com/Palakis/obs-ndi/files/3046933/de-DE.ini.txt)

**Comment by Presskopp** [comment]
[de-DE.ini.txt](https://github.com/Palakis/obs-ndi/files/3620732/de-DE.ini.txt)
made some (small) corrections

**Comment by tt2468** [comment]
Closing since v5 will be the next release, with all new locales.
