### ISSUE TITLE
Source freeze on Mac encode computer.

### ISSUE THREAD

**Issue by Provensis** [Palakis/obs-ndi#302]
Hey,
First of all. I looked into all other Issues in here, and no one has the same problem or a fix for it.
I got Medai Sharing on, Firewall exception , same version both OBS and NDI, I even danced a little good luck dance. NOTHING has worked. :(
I got a problem. I run NDI on a PC and a Macbook. When I only got my webcam it works perfectly, so I could potentially stream my webcam 1080p 60fps no problem. But when I put a Screen recorder or GameCapture on, both the camera, screen recorder and gamecapture freezes and only the audio works.
No errors or anything.

PC is gaming computer, Macbook is encoder computer.
They got the same version of NDI and it worked a couple of months ago.

**Comment by paulpv** [comment]
This seems fixed in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC; Closing.
Feel free to comment if you test and disagree and I should reopen.
