### ISSUE TITLE
obs-ndi output no longer works on linux

### ISSUE THREAD

**Issue by AlexDaniel** [Palakis/obs-ndi#304]
There is no problem with obs-ndi 4.5.3, but obs-ndi 4.6.0 no longer works. You can turn the output on but it won't be found on other devices. Downgrading to 4.5.3 on devices that will do output resolves the problem (I can use 4.6.0 to receive streams). libndi version makes no difference (old obs-ndi works with the newest libndi). I tried building this module on master but it seems like the issue is still there.

I can't post the output right now, I'll try to do it later. However, I found this message that has pretty much identical output: https://obsproject.com/forum/threads/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.69240/page-3#post-319430

The important bit is:
```
 19:04:32.632: obs_register_source: Tried to register obs_source_info with size 264 which is more than libobs currently supports (248)
```

I'm getting the same message but with different numbers.

**Comment by Tomcatt** [comment]
I too have the issue when upgrading to 4.6, it crashes as soon it as my production computer receives data from the game computer.  If I just run the production computer only, it works.  I've tried downgrading the game system NDI to 4.5.3 to no avail the second system still crashes.

The ndi-sdk file that I need for obs-ndi-bin killes obs over all.  I'm going to roll my system back and see if I can just install obs-ndi-bin without ndi-sdk.

BTW, I'm running Manjaro (Arch) Linux.

**Comment by joenio** [comment]
I also having this issue in a Debian testing environment.

**Comment by TTMikeK** [comment]
I haven't looked too closely yet, but it looks like I have the same issue. Had no troubles getting a Windows PC to send their stream (to a destination Windows machine), but no luck on my Ubuntu laptop.

**Comment by Tomcatt** [comment]
Now I'm totally dead in the water.  Linux can stream out but not in.  My Mac can see the windows box just fine.

Even when I rollback the linux box now I can't get NDI to work anymore.  There maybe a linux update that's killing it.  I have a few more older archive I COULD use to see what's but if the problem been going on this long, I guess Linux support is dying off...?

**Comment by mikekasprzak** [comment]
Looking at the log
```
12:49:19 PM.203: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.3'
12:49:19 PM.204: [obs-ndi] NDI runtime loaded successfully
12:49:19 PM.204: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:00:58 Dec 21 2018 3.8.0)
```

**Comment by mikekasprzak** [comment]
For those looking to keep their firewalls running, here's some info.

I couldn't find the exact ports listed in their forums, but according to the NDI SDK, NDI uses a handful of ports:

* `5353` for mDNS
* `5960` for the messaging server
* `5961 to ...` for the video channels (1 port per channel)

So on Ubuntu you might do something like this:

```
sudo ufw allow 5353/tcp
sudo ufw allow 5960:5668/tcp
```

It's not clear if 1 channel is enough per output per IP (I would think so). I opened all ports on TCP and it worked, but I seem to remember the docs suggesting some part of the NDI protocol used UDP. :thinking: 

Some other links on the internet suggested NDI used the ephemeral ports. Maybe the UDP traffic goes over this? I'm not 100% sure yet.

**Comment by Palakis** [comment]
Upcoming obs-ndi 4.6.1 should fix this issue, as it will be compiled against OBS 23.2.
