### ISSUE TITLE
Make setting profile specific so it can be turned on or off per profile

### ISSUE THREAD

**Issue by digitalfiz** [Palakis/obs-ndi#305]
It would be super nice if this could be turned on or off at a profile level so when switching back and forth its not on when we dont need it

**Comment by Palakis** [comment]
@digitalfiz duplicate of #269, currently WIP on #304

**Comment by Palakis** [comment]
@digitalfiz nevermind, mistook for the WIP in obs-websocket

**Comment by zyberspace** [comment]
Hi @Palakis ,

i need this feature myself.

I'm not a C++ developer but is there more work to do for this change than just switching out the three  `obs_frontend_get_global_config()` calls in `src/Config.cpp` with `obs_frontend_get_profile_config()` ?  If not, i will happily open a PR if you don't have time to change it yourself.

(Found the profile call in https://github.com/obsproject/obs-studio/blob/master/UI/obs-frontend-api/obs-frontend-api.h#L187-L188)

**Comment by tt2468** [comment]
Unfortunately, storing configurations per-profile is unfortunately a change which would make an equal amount of people want it stored globally.

**Comment by digitalfiz** [comment]
I don't disagree with that but at least if it was stored per profile it would match how all the rest of the settings in obs work.
