### ISSUE TITLE
Allow network configuration of NDI

### ISSUE THREAD

**Issue by LevelOnGaming** [Palakis/obs-ndi#306]
I really LOVE NDI and it addresses a lot of the problems that I was trying to get around with having a dedicated streaming box and a dedicated gaming box. I purchased dedicated pci ethernet cards for both of my boxes and hard wired them together figuring there much be a way to configure NDI to take advantage of this dedicated adapter but I guess this isnt the case? (feel free to jump in if I stated this incorrectly)

I would REALLY love this feature! Thanks!

**Comment by LexusSpeed03** [comment]
Its funny you bring this up I was just about to do this as the last update is now using about 250mbps on the network card. I would like to separate it off on its own. However I am not seeing a way to do it.

**Comment by LexusSpeed03** [comment]
@LevelOnGaming I have been able to force bind IP on the game PC but the receiving PC won't connect to it on the second NIC. Maybe in the next few days will have a solution.

**Comment by LexusSpeed03** [comment]
I can run NDI over the second NIC using regular NDI software but not in the plugin. Can you please look into this as a feature?

**Comment by frogeater** [comment]
Hi,
I really love this plugin and also this request.
Is it possible to add also the sttings for NDI groups integration.
This will complete handling of NDI network features.

**Comment by Palakis** [comment]
This has already been discussed and requested in previous topics. I can't implement this right now because the NDI SDK doesn't give me the possibility to do so. If NewTek adds this to their SDK, then I'll be able to implement it. Closing this in the meantime.

**Comment by paulpv** [comment]
@Palakis I was initially thinking this might be hard to do across platforms, but OBS does this itself and perhaps the code could be re-used somehow:
https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-settings.cpp#L829-L841

Basically they are enumerating the `bind_ip` properties of the `rtmp_output` output property.
Maybe a plugin can get those too? Maybe not.

Related to the unrelated Groups comment above, it looks like https://github.com/keith8496/obs-ndi/ has done the work of updating the code to NDI 5.x.
This should allow the plugin to add the option of Groups.
Any interest in brushing off this plugin to update it to support groups?
Would you encourage/support someone willing to do this themselves?
Thanks!
