### ISSUE TITLE
Skype to OBS not working

### ISSUE THREAD

**Issue by Nile1230** [Palakis/obs-ndi#307]
I have been using Skype to OBS with the NDI plugin for a month now with no issues. Skype and OBS both did updates and now there is no video or audio to my NDI source. When I add the NDI source all I get is a red dot in the top left corner (yes I have an active Skype call going and NDI is enabled). So the source is there but receiving the data. Is this happening to anyone else? I have tried everythin gi could think of to fix it with no prevail. I have a grow YouTube channel and now I cannot interview my guests. Please help if you can this plugin is amazing!

**Comment by ciprian90** [comment]
same here :(

**Comment by Nile1230** [comment]
I did solve it the other day. Just go to google and type in Skype for creators. Download that version because the other skype still is not working. Then utilize the creators version for your NDI on OBS. When you have the window open to add your NDI set the latency to low otherwise the audio and visual don’t sink well. Now I am up and running. Hope that helps!

**Comment by ciprian90** [comment]
I just returned to also tell you that I solved it in like 2 ways.
The actual goal was to capture skype. I just did exactly what you did and there it works.
However, I also noticed, that when running Skype with "--disable-gpu --disable-gpu-compositing" you can even Window-Capture it!
Thanks and cheers! :)

**Comment by Palakis** [comment]
@Nile1230 Is your issue solved? Mind if I close this?

**Comment by Nile1230** [comment]
Yes it is

~Sent from my iPhone~
Nile Scala
203-572-3639
nilescala@gmail.com

**Comment by wero1414** [comment]
Thanks!
