### ISSUE TITLE
OBS/NDI Source doesn't appear to be working properly.

### ISSUE THREAD

**Issue by boxsterpaul** [Palakis/obs-ndi#308]
Hi! 

I had OBS-NDI working (2PCs), really wonderful BTW, but while changing some settings in Windows (Network/Graphics)  I accidentally made the ability to capture the screen stop working.   

On same machine: GamePC

It appears like the NDI Source started with OBS doesn't capture the screen.

Start NDI TestPattern
Start NDI Studio Monitor => Select TestPattern => Works, displays test pattern
Start OBS => Select (NDI Source = TestPattern) => Works.

When I select ScreenCapture (name of  screen source) it displays a black screen in both applications.

Any thoughts?

**Comment by Palakis** [comment]
Duplicate of #62
