### ISSUE TITLE
Red dot in top left corner in obs

### ISSUE THREAD

**Issue by Hyllore** [Palakis/obs-ndi#31]
on my streaming pc i can see the source when i add an ndi source, but i only have one red dot in the left top corner with no image, i tried with video monnitor, seems to not work too ,don't know how to resolve this :/

**Comment by btaylor405080** [comment]
Turn off your windows firewall, it worked for me!

**Comment by Hyllore** [comment]
Oh yes it work ! There is a Way to choose thé quality ?

**Comment by Palakis** [comment]
@Hyllore By default it is set to the highest quality for the resolution and framerate configured in OBS' video settings. Anyway, NDI sources have a "Low Bandwidth mode" option disabled by default that can be enabled on a per-source basis, even though it's only useful in very specific cases (like previewing or for a live thumbnail in lower-third, for example).

**Comment by Palakis** [comment]
As said in #31:
> You can keep the windows firewall enabled (which is best) and add an exception for OBS into it.
