### ISSUE TITLE
Can't name Output

### ISSUE THREAD

**Issue by SammiRae422** [Palakis/obs-ndi#310]
When ever I got to my NDI Output setting, it won't show a box for me to input my Output Name. On my streaming computer, I installed exactly the same and everything shows up fine. I've deleted everything - OBS, NDI, etc. - and done a full reinstall of all of them, but it's still not appearing, so I'm unable to name the output and therefore can't connecting it to my streaming computer.
OBS (64-bit) 23.1
NDI download is listed as 4.6, but in the NDI Output settings it says "NDI DK WIN64 13.08.27 Apr 17 2019 3.8.1"

**Comment by Palakis** [comment]
@SammiRae422 Try resizing the NDI Output settings dialog vertically so that text fields can show up properly

**Comment by Klaumbaz** [comment]
Same problem. and expansion of the frame doesn't work.

**Comment by tieguaili3d** [comment]
also having the same problem, text fields never show up, multiple full reinstalls of both OBS and NDI, unable to scale the NDI output settings window vertically (no idea why, it just allows scaling horizontally rather than vertically)

**Comment by ELLIOTTCABLE** [comment]
I have this problem as well; I *can* resize it vertically, but only a tiiiiny amount:

![image](https://user-images.githubusercontent.com/200/74078876-75c6cf00-49f5-11ea-8bc9-63f939369c4c.png)
