### ISSUE TITLE
The Installation Failed

### ISSUE THREAD

**Issue by liquidvisual** [Palakis/obs-ndi#314]
I can't seem to install this. I'm running macOS Mojave 10.14.5 and the installation fails with:

**"The installation encountered an error that caused the installation to fail. Contact the software manufacturer for assistance."**

**Comment by francoestrubia** [comment]
Failed here too. Installed the runtimes, but same result. It just don't install.

**Comment by samsterckval** [comment]
I can't download the runtime it seems, could the server be down?

**Comment by SirBryan** [comment]
The installer (and link in the instructions) go to the domain new.tk to get the runtime.  In my case, it was being blocked by my piHole (ad-blocker): the DNS entry was resolving to 0.0.0.0.

I whitelisted the domain in the piHole's settings and it installed just fine.

In your case, you might have to change your DNS server (try 1.1.1.1) or put a manual entry for new.tk in /etc/hosts to get the install to complete:

```
64.150.181.205           new.tk
```

**Comment by Palakis** [comment]
Thanks @SirBryan !

I think I should stop having the installers (both Windows and macOS) download the runtime automatically. Better let users install it I guess.
