### ISSUE TITLE
NDI Source changes size

### ISSUE THREAD

**Issue by ASchmidt286** [Palakis/obs-ndi#315]
I have the issue that the NDI source jumps to another size when the resolution of the source changes. I know that it can be fixed be by transforming the source to bounding box style "inner boundings". 
But if you crop the source, so that it fits a frame on my layout the "jumping" of the sources reappears.

**Comment by ioooo0** [comment]
I got the same issue. How did you do please ? Cause not pluging related... 
Thanks !
