### ISSUE TITLE
Red dot in top left of screen/No video on output device

### ISSUE THREAD

**Issue by btaylor405080** [Palakis/obs-ndi#32]
So when I click add ndi source and find my pc and click okay, it shows up a red dot in the top left corner and a black screen.

**Comment by Helgaiden** [comment]
Couldn't you just have commented you also have this issue on the post with the user having the same exact issue?

**Comment by btaylor405080** [comment]
Sorry I was not paying attention, I have tried almost everything and have not gotten anything to work, I'm just looking for a solution.

**Comment by btaylor405080** [comment]
That worked thank you so much!!!

**Comment by Palakis** [comment]
@btaylor405080 This is a duplicate of #31. Next time, please read the issues list before opening one.

By the way, you can keep the windows firewall enabled (which is best) and add an exception for OBS into it.

**Comment by rpoblad** [comment]
In my case I found the folloiwng solution:  This is different from any other posting I found.

Change the parameter for this source property:  NDIPlugin.SourceProb.Behavior
   BAD:                    NDIPlugin.SourceProb.Behavior.KeepActive
   GOOD:               NDIPlugin.SourceProb.Behavior.StopResumeLastFrame
