### ISSUE TITLE
Special NDI installation @palakis 

### ISSUE THREAD

**Issue by AustinOlig** [Palakis/obs-ndi#327]
I was wondering if I could get this  “https://ci.appveyor.com/api/buildjobs/soac3t7rmcy40o9d/artifacts/obs-ndi-d956581.zip” specific obs-ndi version. My cpu doesn’t haven’t ssse3 but this may or may not have potentially solved it but the link is now dead. This version is over a year old and it was supplied by you. I’d really appreciate it if you could rehost it. 

Cpu: AMD Phenom ii x4 955

**Comment by DaDavinci** [comment]
I would love for someone to give a working link, since I cannot simply update my hardware
So please someone give us another link, someone shouldve downloaded it
