### ISSUE TITLE
Missing "NDI Source" option in the source drop down

### ISSUE THREAD

**Issue by iCassius** [Palakis/obs-ndi#331]
After update 4.6.1
NDI source is gone away, cant add it.
NDI Output settings is working.

Properties with previously NDI source display:
"No properties available"

NDI Source can be added when downgrade to 4.6.0

**Comment by Palakis** [comment]
@iCassius I got a similar report on the OBS Discord. Can you please provide an OBS log of when this happens?

**Comment by GEEKsogen** [comment]
Same problem on  4.6.2

**Comment by ncristianandrei** [comment]
i have the same issue

**Comment by ncristianandrei** [comment]
https://obsproject.com/logs/LFKLAcBd1k0OWYos
This is from my gaming pc

**Comment by whaaaley** [comment]
Here is my log file.
https://gist.github.com/whaaaley/66dadcfbfabd4e627c6fbc4982da5b83

However everything relating to obs-ndi seems to look good to me.

**Comment by whaaaley** [comment]
Upgrading to OBS 24.0.4 solves this issue.
