### ISSUE TITLE
Where do I find the NDI SDK files for Mac Installation?

### ISSUE THREAD

**Issue by xman51** [Palakis/obs-ndi#336]
This is the last step:

>` # Copy libndi.dylib from the NDI SDK to the obs-plugins folder too`

I downloaded both sdks from the Newtek website, but I am unable to find the file referenced in the OSX instructions.

Can someone provide more detailed instructions for this?

Thanks.

**Comment by Palakis** [comment]
@xman51 Grab the macOS NDI runtime here: https://slepin.fr/obs-ndi/runtime/ndi-runtime-4.0.0-macOS.pkg
