### ISSUE TITLE
Dedicated Audio Only Filter Not Being Recorded

### ISSUE THREAD

**Issue by moorecp** [Palakis/obs-ndi#337]
Source PC: Windows 10, OBS 23.2.1, NDI 4.6.2
Streaming Computer: OSX 10.14.6, OBS 23.2.1, NDI 4.6.1

On the Source PC:
I have Main Output with just Desktop Audio on audio track 1.
I have a Dedicated NDI output (Audio Only) filter applied to my Mic

On the Streaming Computer
I have an NDI Source with the Main Output from the Streaming PC
I have another NDI Source that is Audio Only connected to the Audio Only feed from the Streaming PC

If I enable Monitoring, I can hear everything as expected and all seems well. I don't keep monitoring enabled, I just toggled it on to ensure both sets of audio were coming through as expected.

For my recording, I have both audio tracks on track 1, the Main Output audio on track 2 and the Mic audio on track 3. In the resultant MKV recording, I only get the Main Output audio on track 1, track 2 is fine (since it is only supposed to be the Main Output audio) and track 3 is completely muted.

My audio only source isn't muted and seems perfectly fine until it comes to recording.

I tried simplifying things and removed all sources except for the audio only NDI Source and that also did not work. It remained silent in the resultant recording. You can see the meter moving as expected in the Meters section and monitoring lets you hear the audio; it's just not recorded.

**Comment by mark-ting** [comment]
Running into this issue as well. I noticed that there seem to exist lines after "Recording Stop" for

> [obs-ndi] audio thread for 'audio_only_audio_source_name' completed

for each such source the first time (it works), but not on subsequent runs where no audio is being recorded.

**Comment by Palakis** [comment]
@moorecp As far as the plugin is concerned, it works fine. Check your recording settings and your source monitoring settings, as the culprit is possibly lying in these places.
