### ISSUE TITLE
OBS NDI Plugin not installing on mac 

### ISSUE THREAD

**Issue by dlazaro7792** [Palakis/obs-ndi#339]
Hi,

I have a Macbook, running on MacOS mojave version 10.14.6. i downloaded the OBS link from the elgato downloads page but every time i try to download the NDI plugin (using the latest version for mac), I get an installation failed message. is there any way to fix this? let me know if you need more information.

**Comment by gregvital** [comment]
I am having the same problem. Its says installation was successful, but I cant find it anywhere, and my OBS is not recognizing it.

**Comment by liquidvisual** [comment]
Same issue, so annoying

**Comment by Pylawn** [comment]
Seem to be getting the same error as above. The Runtime can't be found no matter what I try. Anyone tried to see if there's an older release that does work?

**Comment by Palakis** [comment]
@dlazaro7792 @gregvital @liquidvisual @Pylawn Version 4.7.0 of the plugin is coming out soon and fixes this issue. Duplicate of #343
