### ISSUE TITLE
NDI plugin disabled

### ISSUE THREAD

**Issue by SOAPieJLaw** [Palakis/obs-ndi#34]
Hello,  whenever i select the plug in on my second pc the ndi source never comes up, i have everything set up but nothing comes up on my laptop﻿.  I researched through the obs help logs and found a message stating (plugin is disabled for performance reason on window versions prior to 8)   and my laptop is running on windows 7.   so is there a way to force it?

**Comment by Palakis** [comment]
Add a firewall exception for obs, or completely disable Windows' firewall.

**Comment by Palakis** [comment]
> I researched through the obs help logs and found a message stating (plugin is disabled for performance reason on window versions prior to 8)

That has nothing to do with obs-ndi.

**Comment by SOAPieJLaw** [comment]
i tried both and no go.    #facepalm    lol

**Comment by Palakis** [comment]
How did you installed obs-ndi? Installer or ZIP archive?

**Comment by SOAPieJLaw** [comment]
Installer

**Comment by Palakis** [comment]
> the ndi source never comes up

Do you mean:
- the NDI Source in the proposed sources list?
- or sources discovered on the network in the NDI Source properties in OBS?
