### ISSUE TITLE
Feature Request: Broadcast Delay

### ISSUE THREAD

**Issue by BlakeB415** [Palakis/obs-ndi#340]
I’m using NDI to send the feed to another computer and output to an HDMI, I’d like to be able to delay the video feed so in case someone curses, I can cut it before that airs. Maybe also add a keybind to stop the NDI output which removes the X seconds delay buffer?

**Comment by BlakeB415** [comment]
At least a delay option since OBS doesn’t handle that for this plugin.

**Comment by Palakis** [comment]
@BlakeB415 You can apply a delay filter on the receiving end (if it's OBS). A Dump feature is not something that belongs to the scope of this plugin.
