### ISSUE TITLE
No option for NDI output and for Add source

### ISSUE THREAD

**Issue by GEEKsogen** [Palakis/obs-ndi#341]
I have installed both OBS studio, NDI 4.6.2 multiple times, and when I go into tools there is no option for NDI output and for Add source. NDI 3.8+ Runtime is present. Maybe some Net Frawork or something else needed ?

**Comment by Helgaiden** [comment]
Any NDI related errors in the OBS log?

**Comment by GEEKsogen** [comment]
20:12:25.580: Failed to load 'ru-RU' text for module: 'obs-ndi.dll'
20:12:25.580: [obs-ndi] hello ! (version 4.6.0)
20:12:25.580: [obs-ndi] Trying 'C:\Program Files\NewTek\NewTek NDI 3.8 Runtime\v3'
20:12:25.594: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NewTek NDI 3.8 Runtime/v3/Processing.NDI.Lib.x64.dll'
20:12:25.796: [obs-ndi] NDI runtime loaded successfully
20:12:25.796: [obs-ndi] CPU unsupported by NDI library. Module won't load.
20:12:25.796: Failed to initialize module 'obs-ndi.dll'
20:12:27.049: Couldn't find VLC installation, VLC video source disabled
20:12:27.577: No blackmagic support

**Comment by GEEKsogen** [comment]
https://obsproject.com/logs/fDoSK8Qild3V3vkW

**Comment by Helgaiden** [comment]
You see that error that says module could not load: CPU unsupported? There's you're answer.

Phenoms do not carry the necessary instruction set for NDI to work. You need SSSE3 support (aka supplemental sse3). For AMD, this instruction set was integrated starting with the Bulldozer architecture. Check to see if your motherboard bios can be updated to support an FX series CPU, and if it does then swap in something like an FX-6300/6350 or better, then you will be able to run NDI.

**Comment by GEEKsogen** [comment]
So sorry to hear that. This information must be specified in the system requirements.
