### ISSUE TITLE
Plugin not working with the NDI 4.0 Runtime

### ISSUE THREAD

**Issue by TheSalon112** [Palakis/obs-ndi#342]
Hello

Ive installed new OBS, new version of your plugin, and runtime (from destcription).. It wasnt working, so i donwloaded full tools, but its showing same bullshit in log files:

23:06:38.685: [obs-ndi] hello ! (version 4.6.2)
23:06:38.685: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Tools\Runtime'
23:06:38.686: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Tools/Runtime/Processing.NDI.Lib.x64.dll'
23:06:40.517: [obs-ndi] Can't find the NDI library
23:06:43.016: Failed to initialize module 'obs-ndi.dll'

..........................................................................................................

Full log: https://obsproject.com/logs/Zq41i2r21WE7EXMt

What should i do ? Thanks in advance

Of course i restarted computer several times

CPU: I7 870 (Have SSE3)
GPU: 1050ti

**Comment by ddv2005** [comment]
I have the same problem after update to NDI 4.0

**Comment by uzinafreak** [comment]
I have the same problem after reinstalling OBS

**Comment by hexagonzo** [comment]
no Updates ????

**Comment by Palakis** [comment]
@TheSalon112 @ddv2005 @uzinafreak Fixed the plugin, gonna publish a new release in a few moments.

**Comment by Palakis** [comment]
Mind if one of you tries this? https://ci.appveyor.com/api/buildjobs/viy64p887d9y8sq0/artifacts/obs-ndi-b32911f-Windows-Installer.exe

**Comment by TisBeRemmy** [comment]
mine still says NDI Runtime not found

**Comment by shuddertrix** [comment]
> Mind if one of you tries this? https://ci.appveyor.com/api/buildjobs/viy64p887d9y8sq0/artifacts/obs-ndi-b32911f-Windows-Installer.exe

The installer works for me with NDI Runtime 4.0 and NDI Tools 4.0 installed on Windows 10. I also compiled b32911fe18a6144a146c8c2bc59469d91477bc4a on Arch Linux with NDI 4.0 runtime (modified ndi-sdk PKGBUILD to get version 4.0) installed and it also works there.

[2019-09-16 23-00-18.txt - Windows](https://github.com/Palakis/obs-ndi/files/3619070/2019-09-16.23-00-18.txt)
[2019-09-16 23-02-01.txt - Linux](https://github.com/Palakis/obs-ndi/files/3619069/2019-09-16.23-02-01.txt)

**Comment by Palakis** [comment]
Release 4.7.0 fixes this issue: https://github.com/Palakis/obs-ndi/releases/tag/4.7.0
