### ISSUE TITLE
NDI 4.7.0 update issue

### ISSUE THREAD

**Issue by Koodikalle** [Palakis/obs-ndi#347]
this new update is not working with obs, its dia show now. 

E: obs versio 24.0 RC 5

**Comment by saitoh183** [comment]
I also installed 4.7 and installed  24.0 RC 5 and installed Runtime v4 and rebooted but still no ndi in obs

**Comment by saitoh183** [comment]
Fixed my issue, After installing  obs 24.0 RC5 and runtime v4 , i removed obs-ndi because it was installed before i had installed the 2 others. after a reboot and installing again, then another reboot, it appeared in obs

**Comment by farthhhh** [comment]
> Fixed my issue, After installing obs 24.0 RC5 and runtime v4 , i removed obs-ndi because it was installed before i had installed the 2 others. after a reboot and installing again, then another reboot, it appeared in obs

worked for me, thx :P

**Comment by ZeroTwoNineInc** [comment]
> this new update is not working with obs, its dia show now.
> 
> E: obs versio 24.0 RC 5

Same here, the stream on my remote machine always hangs and continues after a while :(
