### ISSUE TITLE
NDI Runtime Not Found 

### ISSUE THREAD

**Issue by aarontreee** [Palakis/obs-ndi#348]
hey, i downloaded NDI on my Windows Laptop and it said NDI Runtime Not Found (download NDI Runtime 4) i downloaded it and it says the message again
i deleted ndi and the ndi plugin again and same issue
i deleted everything from OBS, NDI and reinstalled it. it said it again.
I tried obs 24 same issue.
i tried the root folder same issue.
i searched for answers and they were none.
in my Macbook Air it was working but on my Windows Laptop i tried everything.

help me i was trying it for 2 days.

**Comment by DrakeekarD** [comment]
In the windows machine, right click the installers, click on properties and makes sure they are not blocked. That was my issue.

**Comment by aarontreee** [comment]
woah thanks. it works now!
That was my problem hah
