### ISSUE TITLE
Ndi Runtime not found click here to download it

### ISSUE THREAD

**Issue by MrOPOblivious** [Palakis/obs-ndi#35]
I used the windows installer to install the ndi plugin and then saw that it said Ndi Runtime not found click here to download it so i clicked the link downloaded it installed it and now everytime i open obs it still says Ndi Runtime not found click here to download it.... can anyone help me with this?

**Comment by Palakis** [comment]
You need to reboot your computer to have the NDI runtime recognized after installing it. Have you done this?

**Comment by MrOPOblivious** [comment]
I did and it wasnt working but i started all over and my streaming pc worked so now trying it on my gaming  i ahd to do it more than once for whatever reason

**Comment by MrOPOblivious** [comment]
Didnt work on my gaming pc i uninstalled obs reinstalled it then re installed that NDi runtime restarted then put the data and the obs-plugins into the obs root folder(cause thats the way it worked on my streaming pc) and still not showing the plugin

**Comment by Palakis** [comment]
> then put the data and the obs-plugins into the obs root folder(cause thats the way it worked on my streaming pc)

Have you tried the obs-ndi installer on the gaming PC?
