### ISSUE TITLE
(MAC)I just cannot install obs-ndi plugin..

### ISSUE THREAD

**Issue by Watdafuk55** [Palakis/obs-ndi#353]
After installing OBS 23.2.1 for mac successfully,
My mac contiunuosly fails to install obs-ndi 4.7.0 pkg release..
Of course I did reboot my mac and it didn't work as well.
And I'm afraid that if it's main problem that I didn't install ndi 4.0+ runtime in advance,
but i cannot download ndi redistributable 4.0 from your link of Newtek domain either.
I think that link is broken, obviously any type of downloading contents link
from newtek domain is ALL BROKEN. Maybe it could be Newtek's server issue though.
Anyway, how can I deal with this situation? Need some help..

**Comment by Watdafuk55** [comment]
After Newtek links all restored, everthing works fine. Thanks to Newtek and Palakis. Everyone who faced trouble during obs-ndi installation like me, plz try to install ndi 4.0+ runtime first.

**Comment by pasayasin** [comment]
Unfortunately the issue persists. I tried to install the latest version and it keep to loop. It seems that the 4.0+ runtime doesn't download (even with the direct link)

**Comment by Palakis** [comment]
Grouping this into #403
