### ISSUE TITLE
Obs NDI 4.7.0 Audio Issues

### ISSUE THREAD

**Issue by issdar** [Palakis/obs-ndi#354]
It seems after updating obs studio and ndi plugin 4.7.0 and ndi runtime 4 I am having completely broken audio. In obs on one PC my audio meters look perfect. On the second PC I am getting fine video but the audio is coming in very broken with only .5sec of audio playing like once ever 5 seconds. Any ideas on the issue? I tried reinstall obs, obs plugin, and runtime from scratch on both PCs.

**Comment by thornza007** [comment]
me too

**Comment by issdar** [comment]
Could not find any info online about this but I fixed it! It seems in one obs client under the advanced settings "low latency mode" was checked and greyed out. I had to check enable new networking code and then uncheck low latency mode and enable new networking code. Threw me for a loop trying to figure this out.

**Comment by cheeyao** [comment]
I'm having the same issue as you and tried to follow your solution, it does not work for me. My streaming PC has no problem receiving video signals, but for audio signal, it is receiving .5 seconds of audio for every 3 seconds. I have tried using low latency mode and internal network mode in NDI's source properties. This is the log file for my streaming PC.

Log file for streaming PC - [https://pastebin.com/1w8LK6h7](url)

I tried applying a filter (Dedicated NDI output) for my desktop audio output, when I do that, in the log file it states that Max audio buffering reached and it does the same thing.

Log file for gaming PC - [https://pastebin.com/cN8QpkF6](url)

**Comment by LordReaver** [comment]
The developers don't seem to look into this anymore are they? Having the same issue, I have a workaround running with NDI Scan Converter. With that you can stream a single audio source ( two, with webcam audio ) and make things work again. But this has to be configured everytime you restart the computer so its not very convenient and it makes all my audio settings in obs obsolete.

**Comment by Palakis** [comment]
@LordReaver 
> The developers don't seem to look into this anymore are they?

I'm the sole maintainer of this plugin and wasn't available that much during these last months. I'd be happy to have some support volunteers in here. My Twitter DMs are open ;)

**Comment by xSooDx** [comment]
I'm having the same issue. Only like 0.1 sec of audio comes every 2-5 seconds on my streaming PC. The rest of the time its silence. Gaming PC works fine.

**Comment by xSooDx** [comment]
FYI: Downgrading to OBS 4.6.2 works for me.

**Comment by LordReaver** [comment]
Yep same for me

**Comment by avestruz76** [comment]
Same problem here. Tried to downgrade to older versions and still nothing.
