### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by VentiVB** [Palakis/obs-ndi#356]
Download failed: The server name or address cannot be resolved..

**Comment by websitecareio** [comment]
Same here when downloading the runtime+ . But i friend in the US can download it fine.

**Comment by Palakis** [comment]
You can grab the runtime installer here: https://slepin.fr/obs-ndi/runtime/

**Comment by Jaifroid** [comment]
@Palakis  I'm getting this issue in the 4.9.0 Windows installer. I'm in the UK if that helps.
