### ISSUE TITLE
NDI Plugin still throttle internet connection speed?

### ISSUE THREAD

**Issue by Discostoff** [Palakis/obs-ndi#361]
Hi,
in the past the plugin was throttling my internet connection and i have seen a lot of other user encountering the same issue. I deinstalled the plugin and never used it again.
Now i consider using it again, so i wanna know if the issue is solved?

**Comment by Palakis** [comment]
@Discostoff Last I check it doesn't. It was something NewTek deployed in previous versions for big networks but seems to have become useless in recent versions.
