### ISSUE TITLE
Not using shipped ObsPluginHelpers.cmake

### ISSUE THREAD

**Issue by Freso** [Palakis/obs-ndi#363]
`ObsPluginHelpers.cmake` is being looked for in `${LIBOBS_INCLUDE_DIR}/../cmake/external/ObsPluginHelpers.cmake`. On Arch Linux at least, `${LIBOBS_INCLUDE_DIR}` should be `/usr/lib/cmake/LibObs` AFAICT, so the make scripts are trying to find the `.cmake` file at `/usr/lib/cmake/cmake/external/ObsPluginHelpers.cmake`… Where it obviously doesn’t exist.

It seems like `ObsPluginHelpers.cmake` is shipped in the `external` directory in the root of the repository. Is there a reason for not simply pointing the make scripts to this file?

**Comment by paulpv** [comment]
This should be fixed in the new https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC.
It uses obs-plugintemplate's ObsPluginHelpers.cmake, which is official enough.
