### ISSUE TITLE
Audio in VU meters but it does not record

### ISSUE THREAD

**Issue by MiloMindbender** [Palakis/obs-ndi#364]
Ok...I have windows 10, obs 24.0.3, ndi plugin 4.7 and the latest NDI HX camera app from newtech on my iphone x.

I am getting good video and the audio from the phone shows up in the audio mixer on the VU meters but when I record I get no audio on the recording.  I think I've checked everything, the advanced settings for the audio has all the track boxes ticked and in the main settings it is set to record track one.  Everything else is pretty much set to defaults.

If I go into advanced settings on the audio mixer and turn on monitoring, I hear audio from the phone.

The only way I have been able to get the audio from the phone to record is by turning on monitoring in advanced settings, then the audio from the phone appears in the "desktop audio" track and does get recorded.

On a couple of occasions (it is not repeatable) I have heard brief snips of audio in the recording, these seem to be way ahead of the video....one time for example I started the recording, said Testing 1 2 3 and clapped my hands several times.  When I played back the recording at the very beginning I heard "three" and that was all.

Audio from my desktop microphone also records normally.

Any idea what's going on?

**Comment by Palakis** [comment]
@MiloMindbender This is not an issue with the NDI plugin. Check your recording settings to see if your recordings get the correct audio tracks.
