### ISSUE TITLE
OBS-NDI stream freeze

### ISSUE THREAD

**Issue by Truf** [Palakis/obs-ndi#366]
Been having a fairly new issue. Using OBS NDI the NDI stream will freeze on the receiving end. If I try to interact with the source on the receiving end it will freeze OBS. I can add the same source and it works again, but I can't delete the old one. If I do this more than 2 times it lags like crazy (probably because the bandwidth of 3 4k streams.. OBS only crashes once I try to interact with the NDI source that has a frozen video feed. The audio from the feeds is fine. This happens at any resolution/framerate I've tried many.

On the sending end, on my gaming PC OBS is functioning perfectly. I don't even have to be streaming or recording for this video feed freeze to occur.

I am on The latest release of both obs/ndi as well as windows. NDI is the only thing I have set up to OBS besides being signed into mixer account for streamkey.
[Crash 2019-11-08 14-09-54.txt](https://github.com/Palakis/obs-ndi/files/3825911/Crash.2019-11-08.14-09-54.txt)

I recently fully updated my bios to the most recent. Now instead of the previous issues it just CTD with no log. I have no OC

**Comment by Nekoi** [comment]
I thought I'd update https://obsproject.com/forum/threads/libglesv2-dll-crash.112393/ Some discussion here but ultimately still having the issue. That is 100% related to NDI in some way.

**Comment by Nekoi** [comment]
I think it has to do with 4k. As setting both sending and receiving computer to 1080p stopped crashing.

**Comment by LexusSpeed03** [comment]
I am having this issue all the time and did not previously. Receiving end keeps freezing I have to stop the NDI output from game PC and fixes it.
