### ISSUE TITLE
Multichannel Audio Issues

### ISSUE THREAD

**Issue by reustaquiojr** [Palakis/obs-ndi#369]
It would be possible to choose which audio channels should be used for a source of NDI signal ?

I had some issues in multichannel audio sources.... Sometimes some channel groups come up with white noise and/or audio description and all they get routed to the the main (just stereo) encoder stream...

Is there any workaround ?

**Comment by Palakis** [comment]
@reustaquiojr You can use the rematrix filter plugin: https://obsproject.com/forum/resources/rematrix-filter-plugin.620/
