### ISSUE TITLE
Maximum quality and few questions

### ISSUE THREAD

**Issue by morskoyzmey** [Palakis/obs-ndi#370]
Is there any chance that it is possible to maximize translation quality (more than it is now)?
And how it is happen that I can setup options like YUV Range/Color Space/Bandwidth in a NDI Source options (on a client machine)?

**Comment by Palakis** [comment]
@morskoyzmey 
> how it is happen that I can setup options like YUV Range/Color Space/Bandwidth in a NDI Source options (on a client machine)?

Because Bandwidth in NDI is a client-side setting, and being able to adjust YUV range and color space is also something possible in Video Capture sources.
