### ISSUE TITLE
Cant name ndi output

### ISSUE THREAD

**Issue by imsoapie** [Palakis/obs-ndi#373]
i installed ndi on my gaming computer and when i go to the ndi output settings under tools, there isnt a box for me to name my output settings. i resized the window to the biggest it can be and i still dont get the box.

**Comment by tieguaili3d** [comment]
i have the same problem, would like to see it fixed so i can stream from my tablet

**Comment by ELLIOTTCABLE** [comment]
Same; maybe a new-ish bug? I see only this:

<img width="236" alt="ndi_cant_name" src="https://user-images.githubusercontent.com/200/74078852-0ea91a80-49f5-11ea-9799-720912fc9c2c.png">
