### ISSUE TITLE
obs_source_set_async_unbuffered(s->source, true);** to false (Where to find)?

### ISSUE THREAD

**Issue by Viskositaet** [Palakis/obs-ndi#376]
Hi mate, no problem, I don't mind if you fix it right away, that'll be fine - it's more or less just changing **obs_source_set_async_unbuffered(s->source, true);** to false. I'm not sure if you would want to enable that to be toggled or if having it set to true will be bad in all cases, but with my own personal experience it was definitely stuttering often with it set to true.

_Originally posted by @loopy750 in https://github.com/Palakis/obs-ndi/issues/234#issuecomment-470990246_

**Comment by Viskositaet** [comment]
Can some one eplain me how to change it or where to find this code?
obs_source_set_async_unbuffered(s->source, true);

**Comment by Palakis** [comment]
@Viskositaet It's been fixed already
