### ISSUE TITLE
error installing (runtime download error)

### ISSUE THREAD

**Issue by rohansubedi** [Palakis/obs-ndi#378]
installer: installer cant download the files and shows error... says check your connection(connection is fine)
zip: zip has runtime missing... download link takes to a page that says file transfer blocked

**Comment by XaviFabregas** [comment]
same issie for me with 4,.7.1 and 4.6.3 windows installer,... did you solve this problem?
Thx

**Comment by Palakis** [comment]
Grouping this into #403
