### ISSUE TITLE
URL new.tk/NDIRedistV4Apple doesn't work properly

### ISSUE THREAD

**Issue by trusty82** [Palakis/obs-ndi#380]
Hi,

I have tried to install OBS NDI Plugin but I have an error (installation failed) 
<img width="732" alt="Capture d’écran 2019-12-21 à 11 02 34" src="https://user-images.githubusercontent.com/16706385/71306507-65c14480-23e1-11ea-88cc-d28ebe20a230.png">

On your script post install you download ndiruntime.pkg to http://new.tk/NDIRedistV4Apple

But this URL http://new.tk/NDIRedistV4Apple doesn't work 

<img width="414" alt="Capture d’écran 2019-12-21 à 11 04 19" src="https://user-images.githubusercontent.com/16706385/71306530-ba64bf80-23e1-11ea-9410-ade280f6da2d.png">

<img width="607" alt="Capture d’écran 2019-12-21 à 11 05 59" src="https://user-images.githubusercontent.com/16706385/71306539-ea13c780-23e1-11ea-9173-65eda5860f89.png">

Can you try to include ndiruntime directly into obs-ndi installer?

Kind regards

**Comment by trusty82** [comment]
Same problem on Windows....

**Comment by whaaaley** [comment]
The site seems to be down atm. I've been looking around the internet to see if I could find the runtime hosted somewhere else to see if I could solve another problem I'm having.

**Comment by ermax** [comment]
Sam problem.... my Elgato don’t working with obs. help me please .

**Comment by PatTheMav** [comment]
Unfortunately this seems to happen from time to time - the redirect host becomes unresponsive, only to resume work a few hours/days later.

FWIW I just checked and all NDI short links seem to work for the moment.

**Comment by Palakis** [comment]
Grouping this into #403
