### ISSUE TITLE
URL http://new.tk/NDIRedistV4 is down or has been moved

### ISSUE THREAD

**Issue by liplop95** [Palakis/obs-ndi#383]
Unable to install NDI as the 4.0 Runtime cannot be found

Error This site can't be reach

**Comment by liplop95** [comment]
15days and still no update :(

**Comment by Palakis** [comment]
I've put up my own mirror of the NDI runtime downloads if you still can't download the runtime: https://slepin.fr/obs-ndi/runtime/

Future releases will use this mirror instead of NewTek's.

**Comment by Palakis** [comment]
Grouping this into #403
