### ISSUE TITLE
“obs-ndi-4.7.1-macOS (7).pkg” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by LukeGillespie** [Palakis/obs-ndi#385]
<img width="418" alt="Screenshot 2020-01-04 at 18 52 22" src="https://user-images.githubusercontent.com/55156330/71770337-5d115800-2f23-11ea-92af-db90ce67f490.png">

I have tried to download the lates OBS Ndi, but it will not download and has said the software needs to be updated and to contact the developer.

Please could you help me with this issue so i can start streaming again.

**Comment by dshvydka** [comment]
I have the same

**Comment by tangential56** [comment]
I have this problem as well

**Comment by dodgepong** [comment]
If you right-click on it (or two-finger click) and click "Open" there should be an option to open it anyway.

**Comment by djcello13** [comment]
did anyone figure this out?? having the same issue 

<img width="447" alt="Screen Shot 2020-03-25 at 12 06 40 PM" src="https://user-images.githubusercontent.com/62661741/77559259-57783e00-6e92-11ea-8a32-896dbc8e9508.png">

**Comment by Palakis** [comment]
Fixed by #434
