### ISSUE TITLE
Automated NDI runtime install fails on macOS Catalina

### ISSUE THREAD

**Issue by johnathanortiz173** [Palakis/obs-ndi#388]
Hi im having an issue where I download the NDI plugin on Mac and I install it as well but the NDI Source doesn't show up on OBS??

**Comment by SquishySlipper91** [comment]
I am also having this issue. I've tried restarting and reinstalling everything. I'm using OBS 24.0.6. It's almost like OBS won't recognize the plugin... Very frustrating.

**Comment by SquishySlipper91** [comment]
I figured it out! You need to download both the plugin AND the runtime from here https://github.com/Palakis/obs-ndi/releases
When you try to open the plugin MacOS won't allow it, but you can go into security preferences and force it to open.

**Comment by johnathanortiz173** [comment]
Where is the runtime lol

**Comment by johnathanortiz173** [comment]
Scratch that where would you find the download is security preferences

**Comment by SquishySlipper91** [comment]
System Preferences > Security & Privacy > General
The last file that failed to open should be listed there, and you can hit "Open Anyway"

**Comment by johnathanortiz173** [comment]
Ah man for some reason I can’t see my last file rip😭

**Comment by SquishySlipper91** [comment]
Try to open it first, it won't let you, then look again?

**Comment by Palakis** [comment]
Thanks @SquishySlipper91. I think Catalina broke the embedded NDI runtime installer. Gonna fix the installation instructions accordingly.

**Comment by hannahgrace1234** [comment]
@Palakis I am having a lot of troubling trying to download the plugin to mac... I have tried on my macbook (mojave) and my imac (catalina) and neither are working. The installer will run and then nothing happens and I can't find the file anywhere to drag into the plugins folder myself. Can someone please help me work out what is going wrong? I really need the plug in to be able to link skype during my livestream.

**Comment by Palakis** [comment]
@hannahgrace1234 obs-plugins are in `\Library\Application Support\obs-studio\`

**Comment by tabarnhart** [comment]
i have run the installer (obs-ndi-4.9.0-macOS.pkg) and the ndi runtime installer (ndi-runtime-4.5.1-macOS.pkg) multiple times. get told the install was fine. open OBS, and i'm told i need to install NDI.

in Libary/App Support/obs-studio/plugins i find obs-ndi with bin & data.

i have the latest catalina, latest obs. this is frustrating as i want to use obs for recording skype calls & i can't even hear the incoming. thanks.
