### ISSUE TITLE
Don't working in windows 10

### ISSUE THREAD

**Issue by s0ilbr** [Palakis/obs-ndi#39]
I have two computers, one have win 7 and the other have win 10, i can't send image of my computer with win 10 to the win 7 but I can do the same thing with windows 7 for windows 10 that works, any suggestion of what to do?

**Comment by Palakis** [comment]
Add a firewall exception for OBS on both computers and make sure they are on the same network.

**Comment by s0ilbr** [comment]
The two computers are on the same network, they are connect right in the modem and my firewall in the both pc's are disable

**Comment by Palakis** [comment]
Have you tried disabling your AV?

**Comment by Palakis** [comment]
Also, Windows 7 is quite old and is reaching end of life. You should at least use Windows 8.1.

**Comment by Palakis** [comment]
@s0ilbr Closing this, as I still get no response from your end. Feel free to comment here if you still encounter this issues, and we'll consider reopening this again.
