### ISSUE TITLE
NDI causing some dort of driver issue?

### ISSUE THREAD

**Issue by Xylarthen** [Palakis/obs-ndi#391]
It is entirely possible that this is correlation and not causation, but is it possible that NDI could somehow create some type of driver conflict? I've been having tons of issues over the past several days since downloading NDI. Boot failures, wifi not working. I got one BSOD with a driver power state error. Went so far as to replace my hard drive and network card. Every time that the issues reappear, it's immediately after downloading and installing NDI. Delete NDI, and the issues are gone like a charm.

Thoughts?

**Comment by Palakis** [comment]
@Xylarthen I don't think so. NDI doesn't deal with driver stuff on Windows.
