### ISSUE TITLE
Plugin not working on Mac...

### ISSUE THREAD

**Issue by hannahgrace1234** [Palakis/obs-ndi#399]
Hi, I have been trying to download for mac and am having a lot of trouble. I have tried multiple times on both my macbook (mojave) and my imac (catalina) and neither are working. The installer will run and then nothing happens and I can't find the file anywhere to drag into the plugins folder myself. Can someone please help me work out what is going wrong? I really need the plugin to be able to link skype during my livestream.

**Comment by celbasi** [comment]
same for me on catalina

**Comment by makeitTim** [comment]
Mojave. Cannot even install.

**Comment by gleasonmagic79** [comment]
I'm having the same problem...Catalina 10.15.3

**Comment by Auto-moto-kyoto** [comment]
I have the same issue exactly, i'm also on 10.15.3 and plug in 4.7.1 - I get the same warning.

**Comment by Palakis** [comment]
Duplicate of #385
