### ISSUE TITLE
Image tearing on frames from NDI Dedicated Output

### ISSUE THREAD

**Issue by gamespeaker** [Palakis/obs-ndi#41]
Hello, thank you first of all for coming out with 4.1 so quickly.  I just tested it and I noticed that the ndi source seems to be tearing.  Kind of like interlacing.

Update....Does not do it if I use low bandwidth option selected.

**Comment by Palakis** [comment]
What software/hardware is your NDI source? I've done some testing with VLC as the NDI source playing a tearing test video and can't reproduce. Maybe check your monitor and your GPU settings.

**Comment by gamespeaker** [comment]
Sorry latest OBS studio On Windows 10, Using Logitech c910 webcam.

**Comment by Palakis** [comment]
Maybe you mean the NDI filter a.k.a Dedicated NDI output? Because I can notice heavy tearing there.

**Comment by gamespeaker** [comment]
Yes.   Am I doing it wrong ?

**Comment by Palakis** [comment]
Not from what I can see. I can reproduce this issue on my end.

**Comment by gamespeaker** [comment]
Hopefully easy fix.  Thank you again for looking at this.

**Comment by gamespeaker** [comment]
Are there any updates to this issue yet?  Thank you

**Comment by Palakis** [comment]
There's work underway on this but I have no idea why this happens.

**Comment by gamespeaker** [comment]
Hello, I just installed 4.1.1 and same issues with image tearing for NDI Dedicated Output?
Is there a way to uninstall the plugin and re install?

**Comment by Palakis** [comment]
> Is there a way to uninstall the plugin and re install?

Yes, standard uninstall procedure on Windows.

**Comment by gamespeaker** [comment]
Hi
This plugin  has no uninstaller.  
Can we just delete the .dll?

**Comment by Palakis** [comment]
Yup.

**Comment by gamespeaker** [comment]
Ok, I just did that and reinstalled 4.1.1 tearing is still an issue.

**Comment by Palakis** [comment]
> Ok, I just did that and reinstalled 4.1.1 tearing is still an issue.

I haven't said the opposite. I'm still working on fixing this.

**Comment by gamespeaker** [comment]
Ah ok 😊. Love the plugin though.

**Comment by Palakis** [comment]
Fixed in the latest commit to date.
