### ISSUE TITLE
NDI audio only plays in monitor, not audible in recording

### ISSUE THREAD

**Issue by parkerknabb** [Palakis/obs-ndi#411]
Audio coming in from NDI sources will appear in mixer and play over monitor, but will not be audible in a recording. It appears this is a bug with the latest version of OBS (25.0.1). I installed 24.0.3 and audio is fine. Also works in 25.0-rc6.

**Comment by parkerknabb** [comment]
Huh. I installed 24.0.3, then 25.0-rc6, then reinstalled 25.0.1 and it works now. Please disregard.

**Comment by Palakis** [comment]
@parkerknabb Check your audio monitoring setting for your NDI source. It's in the Advanced Audio Settings dialog (in the Mixer panel, click the cogwheel next to a source, then click on Advanced Audio Settings in the context menu that appears).

**Comment by parkerknabb** [comment]
This is actually still a problem. I have two NDI sources, both set to Monitor and Output. I can hear them in headphones but not in recording when I mute desktop audio.

**Comment by parkerknabb** [comment]
It appears that the problem is being caused by a particular NDI input I am using, an iPhone running the official NDI HX Camera app. Everything works fine on OBS 24.0.3 without that source being used.

**Comment by ryanjpodonnell** [comment]
@parkerknabb and @Palakis  hello! So I cannot figure out how to get sound during a recording with OBS 25.0.4 on windows using the NDI HX Camera app on an Iphone. I also could not get this working with OBS 24.0.4. I can see the sound waves in the monitor, but when viewing the video. There is no audio. If I add another microphone to the scene, the audio is super choppy and unusable...

I recently got a Windows 10 laptop and have had no luck with the NDI source. The video looks great tho. This was working fine on my mac. Any ideas?
