### ISSUE TITLE
Download error with windows.exe

### ISSUE THREAD

**Issue by astreet24601** [Palakis/obs-ndi#414]
I'm getting a download error when I try and download the windows.exe.  Is it just my PC or is anyone else seeing it?  If so, is there an alternative download somewhere?

**Comment by Palakis** [comment]
@astreet24601 This is a known issue. obs-ndi 4.8.0 will use my own mirror for downloads, as NewTek's tend to fail. In the meantime, in the Windows installer you can untick the "Install NDI Runtime" option and install the NDI runtime manually.

You can download the NDI 4 runtime either [here (NewTek's download link)](http://new.tk/NDIRedistV4) or [here (my own mirror)](https://slepin.fr/obs-ndi/runtime/ndi-runtime-4.0.0-Windows.exe)
