### ISSUE TITLE
Reporting Potential Bug

### ISSUE THREAD

**Issue by mplsmateo** [Palakis/obs-ndi#418]
I spent hours troubleshooting the NDI system as a whole. I recently purchased an elgato HD60s, so I needed the OBS Link, which uses NDI. According to the people who I've reached out to, there is an issue inside the NDI library. All I want is to be able to use OBS and my elgato to stream. Please help. I have attached the crash report.
[obs_2020-04-03-175601_Mateos-MacBook-Pro.crash.zip](https://github.com/Palakis/obs-ndi/files/4430528/obs_2020-04-03-175601_Mateos-MacBook-Pro.crash.zip)

**Comment by Palakis** [comment]
@mplsmateo This is a known issue. The obs-ndi plugin needs to be rebuilt to support NDI 4.5. The installer downloads and installs it automatically and I have no control over that. A fix will be released later this week.
