### ISSUE TITLE
Video image from NDI source on receiving PC is brighter/more saturated

### ISSUE THREAD

**Issue by AHSMB** [Palakis/obs-ndi#42]
Not sure if I'm the only one having this issue, but I seem to be seeing some weird differences in the video colors from the sending PC, which is currently using an Elgato PCI-E capture card to capture console game footage, and the receiving PCI using the NDI source plug-in.

Both computers are using the same i7-5820K Intel CPU, and the two screenshots below were recorded using the exact same settings on both PCs (x264, CRF=10, preset=fast, profile=high, flv). Video settings for color space were set to 709/full wherever possible, including the Elgato capture source profile.

http://screenshotcomparison.com/comparison/115267

I thought adding some filters would help, but that seems more like a bandaid solution than anything else.

Version of obs-ndi is 4.1, though I had the same issues with 4.0.1 as well.

**Comment by gamespeaker** [comment]
Make sure you put the version of NDI you are using.

**Comment by AHSMB** [comment]
A better comparison after fixing the video rendering on my player to match VLC output.

http://screenshotcomparison.com/comparison/115459

So the image on the receiving PC is just slightly more saturated/brighter.

**Comment by z0bz** [comment]
Having the same problem - much higher contrast on stream than I'm seeing in game and the colors are just way off. Dark colors are especially bad. This is on version 4.1.1.

I know photographing a monitor can be misleading, but these images are very accurate of what I see in game (left) vs. what my stream is pushing out (right): http://imgur.com/a/DAWXw (I promise viewing angles aren't causing the differences here)

I don't have this problem when I stream from a single PC, without NDI.

I'm also just not seeing the sharpness/clarity that I should be getting for my encoder settings:

x264, 1080p (no downscale), 60fps, 6000kbps, veryfast

My encoding PC can handle the load no problem (overclocked 2600K at 20-30% load), so the quality seems to be lost somewhere in the NDI shuffle.

**Comment by Helgaiden** [comment]
@z0bz 
6000fps isn't really enough bitrate for 1080p60. You would see a MASSIVE jump in visual quality and clarity if you downscalred to 1280x720, but still with 60fps, and set the CPU preset to Medium. 

Otherwise flip it down to 30fps if you want to stick to 1080p and you'll double your visual quality. Have you tried upping your CPU preset and testing? Each better (slower) setting makes a pretty big difference. via NDI, that streaming PC would only be dedicated to encoding/streaming...you should be able to least hit "faster" with your current settings i imagine.

**Comment by z0bz** [comment]
@Helgaiden 
Trust me, I've tried every combination of resolutions/downscales, framerates, presets, etc. that I can. It's as if NDI isn't sending enough data from my gaming PC to the encoding PC.

Both PCs are wired into a gigabit router with little additional traffic. I don't see any QoS settings active that might be limiting this traffic. Both PCs sending/receiving 120-180Mbps, perfectly in sync so I doubt any data is being lost in transit.

It sorta looks like a recording of a recording, like it's being double compressed. I've tried cranking the OBS settings on the gaming PC to absurdly high bitrates and Veryslow presets to see if maybe that had an effect on compressing the signal before it was received by the encoding PC, but that did nothing.

**Comment by Helgaiden** [comment]
@z0bz I can't particularly speak to the issue you're having short of suggesting a full uninstall, Ccleaner run, CCleaner registry cleaner run, reboot, reinstall everything, reboot, and making sure OBS is allowed thru the firewall on both PCs...
but everything i said in my last post still applies, even if NDI was working correctly.

**Comment by Palakis** [comment]
Looks like a YUV Color Range/Space issue. What's the result with 709 Color Space and Full Color Range? (under Settings > Advanced > Video)

**Comment by Palakis** [comment]
> What's the result with 709 Color Space and Full Color Range? 

Actually, try with Partial Color Range, but still in 709. Can't remember what's the default setting in OBS.

**Comment by AHSMB** [comment]
I'll give those a try when I get home, though I remember trying all the options and they didn't seem to change the issue. Will confirm.

**Comment by Farmagud** [comment]
Whites/greys seem to have a yellow tint to them while using any YUV color space setting and combinations. Weirdly enough, I actually have the same issue using NVENC encoding on a single PC setup. Maybe it’s an NVIDIA issue?

**Comment by Palakis** [comment]
@AHSMB 
> Video settings for color space were set to 709/full wherever possible
BT.709 colors are the right choice if you've streaming in HD, however Full Color Range may be the reason why the NDI source looks brighter. Try with 709/partial on both computers.

**Comment by Palakis** [comment]
Bit of quick explanation:
- Partial YUV color range: black pixels aren't exactly black, white pixels aren't exactly white
- Full YUV color range: black pixels are black, white pixels are white

**Comment by AHSMB** [comment]
What about the Elgato PCI-E capture card? I think there was an extended/standard color option as well as more color space settings in the OBS configuration for that. Same thing?

**Comment by AHSMB** [comment]
Here's another comparison. Advanced video is set to Direct3D 11, NV12, 709, Partial. Elgato capture card is set to 709 Partial.

http://screenshotcomparison.com/comparison/116321

The saturation in the hair should be pretty obvious here.

**Comment by Palakis** [comment]
@AHSMB YUV color range options for NDI receivers were introduced in release 4.3.0
