### ISSUE TITLE
NDI Source not showing up 

### ISSUE THREAD

**Issue by detrophy** [Palakis/obs-ndi#421]
System info:
Ryzen 2700x
Radeon VII
32B RAM
Win10 Pro (latest stable)

I've installed OBS 23.1 (64bit) and OBS-NDI 4.7.1 with Runtime v4, normal paths.
Link to the last log of OBS: https://pastebin.com/Q8Y2kKGB
I'm trying to get the NDI stream of my iPhone NDI HX app into OBS, but under "Sources -> Add" NDI is not available. Not even greyed out. iPhone is on the same network and sub-network as the PC.

Do I miss something?

**Comment by Palakis** [comment]
@detrophy obs-ndi 4.7.1 requires OBS v24 (or higher)

```
21:20:42.101: obs_register_source: Tried to register obs_source_info with size 288 which is more than libobs currently supports (280)
21:20:42.101: obs_register_source: Tried to register obs_source_info with size 288 which is more than libobs currently supports (280)
21:20:42.101: obs_register_source: Tried to register obs_source_info with size 288 which is more than libobs currently supports (280)
21:20:42.101: obs_register_source: Tried to register obs_source_info with size 288 which is more than libobs currently supports (280)
```

The download page was wrong about the minimum OBS version required. Fixed it.
