### ISSUE TITLE
NDI Download and Install ..now OBS wont open

### ISSUE THREAD

**Issue by luffkid123** [Palakis/obs-ndi#422]
I downloaded the Mac Os and when finished download the OBS app "unexpectedly quit" .  I've uninstalled OBS 3 times and still says same thing.   I can't find where the plug in was saved on my hard drive.  I want to get it off my computer and go back to how I had it 20 min ago.  Any help much appreciated.

**Comment by asstronot** [comment]
go to 
"macintosh hd"
go to library
then to application support
in application support u may see a folder for obs or obs-ndi
once I deleted the folder my obs was working again

**Comment by Palakis** [comment]
@luffkid123 Try the macOS build provided here (the macos_build download): https://dev.azure.com/Palakis/obs-ndi/_build/results?buildId=1068&view=artifacts&type=publishedArtifacts

**Comment by koraysels** [comment]
yeah same here.. on a mac it stops OBS from working.. looking to uininstall too..
