### ISSUE TITLE
OS X Catalina NDI Source not showing

### ISSUE THREAD

**Issue by crypiehef** [Palakis/obs-ndi#425]
I have successfully installed the NDI plugin by following the rules to bypass the infamous Apple security settings. However, Add NDI source is not showing up in OBS.

OS X Catalina 10.15.4

OBS: Version 24.0.6
NDI: Version 4.7.1

On My Windows 10 box: OBS shows the NDI Source in the menu fine.

**Comment by Palakis** [comment]
@crypiehef There is a bunch of macOS issues that will be fixed in a release later this week.

**Comment by crypiehef** [comment]
You all rock! Thanks for all you do!
