### ISSUE TITLE
Output Height broken?

### ISSUE THREAD

**Issue by AxyxDeveloper** [Palakis/obs-ndi#431]
https://github.com/Palakis/obs-ndi/issues/373

I have the same as here :(

**Comment by Palakis** [comment]
@AxyxDeveloper This is fixed and will be released in obs-ndi 4.8.0

**Comment by Palakis** [comment]
Duplicate of #373

**Comment by AxyxDeveloper** [comment]
it isnt fixed for me

**Comment by AxyxDeveloper** [comment]
it worked on my second device but not on my main

**Comment by dodgepong** [comment]
obs-ndi 4.8.0 isn't released yet. Wait for the release and update when it is available, then it will be fixed.

**Comment by AxyxDeveloper** [comment]
i fixed it with reinstalling but i still get blackscreen and my firewall is set
