### ISSUE TITLE
OBS 24.0.3 doesn't launch after installing obs-ndi 4.8.0

### ISSUE THREAD

**Issue by luigidasonic** [Palakis/obs-ndi#437]
After installing obs-ndi 4.8.0 and OBS version 24.0.3, OBS doesn't open for some reason.

Looked at OBS logs and found this:
14:13:00.803: [obs-ndi] hello ! (version 4.8.0)
14:13:00.803: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
14:13:00.804: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
14:13:00.806: [obs-ndi] NDI runtime loaded successfully
14:13:00.808: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
14:13:00.812: obs_register_source: Tried to register obs_source_info with size 384 which is more than libobs currently supports (288)

**Comment by carlosarandadj** [comment]
Tengo exactamente el mismo problema,alguna opcion de solucion?

**Comment by Danjuanlab** [comment]
4.8 into support V25 and above

**Comment by carlosarandadj** [comment]
Es correcto en Mac Os solo llega hasta la version 24.03

**Comment by Palakis** [comment]
@luigidasonic As @Danjuanlab said, obs-ndi on Windows & Linux only works with OBS v25 and above.
![image](https://user-images.githubusercontent.com/1812130/79232224-8406f080-7e67-11ea-8831-cde0fdb20a17.png)
