### ISSUE TITLE
CPU usupported by NDI library. Module won't load.

### ISSUE THREAD

**Issue by Qranequinn** [Palakis/obs-ndi#44]
This is it pretty much. Got it in log file, was looking at it out of desperation.
AMD Athlon II X2 215. The bug or have I gotten just a shitty hardware?

**Comment by Palakis** [comment]
Duplicate of #33. Please contribute to the discussion there.

**Comment by Palakis** [comment]
Also, please try the binary provided as a comment in #33 to see if the plugin loads properly. And report success or failure in that thread, not here.
