### ISSUE TITLE
NDI Sources are blank with Skype from the Windows Store

### ISSUE THREAD

**Issue by fuzzzerd** [Palakis/obs-ndi#442]
The sources show up, and even enumerate participates on a live call; however, the video and audio feeds are blank/empty while using Skype from the Windows Store. 

Switching to the direct download from the Skype website and things work as expected.

**Comment by richross** [comment]
Check your version of Skype.  Version 8.56 was giving me the same issue even though the NDI capability is included in the settings.  
There is a different version you can find be looking for Skype for Content Creators.  This is version 8.59.  It is also a larger app (200 MB v 45MB).  I've been using this in my live streams and it works well.  
https://www.skype.com/en/content-creators/

**Comment by fuzzzerd** [comment]
@richross thanks for the feedback! I just checked and sure enough the Windows Store version (not working, despite NDI showing up as an option) is v8.56.0.102 and the version (that does work as expected) from the website is v8.59.0.77.

Interestingly, the version from the Windows Store also includes a second 'Application' version: 
![image](https://user-images.githubusercontent.com/711755/80177048-1d4caa00-85c0-11ea-89e1-7ee4d21d1fd5.png)

I'll continue to monitor the store version and see if it get sup to v8.59 and if it begins working.
