### ISSUE TITLE
Audio delay + heavy FPS drops

### ISSUE THREAD

**Issue by nzfade** [Palakis/obs-ndi#46]
Been using this for a couple days, been loving the functionality of it so far.

Main PC: i5 6500, MSI GTX1070, 16GB RAM, 256GB SSD
Stream PC: i5 4460, MSI GTX960, 8GB RAM, 256GB SSD
Output of stream PC x264, very fast, 1080p downscaled to 720p 60 fps, 6000 bit rate (averaging 5,801)

Currently, there's an issue when I'm running it on x264 preset on the stream PC, where there is noticeable FPS drops on the stream especially during shooter games like counter strike which isn't very taxing on my gaming PC, pressing down the fire button (LMB) results in FPS drops and delayed audio of up to 1-2 seconds.

Is this an issue that's isolated to this specific preset? 

I've been using NVENC encoding since then on the same settings for a 720p 60 fps stream with no noticeable issues - however I'd like to try fix the x264 problem as it does provide a more crisp overall stream quality. I noticed on the stream PC that the CPU usage does not exceed 25%, shouldn't this be higher if I ONLY use the stream PC for the entire use of encoding?

Does the encoding settings of my gaming PC matter at all in the OBS?

Any advice is appreciated and if nothing can be done it's fine, still love using it without needing to purchase a capture card so I'll have to settle with the NVENC encoder.

**Comment by Palakis** [comment]
Do the FPS drops happen in the OBS preview on the streaming computer?

**Comment by nzfade** [comment]
No it is not noticeable on the preview.

**Comment by Palakis** [comment]
> No it is not noticeable on the preview.

So, if there's no frame drops noticeable on the preview shown on the OBS of the streaming computer (which receives the NDI stream from your gaming PC), I suggest you check OBS stats on the streaming computer, or try other H.264 settings.
