### ISSUE TITLE
Possible Malware is obs-ndi-4.9.0-Windows-Installer.exe

### ISSUE THREAD

**Issue by superaven** [Palakis/obs-ndi#462]
I just downloaded obs-ndi-4.9.0-Windows-Installer.exe from the release page and Windows Security is reporting it contains Trojan:Win32/Zpevdo.A

The zip versio of the release (obs-ndi-4.9.0-Windows.zip) doesn't have this issue.

[Trendmicro entry](https://www.trendmicro.com/vinfo/us/threat-encyclopedia/malware/trojan.win32.zpevdo.ae)
[Microsoft Security Entry](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Zpevdo.A!MTB&threatId=-2147227126)

**Comment by chansey97** [comment]
I have the same issue on windows.

**Comment by snargledorf** [comment]
Same issue, picked up by Windows Security on Windows 10

**Comment by KovalevArtem** [comment]
https://github.com/Palakis/obs-ndi/issues/455

**Comment by Palakis** [comment]
Duplicate of #455
