### ISSUE TITLE
Muted NDI Source makes main sound a lot louder

### ISSUE THREAD

**Issue by DarkR** [Palakis/obs-ndi#463]
The sound from NDI Source affects a main Audio Input Capture Source so it sounds louder and can clip on stream. However there is no issues on monitoring.

Please solve that. I'll make a donation for a solution.  Thanks a lot.

**Comment by walterav1984** [comment]
What OS, OBS-studio and OBS NDI plugin version? 

What are your NDI sources, is your framerate/resolution/audiosamplerate/etc?

Does this still affect you when disabling/muting all audio monitoring and disable Desktop audio in OBS-Studio(just make sure you don't internally virtually loop the audio)?

**Comment by DarkR** [comment]
Sorry, but we've figured it out. That was an issue when the same Sound Sources in different scenes multiplie and combined in one new scene where these scenes with sound was added as Sources to make collage. We wrote this issue to obs-studio github.
