### ISSUE TITLE
License for runtime

### ISSUE THREAD

**Issue by flcdrg** [Palakis/obs-ndi#465]
I'm looking to create a Chocolatey package for obs-ndi to faciliate installation on Windows machines.

I've discovered that the .exe installer can be installed silently, but it still pops up a dialog when the runtime installs, so no good for automated installs.

I'm researching whether it's better to create a separate package for the runtime installer, but in doing that it would be good to get some more information about the origins of the runtime.

**Comment by dodgepong** [comment]
The runtime can't be distributed with this plugin legally. It has to be the user's responsibility to get it on their own.
