### ISSUE TITLE
Can't download  obs-ndi

### ISSUE THREAD

**Issue by Thunter1665** [Palakis/obs-ndi#466]
Can't download 
obs-ndi nothing happens what do  I do?

**Comment by Palakis** [comment]
@Thunter1665 I'm gonna need a lot more details to help you. What do you mean by "can't download"?

**Comment by Thunter1665** [comment]
I click on the link forOBS NDI download and nothing happens.  Anti-virus
protection and firewalls are turned off.
Terry Hunter

*as good as an apple a day*
*www.halmet.ca <http://www.halmet.ca>*
