### ISSUE TITLE
Applying "Dedicated NDI Output" filter to multiple scenes has no effect

### ISSUE THREAD

**Issue by Lange** [Palakis/obs-ndi#47]
I'm trying to send multiple scenes as NDI outs, but the filter seems to only work on the first scene I apply it to. Applying it to additional scenes has no effect, and those additional scenes to not become available for me to ingest on the receiving side.

Is this intentional?

EDIT: This is with v4.1.1 on Windows 10 x64

**Comment by Palakis** [comment]
It's not intentional, I'm in the process of releasing 4.1.2 which has an improved dedicated output filter, gonna link the build here when it's finished.

**Comment by Lange** [comment]
Wonderful, thank you!

**Comment by Palakis** [comment]
Here it is: https://ci.appveyor.com/api/buildjobs/d0bveo4q0ca266wp/artifacts/obs-ndi-2a141c6.zip

**Comment by Lange** [comment]
Seems to work! 

Sometimes when I make a bunch of changes in OBS, it seems like I have to restart OBS before the receiving end can see the appropriate channels. But, it does eventually work and I can receive all the NDI channels that I am sending (5 in this case).
