### ISSUE TITLE
Avast antivirus throws an error when installing obs-ndi-4.9.0-Windows-Installer.exe

### ISSUE THREAD

**Issue by Spinball** [Palakis/obs-ndi#476]
![1](https://user-images.githubusercontent.com/5878475/81167648-7b4c9a80-8f8d-11ea-870c-f32dfcb9d1e8.png)
When installing obs-ndi-4.9.0-Windows-Installer.exe Avast says it contains the IDP.ALEXA.53 virus.
So I have not installed it.
Are people aware of this issue?

**Comment by walterav1984** [comment]
Yes they are aware of other AV behaving the same see duplicate issue #455

**Comment by walterav1984** [comment]
Perhaps you may close this issue and continue your feedback in #455?

**Comment by Spinball** [comment]
Duplicate.  I *did* search for it, I promise.  But I searched for Antivirus and that's not in the title of the other report.  Cheers.
