### ISSUE TITLE
quality problem

### ISSUE THREAD

**Issue by 7hemas7er** [Palakis/obs-ndi#48]
hi, 
quality problem
source is 1920x1080 60fps
destination: i have tray Hardware acceleration but nothing changes

network utilization 90/120 Mbps

Source 
![sour](https://user-images.githubusercontent.com/31734645/30166973-360e53e2-93e5-11e7-9596-370ec01e5054.png)
Destination
![dest](https://user-images.githubusercontent.com/31734645/30166900-fe83720e-93e4-11e7-8d55-05970769fa2b.png)

**Comment by 7hemas7er** [comment]
that's incredible,
the problem is "pixel" static image
https://orig11.deviantart.net/1c8a/f/2010/273/b/f/no_signal_found_by_epicfail23-d2zseqv.jpg
i don't understand why

**Comment by Palakis** [comment]
This is a problem with SpeedHQ, the video codec used for NDI streams. I guess that's an edge case here, and that it's not a big issue since very few users have that kind of graphics in their NDI workflows.
