### ISSUE TITLE
Stream fps capped on Ubuntu 20.04

### ISSUE THREAD

**Issue by MzlmDmn** [Palakis/obs-ndi#484]
Hi everyone,

I wanted to switch my streaming pc from Windows 10 to Ubuntu 20.04 so I could make use of a rtmp server and ffmpeg.
On Windows my setup works great at 1080p60fps with this config i7 4790k, Intel Graphics, 16GB RAM, 500GB SSD. But with Ubuntu, NDI has a lot of issues to be smooth. I tried the last version obs-ndi 4.9.0 with libndi 4.5.1 and the stream is freezing every 2/3 seconds, the network goes up and down, 0 to 20MB again and again, consistantly and the stream achieve 55fps at its best. So I tried obs-ndi 4.6.1 with libndi 3.8.0 and the network is now stabilized at 20MB which should be enough to get the ~125Mbps feed a 1080p60fps NDI emits but then in OBS the stream is caped around 25/30fps and will never go higher (only at startup of the source it goes to ~50fps).

I'd like to remind that everything works great with Windows 10 but I checked and tried everything, all the properties for the source, even Low bandwidth makes minor differences in fps, checked all my cables that are gigabit (and recognized as Gigabit on both systems), I tried to update my network driver, I also used an ethernet usb dongle, I tried a network bridge from my Windows to Ubuntu too. Added rules to ufw to open ports used by NDI I found around (5353/udp for mDNS, and a couple ports from 5960:xxx for the streams) so I'm a little out of ideas now :/

Is anyone experiencing this issue or have any suggestion?

**Comment by walterav1984** [comment]
Which ubuntu desktop environment are you running and you probably made sure recording or streaming without NDI is working at ~60fps?

Doing 720p50 on ubuntu-mate 20.04 with OBS-Studio 25.03 and OBS-NDI 4.8 with intel HD4400 graphics although I disabled cpu throttling `sudo systemctl disable ondemand.service` and use the kernel boot parameter `init_on_alloc=0 ipv6.disable=1`. These are currenlty the things that came to my mind since I don't have access to the machine right now.

Don't forget that "apt" might do stuff in the background and especially "snapd" will do update stuff without user interaction like updating the "chrome-browser".

**Comment by MzlmDmn** [comment]
Hi thanks for your answer Walter

I use the default DE: Gnome, its a fresh install and I'm using OBS-Studio from the website, installed manually through apt-get ./filepath, the PPA version can't find obs-ndi for some reason (I already symlinked to /usr/lib/obs-plugins). 

I think that you're right, there is nothing to do with OBS nor NDI, it seems that its my iGPU (HD4600) which is not running correctly and at the right speed so everything is lagging because it relies too much on my CPU. I'm sorry for opening this issue I tought it has to do with NDI but they are probably due to graphics issue, I tought linux kernel had good support for Intel Graphics by now.

But I can't find any correct answers anywhere to fix it so if you're willing to help me, I would be very grateful

I updated grub and disabled ondemand service, chrome-browser which a little smoother but not smooth enough. dsmeg command gives me:
`libobs: graphic[1799]: segfault at 78 ip 00007f8525953c4a sp 00007f85166a9120 error 4 in i965_dri.so[7f85258f6000+8b0000]`

I think that its the hardware acceleration that is failing on me, its been 3 hours I'm looking into it but nothing..

**Comment by walterav1984** [comment]
Would you try a other desktop-environment maybe even "openbox" and see if it matters?

If you are into web-browser/cef plugin or standalone webbrowser gpu acceleration will mostly be lacking on linux, or you have to use a special "vaapi" chromium-browser version or parameter to use atleast video playback acceleration in the webbrowser (even not talking about the obs-browser included). 

I do use chromium-browser combined with "desktop/screen" capture but not going higher than 720p50, that performs way better than the obs included browser(tried with the 25.08 ppa). Even playback of 4k video in seperate VLC player on 2nd screen is better than OBS included VLC or media source. However in 1080p/720p OBS mediasource/vlc playback is ok. The setup is simple nly NDI input (SD) and output (HD720p50) is used with 2decklink sdi camera sources but no recording nor streaming, just switching and simple composting of static titles and even with alpha channel uncompressed quicktime animation codec lowerthirds. 

Strange enough for the "opengl" part the intel linux graphics drivers are newer and better performant than the Windows 10 drivers, but under windows OBS-Studio is probably better optimized for D3D and other hardware accelerated gpu features.

There are more kernel parameters affecting i965 powersave/throttling but I have not tried them yet, I guess 1080p50 may be the same trouble for this machine.

**Comment by MzlmDmn** [comment]
I'm not gonna use OBS on Ubuntu for anything else than streaming to a local RTMP server, my scenes and sources will be handled by my main Windows OBS so I'm not looking for how to make everything work on Linux, I'm already frustrated enough with the basic not working hahaha

I'm willing to try another desktop-environment, going with KDE Plasma but I don't understand how that may improve the fact that OBS isn't loading i965 driver correctly to render the scene, that's the only issue I have: the scene isn't rendered correctly, streaming the laggy render to a local rtmp is playing as good as it is rendered by OBS

**Comment by walterav1984** [comment]
The "vaapi" capabilities are available to the OS, but not all software does take advantage off it in linux. Are you using the default "nv12" or higher color sampling methods and are you expecting vaapi video encoding for streaming or x264? Our setup works for more than a month around 2 hours each day, with a 40~60% cpu usage and 2~3 cpu load. If the system is on for to long a audio delay comes up but is fixed after reboot.

**Comment by MzlmDmn** [comment]
Thanks, I tried Openbox and launched OBS, it does indeed improve the FPS but only for about 5 to 10fps which is great but not what I expect from this rig, and Openbox is really sluggish, everything leaves a trail on the screen and is unusable. Everything is default in OBS settings, only the output and stream url is modified

What's affecting my performance is libobs outputs an error about i965 driver, so its not using iGPU for rendering the scene which affects the stream overall performance

**Comment by walterav1984** [comment]
Will look later this week into our log/dmesg if the segfault for the i965 might turn up but I haven't noticed it yet. 

Maybe close this ticket and continue discussion on obs forum focussed on integrated intel graphics HDxxxx performance on linux ?

**Comment by MzlmDmn** [comment]
Yes I'll do that, it'll be a better place to discuss about it. Thanks for you help

**Comment by walterav1984** [comment]
You may post a link back here to keep me noticed since my cpu Corei3 dualcore and gpu HD4400 is way worse compared to your i7 4790k but performing ok. So I guess your i965 hd4600 segfault is probably affecting other gpu related apps on linux too.

**Comment by MzlmDmn** [comment]
If I create a thread, sure I'll post the link! Yes its affecting all the apps on Linux but I though there was no issue because I came from Debian and it was tearing/lagging like hell because of no driver. So when I installed Ubuntu I though it was working great. For now, I'm going to try to build ffmpeg with ndi sdk from source.

**Comment by walterav1984** [comment]
If you are only interrested in simple NDI input/output to ffmpeg it may be easier to build "[melt](https://github.com/mltframework/mlt)" from the mltframework with ndi support than pipe that to/from ffmpeg. The mltframework is also the core for the opensource video editor shotcut.
