### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by tangjh** [Palakis/obs-ndi#486]
High Sierra 10.13.6

Installed:
obs-mac-25.0.8.dmg
obs-ndi-4.9.0-macOS.pkg
ndi-runtime-4.5.1-macOS.pkg

No video but has audio.

Workaround:
Install libNDI_for_Mac.pkg from obs-ndi 4.7.1.

Let me know if there is a better way.

**Comment by sators** [comment]
Had to do the same - libNDI_for_Mac.pkg from http://514f211588de67e4fdcf-437b8dd50f60b69cf0974b538e50585b.r63.cf1.rackcdn.com/Utilities/SDK/NDI_SDK_Mac/libNDI_for_Mac.pkg

**Comment by paulpv** [comment]
@tangjh by current design that you need to separately install libndi. Closing.
