### ISSUE TITLE
How do I Uninstall the software on Mac?

### ISSUE THREAD

**Issue by RieHiramatsu626** [Palakis/obs-ndi#487]
Hi, I downloaded, installed on Mac but could never find or open the software with no luck. Therefore, I would like to Uninstall the software now that I've given up. Although, I haven't been able to locate any instructions to Uninstall. Could you describe how to Uninstall on Mac? Thanks.

**Comment by fuzzgohan** [comment]
こんにちは、日本の方でしょうか。
英語でのお返事は難しいので、日本語で失礼いたします。
もしまだお悩みでしたら参考にしてください。

私はobs-ndi-4.8.0-macOSをインストールした後、OBSを開くことができなくなりました。
そして、あなたと同じようにアンインストールする方法を探しました。
その結果、SuspiciousPackageというソフトにたどり着きました。
（古いMac OSにも対応したバージョンが用意されています。）
https://www.mothersruin.com/software/SuspiciousPackage/get.html

このソフトを使えば、pkg形式のファイルの中身を確認することができます。
すでにパッケージファイルがインストールされている場合は、ファイルの場所を教えてくれます。
obs-ndiのpkgファイルを検索すれば、削除するべきファイルが見つかります。

よければお試しください。

**Comment by ObsidianX** [comment]
The package installs to the system Library folder: `/Library/Application Support/obs-studio/plugins/obs-ndi`.

Delete that folder and you'll stop seeing the missing runtime errors.

**Comment by CicoZhang** [comment]
On Mac M1, the folder "plugins" does not exist; how to uninstall, with the same question?  Thanks.
![image](https://user-images.githubusercontent.com/11710225/140813328-b0a31d67-a091-45d0-ac7c-f0ab59f85fb3.png)

**Comment by paulpv** [comment]
@RieHiramatsu626 this appears resolved and I am closing; feel free to comment if not
