### ISSUE TITLE
No install Mac OS

### ISSUE THREAD

**Issue by Djphooka** [Palakis/obs-ndi#488]
10.14.6
Doesn't enable NDI setting in OBS.
Tried looking for the .so in the install file as advised in a youtube video but can't find that to put in the non-existent ndi-plugins folder that's supposed to be in the package either. 
Please advise.
Thanks

**Comment by gorbett** [comment]
I have the same problem. I do not see any option in OBS to send to NDI after installing.

**Comment by zeroDevOne** [comment]
macOS 10.13.6 same problem, installed, but cannot find in scene-> source->list of source 

MacOS 10.13.6 
OSB  25.0.8
NDI runtime 4.5.1

maybe im doing something wrong???

**Comment by zeroDevOne** [comment]
> I have the same problem. I do not see any option in OBS to send to NDI after installing.

so i solve my problem just install plugin and runtime itself, they are two diferent files.

https://github.com/Palakis/obs-ndi/releases/tag/4.8.0

**Comment by paulpv** [comment]
@notadevop this appears resolved and I am closing; feel free to comment if not
