### ISSUE TITLE
MacOSX: no video and audio from local NDI Source

### ISSUE THREAD

**Issue by warrior1724** [Palakis/obs-ndi#49]
when I add NDI Source  i have received:

error: [obs-ndi] can't create a receiver for NDI source ''
info: User added source 'NDI™ Source 2' (ndi_source) to scene 'Scena 3'
info: [obs-ndi] started A/V threads for source 'IMAC-M-P.LOCAL (NDI Signal Generator)' at addr ''
info: [obs-ndi] video thread for 'NDI™ Source 2' started
info: [obs-ndi] audio thread for 'NDI™ Source 2' started

there are no video/audio from NDI Source, it doesn't show on screen
BUTwhen I run NDI Signal Generator on another computer in the network and try to show it in OBS it is working properly....

The problem has appeared after change NDI lib to v3.

env:
OBS: 20.0.1
obs-ndi: 4.1.2
NDI source signal is from local NDI Signal Generator

**Comment by unknowndomain** [comment]
I've got the exact same issue on both the current and previous version of this plugin:

```
11:57:34.892: [obs-ndi] can't create a receiver for NDI source ''
11:57:34.894: User added source 'NDI Source' (ndi_source) to scene 'NDI'
11:57:42.536: [obs-ndi] started A/V threads for source 'MB-B1945.ARTS.LOCAL (Display2)' at addr ''
11:57:42.536: [obs-ndi] video thread for 'NDI Source' started
11:57:42.536: [obs-ndi] video thread for 'NDI Source' started
11:57:42.536: [obs-ndi] audio thread for 'NDI Source' started
```

**Comment by Palakis** [comment]
Edited the title because the `can't create a receiver for NDI source ''` is normal behaviour when creating a source. The NDI receiver in OBS is created with no NDI source attached until the user selects one and applies the change.
