### ISSUE TITLE
NDI 4 Runtime Installation Stuck on "Update Network Settings"

### ISSUE THREAD

**Issue by TheMrYesac** [Palakis/obs-ndi#495]
<img width="374" alt="ndi-redist-installer tmp_VCAY8w13ip" src="https://user-images.githubusercontent.com/65423794/82095318-d3da1100-96cc-11ea-8dfa-f93ca1020687.png">

**Comment by tt2468** [comment]
Unfortunately this is an issue with the NDI runtime and not obs-ndi.
