### ISSUE TITLE
Source detected but no video image on Ubuntu 16.04

### ISSUE THREAD

**Issue by rolandf** [Palakis/obs-ndi#50]
I'm on Ubuntu 16.04.3.
I'm using OBS 20.0.1.
I use Newtek NDI app for android.

I installed both deb packages from obs-ndi repo on github (plugin and Newtek libs).
Rebooted the computer, did all upgrades
I started filming from smartphone.
I launched obs using sudo.
I added the source to the default scene.
I found this in the obs logs:

info: [obs-ndi] started A/V threads for source 'LOCALHOST (PyQR)' at addr ''
info: [obs-ndi] video thread for 'NDI™ Source' started
info: [obs-ndi] audio thread for 'NDI™ Source' started

The source first appear in preview as an empty source of size 0 by 0 that I tried to stretch to full screen.
It stay black.

Could this be related to my network ? My pc is connected to the LAN and the smartphone through wifi.

**Comment by unknowndomain** [comment]
I would imagine from reading your description this is exactly the same issue as #49, if you look above slightly do you see this error:

````
11:57:34.892: [obs-ndi] can't create a receiver for NDI source ''
````

**Comment by Palakis** [comment]
What happens if you use Low Bandwidth mode? Just tested this in a 16.10 VM and it works.
Try completely uninstalling libndi and reinstalling it, in case there's a version conflict.

**Comment by unknowndomain** [comment]
It doesn’t work either.

**Comment by rolandf** [comment]
Hi, here is the other messages I get:

00:46:46.397: [obs-ndi] can't create a receiver for NDI source ''
00:46:46.398: User added source 'NDI™ Source' (ndi_source) to scene 'Scene'
00:47:45.515: [obs-ndi] started A/V threads for source 'LOCALHOST (PyQR)'
00:47:45.515: [obs-ndi] video thread for 'NDI™ Source' started
00:47:45.515: [obs-ndi] audio thread for 'NDI™ Source' started
00:48:36.930: [obs-ndi] video thread for 'NDI™ Source' completed
00:48:36.931: [obs-ndi] audio thread for 'NDI™ Source' completed
00:48:37.931: [obs-ndi] started A/V threads for source 'LOCALHOST (PyQR)'
00:48:37.931: [obs-ndi] video thread for 'NDI™ Source' started
00:48:37.931: [obs-ndi] audio thread for 'NDI™ Source' started
00:49:09.848: [obs-ndi] audio thread for 'NDI™ Source' completed
00:49:09.849: [obs-ndi] video thread for 'NDI™ Source' completed
00:49:10.849: [obs-ndi] started A/V threads for source 'LOCALHOST (PyQR)'
00:49:10.849: [obs-ndi] video thread for 'NDI™ Source' started
00:49:10.849: [obs-ndi] audio thread for 'NDI™ Source' started

The name of the device contain localhost, I hope the NDI android app isn't advertising a 127.0.0.1 IP.

**Comment by rolandf** [comment]
By the way I did other tests, I managed to have an image using Obs-ndi output as input source in lowest bandwith mode on the same computer. it's the only configuration I can have an image in the ndi source.
So I think that it may be a network issue between my wifi/lan. Unfortunatelly I have no idea how to test and/fix.

**Comment by rolandf** [comment]
@palakis unfortunatelly I'm on 16.04 because it's a LTS version. I'll try on a 16.10 vm. Thank you.
