### ISSUE TITLE
Audio not sending over the network.

### ISSUE THREAD

**Issue by chazragg** [Palakis/obs-ndi#51]
no audio is transmitting over the network but the video signal is. i am not really sure what else to write i have checked everything i can think of but still nothing.

**Comment by Palakis** [comment]
What is your NDI receiver: OBS ? NDI Monitor ?

**Comment by Palakis** [comment]
@chazragg Where does the output comes from? Main NDI output or a Dedicated Output Filter?

**Comment by chazragg** [comment]
it is coming from one PC sending OBS preview over NDI into another PC using
that NDI as a source. i ended up performing a fresh install of OBS and the
plugin and it has started to work not. i will let you know if it plays up
again

**Comment by SmileOnSpeedDial** [comment]
I am having this same issue. Trying to reinstall now will report back if it fixes it for me too.

When I select the audio source and select "monitor only" I can hear it, but when recording its just no sound.

**Comment by Palakis** [comment]
> it is coming from one PC sending OBS preview over NDI into another PC using
that NDI as a source.

What do you mean by "sending OBS preview over NDI"? Which application is the source?

**Comment by Palakis** [comment]
@SmileOnSpeedDial 
> When I select the audio source and select "monitor only" I can hear it, but when recording its just no sound.

That's what the "Monitor only" option is for: listening to a source's audio without having it on the output. Instead, you must use "Monitor & output".

**Comment by RHSJack** [comment]
Here are screencaps of my settings and my OBS console. Anyone on here who can figure out what happened and why I can't get audio from my gaming PC? It worked before but suddenly decided not to. I just updated to 4.2.2 and the issue is still there. Here:
[https://imgur.com/yqooYQj](url)
[https://imgur.com/mG0Oerj](url)
[https://imgur.com/CUmVv32](url)

**Comment by iamkimkelvin** [comment]
@Palakis mine suddenly doesnt work on my streaming laptop video is, there's no audio tho any fix? running both 21.0.1 obs and 4.2.2 ndi

**Comment by iamkimkelvin** [comment]
![no audio](https://user-images.githubusercontent.com/36532314/36301995-b88c4a90-1356-11e8-9cab-7bd5fdf9c063.png)
