### ISSUE TITLE
OBS NDI doesn't appear in tools tab after installing.

### ISSUE THREAD

**Issue by ChiftelutaYT** [Palakis/obs-ndi#52]
I intall OBS NDI with windows installer 4.1.2, i restart the compunter, but when i open obs 64 or 32 bits, doesn't appear on tools tab.
I have a AMD Athlon II 5400B.

**Comment by ChiftelutaYT** [comment]
Also, i have windows 10 Pro

**Comment by Palakis** [comment]
Same issue as #33. Please contribute to and continue the discussion there.
