### ISSUE TITLE
NDI on virtual machine not shown

### ISSUE THREAD

**Issue by gitelia** [Palakis/obs-ndi#521]
i install NDI and finish.
But on OBS Tools menu not shown.
the windows10  1909 Image file install on proxmox.

**Comment by 0x7a72** [comment]
Lol you're going to need to give a little bit more information than that.

**Comment by gitelia** [comment]
> 大声笑，您将需要提供更多的信息。

I gave up

**Comment by Sebastien-Moraz** [comment]
hi @JzJad, I try with host but it's already don't work, are you install other library for work ?
