### ISSUE TITLE
NDI runtime url broken (NDIRedistV4Apple)

### ISSUE THREAD

**Issue by decoderrrr** [Palakis/obs-ndi#528]
Older Macbook needing 4.7.0 as last working Version

but

"Download and run obs-ndi-4.7.0-macOS.pkg. This will install both the plugin and the NDI 4.0+ Runtime. If it doesn't install the NDI runtime, download it here.

fails because the provided url  "http://new.tk/NDIRedistV4Apple" is broken.

**Comment by tt2468** [comment]
You will have to use the NDI 5 runtimes.
