### ISSUE TITLE
Frame's timestamps wrong scale

### ISSUE THREAD

**Issue by max-verem** [Palakis/obs-ndi#53]
at this line

https://github.com/Palakis/obs-ndi/blob/7454f033b0047f980b5804adbc71e1e6a0dcf2ad/src/obs-ndi-output.cpp#L244

at this code line NDI frame timestamp set in ns (nanoseconds), but NDI use 100ns interval. correct would be device by 100:

```
video_frame.timecode = frame->timestamp / 100LL; 
```

**Comment by max-verem** [comment]
for audio timestamp also should be scaled by 100

**Comment by Palakis** [comment]
Thanks for bringing this. I always wondered what is the wrong scale and asked NewTek about this. I got their answer and the timestamp handling implemented in obs-ndi was all wrong since the beginning. This has been fixed in the latest commit, both for source and main output.

**Comment by max-verem** [comment]
Their NDI Monitor do not use timestamps (i got this information from NewTek) so it hard to check it. But ffmpeg's implementation use timestamp for handling received packets.

Could you make a binary release for windows x64, so i can check.

One more suggestion is to use libndi.so.3.0.3 instead of 3.0.1, because it contains some important fixes...

**Comment by Palakis** [comment]
> Could you make a binary release for windows x64, so i can check.

I released obs-ndi 4.1.3 minutes ago, as this is an important issue.
