### ISSUE TITLE
Plugin does not show up in OBS

### ISSUE THREAD

**Issue by ScubaShneve** [Palakis/obs-ndi#537]
Here's my OBS log: https://obsproject.com/logs/M541NW4-nDPoT5Lb

I have OBS 25.0.8. I went here (https://github.com/Palakis/obs-ndi/releases/) and installed obs-ndi 4.9.0 via the Windows Installer. It also installed the runtime. I rebooted. I opened OBS and it doesn't show up in Tools nor does it show up when adding a new source. I tried re-installing and rebooting a few times. I downloaded the zip file and copied the files in. I just installed the runtime. Reboot after reboot, still does not show up.

**Comment by Vladi-pay** [comment]
Проблему решили?
