### ISSUE TITLE
OBS-NDI plug-in lagging on Windows

### ISSUE THREAD

**Issue by jdotedot** [Palakis/obs-ndi#539]
I'm using NDI Scan Converter to capture a full screen PowerPoint presentation running on a Windows 10 laptop.  On the Windows OBS computer, which is on the same Gigabit Ethernet network, I use the OBS-NDI plug-in to input the PowerPoint slides into OBS.  I've noticed that sometimes the NDI window in OBS lags behind by up to a second or two when I change PowerPoint slides.  When I play a video in PowerPoint, it comes through to OBS flawlessly.  When I run NDI Studio Monitor on the same computer as OBS, it keeps up with the PowerPoint slides and shows no lagging.  To illustrate the problem, I captured the following video [https://www.youtube.com/watch?v=H35Crg1Y6tc](https://www.youtube.com/watch?v=H35Crg1Y6tc).   In this video, recorded using OBS, I'm showing a window grab of NDI Studio Monitor in the top part and the OBS-NDI plug-in in the bottom part,.  You will see that sometimes the OBS-NDI plug-in lags behind, when switching to the next slide.

UPDATE:
The issue described above was fixed by changing 4 lines of code in obs-ndi-source.cpp where the NDI timestamp or timecode is translated to the OBS timestamp.  The NDI timestamp or timecode is in nanosecond intervals whereas the OBS timestamp is in 100 nanosecond increments.  In the existing code, the translation is done by multiplying by 100 (for example):
    obs_video_frame.timestamp = (uint64_t)(video_frame.timecode * 100);

The correct translation should be dividing by 100:
    obs_video_frame.timestamp = (uint64_t)(video_frame.timecode / 100);

This change should be made to all 4 lines of code in obs-ndi-source.cpp where the NDI timestamp or timecode is translated to the OBS timestamp.

**Comment by mattatcha** [comment]
I'm guessing this would be the same for audio right?

**Comment by jdotedot** [comment]
I don't know about the audio.  In my application, I'm only sending video from PowerPoint, so I've never tested the audio.

**Comment by jgwhitebeard** [comment]
Hey dotedot, well done for finding the bug. Have been waiting for ages for this issue to be fixed.

Mattatcha, is there a way for you to release an updated binary for all those who have been waiting please? It doesn't look like we will be getting any response from Palakis.

Thanks

**Comment by jgwhitebeard** [comment]
I like many others am really struggling to get CMake to build the project on windows.
