### ISSUE TITLE
NDI plugin loads fine, but no video is showing up.

### ISSUE THREAD

**Issue by JustStache** [Palakis/obs-ndi#54]
Okay so the CPU I have is an AMD A6 5200. And it supports Supplemental SSE3. But I am getting a black screen with nothing happening when I launch it in OBS on the Streaming PC no-matter how long I wait. I even have Firewall disabled. And I am also not getting any kind of error message. So I don't know what to do here.

**Comment by Helgaiden** [comment]
Are you connected over wifi? does it work if you enable low bandiwdth mode? Make sure both computers are wired in to a router/switch, and that ideally everything is gigabit connected (10/100/1000). Gotta make sure the computer's ethernet ports are also gigabit, for best results. Double check your firewall exceptions and/or it being disabled. Delete then re-add the source as well.

**Comment by cjudge05** [comment]
I am having the same issue, I can see the OBS output in NDI monitor on different computers. I see the list of sources on the network but the video does not come in.

**Comment by JustStache** [comment]
@Helgaiden My gaming PC is wired, but my streaming PC isn't. So you think wiring both of them could be the solution? And I tried Low Bandwidth mode and that didn't do anything different.

**Comment by Helgaiden** [comment]
@JustStache Its the first troubleshooting step i would try, as well as verifying those connections are gigabit.

**Comment by cjudge05** [comment]
I cannot see the NDI Signal Generator running on the same computer in OBS. It sees it in the list of sources but will not bring up an actual video preview.

**Comment by djshotz** [comment]
Same issue here! The NDI plugin is showing up in sources but no video or audio available just a black screen.
Broacaster 20.0.1
OBs NDI plugin 4.1.3

Using
David

**Comment by daniQing** [comment]
I have the same issue here. Firewall exceptions(also tried disabling) on both computers but still a black screen with a red dot on the top left of the streaming PC's preview window. Also tried using ethernet on both PCs.

Gaming PC: AMD FX-6300
Streaming Laptop: Intel Core i7-6700HQ

Broadcaster 20.0.1
OBS-NDI plugin 4.1.3

Daniel

**Comment by ForrestScott** [comment]
Same issue.  OBS can see the source but no image.  What's important was that I had it working and then boom!  Nothing I do can fix it.  OBS 20.0.1 NDI 4.0.3. (4.0.1 was working) on a Mac OS 10.10.5.

**Comment by cs2383** [comment]
Had the same Issue, disabled all network adapters, left only the one connecting to the router. Problem solved.

**Comment by ForrestScott** [comment]
UPDATE: I have found a workaround.  The Sienna NDI monitor see the source Mac's NDI.  I then capture the monitor window.  It's a kluge but it works.  Since the Sienna monitor see's the NDI, the issue appears to be some where in OBS.

**Comment by nealffischer** [comment]
I am running MacOS High Sierra with OBS 20.1.0 and your 4.1.3 OBS-NDI plugin. When I add the source and choose NDI Source it lists the NDI Source I wish to add but no image or audio comes through. My NDI Monitor from Newtek comes through fine. I can also do the capture window workaround and see it, but there is a terrible stutter effect. I installed the plugin from the .pkg file.  I appreciate your work on this. Just having a very hard time getting this to work. What am I missing?

**Comment by artxus** [comment]
same issues here. Gamin PC i7, streaming PC Ryzen 1700x.
OBS on the streaming pc detects NDI source but then displays black screen.
NDI works on xsplit
If I  run NDI output on the streaming PC then it works on gaming...
:( help:)

**Comment by Palakis** [comment]
@artxus Add OBS to the firewall exceptions.

**Comment by unknowndomain** [comment]
@Palakis This issue is still happening for me, I've updated OBS and macOS, do you have any suggestions on what to do?

**Comment by frax46** [comment]
Hi,im having problem on the streaming pc, the game captured is not smooth at all, what could be the problem?

**Comment by Helgaiden** [comment]
@frax46 Have a look through the comments on the video. There are tons of troubleshooting resources here. My guess is you don't have enough bandwidth between PCs. Make sure your connections are gigabit (and show as that in windows on your network device). 

@Palakis Maybe you can put this somewhere as a resource for people to look at the comments of. Im very active in responding there, so there are tons of helpful things for users having issues to read.

https://www.youtube.com/watch?v=AH_ECDLkKEA&t=

**Comment by Jack74r** [comment]
@artxus I have same problem ... you have solution? 
Work PC1 to PC2 but not PC2 to PC1 ...

**Comment by Su-alhamdan** [comment]
FOUND THE FIX!!!!!

1. Go to Firewall settings
2. Click (Allow an app or feature....) find it on the left
3. go down to OBS 64 or OBS 32 and click on the boxes of private and public for both 

Worked for me

**Comment by noway19** [comment]
This solution did not work for me. I had my two pc stream (both ethernet into modem) working fine for weeks. Then a couple days ago it just stopped working, and is giving me a black screen on my streaming pc. My obs works fine on my gaming pc, and can still stream. But no luck on my second PC. Anyone have any other solutions?

**Comment by noway19** [comment]
I just did this ----> suggested by Palakis ---->

Download and install NewTek's NDI Tools and open the Video Monitor to see if the issue happens in this app too (this would mean a broader network issue or NDI library issue)
Disconnect from the any AP or disable the wifi adapter and try to look for NDI sources again

I don't know why, but when I did this it fixed itself. WEIRD. Gl everyone

**Comment by djshotz** [comment]
NEw version 21.0.1 fixed this I have tried it on windows and it works like a charm...Bigup to whoever sorted it out no more capturing windows, straight direct feed with no delay.

**Comment by kersk** [comment]
@Palakis Thanks! In my case NDI had been working fine for a few days then it cut out abruptly. It was due to the firewall settings on the NDI source machine not allowing the connection to be made to the target machine. Just needed to add an exception for obs.exe.

**Comment by zrohtyzn** [comment]
Hi.  
I, too, have been having difficulties with NDI.  Every so often it does work, but most of the time it does not.  (Same black screen with red dot in corner.  Pressing CTRL-F resizes the red dot to a rectangle filling the preview window but still just blackness (and no audio).
I've experimented with firewall settings.  Both machines definitely have gigabit cards and are connected via network cables.  Running OBS from console on the streaming machine indicates that NDI runtime and library are being initialized successfully.  It also displays "started A/V threads for source 'NAME (OBS name)', etc.  Everything appears to be fine.
Gaming PC is Windows whilst the streaming PC is Debian Buster/Sid (kernel 4.14.0-3-amd64).
Like some other posters, the NDI connection appears to work flawlessly from the streaming machine to the gaming machine, but not the "direction" desired.
I've tried all sorts of things from these threads and nothing seems to make streaming through my linux machine reliable (or even remotely viable).  On the rare occasion that it did work,  it seemed to work wonderfully (however, i did not test it for more than about 5 minutes).
Any assistance with this matter would be greatly appreciated.

**Comment by ajrigor** [comment]
Does anyone know any router based troubleshooting tips? Around a year ago, I was able to dual pc stream by nginx rtmp. Then I tried to start up streaming again, and neither nginx nor NDI works. Studio Monitor does display on the gaming PC, but does not send video (but the gaming PC shows up as on the NDI group) to the streaming PC. So at this point i'm pretty sure the problem is network based. Help!

**Comment by lincolnstake** [comment]
In case it helps you, I had to tick the "async" checkbox in the NDI output dialog to get things going for the receiving PCs (was using Windows). Once they got the feed, I could uncheck the box. As far as I could tell, the firewalls were off, but I didn't rule out the firewall impacting discovery.

**Comment by Palakis** [comment]
General networking tips with NDI:
- Use Gigabit Ethernet
- Use a proper switch, either managed or unmanaged, instead of the built-in Ethernet ports of your home router. They work like a traditional switch, but sometimes processing is done on the router's CPU instead of on a dedicated processor.
- On Windows
  - **Don't ever use the Public profile on the network adapter used for NDI.** This interferes with source discovery.
  - Add a firewall exception for OBS Studio in your firewall
- Reset your TCP settings after installing the NDI runtime, as the installer provided by NewTek silently enable Compound TCP which reduces available bandwidth.

If you still encounter issues, please open a new issue here on this tracker.

**Comment by FairyToothTony** [comment]
Ok, I had the black screen problem and solved by executing OBS on streaming machine with compatibility mode for Windows 7.

**Comment by ajrigor** [comment]
Will try it when I have time!

________________________________
