### ISSUE TITLE
NDI image ghosting

### ISSUE THREAD

**Issue by wnchan2000** [Palakis/obs-ndi#540]
I am using iMac (2012) installed with Catalina 10.15.6. 
Single monitor. 
OBS 25.0.8.
Very serious ghosting effect occurs. There is no such problem with my MacBook Pro (2012).
![ghosting1](https://user-images.githubusercontent.com/8317930/90308000-4a75ed00-df0e-11ea-8759-8ab3ee3e91a7.png)

**Comment by FireController1847** [comment]
Having the same issue, have you found any fix for it?

**Comment by tt2468** [comment]
This looks like color range issues. Hopefully these issues will not appear in 5.0.0. Please reopen a thread if they continue when 5.0.0 is released.
