### ISSUE TITLE
Separate audio would be great

### ISSUE THREAD

**Issue by wrightyrx7** [Palakis/obs-ndi#55]
Keep up the great work!! 

I would love for the Desktop and Mic audio to come through to the streaming PC seperately. 

I have a 3 PC setup for me and the Mrs, but to use this we would need to be able to Mute the Desktop audio for one of the computers but leave the mic on. Audio from two games wouldn't work.

**Comment by Helgaiden** [comment]
I ran a LAN party using OBS NDI with 4-5 computers and muted the audio from each NDI source. However, my workaround was to put the streaming PC in the same Discord chat as everyone else, so you could still hear everyone talk but as the scenes switched from source to source, you just couldn't hear the game audio. Worked pretty well.

**Comment by wrightyrx7** [comment]
Thats a pretty simple workaround.... i like it!! I will probably copy the way you did it :)

But to avoid having to use a workaround it would still be a pretty good feature within the NDI plugin. Im sure it could be used for many other reasons too.

**Comment by Palakis** [comment]
The fix is actually simple : making the NDI dedicated output available for audio-only sources.

**Comment by wrightyrx7** [comment]
Hi Palakis, thank you for your reply. 

Yes this would be perfect! Do you think it is something that will be added in the future?

**Comment by wrightyrx7** [comment]
Is this something i can do or that you guys would need to do?

**Comment by wrightyrx7** [comment]
So i managed to get everything working, I am using VoiceMeeter for the MIC audio.  But i do not have much hair left as it was a nightmare to setup.

It would still be a great addtion to the plugin, or even a seperate plugin. There would be many uses, most people with a dual PC stream like to have the notifications on their streaming rig but have trouble getting the audio for the notifications come through to the gaming pc. This would solve this.

**Comment by Palakis** [comment]
Hi everybody, apologies for the delay.
This is kinda trivial to implement: implement a new audio-only source, or manage to refactor the current ndi_source code to make it available for audio-only OBS sources. Could use some help on this as I don't have much time to dedicate to this 😕

**Comment by Palakis** [comment]
This has been implemented some releases ago. Issue fixed!
