### ISSUE TITLE
OBS-ndi-plugin doesn't recognize to get inactive/transparent when no Signal is sending.

### ISSUE THREAD

**Issue by Wolfi0ne** [Palakis/obs-ndi#553]
I have the following "issue" in OBS 25.0.8 with the NDI plugin 4.9.0 under Windows 10 build 2004:

I have for example a scene with 2 sources, top source is to add an NDI device (NDI client via mobile phone), bottom layer is just a wallpaper image to avoid the black screen of emptiness.

When I start OBS and the NDI sender is not activated, I see - as expected - the wallpaper source. As I start the client-program on the phone (even not sending), the top layer with NDI gets active - that is OK, I see it as a preparation step to activate the NDI sender. Sending thru NDI works perfect, but - even with the Alpha Filter - I experience the following thing:

After closing the NDI sender program on the mobile phone, the top layer (the NDI scene) is still active. I thought it will take a couple of minutes, as it is a network device and there might be caching. But: even after waiting an hour, the NDI scene is still active and doesn't recognize that there is no signal anymore (to make it itself transparent again).

I tested it several times (NDI sender started, NDI sender program closed): it doesn't seem like it is a network caching, because regardless if I wait a couple of minutes or do it directly after the program on the mobile device is closed: after stopping and starting of OBS, the wanted behaviour is there - top NDI layer is transparent because there is no signal, so the bottom layer is shown - comes in.

My conclusio is: is there a possible bug in the "check signal/release scene" routine?

In case someone says: just make an own scene... My goal is to create several nested Scenes (each scene is an own program, like each game), and combine all nested scenes in a general "Lets play"-scene. So a streamer has only to select this scene, and regardless what program/game (for which a nested scene has to be exist) is started this scene fits. This solution works fine with Window and Gamecapture (in Window capture, the only thing is to set it strict to the exe of the game, and nothing else)... Just my NDI source has this behaviour I tried to describe above.

**Comment by tt2468** [comment]
This is not a bug, but a case of missing functionality. It will be working in 5.0.0
