### ISSUE TITLE
include  newtek libndihx.so compatibility

### ISSUE THREAD

**Issue by fukeabigtime** [Palakis/obs-ndi#558]
libndihx is the *quote* new version of the ndi protocol *unquote*

official release is here:
https://support.newtek.com/hc/en-us/articles/360012318274-Linux-NDI-HX-Driver

obs-ndi loads libndi.so   *but does not load libndihx.so*

so ndihx stream are not accepted by obs-ndi.

from obs log:

05:59:16.076: OBS 26.0.0.rc2.r0.g5889e2905 (linux)
[...]
05:59:16.331: ---------------------------------
05:59:16.332: Loading module: obs-ndi.so
05:59:16.333: [obs-ndi] hello ! (version 4.9.1)
05:59:16.333: [obs-ndi] Trying ''
05:59:16.333: [obs-ndi] Trying '/usr/lib'
05:59:16.333: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
05:59:16.337: [obs-ndi] NDI runtime loaded successfully
05:59:16.338: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 18:32:11 Jun 30 2020 4.5.3)
05:59:16.356: output 'NDI Main Output' (ndi_output) created
05:59:16.356: output 'NDI Preview Output' (ndi_output) created
05:59:16.357: ---------------------------------

although if i run % ldconfig --verbose | grep libndi
ldconfig: Path `/usr/lib64' given more than once
        libndi.so.4 -> libndi.so.4.5.3
        libndihx.so -> libndihx.so

the two librairies are installed, but  libndihx.so is not loaded by obs-ndi.

=====

to reproduce: install the  newtek ndihx driver and load obs

=====

behavior of obs-ndi, with an ndihx sender: obs-ndi does "see the sender" and lists it, but when selected, no image or sound.

====

side note:
 thank you palakis !

**Comment by fukeabigtime** [comment]
PS: test was done with a newtek spark plus 4K hardware which works perfectly (as tested with a windows machine on the same network)

**Comment by tt2468** [comment]
I seem to remember ndi-hx working (the version of ndi that is designed to use lower bitrates, at the sacrifice of lower quality). Is this not the same standard? The link provided does not work.

**Comment by fukeabigtime** [comment]
to answer your question, no, ndihx is not the same standard as ndi, and newtek is not forth comming about this fact.
under windows and macos, they use the "NDI Virtual Input" as stated on their page https://ndi.tv/tools/
that "ndi virtual input" is in fact a abstraction layer, and it is through that layer that ndi applications (that are not ndihx) can access ndihx senders.

**Comment by fukeabigtime** [comment]
i have to emphasize: you will reproduce the behavios only if you use an ndiHX sender on the network. (and pro hardware are switching to ndihx)

**Comment by fukeabigtime** [comment]
..;

i am confused.. it hought I'd retry the setup and now.. it works..


-_- 



i did do a full system upgrade on the linux ...

okay 

close this request.

it works. i dunno why it did not before

and i won't try to uderstand ...
