### ISSUE TITLE
HD60 Support

### ISSUE THREAD

**Issue by DJam98** [Palakis/obs-ndi#559]
Hi there, is there going to be support for the HD60 anytime soon (not the S series)?

Currently, when I have my HD60 plugged in and working it still says "please connect a capture device".

OBS Link Software Version: 1.0.1 (159)
Mac OS: 10.15.6
Model of Mac: MacBook Pro (Retina, 13-inch, Mid 2014)

**Comment by nettings** [comment]
Support for the HD60 has nothing to do with the obs-ndi plugin. Please check the OBS forum to get help, and don't misuse the bug tracker for this.

**Comment by tt2468** [comment]
As stated above, obs-ndi is entirely unrelated to this issue. Please use the OBS forum or discord.
