### ISSUE TITLE
NDI doesn't transfer over to my second pc

### ISSUE THREAD

**Issue by darrentaber** [Palakis/obs-ndi#560]
Alright, I have downloaded NDI to both my gaming pc and my streaming. When I turn on the NDI source for my gaming pc and go to my streaming pc to find the network it is there. The issue I am having is that my streaming pc doesn't display anything from my gaming pc. Is there any suggestions that may help?

**Comment by nettings** [comment]
You probably have a firewall issue. Temporarily turn off your firewalls on both PCs and see if you can connect, then learn about the ports that NDI uses and selectively open those.

**Comment by darrentaber** [comment]
Ok thank you
