### ISSUE TITLE
Starting / stopping NDI output via websocket is not successful.

### ISSUE THREAD

**Issue by dr-froehlich** [Palakis/obs-ndi#562]
Hi,

I am creating an automated recording / video transmission solution for our university use relying on NDI.

I try to activate/deactivate the NDI output using the following code:

```python
obs.request('StartOutput', {'outputName':'NDI Main Output'})
obs.request('StopOutput', {'outputName':'NDI Main Output'})
```

Looking at the protocol debug messages, I get *"error": "output start failed: "* when activating, and *"error": "output not active"* when deactivating. In both cases the output was actually activated (checkbox marked).

I am using *simpleobsws*, that part works very well for everything else.

Am I doing something wrong? Is it possible to control the NDI outputs via websockets? Many thanks - great work!

Peter

**Comment by tt2468** [comment]
Hmm I'll have to look into this. The `output` series of obs-websocket requests is very experimental, but I think we could likely implement proper support for it into obs-ndi.

**Comment by tt2468** [comment]
Since there is an open request for obs-websocket control of obs-ndi, I'll be closing this. We've been laying the groundwork over the past few months for integrations like this. Hopefully we can get it finished in a reasonable amount of time.
