### ISSUE TITLE
NDI 4.5.1 macOS runtime link not working

### ISSUE THREAD

**Issue by Hujairi** [Palakis/obs-ndi#573]
NDI 4.5.1 macOS runtime link available in the release page is no longer working.

https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-Windows.exe

any other possible way to download it ?

**Comment by AntyaDev** [comment]
the same for me

**Comment by davilopesbox** [comment]
Link unavailable: DNS_PROBE_FINISHED_NXDOMAIN.

**Comment by Hujairi** [comment]
Closed, Workaround in #576 . add domain ip on host file or use the web.archive.com
