### ISSUE TITLE
ndi.palakis.fr - server ip address could not be found - cannot download ndi runtime

### ISSUE THREAD

**Issue by karlrissland** [Palakis/obs-ndi#575]
Windows and Mac installs are not working because the ndi 4.5.1 runtime is unavailable.  Error shows that the server IP address cannot be resolved.

https://ndi.palakis.fr cannot be resolved.

**Comment by hallidaylam** [comment]
Me also

**Comment by opn** [comment]
Me too.

**Comment by davilopesbox** [comment]
Me too!

**Comment by davilopesbox** [comment]
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by Oolahk** [comment]
me six! I thought I was going crazy

**Comment by LittlePeepPlanet** [comment]
same, page does not work

**Comment by TheGreatLordJim** [comment]
Me as well. What... what do we do?

**Comment by TheGreatLordJim** [comment]
It's working now btw

**Comment by burnbrigther** [comment]
This is down again.  Is there an alternative download site for ndi-runtime-4.5.1-macOS.pkg ?
