### ISSUE TITLE
ATTENTION: Do you have the NDI 4.5.1 Runtime for PC / MAC ?

### ISSUE THREAD

**Issue by Oolahk** [Palakis/obs-ndi#576]
If anyone who already has the 4.5.1 NDI runtime exe for Windows or pckg for MAC could you please link us to the file? Would be much appreciated!! The site is down so many cannot download this file.

Thanks!

**Comment by mikestjean** [comment]
Same - Palakis' site seems to be down so nowhere to download this. I'm looking for Mac.

**Comment by devsparkles** [comment]
I will try to compile it myself following the instruction on the repo. And see if it works for me ... Installing Xcode. (macOS Catalina.)

**Comment by static-something** [comment]
Ran into the same issue as above. Found a temporary workaround using the NDI 4.0+ installer link. That link is not broken, and can be found in the 4.7.1 release. Pasted below for simplicity. At least for my use-case scenario it seems to be functioning properly so far. However, if devsparkles gets 4.5.1 reuploaded, I'd appreciate a link to that as well.

http://new.tk/NDIRedistV4

**Comment by wingfield4** [comment]
Looks like the mac version was archived on the Wayback machine--

Get the mac version here: https://web.archive.org/web/20200708145435/https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg 

Didn't find the windows version, but it sounds like the above solution could work at least temporarily.

**Comment by sehnept** [comment]
It looks like it is a problem with their DNS servers.

For a temporary workaround on Windows, add the following entry to your hosts file (C:\Windows\System32\drivers\etc\hosts)

104.24.99.21   ndi.palakis.fr

Then download [https://ndi.palakis.fr/tools/ndi-tools-4.5.1-Windows.exe](https://ndi.palakis.fr/tools/ndi-tools-4.5.1-Windows.exe)

**Comment by QCgeneral29** [comment]
Worked for me. Thanks a bunch!

**Comment by saiv123** [comment]
> It looks like it is a problem with their DNS servers.
> 
> For a temporary workaround on Windows, add the following entry to your hosts file (C:\Windows\System32\drivers\etc\hosts)
> 
> 104.24.99.21 ndi.palakis.fr
> 
> Then download https://ndi.palakis.fr/tools/ndi-tools-4.5.1-Windows.exe

looks like this website is down too, for people that have this driver could you guys like put it on a github and share it here or a google drive or something

**Comment by ifuchs** [comment]
The wayback machine copy did provide the Mac driver. However, I am not able to get the NDI tools. Does anyone know how to download those?￼ (I was able to get the NDI driver but not the apps)

**Comment by santium** [comment]
> > It looks like it is a problem with their DNS servers.
> > For a temporary workaround on Windows, add the following entry to your hosts file (C:\Windows\System32\drivers\etc\hosts)
> > 104.24.99.21 ndi.palakis.fr
> > Then download https://ndi.palakis.fr/tools/ndi-tools-4.5.1-Windows.exe
> 
> looks like this website is down too, for people that have this driver could you guys like put it on a github and share it here or a google drive or something

I uploaded it to Google Drive.

https://drive.google.com/file/d/1cJCRXf6-z1H1cXriTGjg-k5RP2Dl4V_F/view?usp=sharing

**Comment by saiv123** [comment]
do i just run the exe or do i put it somewhere

**Comment by Oolahk** [comment]
> do i just run the exe or do i put it somewhere

@saiv123 I think you just run the exe to install it.

**Comment by Oolahk** [comment]
Thanks @sehnept !!
I've posted both PC and MAC versions here: https://bit.ly/375VB91

**Comment by Gfctr** [comment]
Thank's, I was trying to install yesterday.

**Comment by ifuchs** [comment]
Unless I am mistaken (someone please tell me), making OBS work with Zoom requires the NDI tools (apps). I was unable to get them from NDI. Does anyone have them or a working link?

**Comment by Oolahk** [comment]
> Unless I am mistaken (someone please tell me), making OBS work with Zoom requires the NDI tools (apps). I was unable to get them from NDI. Does anyone have them or a working link?
@ifuchs :
You do not need NDI to make OBS work with Zoom. All you need is the OBS Virtual Camera Plugin : https://obsproject.com/forum/resources/obs-virtualcam.539/

Then in Zoom you select the virtual camera as the source and it will display whatever you have going on in OBS. There are plenty of  Youtube videos showing how to set up Virtual Camera in OBS.

NDI is used if you want a video source that is not locally on the machine that is broadcasting. Gamers use NDI so that they can play their games on one machine while streaming it from a separate dedicated computer.

**Comment by ifuchs** [comment]
Thanks. That would be good except I am running on a Mac which is why I thought I needed the NDI-tools but I am happy to be proved wrong.

**Comment by Oolahk** [comment]
Yeah I think virtual camera is not natively available for Mac but I quickly
googled this video and seems there is a way to do it.

https://youtu.be/-6lPd_6nSwA

Good luck!

**Comment by Palakis** [comment]
ndi.palakis.fr is back again. Closing this.

**Comment by littleq0903** [comment]
https://web.archive.org/web/20230122090150/https://ndi.palakis.fr/tools/ndi-tools-4.5.1-Windows.exe

**Comment by Shivaxi** [comment]
looking for the ndi-runtime-4.5.1-Windows.exe - seems ndi.palakis.fr is down once again.  Anyone have a re-upload of this?
