### ISSUE TITLE
NDI windows installer server name cannot be resolved

### ISSUE THREAD

**Issue by saiv123** [Palakis/obs-ndi#577]
i was trying to install the NDi plugin with the windows installer, and when it gets to the download it says server name can not be resolved

**Comment by Flepix** [comment]
Take https://drive.google.com/file/d/1u-Mj4uP8glSrkZuGQ0y3AEJs8_T0BSeQ/view?usp=sharing

**Comment by Soypete** [comment]
Same issue for mac runtime

**Comment by Hujairi** [comment]
anyone has the mac version ?

**Comment by Hujairi** [comment]
@Flepix do you have the MacOS version ?

**Comment by Flepix** [comment]
@Hujairi No, sorry.

**Comment by Flepix** [comment]
The link already works https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

**Comment by Soypete** [comment]
it is working today! thank you so much!!!!

**Comment by saiv123** [comment]
thanks you for the help, but i had used the method that was in this post

https://github.com/Palakis/obs-ndi/issues/576#issuecomment-708877042
