### ISSUE TITLE
Question: High Bandwith Usage Normal?

### ISSUE THREAD

**Issue by jslacson** [Palakis/obs-ndi#59]
I just have a question.  Is high bandwidth usage normal?  My situation: I have 1000Mbps connection with normal rates around the 700-800Mbps.   However, with NDI active, my speed drops to 20-100Mbps.

Is this normal?  Just curious.

**Comment by Helgaiden** [comment]
The NDI plugin bandwidth is determined by your OBS video settings, but in general it does use a good chunk of bandwidth. At 720p60, i see around 125mbps usage. Listing your video settings would probably be helpful,

**Comment by jslacson** [comment]
I can't remember off the top of my head, but I do know it's exorbitantly high.  I don't stream, so it's just recording from source pc to recording pc.  1440p/144hz, 50,000 bitrate and 320 audio over 3 channels.

I don't mind losing the speed when I'm recording, but the weird thing is when I'm not recording my speed is still hindered.  I've run "tests" to see if it was something else, but here's what I've deduced so far:

1. Speed is 800+ wlith fresh windows install
2. Speed is 800+ after installation of Steam, Guild Wars 2 and Epic Games Launcher (with all games downloaded)
3.  After install of NDI in OBS, speed drops to <100 Mbps
4.  With all programs closed, including OBS, speed is still <100 Mbps
5.  With all programs, including games uninstalled, speed is still <100 Mbps
6.  After reformat and Windows reinstall, speed is 800+ again.

**Comment by Helgaiden** [comment]
Whats the reason for using NDI to record on a 2nd system? Geforce Share/Shadowplay and Radeon ReLive aren't very system intensive for local recording.

**Comment by jslacson** [comment]
I had an Elgato HD60 Pro, but it was too much of a pain to play at 1440p/144hz.  I did the workaround, but every time I rebooted I had to mess with it.  NDI allowed me to push my normal settings to the second computer.  Recording on the same PC I play on is something I'd like to avoid entirely, just preference.

I'm not familiar with GeForce Share or Shadowplay, I'll have to look into those.

**Comment by jslacson** [comment]
So, new testing brought about new information.

 It seems it's the NDI plugin itself.  After I installed NDI alone (OBS is not installed), I ran a speed test and still had >700Mbps down/>400Mbps up.  AFTER I rebooted the computer, my speed dropped to ~70Mbps down/up.  It looks like, it's not bandwidth usage between the two PCs, but the plugin itself limiting my speed.

I have a ticket open with Newtek to see what's going on.  If you'd like to close this thread, it's up to you.  But, if you leave it open....I'll post updates with what Newtek and I discover.

**Comment by jslacson** [comment]
Response from Newtek Customer Support:

Overall we would expect NDI usage to be apparent however at initial point in the conversation, you would first need to contact the developer of the plugin to find out how they are implementing the use of our NDI SDK.  We have our own information relevant to our own integration of NDI but don't have information on all the 3rd party developers. 

Regards,
Laura

So, it looks like it actually is something attributed specifically to OBS NDI.  Does the plugin "reserve" a certain amount of bandwidth upon installation?  Is there a way to configure this?  I would like to have my full bandwidth available if I'm not using OBS.

**Comment by Palakis** [comment]
> Response from Newtek Customer Support:

Overall we would expect NDI usage to be apparent however at initial point in the conversation, you would first need to contact the developer of the plugin to find out how they are implementing the use of our NDI SDK. We have our own information relevant to our own integration of NDI but don't have information on all the 3rd party developers.

The NDI SDK only provides two bandwidth modes: Lowest and Highest. An NDI source is in Highest Bandwidth mode by default, and can be optionaly set to Lowest Bandwidth ("Low Bandwidth mode").

**Comment by Palakis** [comment]
Furthermode, obs-ndi doesn't do anything network-wise. It is all handled by the NDI SDK.

**Comment by Palakis** [comment]
> It seems it's the NDI plugin itself. After I installed NDI alone (OBS is not installed), I ran a speed test and still had >700Mbps down/>400Mbps up. AFTER I rebooted the computer, my speed dropped to ~70Mbps down/up. It looks like, it's not bandwidth usage between the two PCs, but the plugin itself limiting my speed.

Try this:
1) Install obs-ndi from the Zip archive **without installing the NDI redist**
2) Measure available bandwidth
3) Install the NDI redistributable runtime
4) Measure available bandwidth again
5) Reboot
6) Measure available bandwidth again again

I'm suggesting this experiment because the obs-ndi installer only unpacks the plugin to the OBS installation folder, without touching anything else on the system. However, the NDI redist installer (that is automatically downloaded and ran by the obs-ndi installer) changes system settings.

**Comment by jslacson** [comment]
I will try this as soon as I get home.  I've always used the .exe to install OBS, so this may provide different results.

If bandwidth is still limited, is it reasonable to assume it's the NDI SDK is causing the issue?
If bandwidth is not hindered, is it reasonable to assume that the installer is causing the issue?

**Comment by jslacson** [comment]
Results... (Time: Event - Speed in Mbps)

5:01pm: OBS Installed - 755 down/442 up
5:05pm: obs-ndi unzipped and copied to obs folder - 692 down/420 up
5:16pm: NDI Redist v3 Installed/no reboot - 693 down/366 up
5:22pm: NDI Redist v3 installed/rebooted - 70 down/71 up
5:25pm: NDI Uninstalled/no reboot - 71 down/70 up
5:28pm: NDI Uninstalled/rebooted - 71 down/71 up

//test concluded//

**Comment by jslacson** [comment]
6:07pm: Reformat hard drive, fresh Win10 install -  736 down/467 up

**Comment by jslacson** [comment]
And just for thoroughness' sake, here's a video showing the initial bandwidth, NDI install, reboot and resultant bandwidth.

https://youtu.be/4TGf2TvjIfQ

**Comment by Palakis** [comment]
@jslacson Thanks a lot for these comprehensive tests!

I disassembled the NDI redist installer with `innounp`. Here are my findings from the install script:
- It modifies the registry key `SYSTEM\CurrentControlSet\Control\Nsi\{{eb004a03-9b1a-11d4-9123-0050047759bc}\0`. A quick Google search seems to indicate this key is for TCP Congestion Control settings (NDI uses TCP for A/V traffic) and enables Compound TCP.
- It runs the command `netsh int ip add excludedportrange protocol=tcp startport=49479 numberofports=1`

**Comment by Palakis** [comment]
Powershell command to configure congestion control:
`netsh int tcp set supplemental custom congestionprovider=none`
Where `congestionprovider` can also be set to `none` or `ctcp` (Compound TCP)

**Comment by jslacson** [comment]
Just to clarify, I should disable ctcp to fix the issue?

**Comment by jslacson** [comment]
Hey guys.  So I finally got around to taking screenshots of the before and after netsh settings.  Definitely some changes made by NDI.  I'm testing to see how to get my speed back and will post with results.  The one with "system32" one is the before.

![before](https://user-images.githubusercontent.com/32382037/31754007-d19ab512-b451-11e7-878c-5701ce701de1.jpg)
![after](https://user-images.githubusercontent.com/32382037/31754012-d3cc4350-b451-11e7-9453-ee95cbd438f7.jpg)

**Comment by jslacson** [comment]
I got my speed back!  So, after trying to manually set the congestion control provider to default or none and failing (Microsoft deprecated the command and made it confusing as hell to modify), I accidentally discovered the command that works.

all you have to do to reset your TCP settings as they were with a fresh windows install is:
netsh int tcp reset

And tada, 900Mbps down and 500Mbps up.  The up is a little low, but I'll figure out that in a bit.

Thank you Palakis for taking a look into this and pointing me in the right direction.

**Comment by ijsPod** [comment]
Doesn't work for me, I've tried it on both of my PCs

**Comment by odinho** [comment]
Did NewTek ever reply to this? And say why they enable ctcp, and if it is actually meant to help (it probably was the reason, but clearly something is broken with it)?
