### ISSUE TITLE
Installing on Debian 10 Buster (add to snap?)

### ISSUE THREAD

**Issue by JetForMe** [Palakis/obs-ndi#595]
I've been trying to install the `.deb` packages on Buster, but unfortunately the latest OBS one can get via `apt` is 23.0.3, and this requires 25.0.7 or later.

Using `snap` I was able to install OBS 26.0.2, but the `.deb` packages don't recognize that as being installed.

Would it be possible to add `obs-ndi` to snap? Otherwise it seems I have to build things from source, which seems like a lot of extra work. The machine I want to run this on isn't really a general-purpose machine (it runs a CNC machine), and I'm trying to avoid cluttering it up with things like build tools.

TIA!

**Comment by flexiondotorg** [comment]
I maintain the [OBS snap](https://github.com/snapcrafters/obs-studio) and obs-ndi has been integrated in the snap for sometime now :+1:

**Comment by JetForMe** [comment]
Huh, I must have snap set up incorrectly, then.
