### ISSUE TITLE
Issue - able to get stream from PC 1, while not able to get stream from PC 2

### ISSUE THREAD

**Issue by ncurakovs** [Palakis/obs-ndi#611]
Hi,

So I have 2 WIN 10 PCs, 1 laptop - PC 1 and 1 gaming - PC 2.

I want to stream from PC 1 to PC 2. 

I am able to get video feed from PC 1 to PC 2, while I cannot get video feed from PC 2 to PC 1. All what I get - black screen, no audio. 

I have tried:
To reinstall OBS on both machines, to reinstall NDI plugin on both machines.
I have tried to downgrade NDI to 4.0.0 version.
To disable firewalls on both machines + previously tried to adjust rules accordingly.
To press RBM on red dot => scale to fit.

Every machine is using same OBS, NDI plugin version (no x32/x64 difference as well).

I am pretty sure that it is caused by some weird setting, as I am able to get feed from PC 2 to PC 1, but not vice versa...

Please help!

**Comment by ncurakovs** [comment]
Please kindly note that most similar issue to what I have found is that one - https://github.com/Palakis/obs-ndi/issues/62

It is literally all the same... :(

**Comment by piero21435** [comment]
you  solved  ? I've got the same problem

**Comment by BigMike1978** [comment]
same problem here pls help

**Comment by ncurakovs** [comment]
Hey guys,

Please try to disable ALL network adapters except the ones which are used to access internet - that solved problem for me.

Thanks!

**Comment by piero21435** [comment]
> Hey ragazzi,
> 
> Si prega di provare a disabilitare TUTTI gli adattatori di rete tranne quelli utilizzati per accedere a Internet - questo ha risolto il problema per me.
> 
> Grazie!

which adapters?

**Comment by ncurakovs** [comment]
Here is the guide => https://www.windowscentral.com/how-enable-or-disable-wi-fi-and-ethernet-network-adapters-windows-10

**Comment by piero21435** [comment]
> Ecco la guida => https://www.windowscentral.com/how-enable-or-disable-wi-fi-and-ethernet-network-adapters-windows-10

i only have one connection, what should i deactivate?

**Comment by ncurakovs** [comment]
> > Ecco la guida => https://www.windowscentral.com/how-enable-or-disable-wi-fi-and-ethernet-network-adapters-windows-10
> 
> i only have one connection, what should i deactivate?

Then try to check your firewall/antivirus settings. Other than that - have no idea, sorry. Keep trying.
