### ISSUE TITLE
NDI webcam tool is picking up my video stream but not my audio

### ISSUE THREAD

**Issue by getify** [Palakis/obs-ndi#614]
I have OBS-NDI broadcasting video and audio from one windows10 computer... and on the second windows10 computer, I have OBS-NDI as well as NDI Tools installed.

On the second computer, in OBS, I can see the video stream from the NDI source, and I also see the meter for the audio indicating my voice sound coming through, and at full volume level (yellows and even reds if I talk loudly). I've recorded from OBS studio and the audio comes through just fine. In addition, in windows control panel, if I find this audio device and check its device properties, I see the indicator in there showing that the audio is coming in fine to that device.

However, when I use Webcam (from NDI Tools), and enter a zoom call (via the web interface, not the desktop client), if I select the "Line (NewTek NDI Audio)" audio source for my mic, no audio comes through for others to hear me. Though my video comes through fine.

The audio level in the Webcam systray tool is defaulted to "+0db (SMPTE level)", not the "mute". I tried bumping it to the "+20db" level thinking maybe it was too quiet, but that didn't work.

If I switch to a different mic in the zoom call, everything works fine, but I really want/need my zoom call to pick up on my mic from the NDI feed (that's kinda the whole point of using NDI).

Any idea what the problem might be and how to fix it?

**Comment by paulpv** [comment]
Palakis installs v4.5.1 of the 
https://github.com/Palakis/obs-ndi/blob/master/installer/installer.iss
```
#define NDIRuntimeVersion "4.5.1"
  ndiRedistURL = 'https://ndi.palakis.fr/runtime/ndi-runtime-{#NDIRuntimeVersion}-Windows.exe';
```
The latest as of this moment is 4.6.1, which he has on his share:
https://ndi.palakis.fr/runtime/

You can try installing that and report back here.

**Comment by getify** [comment]
I didn't change anything about my settings or whatever, and had this problem for like 5 days. Then one day, I noticed the audio was being picked up, so it just sorta randomly fixed itself (not even from a reboot). I have no explanation for that, but at the moment, it's been working well for 5 days. So I guess I'll go ahead and close this. Thanks!
