### ISSUE TITLE
Can't get any sources even my own

### ISSUE THREAD

**Issue by someguy736** [Palakis/obs-ndi#619]
I don't know what I did this time but for some reason on my linux box I can't get any sources at all, not even sources I create in the same OBS window! AFAIK the log file is clean, except OBS crying about missing packages but as far as I am aware they are unrelated. However here's the log just in case:

> 02:14:32 AM.035: CPU Name: Intel(R) Xeon(R) CPU
> 02:14:32 AM.035: CPU Speed: 2584.730MHz
> 02:14:32 AM.036: Physical Cores: 8, Logical Cores: 16
> 02:14:32 AM.036: Physical Memory: 32201MB Total, 10878MB Free
> 02:14:32 AM.036: Kernel Version: Linux 4.18.20
> 02:14:32 AM.036: Distribution: "Devuan GNU/Linux" "3"
> 02:14:32 AM.036: Session Type: tty
> 02:14:32 AM.036: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
> 02:14:32 AM.038: Portable mode: false
> 02:14:32 AM.084: OBS 26.1.2+dfsg1-1+b1 (linux)
> 02:14:32 AM.084: ---------------------------------
> 02:14:32 AM.295: ---------------------------------
> 02:14:32 AM.295: audio settings reset:
> 02:14:32 AM.295: 	samples per sec: 48000
> 02:14:32 AM.295: 	speakers:        2
> 02:14:32 AM.311: ---------------------------------
> 02:14:32 AM.311: Initializing OpenGL...
> 02:14:32 AM.354: Loading up OpenGL on adapter nouveau NVC4
> 02:14:32 AM.354: OpenGL loaded successfully, version 4.3 (Core Profile) Mesa 18.3.6, shading language 4.30
> 02:14:32 AM.402: ---------------------------------
> 02:14:32 AM.402: video settings reset:
> 02:14:32 AM.402: 	base resolution:   1920x1080
> 02:14:32 AM.402: 	output resolution: 1920x1080
> 02:14:32 AM.402: 	downscale filter:  Bicubic
> 02:14:32 AM.402: 	fps:               60/1
> 02:14:32 AM.402: 	format:            NV12
> 02:14:32 AM.402: 	YUV mode:          709/Partial
> 02:14:32 AM.403: NV12 texture support not available
> 02:14:32 AM.405: Audio monitoring device:
> 02:14:32 AM.405: 	name: Monitor of GF104 High Definition Audio Controller Digital Stereo (HDMI 2)
> 02:14:32 AM.405: 	id: alsa_output.pci-0000_02_00.1.hdmi-stereo-extra1.monitor
> 02:14:32 AM.405: ---------------------------------
> 02:14:32 AM.407: Failed to load 'en-US' text for module: 'decklink-captions.so'
> 02:14:32 AM.409: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
> 02:14:32 AM.456: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
> 02:14:32 AM.456: No blackmagic support
> 02:14:32 AM.464: v4l2loopback not installed, virtual camera disabled
> 02:14:32 AM.530: FFMPEG VAAPI supported
> 02:14:32 AM.535: [obs-ndi] hello ! (version 4.9.1)
> 02:14:32 AM.535: [obs-ndi] Trying ''
> 02:14:32 AM.535: [obs-ndi] Trying '/usr/lib'
> 02:14:32 AM.535: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
> 02:14:32 AM.536: [obs-ndi] NDI runtime loaded successfully
> 02:14:32 AM.536: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
> 02:14:32 AM.572: VLC found, VLC video source enabled
> 02:14:32 AM.572: ---------------------------------
> 02:14:32 AM.572:   Loaded Modules:
> 02:14:32 AM.572:     vlc-video.so
> 02:14:32 AM.572:     text-freetype2.so
> 02:14:32 AM.572:     rtmp-services.so
> 02:14:32 AM.572:     obs-x264.so
> 02:14:32 AM.572:     obs-transitions.so
> 02:14:32 AM.572:     obs-outputs.so
> 02:14:32 AM.572:     obs-ndi.so
> 02:14:32 AM.572:     obs-filters.so
> 02:14:32 AM.572:     obs-ffmpeg.so
> 02:14:32 AM.572:     linux-v4l2.so
> 02:14:32 AM.572:     linux-pulseaudio.so
> 02:14:32 AM.572:     linux-jack.so
> 02:14:32 AM.572:     linux-decklink.so
> 02:14:32 AM.572:     linux-capture.so
> 02:14:32 AM.572:     linux-alsa.so
> 02:14:32 AM.572:     image-source.so
> 02:14:32 AM.573:     frontend-tools.so
> 02:14:32 AM.573:     decklink-ouput-ui.so
> 02:14:32 AM.573:     decklink-captions.so
> 02:14:32 AM.573: ---------------------------------
> 02:14:32 AM.573: ==== Startup complete ===============================================
> 02:14:32 AM.576: All scene data cleared
> 02:14:32 AM.576: ------------------------------------------------
> 02:14:32 AM.588: [obs-ndi] started A/V threads for source ''
> 02:14:32 AM.588: [obs-ndi] A/V thread for 'NDI™ Source' started
> 02:14:32 AM.590: pulse-input: Server name: 'pulseaudio 14.1'
> 02:14:32 AM.590: pulse-input: An error occurred while getting the source info!
> 02:14:32 AM.591: pulse-am: Server name: 'pulseaudio 14.1'
> 02:14:32 AM.591: pulse-am: Audio format: s32le, 48000 Hz, 2 channels
> 02:14:32 AM.591: pulse-am: Started Monitoring in 'alsa_output.pci-0000_02_00.1.hdmi-stereo-extra1.monitor'
> 02:14:32 AM.594: Switched to scene 'NDI'
> 02:14:32 AM.594: ------------------------------------------------
> 02:14:32 AM.594: Loaded scenes:
> 02:14:32 AM.594: - scene 'NDI':
> 02:14:32 AM.594:     - source: 'NDI™ Source' (ndi_source)
> 02:14:32 AM.594: - scene 'Scene 2':
> 02:14:32 AM.594:     - source: 'Audio Input Capture (PulseAudio)' (pulse_input_capture)
> 02:14:32 AM.594:         - monitoring: monitor and output
> 02:14:32 AM.594:         - filter: 'Gain' (gain_filter)
> 02:14:32 AM.594:         - filter: 'Noise Suppression' (noise_suppress_filter_v2)
> 02:14:32 AM.594:         - filter: 'Noise Suppression 2' (noise_suppress_filter_v2)
> 02:14:32 AM.594:         - filter: 'Limiter' (limiter_filter)
> 02:14:32 AM.594:         - filter: 'Compressor' (compressor_filter)
> 02:14:32 AM.594: ------------------------------------------------
> 02:14:32 AM.646: [obs-ndi] starting NDI main output with name 'OBS'
> 02:14:32 AM.653: [obs-ndi] 'OBS': ndi output started

My main output is enabled and I've even tried filters on screen captures to no avail. I am also dealing exclusively with localhost (127.0.0.1) and virtual bridges that work over localhost (VM vbridges).

Is there a way to directly connect to a peer?

**Comment by someguy736** [comment]
After modifying Avahi-daemon to use DBus I can finally use NDI again. Everything works including local sources. I don't know if this is an avahi issue or an NDI issue or even an OBS issue but for anyone else having this problem you **need** avahi and avahi **needs to use** DBus. If at all possible please remove/add a toggle for any and all dbus dependencies.

**Comment by playaspec** [comment]
It should be added that if you're using obs-studio as a snap package, you have to grant explicit permission for OBS to interface with avahi outside of it's sandbox. Try issuing:

`sudo snap connect obs-studio:avahi-control`

to enable discovery.
