### ISSUE TITLE
NDI source dropdown menu empty

### ISSUE THREAD

**Issue by robertsawko** [Palakis/obs-ndi#629]
Many thanks for open sourcing this plugin and for your work on low-latency real-time streaming through NDI to OBS.

I have setup a Microsoft Surface Pro with OBS Studio, obs-ndi plugin and NDI tools (do I actually need it?). On my personal home network I plug the camera to Ethernet port, set it to DHCP and the tablet is on wifi in the same room as the router. The camera is a PTZOptics NDI|HX camera. At first the camera was not popping up in the dropdown menu of NDI source name, but after restarting the camera and the tablet it did. After selecting low latency experimental mode I could observe very low latency indeed.

Then I moved the camera to the church where as far as I can see the network topology is identical. The tablet and the camera land on the same subnet although they are of course on wireless and Ethernet connection respectively. The building bigger. Despite several restarts and various other attempts I was not able to make the camera appear in the dropdown menu.

Would you be able to advise what might be going wrong? Is there a way to manually specify the IP of the camera in obs-ndi plugin? Is there any NDI, PTZOptics tool that would help your plugin detect the camera. I have tried from another two computers: Mac Book Pro and a desktop plugged into the same network, but to no avail. Is it possible that a PoE injector is causing this mystifying invisibility?

**Comment by robertsawko** [comment]
An update. It seems that the problem is caused by a network switch. Wired network has an additional switch. When I plugged in the camera to the router directly, it was readily available in the dropdown menu. The strange part is that after adding a source., replugging the switch and plugging the camera to the switch instead the existing source was still accessible. It is only the initial detection that is inhibited by the switch.

Please advise. In particular is there a way to manually specify the network location of the camera so that the reliance on automatic detection is not needed.

**Comment by pierreroman** [comment]
Hello Folks,

I'm having similar issues.

I have PC with OBS Studio, obs-ndi plugin and NDI tools installed.
I have setup 2 NDI HX Cameras - 1 android, one iPad over WIFI
1 also have a second PC sending its screen capture using the NDI Screen Capture HX hardwired in an unmanaged switch

On the streaming PC I see ALL NDI feeds using NDI Monitor
![NDI-1](https://user-images.githubusercontent.com/12719812/110992652-31b6a400-8344-11eb-8683-6a4203da6c4b.png)

in OBS the Source Name for my NDI source is empty.

If NDI monitor can see ALL feeds and is on the same machine as OBS why can't OBS see ANY?

**Comment by robertsawko** [comment]
A colleague and I have spent some time debugging the issue. We tried plugging in the camera and PC directly to the switch and that wouldn't work. Plugging both to the router works fine.

I understand from [this](https://support.newtek.com/hc/en-us/articles/218109477-NDI-Discovery-and-Registration) that we're supposed to look for UDP multicast. We've been doing some wiresharking by filtering to field with `224.0.0.251` and we can see when the PC is requesting NDI devices to present themselves but we never see any other traffic. It looks like the switch is filtering that port range?

The switch is Netgear [GS324T](https://support.newtek.com/hc/en-us/articles/218109477-NDI-Discovery-and-Registration) with pretty much all default settings.

The strangest thing of all is that when I use the PTZOptics upgradeV2.8 application in preview mode then that will magically cause the mDNS(?) auto-detection to work. This is a workaround which proven robust so far, but I am worried that until we fix the switch this is going to be unstable.

**Comment by stefankoehne** [comment]
I solved the problem! Windows Firewall was blocking two private connections incoming to OBS Studio.
I edited both rules to "accept connection", but you can also try to disable both rules or disable the whole Windows Defender.

![solution_NDI_HX_Cam](https://user-images.githubusercontent.com/69876166/120789830-66e12580-c532-11eb-9d43-92c4fcd597c0.jpg)

**Comment by robertsawko** [comment]
@stefankoehne can you share a bit more information? Were there any specific ports you had to unblock or were the connections somehow labelled by application? Thanks for sharing.

**Comment by stefankoehne** [comment]
Hi robert! I just went to the windows firewall settings and found the two blocked entries (screenshot above) and allowed them. That simply worked for me. No ports to unblock. 
What more information do you need?

**Comment by robertsawko** [comment]
Sorry, yes, I think my colleague and I got everything and in fact we have an equivalent entry in BitDefender that we're using. I am going to close this.
