### ISSUE TITLE
OBS-NDI windows 10 instillation issue

### ISSUE THREAD

**Issue by fenjam** [Palakis/obs-ndi#63]
Hello! I am having issues installing the NDI plugin for obs on my windows 10 pc. I have a AMD Athlon II x4 645 3.10 GHz processor 16 GB of ram and a nvidia gtx 760 video card. I installed NDI plugin on the pc I wish to use for streaming with no issues. But when I install the NDI plugin on my gaming pc it will not show up in obs no matter how many times I reinstall it. the NDI folder is in the obs studio folder but there is no tool in obs for NDI plugin. Any help would be appreciated thanks :)

**Comment by Sharkdva** [comment]
same issue after upgrade windows 10 to 1709. no problem before
Xeon E3-1230v2, GTX970 (driver  387.92).
ps: works on another hardware w/o nvidia card (notebook to server, server to notebook, or iphone to notebook or server)

**Comment by JustGinger3** [comment]
I'm having the same exact issue. I've tried reinstalling, redownloading, manually moving it into the OBS folder. I've checked YouTube and google for answers. I cant find anything to help. I was hoping to have this setup today. :/

**Comment by Palakis** [comment]
Please:
- Provide OBS logs
- Check if obs-ndi.dll is in OBS' installation folder, under obs-plugins/64bit/ and obs-plugins/32bit/
- Have a look at jakkett's comment here : https://github.com/Palakis/obs-ndi/issues/61

**Comment by Palakis** [comment]
Btw this is a duplicate of #61. Please contribute to existing conversations.

**Comment by r04dw4rri0r** [comment]
Im having issues having NDI show up on my stream pc. Its running a AMD Phenom II x6 1090T. I got it installed on my gaming pc no problem.

**Comment by JustGinger3** [comment]
I finally got mine to work last night. I can post a video of what I did tonight if you’d like.

**Comment by r04dw4rri0r** [comment]
That would be great!

**Comment by Palakis** [comment]
@JustGinger3 Good initiative!

**Comment by JustGinger3** [comment]
@r04dw4rri0r  I'm a bit sick right now so excuse my lack of voice, Here's the video and the link I used. Let me know if you need clarification. I'll end up redoing the video once I'm not as sick.

https://youtu.be/mkQHfP0b-Ns

https://github.com/Palakis/obs-ndi/releases

**Comment by Palakis** [comment]
@fenjam Your CPU doesn't support SSSE3 instructions required for NDI support.
