### ISSUE TITLE
"/verysilent" flag in Windows installer does not accept EULA

### ISSUE THREAD

**Issue by mwmanley** [Palakis/obs-ndi#636]
I have to install this plugin on a series of Windows machines.  The documentation and the command line refers to the "/silent" and "/verysilent" flags, but even when used a dialogue box appears asking to accept the terms of the EULA.  That means our automated installers will balk and die.

Is there a way to give the program a flag to accept the EULA so that we can do scripted installs?

**Comment by mwmanley** [comment]
Ah, the problem is that the ndi-runtime-4.5.1-Windows.exe flags are getting swallowed by the preferred installer.  Running with /verysilent against that works.

**Comment by tt2468** [comment]
Closing since this appears to be resolved.
