### ISSUE TITLE
Outdated NDI Runtime Provided

### ISSUE THREAD

**Issue by Tenisan** [Palakis/obs-ndi#637]
It looks like the NDI Runtime provided with the 4.9.0 release is outdated. NDI signals from some other NDI-based software can not be loaded (in this case for us, it's Sienna NDI Processing Engine). When I copy the NDI runtime dll's that are installed with NDI tools from the NDI Tools sub-folder and replace the ones in the main NDI Runtime folder everything works straight away. So I'd say the download for the Runtime probably just needs to be updated to the latest from Newtek.

Thanks for producing a great plugin! 👍 👍

**Comment by tt2468** [comment]
obs-ndi 5.0.0 will come with the NDIlib 5 headers.
