### ISSUE TITLE
Audio delay while streaming with NDI

### ISSUE THREAD

**Issue by PoGeekenstein** [Palakis/obs-ndi#64]
having a audio delay with ndi. video is working great. though any fixes?

**Comment by Rawdee** [comment]
I am having the same issue, audio/video goes out of sync after a period of time. 

If I restart OBS on the Gaming PC (stream is kept running on Streaming PC), it is in sync again.

I've seen the text that says: "Bug fix: improper timestamp handling in source and main output (this can fix many sync issues)" in the description, but I am not sure if that is something I need to investigate?

**Comment by Palakis** [comment]
@PoGeekenstein Please provide more details, including logs of the OBS instances involved with NDI.

@Rawdee You may want to contribute to the discussion in #60, as your situation seems similar.
