### ISSUE TITLE
Green screen instead of image from streaming PC

### ISSUE THREAD

**Issue by skelaw** [Palakis/obs-ndi#65]
Hi!
Gaming PC:
 i5 3470
GTX 970
8GB RAM
Streaming PC:
intel E5400
Probably 4gb ram

So I conected both pc's to router (horizon), lauched comps then instaled OBS with OBS-NDI plugin. I restarted computers, configured settings. On GamingPC i configured scene, enabled NDI. NDI source showed on StreamPC. I added it to scene but instead of video image i got green (box? screen?) thing. 

tl;dr
**Instead of image** from gaming pc i got **green screen** on streaming pc.

**Comment by 009infinity** [comment]
Same thing happened to me
