### ISSUE TITLE
[Question] NVENC / leveraging hardware encoding

### ISSUE THREAD

**Issue by Neo-Desktop** [Palakis/obs-ndi#653]
Hello!

Thank you for writing such a wonderful plugin, I've been utilizing NDI for my obs streaming setup as of lately.

Some background: 

My setup currently consists of two fairly performant PCs connected via multiple 10-gigabit network interfaces to a 10 port gigabit network switch. The sending system has 3 interfaces, the receiving station has 2.

I use multiple "dedicated" NDI filter outputs in OBS to broadcast captures from the sending system - one stream for video, two streams for audio (microphone and application)

My concern is that during some high-intensity graphics applications, the encoder performance of the streaming system tanks incredibly fast - so much so that the receiving station's preview turns into a slideshow.

I do, however, notice much better performance using the NDI HX Screen Capture from NDI.

For all intents and purposes, I could use the NDI HX Screen Capture application as my main driver; however, I much prefer the per-application capture and overall flexibility provided by OBS.

My main question is as follows:
Does the obs-ndi plugin leverage hardware encoding? Is there a way to gain the same performance I see with the NDI HX Screen Capture while using obs-ndi?

Thank you for your consideration, please advise

**Comment by tt2468** [comment]
Unfortunately, we don't have any control over NDIlib's hardware encoding functionality. There will likely be better support in 5.0.0, but its functionality will still be a black box.

Regarding HX, I believe that NDIlib supports hardware decoding on Windows and Mac. I'm not aware of any hardware decoding or encoding functionality being used for normal NDI.
