### ISSUE TITLE
NDI won't show up

### ISSUE THREAD

**Issue by flexrp** [Palakis/obs-ndi#659]
I have an AMD Phenom(TM) 9750 Quad-Core Processor 2.40GHZ
my obs ndi won't show up and I installed and reinstalled it and reinstalled obs. Can someone help me get it to show up so I can stream

**Comment by TrustMeICan** [comment]
Do you mean there is no "NDI™ Output settings" under Tools in OBS?
You need to re-install obs-ndi after you re-install obs. Does obs-ndi.dll exist in obs-plugins\64-bit of your obs-studio installation folder (e.g. C:\Program Files\obs-studio\obs-plugins\64bit)? Have you installed NDI Runtime or NDI Tools?
You may want to upload your OBS logs (OBS > Help > Log Files).

**Comment by flexrp** [comment]
@TrustMeICan  here is my log file [https://obsproject.com/logs/Un9bgzc9WpqXtRp2](https://obsproject.com/logs/Un9bgzc9WpqXtRp2)

**Comment by TrustMeICan** [comment]
13:12:29.944: [obs-ndi] hello ! (version 4.9.0)
13:12:29.944: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
13:12:29.944: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
13:12:29.955: [obs-ndi] NDI runtime loaded successfully
13:12:29.955: [obs-ndi] CPU unsupported by NDI library. Module won't load.
13:12:29.955: Failed to initialize module 'obs-ndi.dll'

**Comment by flexrp** [comment]
@TrustMeICan is there a way to correct it or not

**Comment by TrustMeICan** [comment]
> @TrustMeICan is there a way to correct it or not

No, your CPU is lacking features that NDI requires. Moreover, a CPU from 2008 doesn't look promising.


> NDI, when running on x86 architectures, requires CPUs that include the SSSE3 instruction set. Most Intel CPU designs starting in 2006 have this instruction set, AMD added support starting in 2011.

https://en.wikipedia.org/wiki/Network_Device_Interface#CPU_architecture_support

**Comment by flexrp** [comment]
is there a workaround or not. or what would be a good CPU to upgrade to

**Comment by TrustMeICan** [comment]
No workaround with your current CPU. The 22-year old model is simply too old for NDI. You will have to upgrade that. Any non-dinosaur CPUs will be able to support NDI (from the Wikipedia, Intel CPUs after 2006 and AMD CPUs after 2011). You don't need high-ended ones to run NDI smoothly (given that you are not planning some demanding work).

**Comment by flexrp** [comment]
ok

**Comment by flexrp** [comment]
@TrustMeICan Could I use a capture card

**Comment by TrustMeICan** [comment]
> @TrustMeICan Could I use a capture card

Could you use a capture card for what?

**Comment by flexrp** [comment]
@TrustMeICan instead of ndi

**Comment by flexrp** [comment]
I have a laptop that supports ndi but since I can't use it then could I use a capture card

**Comment by TrustMeICan** [comment]
Probably yes, though you have given too little context. What causes your concern?

**Comment by flexrp** [comment]
I have an older pc that use for coding and I want to use my laptop to stream off of it so I don't put all that stress on my older pc. I would get a new one but I don't have the money to put toward a new pc right now with graphics cards being so expensive and other parts getting that way @TrustMeICan

**Comment by TrustMeICan** [comment]
That should work

**Comment by flexrp** [comment]
Thanks 👍
