### ISSUE TITLE
NDI Output Settings - Win OBS

### ISSUE THREAD

**Issue by gogaming** [Palakis/obs-ndi#662]
When opening the "NDI Output Settings" panel on OBS the "Main Output" and "Preview Output" text entry boxes are not opened fully to see the text in them, bottom parts of the words are cut off.

![ndi_output_settings-obs_windows_text_box_error-1](https://user-images.githubusercontent.com/50048675/120674692-42cb0900-c48c-11eb-9912-f94cd48bef66.jpg)

**Comment by playaspec** [comment]
Have you changed any fonts/point sizes in your system?

**Comment by tt2468** [comment]
This is due to scaling issues, it may be fixed in 5.0.0
