### ISSUE TITLE
NDI Sources Missing From Dropdown

### ISSUE THREAD

**Issue by robertmain** [Palakis/obs-ndi#663]
I have a PTZOptics NDI camera that shows up in the NDI sources dropdown just fine, however - another PC on the network running NDI Scan Converter isn't showing up in the list of available NDI sources for OBS, but shows up just fine in NDI Studio Monitor. Is that a specific version that this plugin supports or something?

**Comment by tellustheguru** [comment]
Same here but with Minrray PTZ NDI camera.

**Comment by playaspec** [comment]
Check your firewall settings and make sure you're not blocking multicast traffic. NDI uses mDNS to do discovery. Check to see if you can see the announcements using a tool like Bonjour Browser.

**Comment by robertmain** [comment]
@playaspec Yeah, I tried that - but the sources _do_ show up in Studio Monitor, so the traffic is clearly making it into the computer. Just not the OBS plugin

**Comment by tellustheguru** [comment]
I also have Wirecast installed on the computer and have no problem to find sources.

**Comment by playaspec** [comment]
Check your OBS logs. What version of the NDI library and the version of the OBS-NDI plugin?

**Comment by tellustheguru** [comment]
Log dump:

22:17:17.675: [obs-ndi] hello ! (version 4.9.0)
22:17:17.675: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
22:17:17.675: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
22:17:17.678: [obs-ndi] NDI runtime loaded successfully
22:17:17.687: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)

**Comment by lcluster** [comment]
I am also getting this on Linux mint 20.2 with PTZ Optics NDI cameras not showing up.  I can produce an NDI stream from OBS, I just cannot use an NDI stream as a source.

10:11:10 AM.716: CPU Name: Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz
10:11:10 AM.716: CPU Speed: 1987.773MHz
10:11:10 AM.716: Physical Cores: 4, Logical Cores: 4
10:11:10 AM.716: Physical Memory: 5820MB Total, 3363MB Free
10:11:10 AM.716: Kernel Version: Linux 5.4.0-89-generic
10:11:10 AM.716: Distribution: "Linux Mint" "20.2"
10:11:10 AM.716: Session Type: x11
10:11:10 AM.717: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
10:11:10 AM.717: Portable mode: false
10:11:10 AM.791: OBS 27.1.3 (linux)
10:11:10 AM.791: ---------------------------------
10:11:10 AM.791: ---------------------------------
10:11:10 AM.791: audio settings reset:
10:11:10 AM.791: 	samples per sec: 48000
10:11:10 AM.791: 	speakers:        2
10:11:10 AM.802: ---------------------------------
10:11:10 AM.802: Initializing OpenGL...
10:11:10 AM.835: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 2500 (IVB GT1)
10:11:10 AM.835: OpenGL loaded successfully, version 4.2 (Core Profile) Mesa 21.0.3, shading language 4.20
10:11:10 AM.851: ---------------------------------
10:11:10 AM.851: video settings reset:
10:11:10 AM.851: 	base resolution:   1440x900
10:11:10 AM.851: 	output resolution: 1152x720
10:11:10 AM.851: 	downscale filter:  Lanczos
10:11:10 AM.851: 	fps:               30/1
10:11:10 AM.851: 	format:            NV12
10:11:10 AM.851: 	YUV mode:          709/Partial
10:11:10 AM.851: NV12 texture support not available
10:11:10 AM.855: Audio monitoring device:
10:11:10 AM.855: 	name: Default
10:11:10 AM.855: 	id: default
10:11:10 AM.855: ---------------------------------
10:11:10 AM.856: Failed to load 'en-US' text for module: 'decklink-captions.so'
10:11:10 AM.858: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
10:11:10 AM.988: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
10:11:10 AM.988: No blackmagic support
10:11:10 AM.997: [obs-browser]: Version 2.16.3
10:11:10 AM.997: [obs-browser]: CEF Version 87.1.12+g03f9336+chromium-87.0.4280.88
10:11:11 AM.020: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
10:11:11 AM.020: 
10:11:11 AM.020: FFMPEG VAAPI supported
10:11:11 AM.023: [obs-ndi] hello ! (version 4.9.1)
10:11:11 AM.024: [obs-ndi] Trying ''
10:11:11 AM.024: [obs-ndi] Trying '/usr/lib'
10:11:11 AM.024: [obs-ndi] Found NDI library at '/usr/lib/libndi.so.4'
10:11:11 AM.024: [obs-ndi] NDI runtime loaded successfully
10:11:11 AM.024: [obs-ndi] NDI library initialized successfully (NDI SDK LINUX 00:05:02 Apr  1 2020 4.5.1)
10:11:11 AM.040: VLC found, VLC video source enabled
10:11:11 AM.040: ---------------------------------
10:11:11 AM.040:   Loaded Modules:
10:11:11 AM.040:     vlc-video.so
10:11:11 AM.040:     text-freetype2.so
10:11:11 AM.040:     rtmp-services.so
10:11:11 AM.040:     obs-x264.so
10:11:11 AM.041:     obs-vst.so
10:11:11 AM.041:     obs-transitions.so
10:11:11 AM.041:     obs-outputs.so
10:11:11 AM.041:     obs-ndi.so
10:11:11 AM.041:     obs-libfdk.so
10:11:11 AM.041:     obs-filters.so
10:11:11 AM.041:     obs-ffmpeg.so
10:11:11 AM.041:     obs-browser.so
10:11:11 AM.041:     linux-v4l2.so
10:11:11 AM.041:     linux-pulseaudio.so
10:11:11 AM.041:     linux-jack.so
10:11:11 AM.041:     linux-decklink.so
10:11:11 AM.041:     linux-capture.so
10:11:11 AM.041:     linux-alsa.so
10:11:11 AM.041:     image-source.so
10:11:11 AM.041:     frontend-tools.so
10:11:11 AM.041:     decklink-ouput-ui.so
10:11:11 AM.041:     decklink-captions.so
10:11:11 AM.041: ---------------------------------
10:11:11 AM.041: ==== Startup complete ===============================================
10:11:11 AM.044: All scene data cleared
10:11:11 AM.044: ------------------------------------------------
10:11:11 AM.052: pulse-input: Server name: 'pulseaudio 13.99.1'
10:11:11 AM.052: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
10:11:11 AM.052: pulse-input: Started recording from 'alsa_output.usb-Logitech_Inc._Logitech_USB_Headset_H340-00.analog-stereo.monitor'
10:11:11 AM.057: pulse-am: Prevented feedback-loop in 'default'
10:11:11 AM.057: [Loaded global audio device]: 'Desktop Audio'
10:11:11 AM.057:     - monitoring: monitor and output
10:11:11 AM.060: [obs-ndi] started A/V threads for source ''
10:11:11 AM.061: [obs-ndi] A/V thread for 'c1' started
10:11:11 AM.061: Switched to scene 'Scene'
10:11:11 AM.061: ------------------------------------------------
10:11:11 AM.061: Loaded scenes:
10:11:11 AM.061: - scene 'Scene':
10:11:11 AM.061:     - source: 'c1' (ndi_source)
10:11:11 AM.061: ------------------------------------------------
10:11:13 AM.598: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
10:11:13 AM.598:

**Comment by tt2468** [comment]
We just rely on NDIlib's finder instance. The extra IPs option will be included in version 5.0.0 for users having trouble with NDIlib's mDNS implementation working correctly.
