### ISSUE TITLE
NDI Source: "Allow hardware accelation" not working after start of OBS Studio

### ISSUE THREAD

**Issue by dj9pz** [Palakis/obs-ndi#664]
I'm running OBS Studio 27.0.1 and obs-ndi 4.9.0 on Windows 10. I added an "NDI Source" to a scene and use "NDI HX Camera" on iPhone as a source.

"Allow hardware acceleration" is enabled, but seems to not be used after start of OBS Studio:

- "Allow hardware acceleration" is enabled
- Start OBS Studio, CPU usage is 14-17%
- Disable "Allow hardware acceleration" in the NDI Source and save
- CPU usage is unchanged at 14-17%
- Enable "Allow hardware acceleration" in the NDI Source and save
- CPU usage drops to 3-6% (and stays there)
- Restart OBS Studio
- CPU usage is back at 14-17%

Settings in NDI Source:
![image](https://user-images.githubusercontent.com/6215603/121772669-1774a800-cb77-11eb-9b83-27c6649d5f23.png)

**Comment by Aerglonus** [comment]
_**off-topic**_  but is your HX Camera source showing properly? I've been trying to use NDI HX Camera with an iPhone 6 / iPad Pro 2019 NDI detects both devices but doesn't show anything not even a black screen

**Comment by dj9pz** [comment]
@Aerglonus Yes, it is generally working, as long as there is proper network connectivity. In case of connection loss, I did encounter problems for it to reconnect. For my purposes (multi camera live streams) NDI HX Camera is not yet ready for "prime time" as it lacks stability and many features (remote control, white balance, fast reconnect) which DroidCam OBS offers.

**Comment by tt2468** [comment]
This setting only tells NDI that it should use hardware acceleration if it thinks that it will help. It's unfortunately not any kind of guarantee.

**Comment by JimmyPauwaert** [comment]
I confirm this issue. After OBS start the use hardware acceleration (for our NDI sources) are not honored. Just opening the source and saving fixes it. (Drops our cpu usage by 80% !)

**Comment by ogmkp** [comment]
Not working here, no nvdec hardware acceleration with manipulations related here. OBS 29.1.3, Debian 12.
An NDI 5 SDK issue ?

**Comment by tt2468** [comment]
> Not working here, no nvdec hardware acceleration with manipulations related here. OBS 29.1.3, Debian 12. An NDI 5 SDK issue ?

I'm not aware of any official documentation from NewTek that describes what the flag does, or how it works. It's simply a toggle we turn on in the lib and have otherwise no other feedback for. Who knows if it's even hooked up to anything, since there's no info about it.

**Comment by ogmkp** [comment]
The NDI documentation says:
```
NDI® Lib is heavily optimized (much of it is written in assembly). While it detects available architecture and uses
the best path it can, the minimum required SIMD level is SSSE3 (introduced by Intel in 2005). The NDI library
running on ARM platforms requires NEON support. To the degree possible, hardware acceleration of streams uses
GPU-based fixed function pipelines for decompression and is supported on Windows, macOS, iOS, tvOS platforms;
all GPUs on these platforms are supported with special case optimized support for Intel QuickSync and nVidia.
However, this is not required, and we will always fall back to software-based compression and decompression.
```

Thats means Linux don't benefit of the GPU offloading decoding, pray for the NDI team to implement this feature.

**Comment by burtmacklin16** [comment]
> The NDI documentation says:
> 
> ```
> NDI® Lib is heavily optimized (much of it is written in assembly). While it detects available architecture and uses
> the best path it can, the minimum required SIMD level is SSSE3 (introduced by Intel in 2005). The NDI library
> running on ARM platforms requires NEON support. To the degree possible, hardware acceleration of streams uses
> GPU-based fixed function pipelines for decompression and is supported on Windows, macOS, iOS, tvOS platforms;
> all GPUs on these platforms are supported with special case optimized support for Intel QuickSync and nVidia.
> However, this is not required, and we will always fall back to software-based compression and decompression.
> ```
> 
> Thats means Linux don't benefit of the GPU offloading decoding, pray for the NDI team to implement this feature.

Have there been any updates from NDI whether GPU decoding has been implemented on Linux at this time?

**Comment by ogmkp** [comment]
Nothing new. There are NDI 6 coming but still in closed alpha test.

**Comment by paulpv** [comment]
We send `<ndi_hwaccel enabled=\"true\"/>`, which is all we know to do according to the documentation:
https://github.com/obs-ndi/obs-ndi/blob/master/src/obs-ndi-source.cpp#L604
