### ISSUE TITLE
NDI 5

### ISSUE THREAD

**Issue by jmcc94** [Palakis/obs-ndi#668]
Now that NDI 5 has been released, what is the timeline for it being integrated into this plugin?

**Comment by Mazecreator** [comment]
I am running NDI 5 now with this plug-in.... So it seems compatible...

**Comment by jmcc94** [comment]
I was more thinking about the improvements that exist within NDI 5, and getting the plugin to take advantage of them...or is more of a case of getting the updated ndi-runtime (if it exists?)

**Comment by Mazecreator** [comment]
Okay, I installed the latest tool set, I don't know if there are things you need to do in the plugin to use the Bridge and remote connections as they appear to be configured at the Toolset level, maybe there is a way to integrate some of that into the drive, but might give the same functionality the toolset offers.  I will leave it to @Palakis to determine if there is an advantage to integrating.  I am sure the NDI plugin is using the newest NDI 5 drivers, so we should at least get that advantage right away.  Maybe the only think that might need to change is the Audio NDI features, not sure if that is transparent to the API.

**Comment by walterav1984** [comment]
NDI5 is probably part of the obsplugin rewrite which started a day before this issue, not a timeline but atleast you can follow the progress:
https://github.com/Palakis/obs-ndi/tree/rewrite
