### ISSUE TITLE
Broken in OBS 0.16.2 (macOS 10.13.1)

### ISSUE THREAD

**Issue by badloop** [Palakis/obs-ndi#67]
I've installed the latest OBS and the latest version of this plugin and I'm not seeing any options for NDI output or NDI sources.

**Comment by Palakis** [comment]
I'd need a bit more details, please. Can you provide detailed OS and OBS info, along with OBS logs?

**Comment by Herolordman** [comment]
Im using it in 10.13.1 (gaming on pc, and streaming on mac) and it works (except the framerate is very low and sluggish even in the preview window on mac.

**Comment by sublime24** [comment]
Im trying to install the newest version of obs-ndi 4.1.3 on my mac High Sierra (10.13.1 (17B1003)) and the install process runs and completes with out error but the obs studio never starts. It does not seem to install properly as there is nothing in my applications folder.

**Comment by MahdDogg** [comment]
I'm running OS 10.11 Installed OBS Studio then the pkg as directed. OBS starts fine without the plugin, however once plugin 4.1.3 is installed OBS Studio will not launch and I get an error "Failed to find locale/en-us.ini" I checked in the application support folder and in the plugin folder there the file existed.

Removing the plugin allows OBS to start without issue.

**Comment by Palakis** [comment]
Thanks for your feedbacks. I tagged the macOS builds as Experimental again because of the number of issues on that platform.
I'm currently investigating the macOS problems.

**Comment by narcogen** [comment]
FYI-- badloop the latest OBS for Mac is 20.1, not 0.16.2.

**Comment by Jurik81** [comment]
I installed obs 22.0.3 and obs-ndi-4.5.2.pkg on my mac osx 10.13.6 and I can not see a NDI source in obs.
Actually I'm not in my network, but it should be there for setup anyway, shouldn't it?

**Comment by narcogen** [comment]
Downgrade to 4.5.1, there is a bug with 22.0.3 and 4.5.2.
