### ISSUE TITLE
Suggestion: Allow Audio, Video, or Both Selectable as Source

### ISSUE THREAD

**Issue by jasonmvp** [Palakis/obs-ndi#674]
On the source OBS Studio, allow the user to select whether they want to send an audio channel, a video channel, or both.  The audio sent with NDI often cause the receiving OBS Studio to complain about Audio Buffer issues.  It would be nice to just disable the audio completely so it's not even sent.

Please consider.

**Comment by Mazecreator** [comment]
Another use case is when you use the audio input on one of the cameras for a microphone, but in some scenes that camera is not in the scene.  This means you have to put the camera into the scene for just the audio, usually the image gets rendered but not seen using CPU.

**Comment by tt2468** [comment]
This will be a feature in 5.0.0
