### ISSUE TITLE
Extreme latency between OBS machine and NDI source machine

### ISSUE THREAD

**Issue by texasharley** [Palakis/obs-ndi#677]
One machine is running NDI 4.x screen capture so PowerPoint can be brought into OBS.  Other machine is running OBS with the obs-ndi plugin.  It sometimes takes 1 to 5 minutes for the NDI source to show up in OBS.  We have tried turning off firewalls on both machines, ensuring both network connections are set in Windows 10 to use Private Network and not Public.  Issue still exists however.

**Comment by texasharley** [comment]
This is on a Ubiquiti Unifi network (router and switch) so I'm wondering if the problem may be there.

**Comment by dingus9** [comment]
> Did you enable any 'enhancements' on the ubnt side?

What enhancements would impact NDI positively or negatively? Running NDI on a ubnt any tips might help with some delay im trying to clear up.

**Comment by ToeiRei** [comment]
@dingus9 if it's not running I usually make sure there are no 'improvements' like broadcast blocking or even client insulation as you do want to make sure the network is NOT interfering with the NDI setup. When you got it running, you may do broadcast enhancements and all that and see how/when things break.

**Comment by texasharley** [comment]
This issue was resolved.  Latency mode was set to "Low (experimental)".  Changing back to normal setting resolved the issue.
