### ISSUE TITLE
OBS BrowserSource - No alpha channel when sending through NDI Output

### ISSUE THREAD

**Issue by cocoichiban** [Palakis/obs-ndi#68]
Hi, first just want to say thanks so much for this NDI add on to OBS, it's amazing.

I have an issue where I need to send a BrowserSource through NDI with transparency. Unfortunately, when I send a captured BrowserSource (which has a transparent background) through NDI Output in OBS, the backgound just shows as a black background.

This is possible to do in vMix using their Web Browser source, and then setting the Output Format as ARGB32 and turning NDI output on. However, the issue there is that the Web Browser source in vMix is not nearly as good as the one in OBS, we have run into a multitude of issues when trying to run animations through the vMix Browser Source, but runs completely fine in OBS.

It would be insanely helpful if it were possible to send out this BrowserSource with transparency through NDI Output in OBS. 
Is this possible? Thanks for any help.

**Comment by Palakis** [comment]
Hi @cocoichiban, thanks for your feedback.
Frames sent to OBS' main output are composited over a black background, so I can't really do something about it.
However, you can use the "Dedicated Output" filter of obs-ndi. Simply add a new "Dedicated NDI Output" filter to the BrowserSource, name it and click OK. It will then appear as an ndi source on the network.

**Comment by cocoichiban** [comment]
Thank you so much @Palakis for the super timely response, and thanks even more so for this solution. I had no idea that there was a dedicated ndi output filter available for sources. That is absolutely incredible and works exactly as we need it! I truly cant express enough how helpful this is, thank you again for all of your work.
