### ISSUE TITLE
Runtime Website is down

### ISSUE THREAD

**Issue by ankit-gautam-pyxis** [Palakis/obs-ndi#680]
https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

Can we have this file hosted on github also for reliability

![Capture](https://user-images.githubusercontent.com/77270664/131795801-8c52b9cd-7e74-4fe1-958c-1f9b40a81329.PNG)

**Comment by 4p3rtur3** [comment]
I would recommend to use the official "mirror" --> https://www.ndi.tv/tools/ 
NDI 5 SDK should be downward compatible.

**Comment by tt2468** [comment]
It is back up now.
