### ISSUE TITLE
NDI for MacOS fails

### ISSUE THREAD

**Issue by bryanosborne** [Palakis/obs-ndi#682]
After installing obs-ndi-4.9.0-macOS.pkg on Apple M1 running macOS 11.5.2, when starting OBS 27.0.1 (64-bit), the following message is received:

NDI Runtime not found.  Download the installer here: https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

That site doesn't exist/respond.

**Comment by reaperblog** [comment]
same problem for me.

**Comment by spice0814** [comment]
same issue.

**Comment by filimonel** [comment]
Same issue for me aswell. I raised the issue last week and no reply

**Comment by tt2468** [comment]
Site is back up now.

**Comment by Brayyy** [comment]
Despite installing ndi-runtime-5.0.10.1-macOS.pkg and obs-ndi-4.9.0-macOS.pkg, I had a similar issue, with OBS failing with "NDI™ Runtime not found", logs showing:

```
21:13:24.032: [obs-ndi] hello ! (version 4.9.0)
21:13:24.032: [obs-ndi] Trying ''
21:13:24.032: [obs-ndi] Trying '/usr/lib'
21:13:24.032: [obs-ndi] Trying '/usr/local/lib'
21:13:24.032: [obs-ndi] Can't find the NDI library
21:13:25.625: Failed to initialize module 'obs-ndi.so'
```

I was able to resolve my problems by copying the dylib file to the file OBS is seeking.

```bash
cp /usr/local/lib/libndi.dylib /usr/local/lib/libndi.4.dylib
```
