### ISSUE TITLE
Streaming PC not Finding Main Output from Main PC

### ISSUE THREAD

**Issue by SoftRedina** [Palakis/obs-ndi#683]
When I turn on Main Output from ''NDI Output Settings'' on my main PC, my streaming PC won't receving any source from it in ''NDI Source'' properties.

**Comment by snaildos** [comment]
Same.

**Comment by cyclemat** [comment]
check if your network working on gigabit second check your firewall dont set it to open on windows deinstall all firewalls use the defender make the same job

**Comment by qualk** [comment]
I'm having this issue.

**Comment by tt2468** [comment]
This will be fixed by allowing the Extra IPs parameter to be configured in NDI in 5.0.0
