### ISSUE TITLE
Cannot edit NDI source properties

### ISSUE THREAD

**Issue by troliver** [Palakis/obs-ndi#69]
Hello,

Apologies is this is either simple or duplicated, I've had a read but can't see anything about it.

I've installed the NDI plugin, and it loads fine, and I can see a source option called 'NDI Source', so far so good, but when I try and add the source, all of the options in the properties window are inoperable. They are not greyed out as if they are inaccessible, when I hover over them they change colour slightly as they should, but none of them work. The drop down menu doesn't drop down, tick boxes don't tick, and the NDI.NewTek.com, Defaults, Ok buttons don't click. The only button that works is the x in the corner and the cancel button of the window.

Any ideas what the issue is here?

Here is the log file:

14:25:51.220: CPU Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
14:25:51.220: CPU Speed: 3392MHz
14:25:51.220: Physical Cores: 4, Logical Cores: 8
14:25:51.220: Physical Memory: 16348MB Total, 10656MB Free
14:25:51.220: Windows Version: 6.1 Build 7601 (revision: 23796; 64-bit)
14:25:51.220: Running as administrator: false
14:25:51.221: Aero is Disabled
14:25:51.221: Portable mode: false
14:25:51.232: OBS 20.1.3 (64bit, windows)
14:25:51.233: ---------------------------------
14:25:51.234: ---------------------------------
14:25:51.234: audio settings reset:
14:25:51.234: 	samples per sec: 44100
14:25:51.234: 	speakers:        2
14:25:51.237: ---------------------------------
14:25:51.237: Initializing D3D11...
14:25:51.237: Available Video Adapters: 
14:25:51.239: 	Adapter 1: AMD Radeon HD 6450
14:25:51.239: 	  Dedicated VRAM: 1057685504
14:25:51.239: 	  Shared VRAM:    4026531840
14:25:51.240: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
14:25:51.240: 	  output 2: pos={-1920, 0}, size={1920, 1080}, attached=true
14:25:51.240: 	  output 3: pos={1920, 0}, size={1920, 1080}, attached=true
14:25:51.260: Loading up D3D11 on adapter AMD Radeon HD 6450 (0)
14:25:51.268: D3D11 loaded successfully, feature level used: 45056
14:25:52.591: ---------------------------------
14:25:52.591: video settings reset:
14:25:52.591: 	base resolution:   1280x950
14:25:52.591: 	output resolution: 960x712
14:25:52.591: 	downscale filter:  Bicubic
14:25:52.591: 	fps:               60/1
14:25:52.591: 	format:            NV12
14:25:52.593: Audio monitoring device:
14:25:52.593: 	name: Default
14:25:52.593: 	id: default
14:25:52.593: ---------------------------------
14:25:52.597: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
14:25:52.605: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
14:25:52.613: [AMF] Encountered Exception during AMF initialization: Unable to load 'amfrt64.dll', error code 126.
14:25:52.613: Failed to initialize module 'enc-amf.dll'
14:25:52.651: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
14:25:52.652: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
14:25:52.654: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
14:25:52.655: Failed to load 'en-US' text for module: 'obs-browser.dll'
14:25:52.655: [browser_source: 'Version: 1.29.0']
14:25:52.671: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
14:25:52.671:  (126)
14:25:52.674: [obs-ndi] hello ! (version 4.1.3)
14:25:52.674: [obs-ndi] Trying 'C:\Program Files\NewTek\NewTek NDI Redist\v3'
14:25:52.674: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NewTek NDI Redist/v3/Processing.NDI.Lib.x64.dll'
14:25:52.678: [obs-ndi] NDI runtime loaded successfully
14:25:52.685: [obs-ndi] NDI library initialized successfully
14:25:53.542: Couldn't find VLC installation, VLC video source disabled
14:25:53.559: No blackmagic support
14:25:53.576: [Media Foundation encoder]: plugin is disabled for performance reasons on Windows versions prior to 8
14:25:53.677: ---------------------------------
14:25:53.677:   Loaded Modules:
14:25:53.677:     win-wasapi.dll
14:25:53.677:     win-mf.dll
14:25:53.678:     win-dshow.dll
14:25:53.678:     win-decklink.dll
14:25:53.678:     win-capture.dll
14:25:53.678:     vlc-video.dll
14:25:53.678:     text-freetype2.dll
14:25:53.678:     rtmp-services.dll
14:25:53.678:     obs-x264.dll
14:25:53.678:     obs-vst.dll
14:25:53.678:     obs-transitions.dll
14:25:53.678:     obs-text.dll
14:25:53.678:     obs-qsv11.dll
14:25:53.678:     obs-outputs.dll
14:25:53.678:     obs-ndi.dll
14:25:53.678:     obs-filters.dll
14:25:53.678:     obs-ffmpeg.dll
14:25:53.678:     obs-browser.dll
14:25:53.678:     image-source.dll
14:25:53.679:     frontend-tools.dll
14:25:53.679:     enc-amf.dll
14:25:53.679:     coreaudio-encoder.dll
14:25:53.679: ---------------------------------
14:25:53.679: ==== Startup complete ===============================================
14:25:53.685: All scene data cleared
14:25:53.685: ------------------------------------------------
14:25:53.704: [obs-ndi] video thread for 'NDI™ Source' started
14:25:53.705: [obs-ndi] started A/V threads for source '' at addr ''
14:25:53.705: [obs-ndi] audio thread for 'NDI™ Source' started
14:25:53.722: Switched to scene 'Scene'
14:25:53.723: ------------------------------------------------
14:25:53.723: Loaded scenes:
14:25:53.723: - scene 'Scene':
14:25:53.723:     - source: 'R' (browser_source)
14:25:53.723:     - source: 'Logo' (image_source)
14:25:53.724:     - source: 'NDI™ Source' (ndi_source)
14:25:53.724: ------------------------------------------------
14:27:41.730: User Removed source 'NDI™ Source' (ndi_source) from scene 'Scene'
14:27:41.812: [obs-ndi] video thread for 'NDI™ Source' completed
14:27:41.815: [obs-ndi] audio thread for 'NDI™ Source' completed
14:28:05.129: [obs-ndi] video thread for 'NDI™ Source' started
14:28:05.130: [obs-ndi] started A/V threads for source '' at addr ''
14:28:05.130: [obs-ndi] audio thread for 'NDI™ Source' started
14:28:05.134: User added source 'NDI™ Source' (ndi_source) to scene 'Scene'

**Comment by Palakis** [comment]
@troliver Have you solved this issue?
