### ISSUE TITLE
Compatibility issue with latest OBS - NDI video 1000ms out of sync

### ISSUE THREAD

**Issue by simplified-life** [Palakis/obs-ndi#693]
I think we may have a compatibility issue with the newer version of OBS and the OBS-NDI plugin.

In 27.1.1 the NDI sources are out of sync by approximately 1000-1300 milliseconds. This number isn't 100% consistent and can fluctuate by about 300 milliseconds as opposed to the usual  30 milliseconds I experience. I had to put three video delay buffers to get this1300  total and to get the lip-sync remotely reasonable for my livestream on the weekend.
I have NDI studio installed and so I checked whether the video feeds were in sync with this on the same computer. They were perfect (within 30 milliseconds). In OBS 27.1.1 one video feed is always ~1000 milliseconds behind the other with filters on or with no filters. This is the same with both source timing and network timing.
To fix the issue all I did was install OBS 27.0.1 with no other changes and the video feeds were both back in sync.

This doesn't give me confidence that future versions of OBS will be compatible with this plugin.  I tried to raise an issue with them (https://github.com/obsproject/obs-studio/issues/5452) as it is always out by ~1000ms which seems like a buffer, but they need more details if the problem is their end. 

Have attached log files
[logs.zip](https://github.com/Palakis/obs-ndi/files/7421906/logs.zip)

**Comment by IonicEcko** [comment]
Ah this would explain the massive latency problems I was having with NDI recently.

Glad to see someone found the cause. Am somewhat concerned that this is unlikely to be addressed though given there's been little to no visible work on the rewrite for 4 months. I do hope I'm wrong, using an NDI stream is so much better than just sending the entire monitor which is all the NDI software itself allows for.

**Comment by simplified-life** [comment]
Okay. So now I'm on OBS 27.1.3 and I used the low-latency mode in the NDI source properties I'm all fixed. 10ms video latency and all sources in sync to the millisecond. This [post was helpful ](https://github.com/Palakis/obs-ndi/issues/691#issuecomment-945382359)
