### ISSUE TITLE
Latency between MacOS to display on PC greater than PC to PC

### ISSUE THREAD

**Issue by majorpoop** [Palakis/obs-ndi#694]
Hello thank you for taking the time for your help, and I really love this plugin for getting my workflow into VR. For a time, I was running the plugin on Bootcamp (dual boot iMac Pro to Windows) capturing my screen with mouse in Bootcamp, and picking up the feed in Studio Monitor on my VR PC with nearly zero lag. I switched back to MacOS temporarily and tried Scan Converter, but can't seem to get anything but a choppy feed, and the mouse displaying stuck in one spot on Studio Monitor, despite moving on the iMac. 

So I switched back to the plugin since it works amazing on Bootcamp, but it seems no matter what I mess with, I always have a high latency, it's smooth, but feels drunk when moving anything on desktop or just general mouse use. 

Any recommendations to reduce the latency from MacOS to pc, I feel like the iMac is throttling the feed or something, I'm honestly not the most knowledgeable on it, embarrassingly so lol. Thank you. 

iMac Pro 2017
3GHz 10-Core Intel Xeon W
128 GB 2666 MHz DDR4
Radeon Pro Vega 64 16 GB

**Comment by JoemerRamos** [comment]
Hey, Im having an issue sending an NDI output from my mac to my windows PC, can you share what applications youre using and the steps to send your mac output to your windows as an NDI source?

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
