### ISSUE TITLE
Audio lag behind video when via Gigabit local network

### ISSUE THREAD

**Issue by CicoZhang** [Palakis/obs-ndi#696]
PC: Windows 10, Desktop, Ryzen 7 3700X, 32GB Ram, RX 590 GPU, OBS + NDI plugin, audio is sent from audio interface (where delay is set properly) to be in sync with video from Cam Link 4K (from Fujifilm X-T4); it works well without any delay issue on the same PC when using NDI virtual input as web camera or using OBS virtual camera.

Mac M1 16 RAM: when use the NDI virtual camera there, the video/audio source is from PC (OBS) via ethernet cable, and audio lags behind video.

OBS is the latest version 27.1.3, this problem has been existing all along in the computer used.

Is there any solution to this? Thanks.

**Comment by tt2468** [comment]
This is a known issue, we're hoping to fix it in version 5.
