### ISSUE TITLE
Please offer rpm packages

### ISSUE THREAD

**Issue by RAMChYLD** [Palakis/obs-ndi#698]
I'm moving away from Ubuntu, reason being they're moving more stuff to snap and I don't like some aspects of snap.

I decided to switch my streaming machine to OpenSuSE at the suggestion of a redditor. But I encountered a problem.

Under Ubuntu, the 64-bit library directory is lib and 32-bit compatibility libraries go into lib32
On OpenSuSE, it's the opposite, the lib directory is for 32-bit compatibility while the native packages go into lib64.

Naturally, this makes alien create unusable and dangerous packages. 

So I'd like to ask, please make rpms available. I would love to compile from source, but the ndi sdk version 4 is no longer available for download.

**Comment by tt2468** [comment]
Unfortunately, this isn't something that is worth doing for us at the moment. I should say though that we have been doing some work on the `rewrite` branch, which uses NDI 5. If you only need input (source) support, it has that right now and you can build it on your own.
