### ISSUE TITLE
NDI screen capture freezing

### ISSUE THREAD

**Issue by npkamen** [Palakis/obs-ndi#699]
Hi there,

We're new to using NDI in our church services since a recent upgrade we just completed (mostly sound system oriented). We used to use HDMI USB capture cards and didn't have this issue prior to switching to NDI.

Our setup consists of two desktop PCs.:

One PC drives the in-house multimedia system displaying song lyrics, Powerpoint presentations, videos etc for the congregation to see in house. We use a software package called Worship Extreme for this purpose and it generally works quite well.

The second PC is our audio recording and streaming PC. This PC takes in a Dante audio feed from the mixer and also takes in an NDI feed from a PTZ camera (Birddog P100) as well as a screen capture of the second screen on the multimedia PC (the screen which is displayed to the congregation). We use OBS as our streaming software and video switcher using the latest version of the obs-ndi plugin.

Both PCs have the latest NDI tools installed (5.0.5 I believe). I realise that 5.0.10 has been released now however I haven't had a chance to upgrade to it yet.

What we find is that when the OBS doesn't have the multimedia PC in is live view (and we are just on the camera), the NDI output will freeze from the multimedia PC. Switching back to the multimedia PC output in OBS shows the last frame that was viewed (even though the screen content has changed in that time while the multimedia PC was not being broadcast).

The only way to get it to update the NDI output is to move the mouse from the main monitor to the captured monitor on the multimedia PC. I've done some research and there seems to be similar issues experienced but none of the fixes have worked or applied to our setup.

Can anyone please help me out on what might be going on here? It is very frustrating and we only have a small team of fairly inexperienced volunteer operators who run this thing on a Sunday morning.

Thanks

**Comment by tt2468** [comment]
Would you be able to provide an OBS log from the streaming PC?

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
