### ISSUE TITLE
High CPU usage on Mac OS

### ISSUE THREAD

**Issue by tbartel** [Palakis/obs-ndi#70]
I'm attempting to stream from one Mac to another via NDI and a crossover cable and everything is working very well with the exception of high CPU usage on the sender.  Outputting at 1280x720@30 output seems to cause about a 30% CPU load, whereas 1920x1080@30 is around 70%.  This is more or less in line with what I see when using the x264 software encoder, whereas CPU usage while using the Apple VT h.264 hardware encoder is somewhere around 3%.  My guess is that the NDI output is not taking advantage of the hardware encoder.  Is there a way to specify how the output is encoded or am I stuck with software only?  For reference, I'm using OBS 20.1.0/OSX 10.11 on both ends.

**Comment by PatTheMav** [comment]
Can confirm that NDI and using the built-in VT H.264 encoder brings OBS to constant 70+%ish CPU load (most recent OBS/NDI-plugin and macOS versions).

I encode 1920x1080@60 with 10Mbit and have a browser source put over the NDI source.

IIRC CPU load on Windows (the source machine) was quite high as well, will check those values again and report back.

**Comment by Helgaiden** [comment]
Make sure if you have any browser sources (or any other sources, id check all of them in every scene), that you check the box in the source properties that says "shut down source when not in use." Some sources, browser sources specifically (but im not sure if its all sources) still technically run when you arent using them and eat CPU power, especially animated overlay types from places like streamelements.

**Comment by PatTheMav** [comment]
Funnily enough, just minimizing the OBS window brought CPU usage _and_ encoder delay down considerably. Just like on Windows, the preview window is a resource hog but minimizing works its magic on macOS at least.

Also browser sources use CPU even if hidden as OBS still spawns the Chrome process.

One note about the Apple VT encoder - from what I read it's a QuickSync "bridge" but doesn't allow CBR encoding, so it's not advisable to use it for streaming. When using a single bitrate value, the VBR stream is interrupted after a few seconds when streaming to YouTube, setting an identical bitrate maximum "stabilizes" the bitrate somewhat, but it's still VBR and results in noticeable macro blocking/artefacts every few seconds.

**Comment by Palakis** [comment]
@PatTheMav 
> Funnily enough, just minimizing the OBS window brought CPU usage and encoder delay down considerably. Just like on Windows, the preview window is a resource hog but minimizing works its magic on macOS at least.

wut.
Okay, maybe this has something to do with an issue someone reported to me. Gonna try a fix a provide a dev build to test with.

**Comment by PatTheMav** [comment]
@Palakis - yep the Encoder delay goes down to 3ms and CPU usage goes down by ~30%. 

Also dropped frames due to render delay do not happen at all and I got about 10 dropped frames due to render delay in 2 hours of streaming.

Could be an macOS issue with OBS itself though.. ¯\_(ツ)_/¯

**Comment by chuckreynolds** [comment]
same issues. commenting to follow issue. I had previously assumed my MBP could handle streaming better than it does but... oof... 100+% cpu when streaming from PS4->capcard->obs->twitch
<img width="303" alt="about_this_mac" src="https://user-images.githubusercontent.com/46185/44113714-d1d25f1e-9fbd-11e8-856f-3a872a678629.png">

**Comment by fredemmott** [comment]
I'm still seeing this with latest master on Mojave; it happens as soon as the source is added - even if there is no input, OBS CPU usage jumps from 5% to ~ 200%. Not streaming or recording or even with preview window disabled; just having the source there eats cpu.

**Comment by PatTheMav** [comment]
@fredemmott - can confirm: Since updating to macOS Mojave, CPU usage instantly jumps to 200% as soon as a NDI source is present.
