### ISSUE TITLE
Dedicated output filter causes OBS to fail to start up

### ISSUE THREAD

**Issue by enigma0Z** [Palakis/obs-ndi#702]
Expected: 

When a source has a dedicated output filter applied to it, I can close OBS and restart it, and said dedicated output will remain available

Actual:

OBS "starts up" according to the log https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FBAMu5rez3kYcB9IX#logURL but OBS's ui is never displayed.  In order to close it, I need to force-quit the app entirely.

Removing the NDI filter manually from the sources (even just one video source), will allow OBS to start up again.

What I'm trying to do:

Stream two webcam feeds over the network to be composited on a remote streaming machine.

Environment info:

Mac OS X
2015 Macbook pro
Plugin version 4.9.0

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.

**Comment by MrSam7K** [comment]
This is also happening to me on 4.14.1

https://obsproject.com/tools/analyzer?log_url=https://obsproject.com/logs/jSBLUHXnoXa0LTfz

**Comment by MrSam7K** [comment]
Though the message above would re-open the issue again, but I guess it did not
@paulpv (in case you didn't see this yet)
