### ISSUE TITLE
Windows computer isn't detecting mac NDI source (not m1 chip)

### ISSUE THREAD

**Issue by remeoj** [Palakis/obs-ndi#707]
I'm not sure why, but my mac computer (Macbook pro 2019 i9) can detect when my windows computer (Windows 10) becomes a main source, but it doesn't work the other way around. Anyone know how to fix this? Ive tried turning off all firewalls and it still didn't work. Not sure why my windows computer can't pick up my mac. I've used NDI virtual input and NDI Scan Converter, but it doesnt show any source on windows pc. Help please
Log File:
[2021-12-05 16-37-45.txt](https://github.com/Palakis/obs-ndi/files/7656903/2021-12-05.16-37-45.txt)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
