### ISSUE TITLE
Obs ndi issues on windows 11

### ISSUE THREAD

**Issue by JoqniX** [Palakis/obs-ndi#708]
hi, i've been a active user of ndi for a while ~ and recently ever since i had upgraded to windows11( currently on win11 OS Build 22000.348)  i had faced an issue where my obs eats up an whole tons of data when  ndi is sent to my stream pc~ thus making my game pc can't even connect to internet~ thus every apps become offline ish~ and this is one of the issues~ 2nd issue is i tried using ndi hx and screen capture, the same thing happend for a while but hx always crashed my stream obs for no reason~ also now it became a point where im really in needa of a capture card, recently i cant even do ndi screenshare or ndi hx or even obs ndi~ please do fix this issue on windows 11! and also im running a gigabite internet and my ethernet links are 1000/mpbs~ i've analyzed and tried troubleshooting my ethernet cables and other known ways to fix it~ please do update and fix this ~ thank you <3 for reading and helping and also thank you palakis for your hardwork as always 💖~
![msedge_Jz8RXVBhd5](https://user-images.githubusercontent.com/54277349/145702880-b162a628-00ce-482f-be12-f758c971344e.png)

**Comment by MilanPutnik** [comment]
There is nothing like that to fix - there is an issue with your system.
You mentioned you attempted some troubleshooting, however from the screenshot you posted, I can see you have an issue with your network capacity.
Your NIC certainly doesn't work with the capacity of 1Gbit/s (1000 Mbit/s or ~125 MB/s) - there it states it is at it's 100%, while it far from being maxed.

Windows 11 is not really precise with that one at the moment for some reason, however from practice I can tell you that on your screenshot you are actually pulling between 30-40 MB/s. That's ~250-300 Mbit/s. Had your NIC been synchronized and working at its rated full capacity of 1 gig, it should have been indicating ~25-30%.

There is something wrong within your network - it can be your NIC, but it can also be your default gateway having an issue and forcing the whole network to lower speeds - or even erroneous settings on some other network interface within your subnet that interacts with this one and forces it out of the full-duplex.

Another detail - pay attention to your Voicemeeter setup in relation to your NDI stuff. Tripple check that. I've had a client with a particularly mysterious case of network congestion that already a few of their engineers just started getting out of options.
I discovered it was a fairly complex loop accidentally created after setting up some VBAN+RTMP+NDI based implementation.

That Voicemeeter pulls quite a lot. It is not unusual, but you need to be exchanging at least a dozen 24bit/48KHz channels with some other host on your network.
Erroneously configured NDI setup can pull an already shared VBAN audio channel. creating a major loop and multiplying the voltage frequency within the network. To avoid damage, the system creates an emergency interrupt and halves the network speed at the interface, at one point shutting it down completely.

All the best!

Putnik
_mr.sci.eng._

**Comment by DukeStamina** [comment]
something I ran into with my 2 pc stream setup over ndi was actually due to the network card that came stock with the motherboard

check device manager to see if you've got an Intel(R) Ethernet Controller I225-V
That's the one I was using, and it did the same thing or sometimes would frequently drop the signal 
I solved this by picking up cheap 16$ networking cards off amazon and installing em into both of my computer's which luckily had available pci-e slots.

hope this helps you!

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
