### ISSUE TITLE
Blank screen from iphone through to OBS

### ISSUE THREAD

**Issue by ciderandhavoc** [Palakis/obs-ndi#71]
Hi there,

I spent a good amount of time reading up on this awesome plugin for OBS.

- MacOS 10.13.1 Sierra
- OBS 20.1

What I'm trying to do: use my iPhone as a source in OBS

I installed all the necessary components from NewTek
And installed the most recent version of this plugin.
Installed the NewTek Camera App for iOS

I am able to confirm that the camera on iPhone is working in the NDI Video Monitor

But when I add IPHONE as a source in OBS (so it sees the device is live) the image is blank(/black). I've maximised in case it's hidden in a corner but it remains blank.  I've tried a few things and nothing seems to be working. I've read through documentation here but cannot find a solution.

**Comment by Palakis** [comment]
The latest macOS release of obs-ndi seems broken for some reason. I'm currently investigating this.
