### ISSUE TITLE
Win11 problem with Mouse Capture

### ISSUE THREAD

**Issue by beppexx80** [Palakis/obs-ndi#711]
Hi,
with the Capture mouse active, in the OBS i have the black window with the arrow mouse movement.
![Immagine 2022-01-05 184415](https://user-images.githubusercontent.com/24457253/148264031-034a56e6-d769-4a75-b8ae-4a6cf52cf347.png)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
