### ISSUE TITLE
Please check libndi.so at the configure time

### ISSUE THREAD

**Issue by yurivict** [Palakis/obs-ndi#712]
Users complain that obs-studio fails to add the ```obs-ndi``` plugin.

See the [downstream bug report](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258694).

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
