### ISSUE TITLE
NDI Plug In doesn't show up

### ISSUE THREAD

**Issue by TheLiamStevenson** [Palakis/obs-ndi#714]
I'm Using OBS V27.1.3 
and tried plug in V4.9.0 and .1 

Neither of them show up after restart.

**Comment by Mazecreator** [comment]
Did you install the SDK from NDI.tv?

Here is a Video that may help you get setup:
https://www.youtube.com/watch?v=a7jJ122niaA

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
