### ISSUE TITLE
Crackling sound NDI-source (Screen Capture HX)

### ISSUE THREAD

**Issue by JahMiroKey** [Palakis/obs-ndi#716]
I am getting crackling and bad-quality sound on my NDI-source.
Below my setup;

Streaming PC;
Windows 10 (21H2)
OBS Studio 27.1.3
NDI Tools 5
obs-ndi-4.9.0
Sound settings in windows 24bit 48khz
Sound settings in obs 28khz

Gaming PC;
Windows 11 (21H2)
NDI Tools 5 (Screen Capture HX)
Sound settings in windows 24bit 48khz

With Streamlabs OBS this setup works fine.

**Comment by gallem777** [comment]
I report the same problem, crackling and noisy sound. The condition is specifically severe when the NDI plugin is running in other accounts on Windows OS, sometimes leading to 100% CPU utilisation and inresponsive state. Not sure though if this is the issue with OBS NDI plugin or NDI Webcam input app. I've been testing this with 4.9.x and 5.1.x SDK. The only way to make it work in a stable condition is to log out other accounts and run it only on a single one.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
