### ISSUE TITLE
MacOS Monterey 12.1 NDI Black Screen

### ISSUE THREAD

**Issue by trulow** [Palakis/obs-ndi#717]
The black screen issue still occurs when using MacOS Monterey 12.1 with NDI and OBS. The solution for now is to use the NDI Runtime v4.0.0 instead of the latest release of v4.5.1

https://ndi.palakis.fr/runtime/ndi-runtime-4.0.0-macOS.pkg

**Comment by high-solutions** [comment]
i have this issue on Catalina/big sur en monterey. Ndi-runtime-4.0.0 works fine for NDI-3 and below. 
But is doesn't support NDI -4 or higher devices.
Because i have both i'm in a pickle. There is no update yet for NDI-4 of my hdmi encoders so i can't use half of my camera's....

**Comment by 1091sw** [comment]
Just an update, NDI Runtime 5.0.10.1 is out but the black screen issue is still persistent. Downgrading back to runtime 4.0 until issue is resolved.

**Comment by trulow** [comment]
Update: [NDI Runtime 5.0.10.1](https://ndi.palakis.fr/runtime/ndi-runtime-5.0.10.1-macOS.pkg) is out but still have the black screen issue with MacOS Monterey. Downgrading back to 4.0 until a working runtime is available.

**Comment by high-solutions** [comment]
thats a perfect solution on all my machines, i noticed that even when you update the runtime obs would stay stuck on 4.5.1 anyway. your solutions fixed that.

**Comment by high-solutions** [comment]
@trulow Okay, the black screen issue is resolved but now with this fix i have issue's with NDI output from OBS Program/Preview. 
On 3 out of 5 machines those streams show up but don't show video/audio and on 2 out of 5 machines those sources cause even all other NDI streams on the same network to freeze......

I'll try to find the issue somewhere next week if I have more time on my hand. Maybe it's just a network error of some kind but never had this before

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC.
Try rebooting the Mac?
Closing.
Feel free to re-open if you test and disagree.
