### ISSUE TITLE
NDI Plugin wont show up On linux

### ISSUE THREAD

**Issue by leradamus** [Palakis/obs-ndi#721]
After installation of first libndi4_4.5.1-1_amd64.deb and then obs-ndi_4.9.1-1_amd64.deb. (like mentioned)
the NDI option is still not availlable under tools setting on OBS player.
Distro is POP-OS ubuntu

**Comment by bloatedgoat** [comment]
Fixed by deleting OBS version from POP-OS store and installing OBS according to https://obsproject.com/wiki/install-instructions#linux

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
