### ISSUE TITLE
Linux - Every 2 seconds the picture + sound freezes

### ISSUE THREAD

**Issue by Hoerli1337** [Palakis/obs-ndi#722]
Every 2-3 seconds the picture and sound freezes on my Linux system that I use for streaming.
When I use Windows 10 on my stream PC everything works great, only on Linux there are problems.
Would like to change my stream system to Linux because my CPU does not get Windows 11 support and I want to switch to Linux in general.

Source-PC
- System: Windows
- CPU: AMD Ryzen9 3900X
- RAM: 32GB
- GPU: AMD Radeon RX 5700XT (OC)
- Network: 2.5Gbit/s (RJ45 - copper)
- OBS 27.2.0 (Also older versions already installed / tested)
- Plugin: 4.5.1.0

Stream-PC
- System: Linux Mint 20.3 (also tested with 20.1 + 20.2)
- CPU: Intel Core i7 7700HQ
- RAM: 16GB
- GPU: nVidia GeForce GTX 1070
- Network: 1Gbit/s (RJ45 - copper)
- OBS 27.2.0 from OBS Repo (Also older versions tested)
- Plugin 4.9.1-1

The following was tested / checked:
- Necessary bandwidth is available => Yes
- Necessary CPU/GPU resources are available => Yes
- Time is synchronous => Yes (own time server (ntp) installed in LAN)
- Bandwith => Highest / Lowest makes no difference
- Sync => Network / Source makes no difference
- Allow hardware acceleration => On / Off makes no difference
- Fix alpha blending => On / Off no difference noticeable
- YUV Range => Partial
- YUV Color Space => BT.709
- Latency Mode => Low / Normal makes no difference

**Comment by Hoerli1337** [comment]
Update:
Apparently the problem is triggered by the source.
When I use the NDI tools to send the image to my stream machine, everything works fine.
(https://www.ndi.tv/tools/#download-tools)
Apparently the plugin has cross-system problems.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
