### ISSUE TITLE
5.0 VS 5.0.10.1 little spell mistake and what changes ?

### ISSUE THREAD

**Issue by BestNoob** [Palakis/obs-ndi#728]
Hello, ndi-runtime 5.0 is working perfect with Windows 10 x64 21H2. 
I just want to ask what is about 5.0.10.1 is it safe/stable to use and why didnt u add it to "Release" ? 
Im a littlebit careful because you did a spell mistake and normally when 1x mistake has made there more ....

WIndows.exe instead of W**i**ndows

https://ndi.palakis.fr/runtime/
ndi-runtime-5.0.10.1-WIndows.exe

Best regards.

**Comment by Trouffman** [comment]
Not sure why it is not there, maybe @Palakis does not have a lot of time at hand. 

You can alwasy Download the latest Windows Runtime from NDI/Newtek directly at  http://new.tk/NDIRedistV5

(PErsonally tested 5.5.2.0 on both Win10 & 11 > all good!)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
I am not 100% certain about this, but I think it may be against the NDI terms to self-host any NDI runtimes for the public, so it might be best for @Palakis 's to turn off his runtime collection site.

Just download the NDI runtime directly from NDI:
* Windows: http://new.tk/NDIRedistV5
* MacOS: http://new.tk/NDIRedistV5Apple
* Linux: Use this script: https://github.com/Palakis/obs-ndi/blob/develop/CI/libndi-get.sh. 
  I plan to improve this script a little more...soon.

**Coincidentally, http://new.tk seems down right now**, but that is not [yet] an argument to not rely on it.
It worked a few days ago and seems like like a random error that could have just as easily happened to anyone's serverm even @Palakis 's.
I have posted a notice on their forums at https://forums.newtek.com/threads/http-new-tk-seems-down-and-thus-http-new-tk-ndiredistv5-http-new-tk-ndiredistv5apple.167380/
If it stays down, then we can think of an alternative.
Unless NewTek is going out of business, there is no reason [yet] to believe that the http://new.tk site is not valid.

Similarly, hosting the linux libndi .deb files here on GitHub may also be a violation of the NDI terms, thus why I plan to improve the script and eventually stop distributing the Linux libndi runtime here.

4.11.0-RC uses the links mentioned above.
I am closing this bug for now.
Feel free to comment if you disagree and I can reopen.

**Comment by Trouffman** [comment]
For reference this is now centralised in this discussion : #831
