### ISSUE TITLE
NDI problems - streaming works only one way

### ISSUE THREAD

**Issue by LotharHS** [Palakis/obs-ndi#73]
Hey,

first of all - im amazed by the NDI and thank you very much for creating the plugin. 

I have a small issue tho.
I have dual PC setup, one streaming and one gaming pc. 
I followed all the instructions and installed the plugin on both OBSs and so on.

The result:
My OBS can see the NDI signal from the streaming PC but the streaming PC can't see the image from the gaming PC. Which is obviously a problem. It only works that way. I tried installing the plugins again. Changing the NDI outputs back and forth and the result is still the same:
When i add ndi source on my streaming PC the only thing that shows up is a small red circle  in the left upper corned, the same circle that you use to resize an element in the scene in OBS.

Any help?

Cheers
Lothar

**Comment by LotharHS** [comment]
Can be closed, sacrificed the valuable five minutes to actually read the other people issues and found the solution - firewall.
Thank you!

**Comment by Palakis** [comment]
Good to know that's a pretty common fix!
