### ISSUE TITLE
MacBook Pro output, but Windows shows the black screen.

### ISSUE THREAD

**Issue by Steven-nagisa-Y** [Palakis/obs-ndi#730]
In MacBook Pro: OBS version: 27.2.2 (64bit) OS version: macOS12.2.1
In Windows: OBS 27.2.3 (64bit) OS version: Windows 10
Both installed the newest version of obs-ndi

OBS on Windows is able to add ndi source from my MBP, but the screen is black. No output.

**Comment by cyclemat** [comment]
Did you use a cablen conection? Please dont say you try wifi. Check 3th Party security Software.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
