### ISSUE TITLE
Compile in ARM64 Silicon M1

### ISSUE THREAD

**Issue by vitorallo** [Palakis/obs-ndi#733]
I have a proper built version of obs-studio, all in arm apple binary, trying to compile ndi plug in but its driving me crazy. I tried everything but cmake can't find libobs... libobsConfig.cmake is there in the _DIR specified. I tried both with the ver 4 and with the branch rewrite of ver 5... same behaviour. I really can't figure it out... 

here is the debug-output 

❯ cmake -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" -DLIBOBS_LIB="../../obs-studio/build/_CPack_Packages/Darwin/DragNDrop/OBS-27.2.0-1-macOS-Apple/ALL_IN_ONE/OBS.app/Contents/Frameworks/libobs.0.dylib" -DLIBOBS_FRONTEND_DIR="../../obs-studio/build/UI/obs-frontend-api/libobs-frontend-api.dylib" -DCMAKE_INSTALL_PREFIX=/usr -DLIBOBS_DIR=../../obs-studio/build/libobs -G Ninja -DCMAKE_OSX_ARCHITECTURES=arm64 --debug-output ../
Running with debug output on.
-- The C compiler identification is AppleClang 13.1.6.13160021
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- The CXX compiler identification is AppleClang 13.1.6.13160021
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerId.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting C compiler ABI info
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerABI.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting C compiler ABI info - done
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerABI.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
   Called from: [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting C compile features
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompileFeatures.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting C compile features - done
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompileFeatures.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting CXX compiler ABI info
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerABI.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting CXX compiler ABI info - done
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompilerABI.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
   Called from: [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting CXX compile features
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompileFeatures.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Detecting CXX compile features - done
   Called from: [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeDetermineCompileFeatures.cmake
                [2]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/CMakeTestCXXCompiler.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Found Libobs: /Users/vito/Downloads/obs/obs-studio/build/_CPack_Packages/Darwin/DragNDrop/OBS-27.2.0-1-macOS-Apple/ALL_IN_ONE/OBS.app/Contents/Frameworks/libobs.0.dylib
   Called from: [4]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageMessage.cmake
                [3]	/opt/homebrew/Cellar/cmake/3.23.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake
                [2]	/Users/vito/Downloads/obs/obs-ndi/cmake/FindLibObs.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
CMake Deprecation Warning at /Users/vito/Downloads/obs/obs-studio/cmake/external/ObsPluginHelpers.cmake:23 (message):
  You are using an outdated method of adding 'libobs' to your project.  Refer
  to the updated wiki on how to build and export 'libobs' and use it in your
  plugin projects.
Call Stack (most recent call first):
  cmake/FindLibObs.cmake:98 (include)
  CMakeLists.txt:56 (include)

   Called from: [3]	/Users/vito/Downloads/obs/obs-studio/cmake/external/ObsPluginHelpers.cmake
                [2]	/Users/vito/Downloads/obs/obs-ndi/cmake/FindLibObs.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
CMake Error at /Users/vito/Downloads/obs/obs-studio/cmake/external/ObsPluginHelpers.cmake:27 (find_package):
  By not providing "Findlibobs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libobs", but
  CMake did not find one.

  Could not find a package configuration file provided by "libobs" with any
  of the following names:

    libobsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "libobs" to CMAKE_PREFIX_PATH or set
  "libobs_DIR" to a directory containing one of the above files.  If "libobs"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/FindLibObs.cmake:98 (include)
  CMakeLists.txt:56 (include)

   Called from: [3]	/Users/vito/Downloads/obs/obs-studio/cmake/external/ObsPluginHelpers.cmake
                [2]	/Users/vito/Downloads/obs/obs-ndi/cmake/FindLibObs.cmake
                [1]	/Users/vito/Downloads/obs/obs-ndi/CMakeLists.txt
-- Configuring incomplete, errors occurred!
See also "/Users/vito/Downloads/obs/obs-ndi/build/CMakeFiles/CMakeOutput.log".
See also "/Users/vito/Downloads/obs/obs-ndi/build/CMakeFiles/CMakeError.log".

**Comment by vitorallo** [comment]
yes, I know there is around a universal libndi dlyb compiled universal from NewTek but all this story to install obs on m1 completely in intel, then ndi-obs compiled intel... it's dirty as hell... I have a clean ARM apple bin OBS and cannot use the available .pkg built for intel. the .so obviously is intel...

❯ file obs-ndi.so
obs-ndi.so: Mach-O 64-bit bundle x86_64

**Comment by ioridev** [comment]
Here is an installer that someone has built.
https://obsproject.com/forum/threads/obs-on-apple-silicon.133606/page-8#post-552946

**Comment by ioridev** [comment]
https://github.com/kilinbox/obs-ndi/releases

**Comment by vitorallo** [comment]
thanks, it works.. I don't need to get more headaches trying to compile...

info: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
info: [obs-browser]: Version 2.17.14
info: [obs-browser]: CEF Version 95.0.4638.69 (runtime), 95.0.0-MediaHandler.2462+g95e19b8+chromium-95.0.4638.69 (compiled)
warning: Failed to load 'en-GB' text for module: 'obs-ndi.so'
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
info: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.4.dylib'
info: [obs-ndi] NDI runtime loaded successfully
info: [obs-ndi] NDI library initialized successfully (NDI SDK APPLE 16:47:54 Mar  2 2021 4.6.2)

**Comment by arcreigh** [comment]
While it is nice to have kilinbox's precompiled I would still like to try and replicate what he did so that we are able to compile this on our own. I am running into an identical issue as above where the library is not properly being found by the findlibobs.cmake job. Even though it does actually exist at the specified location. 


For reference kilinbox used the following command to get his build working. However attempting to follow in his footsteps returns the error originally reported above.

```
cmake -DLIBOBS_INCLUDE_DIR=../obs-studio/libobs \
 -DLIBOBS_LIB=../obs-studio/libobs \
 -DOBS_FRONTEND_LIB:STRING=/Applications/OBS.app/Contents/Frameworks/libobs-frontend-api.dylib \
 -DQTDIR=../obs-build-dependencies/obs-deps \
 -DCMAKE_OSX_ARCHITECTURES=arm64 \
 -B build .
 ```
His instructions for compiling OBS on Apple Silicon do work and I do see others having success so I am wondering if my inexperience in compiling software is what is biting me here or if it is indeed due to us not having any "official" M1 builds from the OBS team until v28 (not yet released)

**Comment by arcreigh** [comment]
Looping back around after some digging Apple Silicon support has been officially added to OBS via https://github.com/obsproject/obs-studio/pull/5155
This has been merged.
So while I know most of the focus is on NDIv5 at the present It would be nice to dedicate some time to at least helping us compile this on what is currently available in the meantime so that us M1 users are not left with no options.

**Comment by thpryrchn** [comment]
Well, Apple Silicone is finally available for OBS!! Get OBS 28 Beta 1!!

**Comment by Byfrost** [comment]
> Well, Apple Silicone is finally available for OBS!! Get OBS 28 Beta 1!!

I believe the plugin is not yet supported for OBS28; someone's NDI plugin isn't working for them... what's everyone's experience on this?. The thread indicates this needs to be flagged to the author of the plugin
(ref) https://obsproject.com/forum/threads/obs-studio-28-0-beta.158248/post-579492

**Comment by voxxit** [comment]
> > Well, Apple Silicone is finally available for OBS!! Get OBS 28 Beta 1!!
> 
> I believe the plugin is not yet supported for OBS28; someone's NDI plugin isn't working for them... what's everyone's experience on this?. The thread indicates this needs to be flagged to the author of the plugin (ref) https://obsproject.com/forum/threads/obs-studio-28-0-beta.158248/post-579492

It's not. OBS 28 has a number of updates which plugin authors are required to integrate, such as Qt5 to Qt6. Here are some resources I found:

* https://github.com/obsproject/obs-plugintemplate/pull/27
* https://github.com/obsproject/obs-studio/discussions/6481#discussioncomment-3312039

**Comment by thpryrchn** [comment]
> https://github.com/kilinbox/obs-ndi/releases

For 28 b1, they have a qt-6 version for OBS!!! There is also many other OBS plugins that are ARM compiled with QT6 in that REPO!!!! 

I wish they had the source code differences so we can see what is done to make them work though.... But hey, it works!

**Comment by tt2468** [comment]
Alpha build available at https://github.com/Palakis/obs-ndi/actions/runs/2977380826
