### ISSUE TITLE
No Audio in Stream and Blackstream in some Gamecapture

### ISSUE THREAD

**Issue by LivePlayerHD** [Palakis/obs-ndi#734]
Hey there,
I have the problem that I have no sound while I'm streaming but i see on my Streaming PC that he has sound from my Gaming PC.
And a other problem is with the Gamecapture. Some Game are only Blackscreen in OBS

**Comment by 0TheCho0** [comment]
I'm having the exact same problems, please help!!!!!!

**Comment by 0TheCho0** [comment]
Found this solution, hope it works for you! https://youtu.be/I1FjKc-RHow
And for some games you need to put in window mode and use the windows capture feature!

**Comment by LivePlayerHD** [comment]
I think that's a problem because I use a newer version from OBS but I don't know

**Comment by 0TheCho0** [comment]
I use the lastest version of OBS too, today I do a stream perfectly

**Comment by LivePlayerHD** [comment]
Yes I found the problem. I don't know why but no audio track was activ
