### ISSUE TITLE
ProPresenter 7.9 black screen issues sharing with ndi

### ISSUE THREAD

**Issue by rajivg91** [Palakis/obs-ndi#736]
After we updated propresenter to the newest version: 7.9, we started to see the same issue across multiple clients with this obs plugin. Our setup is one windows machine running obs 27.2.4 and this ndi plugin,  in a different computer (windows or mac) we have propresenter, both computers are the only devices in the same network and they're using ethernet cables. When we share slides or videos through ndi from the laptop using propresenter and we open obs, most of the times the ndi source displays a black image. The only way to get obs and the plugin to start displaying the ndi source correctly is open the ndi source, change the the source with a dummy one, then select again the one we need and immediately start displaying what we share from propresenter. 
We already tried to update the plugin and obs to the latest versions and the problem persists in multiple setups. 
Has anyone encountered this problem and the new version of propresenter?

Thanks

**Comment by RN-Mexico** [comment]
I'm having same problem between ProPresenter and OBS. Did you got any solution?

**Comment by cramaboule** [comment]
We have issue of short black fade during transition of the slide from Propresenter (latest version) to OBS 27.2.4

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by cramaboule** [comment]
@paulpv It is solved with Propresenter 7.11. thanks anyway !

**Comment by paulpv** [comment]
@cramaboule Great! Closing!

**Comment by wpmccordiv** [comment]
> We have issue of short black fade during transition of the slide from Propresenter (latest version) to OBS 27.2.4

@cramaboule

Did upgrading to ProPresenter 7.11 solve the black fade transition issue with lower thirds or slides being presented on a live OBS feed? Or did you have to do anything else? Was wondering if making sure no transition was used would solve it?
