### ISSUE TITLE
Output timer stops immediately after 1 frame, creating 1K file

### ISSUE THREAD

**Issue by therentabrain** [Palakis/obs-ndi#739]
This appears to happen every other recording.  (!!)

Please see these links for more information:
https://obsproject.com/forum/threads/output-timer-stops-video-prematurely.118949/
https://obsproject.com/forum/threads/output-timer-potential-bug.118065/

This may be related:
https://obsproject.com/forum/threads/timeout-on-recording-causes-next-recording-to-stop-immediately.153212/

**Comment by tt2468** [comment]
This appears to be entirely unrelated to obs-ndi. Closing.

**Comment by therentabrain** [comment]
You are correct, I have no idea how I wound up posting it here.  Sincere apologies, too many tabs.
