### ISSUE TITLE
Changing audio filter NDI name causes crash

### ISSUE THREAD

**Issue by Scokee** [Palakis/obs-ndi#74]
When applying the "Dedicated NDI™ output (Audio Only)" audio filter, changing the NDI name and hitting Apply changes will cause OBS to crash.  Crash log attached.

[NDI Audio Crash.txt](https://github.com/Palakis/obs-ndi/files/1565888/NDI.Audio.Crash.txt)

**Comment by lebaston100** [comment]
Can confirm this. Happens with the Video filter too.
[Crash 2017-12-17 19-21-46.txt](https://github.com/Palakis/obs-ndi/files/1565912/Crash.2017-12-17.19-21-46.txt)
[2017-12-17 19-19-45.txt](https://github.com/Palakis/obs-ndi/files/1565915/2017-12-17.19-19-45.txt)

**Comment by Palakis** [comment]
Thanks. Gonna investigate this ASAP and issue a hotfix.

**Comment by BOLL7708** [comment]
Can confirm. I tried adding multiple filters, as I had multiples I had to rename them to get all of them to show up, as now all had the same name, but pressing apply does the mentioned crashing :)

**Comment by Palakis** [comment]
Fixed it. Gonna upload new release soon.

**Comment by Palakis** [comment]
4.2.1 uploaded!
