### ISSUE TITLE
NDI Access Manager External Sources not working only on macOS

### ISSUE THREAD

**Issue by kathampy** [Palakis/obs-ndi#740]
I have an NDI camera on different VLAN.
In NDI Access Mangaer, under External Sources, I have added the camera's IP address as an NDI source.
The source is now detected in other NDI applications like Video Monitor and Virtual Input.
The source name has the format `RC26 (NDI HX2, 192.168.0.100)`.

However, on macOS, the source does not show up in OBS with the NDI plugin. Even if I type the full source name manually, it does not detect the feed.

This works fine on Windows and the source is automatically detected in OBS.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by kathampy** [comment]
Unfortunately I no longer have access to the camera on a different VLAN to test it.

**Comment by paulpv** [comment]
Thanks for the reply 
I'll close and consider it again if someone else reports.
