### ISSUE TITLE
MacOS M1 Machine not showing as a source in Ubuntu

### ISSUE THREAD

**Issue by agjs** [Palakis/obs-ndi#743]
I'm trying to set up my MacOs M1 (that I stream from) with my Ubuntu laptop. Essentially, I want my Ubuntu laptop to do all the streaming stuff and relieve my MacOS from needing to all that.

I can see my Ubuntu machine as a source on my MacOS, but not vice versa. Is there a known issue when trying something like this?

Is it not possible to use a MacOS source with the Ubuntu machine?

**Comment by agjs** [comment]
I have just also tried to add my MacOS as a source on my Windows PC and same issue, my M1 is just not even found.

**Comment by tt2468** [comment]
OBS is probably missing some kind of network permissions to use mDNS on your system.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
