### ISSUE TITLE
Muting any NDI sound source  on Gaming PC doesn't mute it on Stream PC

### ISSUE THREAD

**Issue by OGNetheri** [Palakis/obs-ndi#746]
This issue is still alive and kicking, just noticed it today when I was about to kick stream on. There's no muting happening when it's done on gaming PC. Therefore also when the scene is changed, audio sources keep going through to streamPC even when they aren't in the scene used in OBS.

There's no matter is the Main NDI output on or off in this issue. Although I want to use Main NDI to capture game and use NDI output for sound and keep stream pc main NDI input muted as the "filter NDI" raises the time to render frame usually very high on game pc for some reason and OBS starts to drop and skip frames. Apparently dedicated NDI isn't a "relay" for video and sound through it as the Main NDI output is?

But the main issue anyway is the lack of  muting on gaming pc. EDIT: also changing the volume of the OBS source in gaming PC  doesn't affect the sound going through in any way other than apparently the possible monitor levels on headphones. Actual source's volume in gaming PC and volume of the NDI-input on streaming PC affect the volume going out to stream.

**Comment by tt2468** [comment]
This is expected behavior with the NDI filter. Filters operate before any kind of muting or volume adjustment, so you will always get audio through the output for as long as the source is producing it.

**Comment by OGNetheri** [comment]
Is it then possible to make sound related filters so (at least the NDI-filters) that when you mute the ouput on gaming pc, it doesn't send the signal to streaming pc's ndi-input? It would ease the NDI-streaming management. In the simplest example: "IF mute is 1, then output 0".
