### ISSUE TITLE
Even the NDI studio monitor crashes after some minutes 

### ISSUE THREAD

**Issue by Smarti0101** [Palakis/obs-ndi#747]
I tried to get everything running but obs crashes after some minutes. I tried 32 & 64 bit version of obs studio. Even the original NDI studio monitor crashed when this output plugin is active

The only solution I found: capturing with the original NDI screen capture and display out with obs (remote PC)

**Comment by paulpv** [comment]
What is your OS? Can you give any more details?

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
