### ISSUE TITLE
Feedback on Triple PC Setup

### ISSUE THREAD

**Issue by Helgaiden** [Palakis/obs-ndi#75]
Hi Palakis, i just wanted to thank you for developing this plugin. I didn't know how to contact you directly so im posting here. Sorry if it doesn't belong. But we did a 24hr stream a little over a week ago, using a laptop with an i7-3610qm as the streaming rig and two desktops as the sources, and everything went off without a hitch. OBS CPU usage on the streaming rig would occasionally spike up to 60-90% and start dropping frames, and im not sure what was causing the CPU load spikes but i imagine the laptop was cooling wasn't keeping up quite as well as it needed to and the CPU would thermal throttle down a little bit, calm down, and everything would run smoothly again after 10-15 mins. This only happened like 3-4 times throughout the 24hr stream, but for the most part everything was great. We did a little video on the setup we wanted to show you, and anyone else interested. The best part: we didn't run into any audio desync issues! At one point, i even set up my phone to as an NDI camera in OBS and walked around the house with it. Enabling the mic on the phone caused strange audio issues so i turned that off, but the videofeed worked great like that. That was cool.

[https://www.youtube.com/watch?v=Z7fbo9zMGYU](url)

**Comment by Farmagud** [comment]
High motion scenes will cause CPU spikes. Try streaming again and pay attention to how much CPU is being used with high motion scenes versus scenes where not much is going on. My second PC with an i7 2600 will spike from 30 to 85% CPU usage whenever I move my mouse quickly in games I’m streaming.

**Comment by Palakis** [comment]
Hi @Helgaiden, thanks for your feedback and your help in issue threads!
Both your theory and @Farmagud's are valid, even linked.

> The best part: we didn't run into any audio desync issues!

Damn that's good to hear!

>  i even set up my phone to as an NDI camera in OBS and walked around the house with it. Enabling the mic on the phone caused strange audio issues so i turned that off

What kind of audio issues?

**Comment by Helgaiden** [comment]
@Palakis Happy to help. NDI for OBS is the best.

Heres a clip where we turn the camera on with NDI on the phone. Turning it on with microphone made the audio very sorta...choppy, even the audio that wasn't coming through the phone. Just the regular audio coming through discord from one of the gaming PCs (not the NDI/streaming PC).

https://clips.twitch.tv/DelightfulDistinctPepperoniLitty

**Comment by Palakis** [comment]
@Helgaiden I guess the audio timestamps sent by the NDI receiver were sooo late that OBS had already maxed out audio buffering and dropped audio samples. This could happen if you used a version of obs-ndi prior to the introduction of the "Source Timing" setting, or if "Source Timing" was set to something other than "Local"
