### ISSUE TITLE
Sources Not Populating on Mac

### ISSUE THREAD

**Issue by mmonahan333** [Palakis/obs-ndi#756]
I am having an issue where my sources are not populating in OBS, although I can see them fine using the NDI Video Monitor. I was having this problem with the NDI Video Monitor at first but when I updated my software to the most recent version of NDI (5.5) my sources started populating all of a sudden. 

I'm wondering if there is a new version of NDI Runtime? I'm on Mac OS 12.5. NDI Runtime 4.5.1 is linked here, I've tried poking around the internet for a download for a 5. version of the runtime but haven't been able to find one and try it out. Does anyone know if this new version exists and where I could potentially find it?

Alternatively, the networking on my computer is quite complicated and I'm wondering if the plugin is simply looking at the wrong IP. I've tried binding OBS to my NDI network IP in the OBS settings (although I'm not totally sure what that does) and unfortunately that has not helped me out. Is there an IP search somewhere in the source code where I could just force it to look on a specific address?

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
