### ISSUE TITLE
Feature Request: Transparency 

### ISSUE THREAD

**Issue by TweakGames** [Palakis/obs-ndi#76]
Hello, 

I had troubles finding a features request section, so I hope this is the right place to put this. 

Xsplit NDI allows for transparency (green screen for example).  Is that something we can get in OBS NDI?  

I have a computer dedicated to webcam and other audio tasks, and it sends my green screened webcam with transparent background to the main xsplit and keeps the transparency.  It is very useful.  I don't have to apply the green screen to an already processed image.  

Maybe we already have it and I don't see the option?  Maybe it was in an update recently? I haven't used it since I was getting the audio delay issues.   I would love to have this work in OBS because the OBS green screen filters are superior. 

Thanks.

**Comment by lebaston100** [comment]
Look at this issue where Palakis is explaining it https://github.com/Palakis/obs-ndi/issues/68#issuecomment-348092609
