### ISSUE TITLE
OBS-NDI Plugin Build Failure due to find_package(LibObs REQUIRED) in CMakeLists.txt

### ISSUE THREAD

**Issue by hullio** [Palakis/obs-ndi#763]
I have been installing OBS and the OBS-NDI plugin for the last several years on both Ubuntu 18.04 and 20.04 with no issue. Today working with a newly commissioned system ran into an issue. Never seen this before. Looking for some feedback if others have seen or this is a real issue. On the older systems we started with OBS 27, got the plugin built and installed, and upgrade to OBS 28 recently. 

Here is the build and install process:
1. OBS Install
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install obs-studio v4l-utils v4l2loopback-dkms v4l2loopback-utils ffmpeg

2. OBS-NDI Plugin Build & Install
cd ~/Downloads
cp ~/Fileserver/Tools/OBS/* .
    libndi4_4.5.1-1_amd64.deb
    obs-ndi_4.9.1-1_amd64.deb
sudo dpkg -i *.deb

sudo apt install qtbase5-dev cmake
cd ~/Downloads
git clone https://github.com/Palakis/obs-ndi.git
git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-ndi 
mkdir build && cd build
cmake -DUSE_UBUNTU_FIX=true -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" -DCMAKE_INSTALL_PREFIX=/usr ..
make -j4
sudo make install

Here is the error:
~/Downloads/obs-ndi/build$ cmake -DUSE_UBUNTU_FIX=true -DLIBOBS_INCLUDE_DIR="../../obs-studio/libobs" -DCMAKE_INSTALL_PREFIX=/usr ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:20 (find_package):
  By not providing "FindLibObs.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibObs", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibObs" with any
  of the following names:

    LibObsConfig.cmake
    libobs-config.cmake

  Add the installation prefix of "LibObs" to CMAKE_PREFIX_PATH or set
  "LibObs_DIR" to a directory containing one of the above files.  If "LibObs"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

Line 20 of CMakeLists.txt in the obs-ndi project contains this line: 
find_package(LibObs REQUIRED)

Any thoughts?

**Comment by gustavoninetyone** [comment]
Guys, this new update (28) caused me a headache with NDI because it is not yet supported.

However, if you want to compile the source and test it, just uninstall obs-studio and install libobs-dev. After compiling the plugin, install obs again.

1:
`sudo apt remove obs-studio`

2:
`sudo apt install libobs-dev`

3:
build

4:
`sudo apt install obs-studio`

**Comment by RAMChYLD** [comment]
If you use the OBS PPA, libObs is provided as part of the OBS package.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC.

Just use the `.github/scripts/build-linux.sh` script.

Closing.

Feel free to re-open if you test and disagree.
