### ISSUE TITLE
obs-nde plugin failed to load

### ISSUE THREAD

**Issue by onlize** [Palakis/obs-ndi#771]
##### Technical information
- **Operating System:** 
     Windows 11
- **OBS Studio Version:** 
     28.0.3 (64 bit)
- **obs-ndi Version:** 
     4.9.1

##### Development Environment

I was not using OBS for some time now. Today, I decided to check if everything is still good. When I opened OBS, it told me I had to upgrade it. I upgraded and rebooted. Now, when I open OBS, I receive an error message that says that obs-ndi plugin failed to load. I downloaded and upgraded this plugin, but it did not fix my problem. After that, I uninstalled and installed it again, but I still had the same issue. Can someone help with this?
![image](https://user-images.githubusercontent.com/28982031/193685471-6a757fa5-fe1d-413f-9236-63971c9706fa.png)

**Comment by vfxturjo** [comment]
having same problem... please help

**Comment by Neyyltv** [comment]
same, idk what to do..

**Comment by Neyyltv** [comment]
Ok it's just the obs version, ndi plugin isn't working on obs v28 yet. But it works on obs v27, you have to unistall your actual version and reinstall the latest obs v27 version on the obs studio github.

**Comment by ZachBacon** [comment]
it'll list when plugins are finally compatible with obs 28

**Comment by micromashor** [comment]
I'm also having this issue, but I am unable to install a 27.x.x version of OBS, so we are using hardware workarounds until the plugin gets fixed.

**Comment by c0rychu** [comment]
It seems like it is because obs v28.0.3 uses QT6, but the obs-ndi requires QT5

**Comment by micromashor** [comment]
> It seems like it is because obs v28.0.3 uses QT6, but the obs-ndi requires QT5

This makes sense, and seems to be the consensus in the other threads I have seen (#745 seems to be the main thread for this issue).

Let me know if there's anywhere help is needed.

**Comment by MctomSpdo** [comment]
I have the same Plugin. Going back to the newest Version of V27 solved the problem for me. Please update the plugin, it would really help the community out.

**Comment by SchmalzTech** [comment]
I am experiencing the same issue, following.

**Comment by EddieDemon** [comment]
Known issue, please see #745.

**Comment by nacalai** [comment]
You were looking at the NDI 5 Dev version. You can get the "normal" 4.9-version for obs v28 here with all the features:
https://github.com/dev47apps/obs-ndi/releases

**Comment by RAMChYLD** [comment]
Odd. The Dev version should work fine with OBS 28 tho. I prefer it because it can decode NDI-HX streams and has tighter netcode all around.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
