### ISSUE TITLE
Any plan to port it to raspberry? could be done?

### ISSUE THREAD

**Issue by allegfede** [Palakis/obs-ndi#78]
OBS is open source and i'm quite shure it's already in the raspbian repository.
So, using the dedicated raspi-cam and the NDI plug in, we could use the raspi like a very handy portable network camera.

Don't know if arm platform could give issues with Newtek binaries ....

Thanks.

Good job

**Comment by Palakis** [comment]
The NDI runtime has ARM binaries and I managed to use it succesfully in another project involving a Raspi.
Building obs-ndi for ARM is technically possible, but the user base would be really small.

**Comment by allegfede** [comment]
Do you have a blog? A wiki to look at?
My idea is to build a "webcam" over the raspberry pi and pi camera, obs and
ndi or plain straight ndi, to ne used like network camera in live shows
where enviroment is really little (cars :D)
Or where i have to set the pi in weird strade spot to make strage camera
Angles ;-).

The pi maybe could be also hacked to be POE(d), so 1 cable for power and
video.

It will ne an interesting open source/open hardware project.

Il 04 gen 2018 08:59, "Stéphane L." <notifications@github.com> ha scritto:

**Comment by bmac6996** [comment]
I second this.  The v2 pi cam is a pretty decent cam.. especially that it can do 720/60FPS and maybe more.

**Comment by Palakis** [comment]
I guess what y'all need is a program to take frames from a webcam/picam and send them over NDI. I started working on such a solution several months ago but ran into issues on the raspi. Maybe I'll give it another go and open source.

**Comment by Palakis** [comment]
Update: ffmpeg now supports NDI, both input and output.

**Comment by shodanx2** [comment]
Unfortunately ffmpeg support for NDI has been removed due to licensing shenanigan with Newtek corporation

Confirm here https://github.com/johanels/raspberrypi-FFmpegNDI
Support removed 20th of March 2019

It was removed on this ffmpeg commit 

https://github.com/FFmpeg/FFmpeg/commit/4b32f8b3ebfa011fcc5991bcaa97c3f5b61b49ad
