### ISSUE TITLE
NDI5

### ISSUE THREAD

**Issue by ecoBlackCH** [Palakis/obs-ndi#782]
When using NDI5, the screen on the receiving end flashes black. When it is blinking, the net speed drops from 135 Mbps to 70 Mbps, indicating an unstable connection.
This seems to be a problem with NDI5 since it worked fine when operating NDI with OBS27.
Do you have any suggestions for countermeasures?
I don't think it is a problem with my network environment.

**Comment by thmsdj** [comment]
I can verify this is an issue with OBS 28 and also on Apple Silicon M1. The video is intermittent. The screen goes black and then comes back but then after a random time goes black again.

**Comment by RAMChYLD** [comment]
I encounter this issue in Linux and usually it's down to the network being weak. By using an Ethernet connection I'd have no issues at all.

I can also confirm that this is not an issue with NDI4 and is only happening with NDI5.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
