### ISSUE TITLE
OBS NDI Source Audio Distortion

### ISSUE THREAD

**Issue by AnyaMaki** [Palakis/obs-ndi#793]
##### Issue type
Plugin Source Audio Distortion

##### Description
I use the NDI plug-in of OBS to broadcast Twitch live streams, but when NDI is pushed to the NDI-Source, the audio has distortion on right audio channel, and the video footage is fine.

If I go to Advanced Audio Properties and select 'Mono' and drag the balance all the way to L, I don't get any audio distortion / crackle.(https://github.com/CoSMoSoftware/OBS-studio-webrtc/issues/292#issuecomment-822047612) 
That's my solution for now,but if i did this thing i will lost my dual channel audio,and i can't get back to 4.9.1 cuz i'm using OBS 28.So i can only use 4.10.0 version.
that's not good for streaming anything.cuz the sound came only from one direction.

##### Technical information
- **Operating System: Win11 22H2 (Main PC)    Win1022H2 (2nd PC)
- **OBS Studio Version: 28.1.2(in both PC)
- **obs-ndi Version: obs-ndi 4.10.0

##### Edit
i just found out same issue as mine : https://github.com/Palakis/obs-ndi/issues/785#issue-1435448170
Please fix this issue,Thank from the bottom of my heart.It is important for me.

**Comment by imeiul** [comment]
I had the same problem.
I'm using this fork that didn't have the problem.
https://github.com/dev47apps/obs-ndi

**Comment by AnyaMaki** [comment]
> 

i am using this right now.
https://obsproject.com/forum/threads/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.69240/post-591347
idk some how they delete 5.0 version but thank god some one had back up.
