### ISSUE TITLE
The obs-ndi-4.10.0-Ubuntu64.deb package is actually using Qt6

### ISSUE THREAD

**Issue by RAMChYLD** [Palakis/obs-ndi#794]
##### Issue type

- Bug report

##### Description

I tried repackaging the deb to rpm because OpenSuSE is also using Qt5 for it's OBS. However, upon installing the plugin, OpenSuSE crashes at start, which is a sign of a Qt mismatch.

Out of curiosity I did a ldd on the plugin and sure enough, it was compiled against Qt6 and not Qt5 as mentioned in the release notes. 

[Pastebin of ldd output](https://pastebin.com/c1fJxjt5)

This means that the note is incorrect as the package will work with Ubuntu 22.04 and not Ubuntu 20.04. 

##### Steps to reproduce and other useful info

1. Extract obs-ndi.so from deb file
2. Run `ldd obs-ndi.so'

##### Technical information
- **Operating System:** OpenSuSE Tumbleweed
- **OBS Studio Version:** 28.1.1 Qt5
- **obs-ndi Version:** 4.10.0 Ubuntu64

**Comment by bentech4u** [comment]
Hi

i am using Ubuntu and installed obs-ndi/now 4.10.0 amd64, still NDI is not showing in source list,

anyone managed to enable NDI with latest OBS?

Regards,
Ben

**Comment by johandenhollander** [comment]
4.10.0 is not working with Ubuntu 22.10.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
