### ISSUE TITLE
No NDI Outputs on OBS (Mac)

### ISSUE THREAD

**Issue by profo250** [Palakis/obs-ndi#797]
Issue type

<-- Bug report -->
Unable to see OBS NDI outputs (not even names) from my iMac on other devices within the same network. NDI Output settings menu within OBS appears to be working correctly. Was working with an earlier OBS version. Have attempted uninstalling/reinstalling all components, as well as restarting the iMac. NewTek NDI Tools (Scan Converter, Test Patterns, etc) work fine. Firewalls on both computers are turned off.

Technical Information

Transmitting iMac: macOS Monterey (Version: 12.6.1)
Processor: 3.6 GHz Quad-Core Intel Core i7
Installed RAM: 32GB 2400 MHz DD4
Graphics: Radeon Pro 560 4 GB
OBS Studio Version: 28.1.2 (mac)
OBS-NDI Version: 
NDI Tools Version: 5.5.2.15

Receiving PC: TriCaster TC1 Pro (Build: 7-9-220826, NDI Version: 5.5.1.0)
Processor: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz   3.70 GHz
Installed RAM: 32.0 GB (31.7 GB usable)
NDI Tools Version: 5.5.2.0

**Comment by danibaeyens** [comment]
I had the same issue. The explanation on this article fully helped me:
https://alankent.me/2020/04/05/ndi-stream-and-mac-problem-and-solve/

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
