### ISSUE TITLE
cmake variables

### ISSUE THREAD

**Issue by Fenrirthviti** [Palakis/obs-ndi#8]
I'm attempting to build this, but running into cmake error:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
OBS_FRONTEND_LIB

I see this in the CMakeLists.txt, but I'm not sure where exactly I can find "obs.lib" or this "obs-frontend-api.lib" file. I have built OBS successfully on my system, and I don't see those files as part of the output.

**Comment by Fenrirthviti** [comment]
Nevermind, I sorted it out. Not familiar with linux terminology, the actual files I was looking for were libobs.so and obs-frontend-api.so

**Comment by Palakis** [comment]
@Fenrirthviti I haven't tested obs-ndi on Linux yet. Did you have troubles building it ?
Btw, gonna fix the README to be more multiplatform-friendly. I essentially develop and test obs-ndi on Windows but I'm planning multiplatform support.

**Comment by Fenrirthviti** [comment]
Yes, I had several issues building it. Ran into include issues with the ndi-sdk, even with the proper directory set as cmake var. If you want any help sorting the issues out (I'm not exactly great with C++), swing by the #obs-dev channel on quakenet and shoot me a ping at Fenrir there.

**Comment by Palakis** [comment]
@Fenrirthviti yes, the include paths in the CMakeLists file are not correctly set on OS X and Linux. I'll take some time one of these days to fix these platforms.

**Comment by Palakis** [comment]
@Fenrirthviti obs-ndi compiles successfully on Linux since https://github.com/Palakis/obs-ndi/commit/ef4d064726c2cfd98d5038cc4a0bb57c89d3541e !

**Comment by vedranius** [comment]
@Palakis @Fenrirthviti , I'm trying to compile obs-ndi on Ubuntu and I've got to this point:
` cmake -DLIBOBS_INCLUDE_DIR="<path to the libobs sub-folder in obs-studio's source code>" -DNDISDK_DIR="<root dir of the NDI SDK>" -DCMAKE_INSTALL_PREFIX=/usr .. `
I've git cloned obs-studio source code in home folder, and also downloaded NDI SDK V2 for Linux in another folder.
Wrote the path as described. 1st to .../obs-studio/libobs and 2nd to /NDISDKLinux
It compiles, and founds everything, says build has been written under /build folder, but when I try to "make -j4" I get ton of errors.
Any idea what I'm doing wrong?

Thank you! :)

**Comment by Palakis** [comment]
Please copy a log of those errors. I will help greatly.

**Comment by Palakis** [comment]
*It will help greatly

**Comment by vedranius** [comment]
Hey @Palakis ! Thanks! :)
This is what I tried and what error right now I get, first I've got the compiling OK, but cjmake -j4 wouldn't work, and now I can't even compile again :D 
And yes, I removed build folder to try to rebuild again... :P 

`cmake -DLIBOBS_INCLUDE_DIR="/home/user/Downloads/obs-studioLinux/obs-studio/" -DNDISDK_DIR="/home/user/Downloads/NDISDKforLinux" -DCMAKE_INSTALL_PREFIX=/usr ..
CMake Error: The source directory "/home/user" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by Palakis** [comment]
`cd` to the directory of obs-ndi's source code.

**Comment by vedranius** [comment]
Built it with that code above, I've forgot to get into "build" folder, it was to early for me :D 
`-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Libobs: /usr/local/../lib/libobs.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/obs-ndi/build
`

**Then I try make -j4**
`[ 16%] Building CXX object CMakeFiles/obs-ndi.dir/obs-ndi-output.cpp.o
[ 33%] Building CXX object CMakeFiles/obs-ndi.dir/obs-ndi-filter.cpp.o
[ 50%] Building CXX object CMakeFiles/obs-ndi.dir/obs-ndi-source.cpp.o
[ 66%] Building CXX object CMakeFiles/obs-ndi.dir/obs-ndi.cpp.o
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.compat.h:26,
                 from /home/user/obs-ndi/obs-ndi-output.cpp:24:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.compat.h:26,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.Lib.h:57,
                 from /home/user/obs-ndi/obs-ndi.cpp:25:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.compat.h:26,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.Lib.h:57,
                 from /home/user/obs-ndi/obs-ndi-filter.cpp:28:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /usr/include/c++/4.8/cstdint:35:0,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.compat.h:26,
                 from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.Lib.h:57,
                 from /home/user/obs-ndi/obs-ndi-source.cpp:26:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
/home/user/obs-ndi/obs-ndi.cpp: In function ‘bool obs_module_load()’:
/home/user/obs-ndi/obs-ndi.cpp:75:2: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
  }, nullptr);
  ^
/home/user/obs-ndi/obs-ndi.cpp:75:5: error: ‘nullptr’ was not declared in this scope
  }, nullptr);
     ^
/home/user/obs-ndi/obs-ndi.cpp:79:2: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
  }, nullptr);
  ^
/home/user/obs-ndi/obs-ndi.cpp:85:2: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
  }, nullptr);
  ^
/home/user/obs-ndi/obs-ndi.cpp: In function ‘void main_output_start()’:
/home/user/obs-ndi/obs-ndi.cpp:105:82: error: ‘nullptr’ was not declared in this scope
   main_out = obs_output_create("ndi_output", "main_ndi_output", output_settings, nullptr);
                                                                                  ^
CMakeFiles/obs-ndi.dir/build.make:62: recipe for target 'CMakeFiles/obs-ndi.dir/obs-ndi.cpp.o' failed
make[2]: *** [CMakeFiles/obs-ndi.dir/obs-ndi.cpp.o] Error 1
make[2]: *** Čekam nedovršene poslove....
CMakeFiles/obs-ndi.dir/build.make:110: recipe for target 'CMakeFiles/obs-ndi.dir/obs-ndi-output.cpp.o' failed
make[2]: *** [CMakeFiles/obs-ndi.dir/obs-ndi-output.cpp.o] Error 1
CMakeFiles/obs-ndi.dir/build.make:134: recipe for target 'CMakeFiles/obs-ndi.dir/obs-ndi-filter.cpp.o' failed
make[2]: *** [CMakeFiles/obs-ndi.dir/obs-ndi-filter.cpp.o] Error 1
/home/user/obs-ndi/obs-ndi-source.cpp: In function ‘obs_properties_t* ndi_source_getproperties(void*)’:
/home/user/obs-ndi/obs-ndi-source.cpp:59:2: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
  });
  ^
/home/user/obs-ndi/obs-ndi-source.cpp:71:2: warning: lambda expressions only available with -std=c++11 or -std=gnu++11 [enabled by default]
  });
  ^
/home/user/obs-ndi/obs-ndi-source.cpp:74:72: error: invalid conversion from ‘int*’ to ‘uint32_t* {aka unsigned int*}’ [-fpermissive]
  s->ndi_sources = NDIlib_find_get_sources(ndi_finder, &s->no_sources, 0);
                                                                        ^
In file included from /home/user/Downloads/NDISDKforLinux/include/Processing.NDI.Lib.h:84:0,
                 from /home/user/obs-ndi/obs-ndi-source.cpp:26:
/home/user/Downloads/NDISDKforLinux/include/Processing.NDI.Find.h:78:24: error:   initializing argument 2 of ‘const NDIlib_source_t* NDIlib_find_get_sources(NDIlib_find_instance_t, uint32_t*, uint32_t)’ [-fpermissive]
 const NDIlib_source_t* NDIlib_find_get_sources(NDIlib_find_instance_t p_instance, uint32_t* p_no_sources, uint32_t timeout_in_ms);
                        ^
CMakeFiles/obs-ndi.dir/build.make:86: recipe for target 'CMakeFiles/obs-ndi.dir/obs-ndi-source.cpp.o' failed
make[2]: *** [CMakeFiles/obs-ndi.dir/obs-ndi-source.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/obs-ndi.dir/all' failed
make[1]: *** [CMakeFiles/obs-ndi.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by vedranius** [comment]
@Palakis any idea what to do?

**Comment by Palakis** [comment]
@vedranius What is your compiler's version ?

**Comment by vedranius** [comment]
@Palakis ,  gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2)

**Comment by vedranius** [comment]
I'm not sure how to do it? 
Any way you can compile it or make deb? :P

**Comment by vedranius** [comment]
Hey @Palakis 
I'm trying on another Ubuntu machine, and I got to this right now... Any help what to do?
[http://pastebin.com/8Cd5HEVq](http://pastebin.com/8Cd5HEVq)

Thank you! :)

**Comment by Palakis** [comment]
@vedranius Which Ubuntu version and GCC version are you using? I enforced C++11 on the compiler last week.

**Comment by Palakis** [comment]
@vedranius Still GCC 4.8.5 ?

**Comment by Palakis** [comment]
@vedranius Also, did you tried this with the latest `master`? If not, `git pull` and try again, please.
