### ISSUE TITLE
Audio Issue / Stereo / NDI Audio Filter

### ISSUE THREAD

**Issue by MajeoT** [Palakis/obs-ndi#800]
### Discussed in https://github.com/Palakis/obs-ndi/discussions/799

<div type='discussions-op-text'>

<sup>Originally posted by **MajeoT** November 27, 2022</sup>
The sound recieved by the stream rig via an NDI audio filter from a dedicated audio source on my music line (like a virtual cable) on the goxlr is distorted/crackly and somewhat bass boosted/gain boosted it sounds like, when the OBS audio settings are set to "Stereo" or anything that isn't "Mono" for some reason, it wasn't like this last week.

If I drop it to Mono in Settings > Audio > General > Channels there is no distortion at all, however it doesn't sound as good as if it's on stereo though I doubt anyone would realistically notice as its more for background noise. None of the other settings, 2.1, 5.1 ect work, they're all crackly too though a little louder/clearer than Stereo. Changing it to mono is the "Advanced Audio Properties" but keeping it in Stereo as above still gives the same issue.

All of my sample rates are at 48kHz due to the GOXLR on both machines. I've tried reinstalling the ndi plugin but no luck.

I've tried "monitoring" the audio source on the game rig obs and it sounds fine, it sounds fine in the source its coming from (chrome/spotify) but it's disorted on the stream rig end when going out to the stream or using monitoring to test if its fixed or not, so something is happening when its being sent.

Running OBS version 28.1.2 64bit.</div>

**Comment by xghoulTK** [comment]
Just confirming same OBS version and settings as above with the same issue. 

Using the mono fix ATM that OP suggested.

**Comment by MajeoT** [comment]
I'm wondering if this is an issue with an updated NVIDIA driver as thats the only thing that could have changed in that time, I think I might have updated on either the game rig or the stream rig.

PC's for reference

Game Rig: i9 9900k / MSI GeForce RTX 3070 GAMING Z TRIO 8GB / 32gb 3600mhz LPX Vengeance / MX500 SSD x2 / Samsung 970 Evo Plus | Gigabyte Z390 AORUS Master | Corsair RM850 850 Gold PSU | NXZT Phantom Full Tower (White/Red) | NOCTUA nh-d15

StreamRig: Ryzen 7 1700 | GTX 1060 3GB | | 16gb 3000mhz LPX Vengeance Ram | B350 PC Mate | Aerocool Split Tempered Glass Windowed Mid Tower | CiT FX Pro 800W Power Supply | Masterliquid Ml240r AIO

Been using this stream rig since the Ryzen 7 1700 was new-ish and the game rig for around two years now.

**Comment by kree-nickm** [comment]
Possibly same issue as #785

**Comment by MajeoT** [comment]
https://github.com/DDRBoxman/obs-ndi/releases/tag/4.10.1 this fixes the issue :)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
