### ISSUE TITLE
macOS Universal Support

### ISSUE THREAD

**Issue by hstriepe** [Palakis/obs-ndi#808]
##### Issue type

 - Feature request

##### Description
The macOS version is currently x86_64 only. Please make it Universal adding ARM64. PleOBS has an M1 version which cannot use NDI libs running under Rosetta2.

##### Technical information
- **macOS 13.1** 
- **OBS Studio Version:28.1.2** 
- **obs-ndi Version: 4.10..0**

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
