### ISSUE TITLE
NDI Runtime Not found

### ISSUE THREAD

**Issue by stevecah** [Palakis/obs-ndi#809]
Issue type: NDI Runtime Not found Macbook Pro M1

##### Description
Upon running OBS Studio 28.1.2 on Macbook Pro M1  14-inch, 2021  A message appears "NDI Runtime Not found. No NDI source available." I have downloaded the runtime installer and installed and same issue again.

##### Technical information
- **Operating System:  MacOS Monterey 12.2.1** 
- **OBS Studio Version: 28.1.2** 
- **obs-ndi Version: 4.5.1** 
- 
![Screen Shot 2022-12-11 at 15 31 04 PM](https://user-images.githubusercontent.com/50542214/206927250-50c8729f-81ec-4c8f-ab98-dac8ddb0d978.png)

**Comment by stevecah** [comment]
I was able to solve this issue, now working.
1. Watch YouTube video.
https://youtu.be/EP3ZQAx7qL4

2. Instructions and file dl here @
https://github.com/kilinbox/obs-ndi/releases/tag/4.9.1

**Comment by Kormylets** [comment]
> I was able to solve this issue, now working.
> 
> 1. Watch YouTube video.
>    https://youtu.be/EP3ZQAx7qL4
> 2. Instructions and file dl here @
>    https://github.com/kilinbox/obs-ndi/releases/tag/4.9.1

Thank you!!!
