### ISSUE TITLE
Struggling to install on Ubuntu

### ISSUE THREAD

**Issue by Will737** [Palakis/obs-ndi#81]
Hi,
I'm quite new to Linux and I'm trying to install this plugin, I downloaded 'obs-ndi_4.2-1_amd64.deb' and 'libndi3_3.0.1-1_amd64.3.deb'. I then opened the terminal and typed:
'sudo dpkg -i libndi3_3.0.1-1_amd64.3.deb'
'sudo dpkg -i obs-ndi_4.2-1_amd64.deb'
and It all looked like it successfully installed, but when I launch obs the plugin doesn't seem to be installed. So I'm guessing I've not installed it properly. Is there another step to installing the plugin that I've missed?

Any help is much appreciated

**Comment by Palakis** [comment]
@Will737 Can you provide an OBS log, please?

**Comment by mrmakeit** [comment]
OBS now uses /usr/lib/x86_64-linux-gnu/obs-plugins as the plugin search directory instead of /usr/lib/obs-plugins.  So that may be what is happening here.

You may want to check that the plugin is in /usr/lib/x86_64-linux-gnu/obs-plugins and not /usr/lib/obs-plugins where they usually appear.

**Comment by huntingtiger1004** [comment]
Hi there, I've also run into the same problem, and am also a Linux noob. It was installing to the wrong directory, but I managed to copy the directory to the right spot according to what you said, double checked folder names. Despite this, OBS Studio still is not detecting it. If you're still willing to help with this, I'll be keeping an eye on this post. If you still need that OBS log, then I can try and provide that.

**Comment by Palakis** [comment]
@Will737 @mrmakeit @huntingtiger1004 Will be fixed in obs-ndi 4.6.1, which will be released later today.
