### ISSUE TITLE
Install fails on Macmini6,2

### ISSUE THREAD

**Issue by SciFiModelmaker** [Palakis/obs-ndi#811]
##### Issue type

 - Bug report

##### Description

Attempting to install obs-ndi-4.10.0-Qt6-macOS on Mac Mini late 2012 results in the following error being displayed:

You cannot install obs-ndi in this location. The obs-ndi installer does not allow its software to be installed here. (log and screenshot attached)

##### Steps to reproduce and other useful info

Download and attempt to install latest obs-ndi. Installation fails.

##### Technical information
- **Operating System:** macOS 10.15.7 (19H2026)
- **OBS Studio Version:** 28.1.2
- **obs-ndi Version:** 4.10-Qt6

Thanks for any light you can shed.

[2022-12-12 10-48-50.txt](https://github.com/Palakis/obs-ndi/files/10217949/2022-12-12.10-48-50.txt)
![Screen Shot 2022-12-13 at 7 05 02 AM](https://user-images.githubusercontent.com/2197487/207320699-08ea32e5-fe59-4a3c-979d-2106864535fc.png)

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
