### ISSUE TITLE
NDI Source Not Showing in OBS 28.1.2

### ISSUE THREAD

**Issue by priscillareiss** [Palakis/obs-ndi#815]
##### Issue type
Bug report

##### Description
My HD60S Game Capture card is not findable as either an NDI Source or as a Video Capture Device in OBS 28.1.2 - Does anyone have insight about what the issue might be?

##### Steps to reproduce and other useful info
I have an Intel Mac and installed obs-ndi-4.10.0-Qt6-macOS.pkg and NDI 4.5.1 macOS runtime.
I then installed OBS 28.1.2

##### Technical information
Operating System: Mac Ventura 13.0.1 
OBS Studio Version: OBS 28.1.2
obs-ndi Version: 4.5.1 and I also tried 5.0.10.1

[ndi-runtime-5.0.10.1-macOS.pkg](https://ndi.palakis.fr/runtime/ndi-runtime-5.0.10.1-macOS.pkg)

[2022-12-23 14-58-14 copy.txt](https://github.com/Palakis/obs-ndi/files/10297135/2022-12-23.14-58-14.copy.txt)

**Comment by Trouffman** [comment]
The HD60S Game Capture is Capture card This is not an NDI source but a Video Capture Device.

Lookign at your error log, NDI plugin is not loaded

`
Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not loaded
`

Seems your deveice is not accessible as well : 
`
14:58:16.296: coreaudio: failed to find device uid: AppleUSBAudioEngine:Synaptics:Hi-Res Audio:000000000000000000000000:1, waiting for connection
14:58:16.353: Video Capture Device: Could not initialize device with unique ID '0xd1300000fd90066'
14:58:16.353: Source ID 'ndi_source' not found
14:58:16.354: Failed to create source 'NDI™ Source'!
`
These do not seems related to the NDI plugin

Please do a full test for your Capture Card as :

Do the following to test:

- [ ]  make a new scene collection
- [ ]  only one scene
- [ ]  only one source (your HD60S Source)
- [ ]  Set the source to be the full size (transfrom > fit to screen/canva)
- [ ]  nothing else

This is as far as the testing will go for your Capture Card >or reach out to the OBS community for Support.

For the NDI error : 
- Do a proper Reinstall of the OBS-NDI plugin using the latest release.

**Comment by priscillareiss** [comment]
I am not sure if you have a Mac, but using OBS requires you to load the HD60S Game Capture card as an NDI Source. The issue is absolutely related to the NDI plug in. The reason the HD60S device is not accessible is because the NDI plugin 4.10.0 does not include all of the necessary files to load it as an NDI source.

I did some independent trouble shooting and found that NDI 4.10.0 does not install a "obs-ndi" folder in Application Support > obs-studio. 
However, NDI 4.9.0 does install this folder.

Therefore, I had to do the following:
Download and Install NDI 4.9.0 THEN Download and Install NDI 4.10.0 ...

**Comment by Trouffman** [comment]
the 4.10.0 release is messed up. Glad you fixed it.

If you need the latest NDI Runtime for MacOS, they can be Downloaded at : http://new.tk/NDIRedistV5Apple

NB : I havent seen much feedback using 5.5.2.0 on Mac yet.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
