### ISSUE TITLE
NDI Source showing no output on OBS 28.1.2

### ISSUE THREAD

**Issue by anaisbetts** [Palakis/obs-ndi#819]
##### Issue type

- Bug report

##### Description

After upgrading OBS to the above version, updating the plugin, installing the new NDI runtime version and rebooting, I can no longer get NDI source working with the phone app like it did in the past.

##### Steps to reproduce and other useful info

1. Install the NDI Android app
2. Set up an NDI source, point it at the Android app, it shows up in the list
3. The source is blank/black

##### Technical information
- **Operating System:** Windows 11 (10.0.25267.1000)
- **OBS Studio Version:** 28.1.2
- **obs-ndi Version:** 4.10.0

There doesn't appear to be much in the way of information, but the OBS log file is here: https://gist.github.com/anaisbetts/9f6565a3cfec83216aa30b4b83fbe932 - let me know if I can provide any other debugging information that would help, I know this isn't much to go on

**Comment by Trouffman** [comment]
Hey @anaisbetts 

In your logs it seems fine : to get the NDI Runtime
```
18:01:58.085: [obs-ndi] hello ! (version 4.10.0)
18:01:58.085: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Runtime\v4'
18:01:58.085: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
18:01:58.127: [obs-ndi] NDI runtime loaded successfully
18:01:58.130: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
```

First, update the NDI Runtime to the latest at : http://new.tk/NDIRedistV5

Then
Do the following to test:

- [ ] make a new scene collection
- [ ] only one scene
- [ ] only one source (your NDI phone source)
- [ ] Set the source to be the full size (transfrom > fit to screen/canva)
- [ ] nothing else

Test if working.

If not, find out if this is the plugin or something else NDI related.

- [ ] Install the NDI Tools
- [ ] Open NDI Studio Monitor

Can you see your source & see the video ?

Please report the new log file of that test - might help!

**Comment by anaisbetts** [comment]
After updating to the latest NDI v5 runtime, I am unable to see the phone in the source properties page. I can only see a "(My Computer Name) Remote Connection 1" source which seems to have been added by NDI Tools as it wasn't there before. 

I _can_ see the source in NDI Studio Monitor and video works correctly there.

The latest log from a clean obs-studio profile:

https://gist.github.com/anaisbetts/98d51957ac02f55b3a112ea0bfbfe67c

**Comment by Trouffman** [comment]
As this is working in the studio monitor, that means the communication between phone and PC is okay .

Please confirm : what is the app on your phone + phone model
Are both connected to the same Network (aka same wifi or at least same subnet)

Can you see the NDI source in the drop-down menu in the ndi source settings ?

Confirm that OBS can access the network without problem (this can come from windows firewall) - to test you can disable it for a couple minutes to do the test.

From the log file the plugin seems to load fine. 

Anything called "ani" rings a bell ?

Thanks

**Comment by anaisbetts** [comment]
@Trouffman Yes, that was me trying to type into the source box to auto-complete the actual name of the source "ANIS Z-FLIP 4" assigned by the NDI Phone app, it doesn't actually exist

**Comment by Trouffman** [comment]
Thanks for the details.
> > Please confirm : what is the app on your phone + phone model
> 
> The NDI source name usually comes out as "ANIS Z-FLIP 4" or something to this effect

Are you using the official NDI Camera app or another one (if so, which one)?


> > Confirm that OBS can access the network without problem (this can come from windows firewall) - to test you can disable it for a couple minutes to do the test.
> 
> I can try this, but OBS hasn't had network access issues before
Please report if this fixed the problem.


> > Can you see the NDI source in the drop-down menu in the ndi source settings ?
> 
> With NDI v4 runtime I _could_ (but the video was black), with NDI v5 I _cannot_ see the source in the dropdown.
The behavior is expected to be the same as they use the same discovery method.
Normally if you do not see the device in the drop-down, it means something it is not communicating / or allowing it ( hence the firewall test above).

As you tested witht he Studio Monitor and confirmed it worked : we can assum "the phone app" is working :D !

> Yes, that was me trying to type into the source box to auto-complete the actual name of the source "ANIS Z-FLIP 4" assigned by the NDI Phone app, it doesn't actually exist. The only source that is found is the "(MY COMPUTER NAME) Remote Connection 1" which seems to be from the NDI Tools.
Correct the "Remote Connection 1" is added by the NDI Tools (that can be disabled in "NDI Remote".

As above, if it is not in the dropdown, it will not be accessible anyway.

> Do you have a good place that I could add some extra logging around network discovery? I don't mind building this plugin from source and attaching a debugger
Actually.. no I don't :(

Please do the test "diablign the firewall" to test.

**Comment by anaisbetts** [comment]
> Are you using the official NDI Camera app or another one (if so, which one)?

I am using the official NDI camera app, "NDI HX Camera v1.63"

> Please do the test "diablign the firewall" to test.

I'll give this a try

**Comment by Trouffman** [comment]
@anaisbetts  : I jsut tested between Android (13 (Pixel 7 pro) and Windows 11 on OBS 29 with OBS-NDI 4.10.1 (From DDRBoxman repo) - this did not work until I set the Network on "Private" 

To get this : 
- Search fro Network and Internet Settings
- Advanced Network Settings
- Get on the connected Network (wifi or Wired) then on the correct Name
- Set Network profile type to "Private Network"

![image](https://user-images.githubusercontent.com/2151317/214392727-71d51ec7-850c-4b01-83dc-05816971ce22.png)

for the firewall "whitelisting"
Get to "Allowed Apps" Find OBS Studio, allow on both private and public.
![image](https://user-images.githubusercontent.com/2151317/214392980-b2de3b49-6647-4ec2-b349-c05c209ebb5a.png)

If you have multiple OBS instsances installed ( or portable) make sure the link in the app is the correct one (double-click int he list)

**Comment by jbcurler2010** [comment]
I have always been told it is a MUST to ALWAYS set network to Private and disable firewall for NDI.

**Comment by anaisbetts** [comment]
Myth Confirmed, this was a firewall issue. I run this machine on the Insiders Dev channel, and I suspect that my firewall settings (in particular, the public vs. private network setting) gets stomped on upgrade.

Given that OBS is often run as elevated administrator, it might be worth in a future PR to actually attempt to configure the firewall explicitly in code, so that this is a Headache that users Won't Know They Won't Have

**Comment by Trouffman** [comment]
> I have always been told it is a MUST to ALWAYS set network to Private and disable firewall for NDI.

This is soemwhat correct, but you can still haev the firewall on, as long as you are set in "Private" it should work.


> Myth Confirmed, this was a firewall issue. I run this machine on the Insiders Dev channel, and I suspect that my firewall settings (in particular, the public vs. private network setting) gets stomped on upgrade.
> 
> Given that OBS is often run as elevated administrator, it might be worth in a future PR to actually attempt to configure the firewall explicitly in code, so that this is a Headache that users Won't Know They Won't Have

You shoudl have a prompt from OBS, the first time you try to run it  where it triggers "do you want this application to access network" And you pick private / public :)

NB : this is not plugin related IIRC, but OBS itself.

**Comment by anaisbetts** [comment]
> You shoudl have a prompt from OBS, the first time you try to run it where it triggers "do you want this application to access network" And you pick private / public :)

Nope, never got that prompt :(
