### ISSUE TITLE
[Question]NDI Plugin support for Streamlabs OBS (SLOBS)

### ISSUE THREAD

**Issue by joXnka** [Palakis/obs-ndi#82]
Hello!
Streamlabs just came out with their own version of OBS Studio called Streamlabs OBS (or SLOBS, as people have began calling it)
At the time it has almost the full functionality of OBS Studio, but it unfortunately does not support your NDI plugin. Is there a possibility you could work with SL to get it integrated?
Info on SLOBS: https://streamlabs.com/streamlabs-obs
Kindest regards,
joXnka

**Comment by Palakis** [comment]
Thanks for your interest @joXnka! Unfortunately, [as I explained here](https://github.com/Palakis/obs-websocket/issues/174), SLOBS has some pieces missing that prevent support of some existing OBS plugins. Unless Streamlabs fixes it on their end.

**Comment by Palakis** [comment]
Alternatively, I could think of a compromise to make obs-ndi compatible with SLOBS. However, only the NDI source (input source) would be available in SLOBS, not the main output.

**Comment by Farmagud** [comment]
That’s a pretty fair compromise, as the main selling point to using SLOBS is just being able to have Chatbot/twitch chat all in one window on your second monitor. Even just having NDI input for SLOBS would make for a much cleaner setup on my second PC/monitor.

**Comment by PixelTwitch** [comment]
Personally I would just be happy be have NDI input in the SLOBs version, I only use OBS on my gaming computer to send over the game and audio.

**Comment by chiefscott** [comment]
Please enable the input!

**Comment by Palakis** [comment]
I'm seeing progress on SLOBS compatibility. Maybe results in the coming days.

**Comment by PixelTwitch** [comment]
Great news, I for one will keep my fingers crossed!

**Comment by chiefscott** [comment]
Hope to hear about this soon! Would enable the ultimate setup imo! really appreciate your energy to it

**Comment by kersk** [comment]
Would love to have NDI support w/ SLOBS, even if it's only the input. I can use vanilla OBS on my NDI source PC.

**Comment by TheAdamame** [comment]
Is there any update to this? Would love to know!

**Comment by Acans** [comment]
+1 Input would be awesome :D

**Comment by travv** [comment]
bump, still looking for SL-OBS integration

**Comment by chiefscott** [comment]
[SLOBS road map](https://trello.com/b/oTl4KiBW/streamlabs-obs-roadmap)

SLOBS' official twitter linked that [here](https://twitter.com/StreamlabsHQ/status/958762989292834817)

So it's coming down the pipe eventually, hopefully its not 2019 by that time. Only thing preventing me from using SLOBS is NDI.

**Comment by TSKsmiley** [comment]
4. Of march they stated active development of integrating it into SLOBS

**Comment by Palakis** [comment]
Right now, the only thing preventing obs-ndi from running into SLOBS is the incompatible compiler versions. obs-ndi is built with VS2013, sames as OBS studio, while SLOBS is built with VS2015.

But still, obs-ndi would only be able to work as an input.
It's good to know that people at Streamlabs are working on NDI support for their software. But on the other hand, I personally think it makes no *bloody* sense to name something with "OBS" in it if said thing can't support the existing OBS Studio ecosystem, even if the app's core is libobs.

**Comment by TSKsmiley** [comment]
Palakis I see what you mean I think that the only reason they call it StreamLabs obs is that its based on the obs core and people are familiar with it

**Comment by Beast96GT** [comment]
Hey Palakis, I'm just curious as to why there's a compiler issue.   I build and work on OBS in VS2017 with no issue.  Is there something I'm not taking into account?

**Comment by Palakis** [comment]
@Beast96GT The compiler issue concerns releases. OBS Studio is built with VS2013, while SLOBS is built with VS2015.
No problems when building both OBS Studio and obs-ndi with VS2017 though.

**Comment by Palakis** [comment]
obs-ndi is now shipped with Streamlabs OBS.

**Comment by Greezyxp** [comment]
Hey Palakis, i saw that streamlabs obs has ndi source now but i have a problem when i try to capture a game in fullscreen mode the game is just frozen. And the game is Fortnite, the only way i can capture it with ndi is by putting the game in windowed fullscreen mode. But i don't want to do that because the game is laggy in trhis mode. Hope you can help me, thanks !
