### ISSUE TITLE
Same issue here! OSB 29.0.1 no NDI plugin in sources after installing 4.10.0 iMAC

### ISSUE THREAD

**Issue by tinykanters** [Palakis/obs-ndi#827]
Same issue here! OSB 29.0.1 no NDI plugin in sources after installing 4.10.0 on iMAC

##### Technical information
- **Operating System:** 
- **OBS Studio Version:** 
- **obs-ndi Version:**

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
