### ISSUE TITLE
NDI screen works but not OBS-NDI (V29)

### ISSUE THREAD

**Issue by Brainarea** [Palakis/obs-ndi#828]
I want to send OBS source from a PC to a MAC. 

Installed  latest version of OBS on both machine then NDI. Plugin shows up on both. 
When I use NDI screen capture on my PC, then NDI source on OBS on my mac works perfectly.
But when I use OBS-NDI on my PC then my MAC can see the output name that I did setup but screen remains black! 
Its as if everything works but it doesnt send any data !

**Comment by blindjerry** [comment]
I am having the exact same issue. I am trying to send the output from 1 windows 11 OBS instance to a second windows 11 OBS instance on a separate machine.  The output is always black, but if I do it via NDI Screen Capture it will show up on the second pc running OBS.  Any help would be appreciated.
OBS v29.0.2 and OBS-NDI v4.10.1

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; I did see this once and rebooted and the problem went away.
Closing.
Feel free to re-open if you test and disagree.
