### ISSUE TITLE
NDI Sources not showing in OBS 29.02 under NDI 5.5.3 on a new W10Pro Installation

### ISSUE THREAD

**Issue by jjpoelli** [Palakis/obs-ndi#836]
Hi,
I'm having a problem on a fresh W10Pro installed new machine. Although everything is working fine on 3 other computers with OBS 29.0.2 and NDI 5.5.3, the new HP Elitebook i7 does not show any source in OBS 29.0.2 with NDI 5.5.3. All drivers are actual, BIOS is updated and all sources are visible in the NDI Studio Monitor. So all networksettings etc. seem to be correct. 
After hours of testing I have no other explanation as an incompatibility of the NDI plugin to OBS....
Thanks VERY MUCH for help since the new computer was intended to be used with OBS and NDI only....
Josef

**Comment by antmerino** [comment]
The same thing happens to me, same plugin version and same ndi version. Both pc on the same subnet. Any solution? thks

**Comment by jjpoelli** [comment]
UPDATE: I had got the new computer with preconfigured W10Pro 64Bit. Since there was not very much software installed I reinstalled Windows 10 Pro once again on a blank drive. Now ist works as it has to with this configuration: OBS 29.0.2, NDI-Plugin 4.10.0 and NDI 5.5.3. Everything ok! No more problems. :-)

**Comment by Jaybonaut** [comment]
> UPDATE: I had got the new computer with preconfigured W10Pro 64Bit. Since there was not very much software installed I reinstalled Windows 10 Pro once again on a blank drive. Now ist works as it has to with this configuration: OBS 29.0.2, NDI-Plugin 4.10.0 and NDI 5.5.3. Everything ok! No more problems. :-)

Where can we get 5.5.3?

**Comment by jjpoelli** [comment]
Here: https://ndi.tv/tools/

**Comment by frob** [comment]
Does anyone have a direct link? The download link is broken.

**Comment by frob** [comment]
Looks like pi-hole was blocking the domain for some reason.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by jjpoelli** [comment]
Hej Paul, tested your RC on two of our 4 systems and did not experience any problem. Thank You! :-)

**Comment by paulpv** [comment]
Welcome! Closing.
