### ISSUE TITLE
audio glitchy and lagging. log in pastebin

### ISSUE THREAD

**Issue by georgetdawson** [Palakis/obs-ndi#839]
https://pastebin.com/fJpc2tD3

says in log audio lagging "Source Desktop Audio audio is lagging (over by 75538.88 ms) at max audio buffering. Restarting source audio.
"
really annoying as i dont know how to stream right now

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849

**Comment by paulpv** [comment]
This seems fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.
