### ISSUE TITLE
Low Fps Problem

### ISSUE THREAD

**Issue by batuhanapatay** [Palakis/obs-ndi#84]
Hello.

I just started to use this plugin and I couldn't get a smooth video transfer over network. 

I connected both PC to the router with ethernet cable and both have a gigabit connection. (Internet Speed is not important I believe.) 

I can't get 60 fps at 1080p or 720p. If I down to 360p or something like that it becomes so smooth. I don't know what am I doing wrong. 

Stream PC has i7 4700HQ and Main Pc has 8700k. 

What should I do?

https://youtu.be/XO0iqHPXjYQ

**Comment by MrBagZ** [comment]
What is your bitrate on gaming and streaming pc?

**Comment by batuhanapatay** [comment]
Does it matter? I was seeing the preview laggy. Before streaming or recording. 

I don't know why but after I restarted my router problem has been fixed. Now it looks perfect.

**Comment by PatTheMav** [comment]
Can confirm, the NDI source is visibly not 60fps even in the preview window on the second machine (2015 27" iMac in my case).

I'll restart my managed gigabit switch later to see if this will fix the issue. But all my streams so far have been encoded at 60fps, but the NDI source' frame rate was always lower (I was able to spot that the animations in my browser source were encoded at fluid 60fps, the game was not). Encoding bitrate is 9Mbit for Youtube.

**Comment by Palakis** [comment]
@PatTheMav If you're using a manageable switch, try disabling any bandwidth control or QoS feature to see if it improves the situation.

**Comment by Palakis** [comment]
@batuhanapatay Make sure there's nothing else consuming bandwidth or your computer, like a BitTorrent client, game updates or other downloads.

**Comment by PatTheMav** [comment]
@Palakis Will check when I’m back home - I believe I only have IGMP snooping and VLAN features on (got IPTV at home).

But was able to confirm that all links were autoconf’ed to 1Gbit and the cable tester showed 0% errors.

**Comment by batuhanapatay** [comment]
Last time I checked it was smooth. And task manager was showing like 150 mbps for that. How much I should see in normal case scenario?

**Comment by PixelTwitch** [comment]
The reality is that at 360p its still not likely smooth its just that the size of the pixels makes the big stutters appear smaller. I believe this is actually a problem with a lack of buffering... I do believe all the frames reach the streaming PC OBS I just believe that they can be desynced causing OBS to constantly miss a frame a frame.

**Comment by JesmoDK** [comment]
I have found, that the stutter is from the playback or your NDI "recording". If you run OBS on a second monitor with e.g. Nvidia FPS overlay, you can see, that the fps of the playback is not a stable 60, especially if you have a GPU intensive game running in the forground. I guess we need some kind of way to priorities the NDI playback over the game.

**Comment by Palakis** [comment]
@MrBagZ streaming bitrate has nothing to do with NDI. It only targets H.264 encoding.
