### ISSUE TITLE
Package NDI 5.5.3 runtime

### ISSUE THREAD

**Issue by qwertychouskie** [Palakis/obs-ndi#841]
https://drive.google.com/file/d/1EpcKOviy7lGK4rM4xcbIz-6yl5-lKZ71/view?usp=sharing

[libndi5_5.5.3-1_amd64.zip](https://github.com/Palakis/obs-ndi/files/10776360/libndi5_5.5.3-1_amd64.zip)
[libndi5-dev_5.5.3-1_amd64.zip](https://github.com/Palakis/obs-ndi/files/10776361/libndi5-dev_5.5.3-1_amd64.zip)

The above debs contain a symlink from `libndi.so.4` to `libndi.so.5` to maintain compatibility with the current obs-ndi release.

**Comment by paulpv** [comment]
This is fixed in 4.11.0-RC; Closing.
Feel free to re-open if you test and disagree.

**Comment by qwertychouskie** [comment]
Perfect, thanks!
