### ISSUE TITLE
OBS 29 Compatibility Fix

### ISSUE THREAD

**Issue by SMVampire** [Palakis/obs-ndi#845]
Using WIndows 10 I was able to get OBS 29.X compatibility by using NDI 5.0.10.1 Runtime. Before it was a blank source.

Here's the link to the runtime directory that the current windows installer has you download.

https://ndi.palakis.fr/runtime/

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
