### ISSUE TITLE
Issue installing with MacOS

### ISSUE THREAD

**Issue by weldontgreen** [Palakis/obs-ndi#85]
macOS high sierra v. 10.13.2
MacBook Pro (Retina, 13-inch, Early 2015)

OBS studio 0.16.2 (most recent)
Plugins: -obs-browser

### Steps so far:

1. Installed via your .pkg installer
2. Start OBS
3. Nothing there
4. Install again
5. Same
6. Install ndi runtime
7. Same
8. Check log files

Excerpt from most recent startup: [2018-01-11 10-24-17.txt](https://github.com/Palakis/obs-ndi/files/1623537/2018-01-11.10-24-17.txt)

`10:32:57.893: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1): Library not loaded: @rpath/QtWidgets
10:32:57.893:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
10:32:57.893:   Reason: Incompatible library version: obs-ndi.so requires version 5.9.0 or later, but QtWidgets provides version 5.4.0`

9. Install Qt 5.10.01 via Homebrew `brew install qt`
10. Start OBS
11. Same

Excerpt from that startup: [2018-01-11 11-23-20.txt](https://github.com/Palakis/obs-ndi/files/1623548/2018-01-11.11-23-20.txt)

`11:23:21.842: os_dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so->/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so): dlopen(/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so, 1): Library not loaded: @rpath/QtWidgets
11:23:21.842:   Referenced from: /Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so
11:23:21.842:   Reason: Incompatible library version: obs-ndi.so requires version 5.9.0 or later, but QtWidgets provides version 5.4.0
11:23:21.842: 
11:23:21.842: Module '/Library/Application Support/obs-studio/plugins/obs-ndi/bin/obs-ndi.so' not found`

I am not sure on the next step to take. Sorry if there's info missing or I submitted this wrong.

**Comment by dodgepong** [comment]
0.16.0 is not the most recent version of OBS. The most recent version is 20.1.0 for Mac.

**Comment by Palakis** [comment]
@weldontgreen Please update to the **latest** stable version of OBS Studio (currently 23.2.1) along with the latest version of the NDI plugin.
