### ISSUE TITLE
[Bug]: obs-ndi 4.10.0 source tarball is from the wrong branch

### ISSUE THREAD

**Issue by bunder2015** [Palakis/obs-ndi#852]
### Operating System Version

gentoo

### OBS Version

28.1.2 and 29.0.2

### NDI Tools Version

[ndi-sdk-bin 5.0.10.1](https://gist.github.com/bunder2015/a709de57a37f8daf0acb71c56f085378)
[obs-ndi 4.10.0](https://gist.github.com/bunder2015/d2fe29cfcc237cd2244a80f1dcce4801)

### Describe the bug

Upgraded ndi packages to support obs 28 or 29, when trying to send video from one PC to another, the receiving PC's obs freezes.  No errors in logs.   All the ui stuff works, just not the a/v send/receive.

### Steps to reproduce

- Install obs on gentoo
- Install ndi using ebuilds above
- Open obs and try using ndi

### Expected behavior

Being able to see source on receiving PC's obs

### Additional context

I wrote those ebuilds based on older (working) ebuilds from the [kripton overlay](https://github.com/kripton/kripton-overlay/tree/master/media-video), if there is an error, please let me know so I can try to fix them :)

edit: I also tried building obs-ndi with sdk 4.5.1, but I only got an error on startup that sdk 5 wasn't installed.

**Comment by bunder2015** [comment]
I think I see what's up with the sdk 5 error...  the obs-ndi-dummy-tag-4.10.0 tarball package is different than the deb files listed...  it appears to be from a sdk 5 branch rather than 4.5.1.

**Comment by paulpv** [comment]
This should be resolved in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
