### ISSUE TITLE
[Clean-up]: Update the Locale files to redirect to the correct Runtime download link

### ISSUE THREAD

**Issue by Trouffman** [Palakis/obs-ndi#856]
### NDI Tools Version

4.11 and above!

### Describe the bug

4.11 and above rely on the NDI 5 Runtime, the links in "locales" are redirecting to the old 4.x on palakis FTP.

Option A : Use the official Link (when working...)
Option B : Redirect to #831 
Option C : Have a redirection in place on controlled & reliable domain/url?

Note : Not sure there is a way to have the liunk to be a globale variable: aka : managed at a central (source of truth). 

To -do 
- [ ] Decide option to implement
- [ ] Do the update :)

**Comment by paulpv** [comment]
Weird! Is this really showing the old urls in 4.11?
The code is updated to use the new paths and not Palakis' server:
https://github.com/Palakis/obs-ndi/blob/develop/data/locale/en-US.ini#L40-L41
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1393897/222684966-3b84f82e-d710-48bc-b14f-2c95fcdc30cb.png">
Maybe there is just something wrong w/ the build?

**Comment by Trouffman** [comment]
I made an error when testing. And tested with the wrong environment -_-
You are correct ,things have been updated!
