### ISSUE TITLE
Progressive Audio Desync

### ISSUE THREAD

**Issue by icallmidsolo** [Palakis/obs-ndi#86]
Hello friends,
I have been streaming Overwatch/HotS over the past two weeks from OBS to Twitch. I was trying to stream from my gaming computer alone at first, but had to turn my graphics down to low and was still getting very choppy results. Now I am using an older PC as a streaming PC and using OBS/NDI to get the input. The video is coming across well, but my viewers say audio appears to be 1-5 seconds delayed. The stream usually starts out with no delay, and then gets progressively worse throughout the session. I notice I get this message in my log often: "adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds" even after turning off device timestamps. 

Another question, does it matter if we have notification/alerts set up on gaming pc vs stream pc? I currently have my scenes set up on my gaming PC. Didn't think that would matter, but thought I would ask.

Setup: 
Computer A (Gaming): 
CPU - i5-6600K (base clock)
GPU - GTX1080
RAM - 16GB
OBS A settings - 
Output ~ rescale to: 720p; encoder: x264; rate control: CBR; video bitrate: 4500; Audio: 160
Audio ~ 48khz
Video ~ base: 2560x1440; rescale to: 1280x720; bicubic 16samples; 60FPS
In Advance - Audio - audio monitoring device - should i have this at default and checked "disable windows audio ducking"?

Computer B (Streaming): CPU - 
CPU - i7-2600
GPU - AMD Radeon HD 6670
RAM - 12GB
OBS B settings - 
Output ~ rescale to: 1280x720; encoder: x264; rate control: CBR; video bitrate: 4500; audio: 160
Audio ~ 48khz
Video ~ base: 1920x1080; rescale to: 1280x720; bicubic 16samples; 30FPS (thought this was at 60, will change to 60...)
Avanced Audio Properties: Monitor & Output OBS A; Monitor Only Desktop Audio
NDI Source: Bandwidth Highest, Sync Internal

Uploading Logs from Computer A (Gaming PC - I see "Adding XYZms of audio buffering...").

[2018-01-10 19-08-46.txt](https://github.com/Palakis/obs-ndi/files/1627164/2018-01-10.19-08-46.txt)
[2018-01-10 20-08-25.txt](https://github.com/Palakis/obs-ndi/files/1627165/2018-01-10.20-08-25.txt)
[2018-01-10 20-18-29.txt](https://github.com/Palakis/obs-ndi/files/1627166/2018-01-10.20-18-29.txt)
[2018-01-10 21-24-12.txt](https://github.com/Palakis/obs-ndi/files/1627167/2018-01-10.21-24-12.txt)
[2018-01-10 16-35-41.txt](https://github.com/Palakis/obs-ndi/files/1627168/2018-01-10.16-35-41.txt)
[2018-01-11 18-16-33.txt](https://github.com/Palakis/obs-ndi/files/1627169/2018-01-11.18-16-33.txt)
[2018-01-11 18-38-55.txt](https://github.com/Palakis/obs-ndi/files/1627170/2018-01-11.18-38-55.txt)
[2018-01-12 10-41-36.txt](https://github.com/Palakis/obs-ndi/files/1627171/2018-01-12.10-41-36.txt)

**Comment by Palakis** [comment]
The desync appears to be unrelated obs-ndi if the "adding audio buffering" messages appear only on the gaming computer.
Some sources (except game capture, desktop capture and browser source) are known to possibly cause desync.

In your Desktop Audio source, try disabling "Use device timestamps". It is enabled by default. Webcams can also be the cause. Try running a test stream without and see if the audio buffering happens again.
