### ISSUE TITLE
Black screen dual-pc stream setup issue

### ISSUE THREAD

**Issue by cpigrome** [Palakis/obs-ndi#88]
Hi,

I have been trying to setup a two PC stream setup using the NDI Output plugin for OBS but I am having an issue when sending my stream on my gaming PC to my streaming PC.

When I add NDI output as a source on my streaming PC and then select the NDI source name of my gaming I get a small red circle in my top left corner and a black screen. 

But when I try and do it the opposite way around by adding NDI output as a source on my gaming PC it works fine and I can stream from my streaming PC to my gaming PC. It's strange as there is obviously something going on my gaming PC that doesnt allow OBS and the NDI output plugin to stream to my streaming PC. 

Any suggestions or help would be much appreciated.

Many thanks!

Heres the log on my streaming PC.

16:46:24.964: CPU Name: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
16:46:24.965: CPU Speed: 3392MHz
16:46:24.965: Physical Cores: 4, Logical Cores: 4
16:46:24.965: Physical Memory: 8078MB Total, 6427MB Free
16:46:24.965: Windows Version: 10.0 Build 16299 (revision: 125; 64-bit)
16:46:24.965: Running as administrator: false
16:46:24.965: Aero is Enabled (Aero is always on for windows 8 and above)
16:46:24.965: Windows 10 Gaming Features:
16:46:24.965: 	Game Bar: Off
16:46:24.965: 	Game DVR Allowed: Yes
16:46:24.965: 	Game DVR: On
16:46:24.965: 	Game DVR Background Recording: Off
16:46:24.966: 	Game Mode: Off
16:46:24.966: Portable mode: false
16:46:24.979: OBS 20.1.3 (64bit, windows)
16:46:24.979: ---------------------------------
16:46:24.979: ---------------------------------
16:46:24.979: audio settings reset:
16:46:24.979: 	samples per sec: 44100
16:46:24.979: 	speakers:        2
16:46:24.980: ---------------------------------
16:46:24.980: Initializing D3D11...
16:46:24.980: Available Video Adapters: 
16:46:24.981: 	Adapter 1: Intel(R) HD Graphics 4000
16:46:24.981: 	  Dedicated VRAM: 33554432
16:46:24.981: 	  Shared VRAM:    1845493760
16:46:24.981: 	  output 1: pos={0, 0}, size={1920, 1080}, attached=true
16:46:24.983: Loading up D3D11 on adapter Intel(R) HD Graphics 4000 (0)
16:46:24.985: D3D11 loaded successfully, feature level used: 45056
16:46:25.634: ---------------------------------
16:46:25.634: video settings reset:
16:46:25.634: 	base resolution:   1920x1080
16:46:25.634: 	output resolution: 1920x1080
16:46:25.634: 	downscale filter:  Bicubic
16:46:25.634: 	fps:               30/1
16:46:25.634: 	format:            NV12
16:46:25.635: Audio monitoring device:
16:46:25.635: 	name: Default
16:46:25.635: 	id: default
16:46:25.635: ---------------------------------
16:46:25.638: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
16:46:25.639: [AMF] Encountered Exception during AMF initialization: Unable to load 'amfrt64.dll', error code 126.
16:46:25.639: Failed to initialize module 'enc-amf.dll'
16:46:25.644: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
16:46:25.644:  (126)
16:46:25.645: [obs-ndi] hello ! (version 4.0.1)
16:46:25.645: [obs-ndi] Found NDI runtime directory at C:\Program Files\NewTek\NewTek NDI Redist\v3
16:46:25.645: [obs-ndi] Found NDI library at C:\Program Files\NewTek\NewTek NDI Redist\v3\Processing.NDI.Lib.x64.dll
16:46:25.671: Couldn't find VLC installation, VLC video source disabled
16:46:25.678: No blackmagic support
16:46:25.771: ---------------------------------
16:46:25.771:   Loaded Modules:
16:46:25.771:     win-wasapi.dll
16:46:25.771:     win-mf.dll
16:46:25.771:     win-dshow.dll
16:46:25.771:     win-decklink.dll
16:46:25.771:     win-capture.dll
16:46:25.771:     vlc-video.dll
16:46:25.771:     text-freetype2.dll
16:46:25.771:     rtmp-services.dll
16:46:25.771:     obs-x264.dll
16:46:25.771:     obs-vst.dll
16:46:25.771:     obs-transitions.dll
16:46:25.771:     obs-text.dll
16:46:25.771:     obs-qsv11.dll
16:46:25.771:     obs-outputs.dll
16:46:25.771:     obs-ndi.dll
16:46:25.771:     obs-filters.dll
16:46:25.771:     obs-ffmpeg.dll
16:46:25.771:     image-source.dll
16:46:25.771:     frontend-tools.dll
16:46:25.771:     enc-amf.dll
16:46:25.771:     coreaudio-encoder.dll
16:46:25.771: ---------------------------------
16:46:25.771: ==== Startup complete ===============================================
16:46:25.772: Service '' not found
16:46:25.774: All scene data cleared
16:46:25.774: ------------------------------------------------
16:46:25.900: WASAPI: Device 'Speakers / Headphones (Realtek High Definition Audio)' initialized
16:46:25.903: Switched to scene 'Scene'
16:46:25.903: ------------------------------------------------
16:46:25.903: Loaded scenes:
16:46:25.903: - scene 'Scene':
16:46:25.903:     - source: 'NDI™ Source' (ndi_source)
16:46:25.903: ------------------------------------------------
16:46:28.976: User Removed source 'NDI™ Source' (ndi_source) from scene 'Scene'
16:47:03.293: User added source 'NDI™ Source' (ndi_source) to scene 'Scene'
16:47:16.913: User Removed source 'NDI™ Source' (ndi_source) from scene 'Scene'
16:48:03.499: Switched to Preview/Program mode
16:48:03.499: ------------------------------------------------
16:48:04.451: User switched to scene 'Scene'
16:48:04.452: Switched to regular Preview mode
16:48:04.452: ------------------------------------------------
16:48:22.736: ---------------------------------
16:48:22.736: video settings reset:
16:48:22.736: 	base resolution:   1920x1080
16:48:22.736: 	output resolution: 1920x1080
16:48:22.736: 	downscale filter:  Bicubic
16:48:22.736: 	fps:               60/1
16:48:22.736: 	format:            NV12
16:48:22.749: Settings changed (video)
16:48:22.749: ------------------------------------------------
16:48:53.111: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds
16:48:53.743: User added source 'NDI™ Source' (ndi_source) to scene 'Scene'

**Comment by PixelTwitch** [comment]
How are they connected?

**Comment by cpigrome** [comment]
They're both connected with Ethernet cables. I tried doing that and still having no luck :(

**Comment by Palakis** [comment]
General networking tips with NDI:
- Use Gigabit Ethernet
- Use a proper switch, either managed or unmanaged, instead of the built-in Ethernet ports of your home router. They work like a traditional switch, but sometimes processing is done on the router's CPU instead of on a dedicated processor.
- On Windows
  - **Don't ever use the Public profile on the network adapter used for NDI.** This interferes with source discovery.
  - Add a firewall exception for OBS Studio in your firewall
- Reset your TCP settings after installing the NDI runtime, as the installer provided by NewTek silently enable Compound TCP which reduces available bandwidth.

If you still encounter issues, please open a new issue here on this tracker.
