### ISSUE TITLE
Getting connection loss?lag? in game using ndi

### ISSUE THREAD

**Issue by Matakor** [Palakis/obs-ndi#89]
So, apparently my set up is snowflakey af, because no one else I've talked to seems to have this particular issue. Anyhow, to the specs and setup.

https://pcpartpicker.com/user/Matakor/saved/4cBbvK 
This is my gaming pc. It is connected directly to my router via cat6 cable. OBS is running in admin, NDI is set to output.

https://www.amazon.com/Strix-G-SYNC-Gaming-Laptop-i7-7700HQ/dp/B01N6KLBR1/ref=cm_cr_arp_d_product_top?ie=UTF8
This is the pc I'm attempting to use to encode/stream. It is connecting with an ac-wifi connection, so bandwidth isn't an issue. I'm not worried about speed so much as quality of the stream. OBS here is also running in admin

Now for quick reference, I'm gaming at 3440x1440p @90hz. I am able to capture and push over ndi at that resolution and 60fps. At stream pc I downscale to 1720x720p and stream. I have TWO issues that pop up in my attempt to do this.

The first is that the laptop does NOT see the NDI source unless it is wired. If I wire it, get the source, and unplug the wire, it will continue fine over wifi. Bit annoying, but doable. As a stand-in, I've just got a cheap long cable and it runs fine over that. However, it is and issue, so I'm reporting it here.

The second and actual problem I'm currently having is while I'm streaming. I will be playing and suddenly I lose game connection and the stream dies. I also speak over discord, but I have no issues talking over that during this period. The loss in game lasts roughly 3 seconds, after which the game continues. On the laptop, I never see a recovery from the loss. Oddly, after a little longer I will see the stream kick back in and continue. Unfortunately, this will happen multiple times, even if I ignore the first hiccup. Playing in PUBG, 3 seconds will kill you (and has killed me about eight times now). This network 'hiccup' will happen over wire or wireless. If wireless, I will not recover the stream and the laptop will no longer find the ndi source until I plug it back in. ~~Now, if I leave ndi running and just have the laptop pick up the source, without starting the stream, I will never see the hiccup. (still can't pick up the source over wifi, but eh)~~ EDIT:: Actually, after leaving it running without the stream for a while, it did hiccup in game. :\

I should also note that the hiccup is inconsistent, happening anywhere from 5 minutes to 40 minutes into the stream.

As a side, the capture also appears to not even get to 60fps, but that might be my settings. I've been tweaking that to attempt to figure it out...

**Comment by Helgaiden** [comment]
Get off WiFi. You might think it's enough but it's just too unreliable and the first point of failure in troubleshooting. If you refuse to do this, on the gaming PC OBS, go into video settings, set base canvas to your monitor res and output (scaled res) to 1280x720 and common fps value to 60. Sending a 1280x720 stream from the gaming PC out over NDI should reduce the network bandwidth it's using a bit. Should be right around 100-120mbps. If you turn it down to 30fps, it's even less bandwidth.

**Comment by Matakor** [comment]
I'd again like to point out that this happens REGARDLESS of my setup with either wifi or wired. And my LAN bandwidth should not be any issue, it can handle 1gb up/down in house. This issue is something else.

If I was experience constant issues with network, then I'd probably agree, but again, it works just fine with that setup, until the hiccup occurs.
