### ISSUE TITLE
Delete Me

### ISSUE THREAD

**Issue by PixelTwitch** [Palakis/obs-ndi#91]

**Comment by Palakis** [comment]
@PixelTwitch Well, what happened?

**Comment by PixelTwitch** [comment]
Well, I have been having major issues with smoothness of NDI between systems. @Palakis 

Spent 100+ hours testing different settings, setups and softwares. I had one constent through all my testing (or at least I thought I did), the Ryzen 1700 CPU. Upon switching away from the 1700 for a test I noticed all the NDI stream was working (i9 7900x -> i7 3930k). So, I made a post saying that the Ryzen 1700 was the problem. However... Since I like to double check everything, I rebuilt the Ryzen 1700 system and connected it to the i9 7900x and... It was running smoothly (at least smoother). So, I came back to delete this post. 

Since then I have dug even deeper since I noticed that the Linux version of OBS NDI would run much smoother than on windows 10 but it was still not as smooth as I would like/hope. So, I tested Linux -> Linux on the Ryzen 1700 and i9 7900x, this resulted in near perfection. This obviously narrowed it down to a Windows 10 problem. 

All computers had been fresh installed multiple times for different tests, This time I combined almost everything I had learned and seem to have got it the best I can. 

(The following was done on BOTH systems)

- Fresh install of Windows 10
- Direct connect the computers via Crossover Cable (not proven to make a difference) 
- Disabled Gamebar, GameDVR, Fullscreen Optimisations (could not disable Gamemode on this verison)
- Set all monitors to Gsync enabled
- Set Nvidia to Max Perfromance and Windows to High Performance
- Removed manufactures webcam drivers
- Used FFdshow to change Mpeg encoder and codec. 
- Run OBS in Admin mode
- Set OBS process priority to BELOW NORMAL (Gaming Computer)
- Lowered Webcam Resolution to avoid render lag
- Disabled Preview (Gaming Computer) 
- Set OBS process priority to IDLE (Streaming Computer) 
- Set NDI to Hardware ON and INTERNAL sync (Streaming computer) 
 **BASKED IN SMOOTHNESS**

I have now tested removing each of these "optimisations" one at a time to test how valid they are. So far I am pretty certain that any one of these things not being done will have a negaitve impact on NDI smoothness in OBS & Xsplit. That said, even without these changes NDI would and does input into NewTeks NDI Tools flawlessly. However, I used an NDI viewer on Linux called ORFAST NDI and that acted the same as Xsplit and OBS. It is also worth nothing that it was not only OBS that would stutter on output to OBS, Xsplit, vMix and ORFAST NDI. So would Xsplit and vMix. But yet again, these programs would appear clean when input to NewTeks NDI Tools. 

All this leads me to one very noobie conclusion (I know nothing about anything really) and that is that OBS, Xsplit and vMix all put out bad frame timings and then on the input do not buffer the NDI streams they bring in. All the things I had to changed where changes that resulted in more consistancy rather than speed. Even now, as smooth as I have NDI working, if it stutters a single frame it can take 5-10 seconds to smooth itself out again. 

I will be doing my first long stream tonight using the setup since getting it smooth.
