### ISSUE TITLE
Audio Only filters do not save NDI name across sessions

### ISSUE THREAD

**Issue by BOLL7708** [Palakis/obs-ndi#95]
Thanks for fixing the crashes! Now I can change the name and actually use my three audio channels sent over to the recording/stream machine! 

But! **If I close OBS and open it again, the NDI names are all reset to default** and my three channels conflict so I have to go an manually change the names back to unique values again. 

This is quite repeatable, so far I've only repeated it twice as well, it's annoying to do the setup too often ;)

**Comment by Palakis** [comment]
Damn, sorry you're encountering this. I'm almost sure the bug's root cause is a dumb error. Gonna look this up.

**Comment by Palakis** [comment]
Have you updated to the last version, btw?

**Comment by BOLL7708** [comment]
I updated to the release two days ago, has there been another one? I have... `obs-ndi-4.2.1-Windows-Installer.exe`

**Comment by Palakis** [comment]
@BOLL7708 Found the bug and fixed it!

**Comment by Palakis** [comment]
4.2.2 has just been released, which includes said fix.
