### ISSUE TITLE
OBS-NDI on Mac: Random video freeze

### ISSUE THREAD

**Issue by RAMChYLD** [Palakis/obs-ndi#96]
I've mentioned this before, but I'm having issues with OBS Studio on a 2011 Mac Mini that has had it's RAM upgraded to 8GB DDR3-1866 (up from 4GB DDR3-1333). 

I am using Youtube's backup ingest server since the primary server seems to make this issue happen more frequently. 

My workflow is that 1080p60 video is captured by OBS Studio on my primary gaming machine and relayed to OBS Studio on the Mac Mini, in which a webcam overlay from a Logitech webcam connected to the mac is inserted into the image, the video is resampled to 720p30, then streamed to Youtube Gaming.  I have set OBS Studio to do the transcoding via the Apple VT hardware. CPU load is a constant 25% during streaming and I can get 720p30 frame rates consistently. 

However, the stream keeps breaking intermittently. OBS would suddenly report that it's stream speed had dropped to about 150 or so kbps. Restarting the stream would usually fix the issue, but the issue will return after a while. The connection seems to drop more frequently on Youtube's main ingest server than with the backup server. 

When I watch back my replays later, it seems that the video stream had just locked up while the audio stream is still going.

Can I know why it's doing this? The CPU load doesn't seem too high at 25%, and OBS reports that the frame rate is a consistent 30fps. 

I'm planning to switch to using Restream.IO as a middleman to see if my connection to Youtube's Ingest servers is at fault and at the same time, make it so I can stream to both Twitch and Youtube at the same time, but is it possible that the NDI plugin or libraries are randomly seizing up?

**Comment by matiaspl** [comment]
This is not obs-ndi nor platform dependent. I observe this very same
behaviour with Apple VT hardware on my private RTMP server as well. The
solution is to use x264.

19.01.2018 17:11 "RAMChYLD" <notifications@github.com> napisał(a):

**Comment by RAMChYLD** [comment]
Well, the problem is, will my Mac Mini be able to handle the workload without hardware acceleration? It’s the lowest end dual core HD Graphics 3000 model.

**Comment by matiaspl** [comment]
You will have to find out yourself, YMMV. I believe think it should work at
720p25 with spare CPU cycles left if you don't have complex scenes and
sources that need decent deinterlacing.

2018-01-23 20:06 GMT+01:00 RAMChYLD <notifications@github.com>:
