### ISSUE TITLE
OBS NDI installed but not work

### ISSUE THREAD

**Issue by Owned67** [Palakis/obs-ndi#98]
Hello,

OBS installed 20.1.3
obs-ndi installer 4.2.1

reboot computer but ndi is not present...

On my second computer, no problem...

Windows 10 Pro x64

edit: uninstalled 4.2.1, restart computer, install 4.2.2, reboot computer and same

log:
http://termbin.com/a611
http://termbin.com/1gki

In C:\Program Files (x86)\obs-studio folder:
C:\Program Files (x86)\obs-studio\ndi\
C:\Program Files (x86)\obs-studio\ndi\data
C:\Program Files (x86)\obs-studio\ndi\data\obs-plugins\obs-ndi\locale
 C:\Program Files (x86)\obs-studio\ndi\obs-plugins\32bit\obs-ndi.dll
 C:\Program Files (x86)\obs-studio\ndi\obs-plugins\64bit\obs-ndi.dll

in C:\Program Files (x86)\obs-studio\obs-plugins folder, i don't have ndi plugins...

**Comment by Helgaiden** [comment]
Those links to your log dont work. Really need to look at them to see how we can help.

**Comment by Palakis** [comment]
@Owned67 Your installation is not correct. You need to put the contents of the zip archive in the **root** of the obs-studio installation folder. Not in a subfolder like you've done.
