### ISSUE TITLE
High CPU problem

### ISSUE THREAD

**Issue by ShayBox** [Palakis/obs-ndi#99]
I've been having a problem with obs-ndi causing my CPU to stay idle at 100%
I have tried installing obs, obs-ndi and ndi v3
Obs is fine when I install it
it is fine when I install obs-ndi
then after I add a source, it ramps up to 100%, if I restart obs it starts low then when the source starts up it goes to 100%
and if I remove the source it stays at 100% until I restart obs
![image](https://user-images.githubusercontent.com/9505196/35293134-ce051e34-0040-11e8-94b8-ebfa47bb783e.png)
This is fresh windows 10 on my second computer connecting through RDP with the lowest res, lowest color depth

It has an FX 6100 3.30ghz 3core 6 thread CPU and it can handle a standard display capture at 1080p just fine, it's only when I use ndi does it jump up to 100%
And this is without even starting the stream or recording

```
13:20:35.050: CPU Name: AMD FX(tm)-6100 Six-Core Processor             
13:20:35.050: CPU Speed: 3307MHz
13:20:35.050: Physical Cores: 3, Logical Cores: 6
13:20:35.050: Physical Memory: 8175MB Total, 6996MB Free
13:20:35.050: Windows Version: 10.0 Build 16299 (revision: 125; 64-bit)
13:20:35.050: Running as administrator: false
13:20:35.050: Aero is Enabled (Aero is always on for windows 8 and above)
13:20:35.050: Windows 10 Gaming Features:
13:20:35.050: 	Game DVR: On
13:20:35.051: Sec. Software Status:
13:20:35.053: 	Windows Firewall: enabled (FW)
13:20:35.053: Portable mode: false
13:20:35.088: OBS 21.0.1 (64bit, windows)
13:20:35.088: ---------------------------------
13:20:35.101: ---------------------------------
13:20:35.101: audio settings reset:
13:20:35.101: 	samples per sec: 44100
13:20:35.101: 	speakers:        2
13:20:35.102: ---------------------------------
13:20:35.102: Initializing D3D11...
13:20:35.102: Available Video Adapters: 
13:20:35.106: Loading up D3D11 on adapter Microsoft Basic Render Driver (0)
13:20:35.108: D3D11 loaded successfully, feature level used: 45056
13:20:36.164: ---------------------------------
13:20:36.164: video settings reset:
13:20:36.164: 	base resolution:   1920x1080
13:20:36.164: 	output resolution: 1920x1080
13:20:36.164: 	downscale filter:  Bilinear
13:20:36.164: 	fps:               60/1
13:20:36.164: 	format:            NV12
13:20:36.184: Audio monitoring device:
13:20:36.184: 	name: Default
13:20:36.184: 	id: default
13:20:36.184: ---------------------------------
13:20:36.186: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/chrome_elf.dll' not found, loading of module failed
13:20:36.187: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
13:20:36.227: [AMF] <obs_module_load> AMF not supported (no AMD graphics)
13:20:36.227: Failed to initialize module 'enc-amf.dll'
13:20:36.251: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libcef.dll' not found, loading of module failed
13:20:36.251: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libEGL.dll' not found, loading of module failed
13:20:36.252: Required module function 'obs_module_load' in module '../../obs-plugins/64bit/libGLESv2.dll' not found, loading of module failed
13:20:36.253: Failed to load 'en-US' text for module: 'obs-browser.dll'
13:20:36.253: [browser_source: 'Version: 1.29.0']
13:20:36.257: LoadLibrary failed for 'nvEncodeAPI64.dll': The specified module could not be found.
13:20:36.257:  (126)
13:20:36.259: [obs-ndi] hello ! (version 4.2.2)
13:20:36.259: [obs-ndi] Trying 'C:\Program Files\NewTek\NewTek NDI Redist\v3'
13:20:36.259: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NewTek NDI Redist/v3/Processing.NDI.Lib.x64.dll'
13:20:36.269: [obs-ndi] NDI runtime loaded successfully
13:20:36.281: [obs-ndi] NDI library initialized successfully
13:20:36.433: Couldn't find VLC installation, VLC video source disabled
13:20:36.448: No blackmagic support
13:20:36.500: ---------------------------------
13:20:36.500:   Loaded Modules:
13:20:36.500:     win-wasapi.dll
13:20:36.500:     win-mf.dll
13:20:36.500:     win-dshow.dll
13:20:36.500:     win-decklink.dll
13:20:36.500:     win-capture.dll
13:20:36.500:     vlc-video.dll
13:20:36.500:     text-freetype2.dll
13:20:36.500:     rtmp-services.dll
13:20:36.500:     obs-x264.dll
13:20:36.500:     obs-vst.dll
13:20:36.500:     obs-transitions.dll
13:20:36.500:     obs-text.dll
13:20:36.501:     obs-qsv11.dll
13:20:36.501:     obs-outputs.dll
13:20:36.501:     obs-ndi.dll
13:20:36.501:     obs-filters.dll
13:20:36.501:     obs-ffmpeg.dll
13:20:36.501:     obs-browser.dll
13:20:36.501:     image-source.dll
13:20:36.501:     frontend-tools.dll
13:20:36.501:     enc-amf.dll
13:20:36.501:     coreaudio-encoder.dll
13:20:36.501: ---------------------------------
13:20:36.501: ==== Startup complete ===============================================
13:20:36.502: Service '' not found
13:20:36.519: All scene data cleared
13:20:36.519: ------------------------------------------------
13:20:36.782: WASAPI: Device 'Remote Audio' initialized
13:20:36.783: Switched to scene 'Scene'
13:20:36.784: ------------------------------------------------
13:20:36.784: Loaded scenes:
13:20:36.784: - scene 'Scene':
13:20:36.784: ------------------------------------------------
```
Logs don't show anything out of normal from what I can see

![image](https://user-images.githubusercontent.com/9505196/35293255-2ce9afd2-0041-11e8-8af8-473e2d5cb582.png)

**Comment by ShayBox** [comment]
And if I lower the base res of obs in settings it can go down to 50% at 640x480, but at idle and that res it should be much lower...

**Comment by Helgaiden** [comment]
What is the CPU Process Priority for OBS under settings? 
The first drop down on this screen
https://i1.creativecow.net/u/294334/obssettingsadvanced.png

**Comment by ShayBox** [comment]
Normal 
![image](https://user-images.githubusercontent.com/9505196/35294656-19c5d49a-0045-11e8-9466-093ac49f2ca7.png)

**Comment by Helgaiden** [comment]
I would uninstall the newtek ndi stuff (under add/remove programs where you would normally uninstall stuff, or "programs and features"), reboot, then uninstall OBS, then reboot, then start over. Maybe something got corrupt during the install.

**Comment by ShayBox** [comment]
I have tried, this is my 3rd install of windows, obs, obs-ndi, and ndi v3
obs is completely fine until I add a ndi source, and it sticks over reboots if I remove the source completely

**Comment by ShayBox** [comment]
Steps to reproduce:

I deleted all the user settings in Roaming/obs and the cpu usage went bacl down
Fresh obs settings 
![image](https://user-images.githubusercontent.com/9505196/35295480-489482b0-0047-11e8-906d-535443e2e934.png)

Added NDI Source + enabled hardware acceleration and stretched it to screen 
![image](https://user-images.githubusercontent.com/9505196/35295576-6cd64ea6-0047-11e8-9ebd-b71a90fde5b0.png)

Trying to turn off preview, doesn't effect cpu usage 
![image](https://user-images.githubusercontent.com/9505196/35295594-7b7e6ea2-0047-11e8-8aa2-d19bb7a5c26a.png)

Increasing base resolution from 800x600 to 1920x1080 so I can record in 1080p and 30fps to 10fps
![image](https://user-images.githubusercontent.com/9505196/35295624-924a0b14-0047-11e8-995a-6aee60117b53.png)
![image](https://user-images.githubusercontent.com/9505196/35295645-9fbbe808-0047-11e8-95ac-ff7a6805653c.png)

Goes to 100% 
![image](https://user-images.githubusercontent.com/9505196/35295667-b020c9d4-0047-11e8-8c8f-bbf1dd7370ff.png)

**Comment by ShayBox** [comment]
It seems that NDI was using 100% of my cpu because I didn't have a gpu, NDI seems to really like to hog the cpu if it can't use gpu hardware acceleration.

**Comment by Helgaiden** [comment]
NDI has never hogged the CPU (which is the entire point of it) for me, even using a 400 series GTX card and a 500 series GTX card, neither of which support hardware acceleration. Or using a 7970 when i dont have the AMD VCE plugin even installed in OBS. Im not sure what your issue is, maybe its specific to how the the FX-6100 works with NDI. I wish you luck in figuring this out. Im not sure what @Palakis can tell you.

**Comment by ThePoot** [comment]
Hi, I'm stumbling across this along time after it was posted, but i want to give you some information I've come across as I've been messing with NDI for about 5-6 months.

I've tried Linux and windows, (windows mainly), but I've recently switched my main PC to Linux while my server runs windows.

### Trouble shooting for windows
I recently got a server that is able to house a GPU. 
before this server i had a server that only had integrated graphics.
If you are trying to do anything with obs it needs a GPU, it can be a 30-40$ GPU
just make sure it can do discrete graphics. The server with integrated graphics would shoot up
to 90-100% CPU usage. I've tried everything but that server will not take a GPU, its too old.

### Trouble shooting for Linux
This part is about Linux but is very much connected with problems with windows and no GPU.
My Linux machine is a gaming PC so its pretty easy to add multiple GPUs.
When I installed Linux and started obs and NDI for a test steam, i was seeing 70% CPU usage!
Even though I would stream on it through windows id get like 10-13% CPU,
In Linux I had the GPU in the PC, what i had noticed is Ubuntu has open source drivers for AMD and its improving, but after I installed the GPU driver from AMD I did another test stream.
I saw an improvement of -40% on the CPU. it would stream at 30-35% CPU.
Still not as good as windows, but that tells you why its important that a GPU is present.

Although there is an improvement, im still not happy with the high cpu usage, I've recently heard about 
Kvm. what i was thinking about doing was running windows through a kvm, and having obs in windows for a smaller cpu strain, i really do enjoy Linux and i plan to keep it for other things than obs.

So make sure you got a gpu, or else you will have a bad day, other things might work like amd apus
that have a pretty good gpu built in the cpu.
