### ISSUE TITLE
obs-ndi can't find NDI library on macOS

### ISSUE THREAD

**Issue by oquas** [Palakis/obs-ndi#995]
### Operating System Version

macOS Sonoma 14.4.1

### CPU

M1 Max

### GPU

M1 Max

### OBS Version

30.1.2

### OBS Installation Method

.dmg

### OBS-NDI Version

4.13.1

### OBS-NDI Installation Method

.pkg

### [Extra] Installation Steps

In addition, installed NDI Tool and NDI SDK. Everything (OBS, obs-ndi, NDI SDK, NDI Tools) was downloaded today and is a first-time-ever install on this machine.

### OBS Log [URL]

https://obsproject.com/logs/aDLSrFbIBqiSZqP1

### NDI Version

6.0

### Describe the bug

After installing OBS, obs-ndi, NDI SDK and NDI Tools, i created the following symlink: `sudo ln -s /Library/NDI\ SDK\ for\ Apple/lib/macOS/libndi /usr/local/lib/libndi.dylib` and rebooted. As soon as i open OBS i get a "NDI runtime not found" error dialogwith a link to http://ndi.link/NDIRedistV5Apple. 

I just noticed, that on 2nd of April 2024 NDI v6 was released and all downloads of NDI SDK and NDI Tools refer to the newest (v6) version. V5 doesn't seem to be available anymore. After reading forums up and down without any further solution i come to the conclusion, that there is some incompatibility between obs-ndi and NDI SDK v6. Please forgive me if i'm wrong.

### Steps to reproduce the problem

Open /Applications/OBS.app and the above mentioned error dialog appears. NDI can't be selected from the sources as the menu entry doesn't exist.

### Expected behavior

obs-ndi should find and recognize `/user/local/libndi.dylib` (v6!).

### Screenshots

<img width="505" alt="2024-04-08-NDI-Dialog" src="https://github.com/obs-ndi/obs-ndi/assets/560346/6b1ec66c-3f8c-426e-a37d-1487f329a91a">
<img width="247" alt="2024-04-08-OBS-source-menu" src="https://github.com/obs-ndi/obs-ndi/assets/560346/81bab6a9-9602-40d6-9310-49f1fec2dd26">

**Comment by Trouffman** [comment]
This sounds more like an issue with access right or symbolink link issue rather than a v6 issue.

Please check the following :
- check that your link is correct :ls -lh  /usr/local/lib/libndi.dylib

- try by doing a hard copy of the lib in that folder. does that fix it ?

**Comment by Trouffman** [comment]
I tested with NDI6 and all good on a macbook air .
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/3ca9e5a1-3dd8-461d-a556-161323583abe)

ls -lh /usr/local/lib/libndi*

Most likely the symbolink link is an issue here.

**Comment by Trouffman** [comment]
ls -lh /usr/local/lib
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/63429281-11ef-497d-9c27-ae9957026497)

Seems your lib folder have different access rights.
![image](https://github.com/obs-ndi/obs-ndi/assets/2151317/de48374f-9266-4010-87f3-a6d493069943)

Try add the r & x flag (should be with : chmod go+rx /usr/local/lib  )
